import { describe, expect, it } from 'vitest';
import { closeWorkspaceDialog, createWorkspaceAccessibilityState, enterWorkspaceFocusZone, openWorkspaceDialog, setCommandPaletteOpen, setWorkspaceConnectivity, setWorkspaceInputModality, setWorkspaceMapBusy, setWorkspaceMediaAccessibility, workspaceAccessibilitySummary, workspaceFocusSelector } from './workspaceAccessibilityModel';

describe('workspaceAccessibilityModel', () => {
  it('creates a frozen bounded initial state', () => { const state = createWorkspaceAccessibilityState(); expect(state.dialogDepth).toBe(0); expect(state.sequence).toBe(0); expect(Object.isFrozen(state)).toBe(true); });
  it('normalizes negative dialog depth', () => expect(createWorkspaceAccessibilityState({ dialogDepth: -20 }).dialogDepth).toBe(0));
  it('tracks modality idempotently', () => { const state = createWorkspaceAccessibilityState({ modality: 'keyboard' }); expect(setWorkspaceInputModality(state, 'keyboard').state).toBe(state); expect(setWorkspaceInputModality(state, 'touch').state.modality).toBe('touch'); });
  it('tracks previous focus zone', () => { const result = enterWorkspaceFocusZone(createWorkspaceAccessibilityState({ focusZone: 'map' }), 'tools'); expect(result.state.previousFocusZone).toBe('map'); expect(result.state.focusZone).toBe('tools'); });
  it('keeps repeated focus entry stable', () => { const state = createWorkspaceAccessibilityState({ focusZone: 'map' }); expect(enterWorkspaceFocusZone(state, 'map').state).toBe(state); });
  it('restores dialog focus origin', () => { const opened = openWorkspaceDialog(createWorkspaceAccessibilityState({ focusZone: 'tools' })); const closed = closeWorkspaceDialog(opened.state); expect(closed.restoreFocusTo).toBe('tools'); expect(closed.state.dialogDepth).toBe(0); });
  it('supports nested dialogs', () => { const first = openWorkspaceDialog(createWorkspaceAccessibilityState({ focusZone: 'map' })); const second = openWorkspaceDialog(first.state); expect(second.state.dialogDepth).toBe(2); expect(second.announcement).toBeNull(); });
  it('ignores unmatched dialog close', () => { const state = createWorkspaceAccessibilityState(); expect(closeWorkspaceDialog(state).state).toBe(state); });
  it('restores command palette origin', () => { const opened = setCommandPaletteOpen(createWorkspaceAccessibilityState({ focusZone: 'map' }), true); const closed = setCommandPaletteOpen(opened.state, false); expect(closed.restoreFocusTo).toBe('map'); });
  it('announces map busy transitions politely', () => { const busy = setWorkspaceMapBusy(createWorkspaceAccessibilityState(), true); expect(busy.priority).toBe('polite'); expect(setWorkspaceMapBusy(busy.state, false).announcement).toContain('tamamlandı'); });
  it('announces offline assertively and recovery politely', () => { const offline = setWorkspaceConnectivity(createWorkspaceAccessibilityState(), false); expect(offline.priority).toBe('assertive'); expect(setWorkspaceConnectivity(offline.state, true).priority).toBe('polite'); });
  it('tracks media accessibility state', () => { const result = setWorkspaceMediaAccessibility(createWorkspaceAccessibilityState(), { reducedMotion: true, forcedColors: true }); expect(result.state.reducedMotion).toBe(true); expect(result.state.forcedColors).toBe(true); });
  it.each([['map','#esri-map-container'],['tools','#sidebar'],['workspace','#experience-workspace-controls'],['command-palette','[data-experience-command-palette]'],['dialog','[role="dialog"]'],['unknown',null]] as const)('maps %s to a stable selector', (zone, selector) => expect(workspaceFocusSelector(zone)).toBe(selector));
  it('builds a frozen concise summary', () => { const summary = workspaceAccessibilitySummary(createWorkspaceAccessibilityState({ modality: 'keyboard', online: false, mapBusy: true, reducedMotion: true, forcedColors: true })); expect(summary).toEqual(['Çevrimdışı','Harita güncelleniyor','Azaltılmış hareket','Zorunlu renkler etkin','Klavye kullanımı']); expect(Object.isFrozen(summary)).toBe(true); });
});
