//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Extensions.Integrations.Pod.AEOServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NobetciEczanelerResultMessage", Namespace="http://tempuri.org/")]
    public partial class NobetciEczanelerResultMessage : object
    {
        
        private bool isSuccessField;
        
        private short ErrorCodeField;
        
        private string MessageField;
        
        private decimal CenterLatField;
        
        private decimal CenterLngField;
        
        private bool NobetZamanimiField;
        
        private AEOServiceReference.NobetciEczaneBilgisi[] NobetciEczaneBilgisiListesiField;
        
        private AEOServiceReference.NobetciEczaneBilgisi[] YakinEczaneBilgisiListesiField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool isSuccess
        {
            get
            {
                return this.isSuccessField;
            }
            set
            {
                this.isSuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public short ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal CenterLat
        {
            get
            {
                return this.CenterLatField;
            }
            set
            {
                this.CenterLatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal CenterLng
        {
            get
            {
                return this.CenterLngField;
            }
            set
            {
                this.CenterLngField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool NobetZamanimi
        {
            get
            {
                return this.NobetZamanimiField;
            }
            set
            {
                this.NobetZamanimiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public AEOServiceReference.NobetciEczaneBilgisi[] NobetciEczaneBilgisiListesi
        {
            get
            {
                return this.NobetciEczaneBilgisiListesiField;
            }
            set
            {
                this.NobetciEczaneBilgisiListesiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public AEOServiceReference.NobetciEczaneBilgisi[] YakinEczaneBilgisiListesi
        {
            get
            {
                return this.YakinEczaneBilgisiListesiField;
            }
            set
            {
                this.YakinEczaneBilgisiListesiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NobetciEczaneBilgisi", Namespace="http://tempuri.org/")]
    public partial class NobetciEczaneBilgisi : object
    {
        
        private string EczaneKeyField;
        
        private string EczaneAdiField;
        
        private string EczaneAdresiField;
        
        private string TelefonField;
        
        private string EczaciAdiField;
        
        private string EczaciSoyadiField;
        
        private string AdresAciklamasiField;
        
        private System.Nullable<decimal> KoordinatLatField;
        
        private System.Nullable<decimal> KoordinatLngField;
        
        private double DistanceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string EczaneKey
        {
            get
            {
                return this.EczaneKeyField;
            }
            set
            {
                this.EczaneKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EczaneAdi
        {
            get
            {
                return this.EczaneAdiField;
            }
            set
            {
                this.EczaneAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EczaneAdresi
        {
            get
            {
                return this.EczaneAdresiField;
            }
            set
            {
                this.EczaneAdresiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Telefon
        {
            get
            {
                return this.TelefonField;
            }
            set
            {
                this.TelefonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string EczaciAdi
        {
            get
            {
                return this.EczaciAdiField;
            }
            set
            {
                this.EczaciAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string EczaciSoyadi
        {
            get
            {
                return this.EczaciSoyadiField;
            }
            set
            {
                this.EczaciSoyadiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string AdresAciklamasi
        {
            get
            {
                return this.AdresAciklamasiField;
            }
            set
            {
                this.AdresAciklamasiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<decimal> KoordinatLat
        {
            get
            {
                return this.KoordinatLatField;
            }
            set
            {
                this.KoordinatLatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<decimal> KoordinatLng
        {
            get
            {
                return this.KoordinatLngField;
            }
            set
            {
                this.KoordinatLngField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public double Distance
        {
            get
            {
                return this.DistanceField;
            }
            set
            {
                this.DistanceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NobetciEczanelerResultMessageBolgeli", Namespace="http://tempuri.org/")]
    public partial class NobetciEczanelerResultMessageBolgeli : object
    {
        
        private bool isSuccessField;
        
        private short ErrorCodeField;
        
        private string MessageField;
        
        private decimal CenterLatField;
        
        private decimal CenterLngField;
        
        private bool NobetZamanimiField;
        
        private AEOServiceReference.NobetciEczaneBilgisiBolgeli[] NobetciEczaneBilgisiListesiField;
        
        private AEOServiceReference.NobetciEczaneBilgisiBolgeli[] YakinEczaneBilgisiListesiField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool isSuccess
        {
            get
            {
                return this.isSuccessField;
            }
            set
            {
                this.isSuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public short ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal CenterLat
        {
            get
            {
                return this.CenterLatField;
            }
            set
            {
                this.CenterLatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal CenterLng
        {
            get
            {
                return this.CenterLngField;
            }
            set
            {
                this.CenterLngField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool NobetZamanimi
        {
            get
            {
                return this.NobetZamanimiField;
            }
            set
            {
                this.NobetZamanimiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public AEOServiceReference.NobetciEczaneBilgisiBolgeli[] NobetciEczaneBilgisiListesi
        {
            get
            {
                return this.NobetciEczaneBilgisiListesiField;
            }
            set
            {
                this.NobetciEczaneBilgisiListesiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public AEOServiceReference.NobetciEczaneBilgisiBolgeli[] YakinEczaneBilgisiListesi
        {
            get
            {
                return this.YakinEczaneBilgisiListesiField;
            }
            set
            {
                this.YakinEczaneBilgisiListesiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NobetciEczaneBilgisiBolgeli", Namespace="http://tempuri.org/")]
    public partial class NobetciEczaneBilgisiBolgeli : object
    {
        
        private string EczaneKeyField;
        
        private string EczaneAdiField;
        
        private string EczaneAdresiField;
        
        private string TelefonField;
        
        private string EczaciAdiField;
        
        private string EczaciSoyadiField;
        
        private string AdresAciklamasiField;
        
        private System.Nullable<decimal> KoordinatLatField;
        
        private System.Nullable<decimal> KoordinatLngField;
        
        private double DistanceField;
        
        private string BolgeAdiField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string EczaneKey
        {
            get
            {
                return this.EczaneKeyField;
            }
            set
            {
                this.EczaneKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EczaneAdi
        {
            get
            {
                return this.EczaneAdiField;
            }
            set
            {
                this.EczaneAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EczaneAdresi
        {
            get
            {
                return this.EczaneAdresiField;
            }
            set
            {
                this.EczaneAdresiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Telefon
        {
            get
            {
                return this.TelefonField;
            }
            set
            {
                this.TelefonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string EczaciAdi
        {
            get
            {
                return this.EczaciAdiField;
            }
            set
            {
                this.EczaciAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string EczaciSoyadi
        {
            get
            {
                return this.EczaciSoyadiField;
            }
            set
            {
                this.EczaciSoyadiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string AdresAciklamasi
        {
            get
            {
                return this.AdresAciklamasiField;
            }
            set
            {
                this.AdresAciklamasiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<decimal> KoordinatLat
        {
            get
            {
                return this.KoordinatLatField;
            }
            set
            {
                this.KoordinatLatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<decimal> KoordinatLng
        {
            get
            {
                return this.KoordinatLngField;
            }
            set
            {
                this.KoordinatLngField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public double Distance
        {
            get
            {
                return this.DistanceField;
            }
            set
            {
                this.DistanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string BolgeAdi
        {
            get
            {
                return this.BolgeAdiField;
            }
            set
            {
                this.BolgeAdiField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AEOServiceReference.ws_AEO_NobetSoap")]
    public interface ws_AEO_NobetSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NobetciEczaneler", ReplyAction="*")]
        System.Threading.Tasks.Task<AEOServiceReference.NobetciEczanelerResponse> NobetciEczanelerAsync(AEOServiceReference.NobetciEczanelerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NobetciEczaneGetirTarih", ReplyAction="*")]
        System.Threading.Tasks.Task<AEOServiceReference.NobetciEczaneGetirTarihResponse> NobetciEczaneGetirTarihAsync(AEOServiceReference.NobetciEczaneGetirTarihRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NobetciEczanelerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NobetciEczaneler", Namespace="http://tempuri.org/", Order=0)]
        public AEOServiceReference.NobetciEczanelerRequestBody Body;
        
        public NobetciEczanelerRequest()
        {
        }
        
        public NobetciEczanelerRequest(AEOServiceReference.NobetciEczanelerRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NobetciEczanelerRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Nullable<double> lat;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<double> lng;
        
        public NobetciEczanelerRequestBody()
        {
        }
        
        public NobetciEczanelerRequestBody(System.Nullable<double> lat, System.Nullable<double> lng)
        {
            this.lat = lat;
            this.lng = lng;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NobetciEczanelerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NobetciEczanelerResponse", Namespace="http://tempuri.org/", Order=0)]
        public AEOServiceReference.NobetciEczanelerResponseBody Body;
        
        public NobetciEczanelerResponse()
        {
        }
        
        public NobetciEczanelerResponse(AEOServiceReference.NobetciEczanelerResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NobetciEczanelerResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AEOServiceReference.NobetciEczanelerResultMessage NobetciEczanelerResult;
        
        public NobetciEczanelerResponseBody()
        {
        }
        
        public NobetciEczanelerResponseBody(AEOServiceReference.NobetciEczanelerResultMessage NobetciEczanelerResult)
        {
            this.NobetciEczanelerResult = NobetciEczanelerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NobetciEczaneGetirTarihRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NobetciEczaneGetirTarih", Namespace="http://tempuri.org/", Order=0)]
        public AEOServiceReference.NobetciEczaneGetirTarihRequestBody Body;
        
        public NobetciEczaneGetirTarihRequest()
        {
        }
        
        public NobetciEczaneGetirTarihRequest(AEOServiceReference.NobetciEczaneGetirTarihRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NobetciEczaneGetirTarihRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Nullable<System.DateTime> NobetTarihi;
        
        public NobetciEczaneGetirTarihRequestBody()
        {
        }
        
        public NobetciEczaneGetirTarihRequestBody(System.Nullable<System.DateTime> NobetTarihi)
        {
            this.NobetTarihi = NobetTarihi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NobetciEczaneGetirTarihResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NobetciEczaneGetirTarihResponse", Namespace="http://tempuri.org/", Order=0)]
        public AEOServiceReference.NobetciEczaneGetirTarihResponseBody Body;
        
        public NobetciEczaneGetirTarihResponse()
        {
        }
        
        public NobetciEczaneGetirTarihResponse(AEOServiceReference.NobetciEczaneGetirTarihResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NobetciEczaneGetirTarihResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AEOServiceReference.NobetciEczanelerResultMessageBolgeli NobetciEczaneGetirTarihResult;
        
        public NobetciEczaneGetirTarihResponseBody()
        {
        }
        
        public NobetciEczaneGetirTarihResponseBody(AEOServiceReference.NobetciEczanelerResultMessageBolgeli NobetciEczaneGetirTarihResult)
        {
            this.NobetciEczaneGetirTarihResult = NobetciEczaneGetirTarihResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ws_AEO_NobetSoapChannel : AEOServiceReference.ws_AEO_NobetSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ws_AEO_NobetSoapClient : System.ServiceModel.ClientBase<AEOServiceReference.ws_AEO_NobetSoap>, AEOServiceReference.ws_AEO_NobetSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ws_AEO_NobetSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ws_AEO_NobetSoapClient.GetBindingForEndpoint(endpointConfiguration), ws_AEO_NobetSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ws_AEO_NobetSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ws_AEO_NobetSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ws_AEO_NobetSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ws_AEO_NobetSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ws_AEO_NobetSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AEOServiceReference.NobetciEczanelerResponse> AEOServiceReference.ws_AEO_NobetSoap.NobetciEczanelerAsync(AEOServiceReference.NobetciEczanelerRequest request)
        {
            return base.Channel.NobetciEczanelerAsync(request);
        }
        
        public System.Threading.Tasks.Task<AEOServiceReference.NobetciEczanelerResponse> NobetciEczanelerAsync(System.Nullable<double> lat, System.Nullable<double> lng)
        {
            AEOServiceReference.NobetciEczanelerRequest inValue = new AEOServiceReference.NobetciEczanelerRequest();
            inValue.Body = new AEOServiceReference.NobetciEczanelerRequestBody();
            inValue.Body.lat = lat;
            inValue.Body.lng = lng;
            return ((AEOServiceReference.ws_AEO_NobetSoap)(this)).NobetciEczanelerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AEOServiceReference.NobetciEczaneGetirTarihResponse> AEOServiceReference.ws_AEO_NobetSoap.NobetciEczaneGetirTarihAsync(AEOServiceReference.NobetciEczaneGetirTarihRequest request)
        {
            return base.Channel.NobetciEczaneGetirTarihAsync(request);
        }
        
        public System.Threading.Tasks.Task<AEOServiceReference.NobetciEczaneGetirTarihResponse> NobetciEczaneGetirTarihAsync(System.Nullable<System.DateTime> NobetTarihi)
        {
            AEOServiceReference.NobetciEczaneGetirTarihRequest inValue = new AEOServiceReference.NobetciEczaneGetirTarihRequest();
            inValue.Body = new AEOServiceReference.NobetciEczaneGetirTarihRequestBody();
            inValue.Body.NobetTarihi = NobetTarihi;
            return ((AEOServiceReference.ws_AEO_NobetSoap)(this)).NobetciEczaneGetirTarihAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ws_AEO_NobetSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ws_AEO_NobetSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ws_AEO_NobetSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://mvc.aeo.org.tr/PublicSayfalar/WebServices/ws_AEO_Nobet.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ws_AEO_NobetSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://mvc.aeo.org.tr/PublicSayfalar/WebServices/ws_AEO_Nobet.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ws_AEO_NobetSoap,
            
            ws_AEO_NobetSoap12,
        }
    }
}
