<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="ClosedXML" Version="0.105.1" />
    <PackageVersion Include="Docnet.Core" Version="2.3.1" />
    <PackageVersion Include="EFCore.NamingConventions" Version="10.0.1" />
    <PackageVersion Include="Magick.NET-Q16-AnyCPU" Version="14.17.1" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.12" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.12" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12" />
    <PackageVersion Include="Microsoft.IdentityModel.Tokens" Version="8.22.0" />
    <PackageVersion Include="Novell.Directory.Ldap.NETStandard" Version="3.6.0" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageVersion Include="PdfPig" Version="0.1.6" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
    <PackageVersion Include="System.Security.Cryptography.Xml" Version="10.0.12" />
    <PackageVersion Include="System.ServiceModel.Http" Version="10.0.652802" />
    <PackageVersion Include="System.ServiceModel.Primitives" Version="10.0.652802" />
    <PackageVersion Include="Tesseract" Version="5.2.0" />
    <PackageVersion Include="UAParser" Version="3.1.47" />
    <PackageVersion Include="xunit.v3" Version="4.0.0" />
  </ItemGroup>
</Project>
