import { createFormFieldModel, type FieldValidator } from './formFieldModel';
const error=(code:string,message:string)=>({code,message,severity:'error' as const}); const warning=(code:string,message:string)=>({code,message,severity:'warning' as const});
describe('formFieldModel',()=>{
 test('starts immutable and tracks dirty touched state',async()=>{const model=createFormFieldModel({id:'address',label:'Adres',initialValue:'Ankara'});expect(Object.isFrozen(model.getState())).toBe(true);await model.setValue('İstanbul');expect(model.getState().dirty).toBe(true);model.focus();await model.blur();expect(model.getState().touched).toBe(true);});
 test('exposes required validation through accessible metadata',async()=>{const state=await createFormFieldModel({id:'district',label:'İlçe',required:true}).validate();expect(state.status).toBe('invalid');expect(state.ariaInvalid).toBe(true);expect(state.errorMessage).toBe('İlçe zorunludur.');expect(state.describedBy).toEqual(['district-error']);});
 test('validates on blur and change when configured',async()=>{const validator:FieldValidator=({value})=>value.length<3?error('short','En az üç karakter girin.'):null;const blur=createFormFieldModel({id:'q',label:'Arama',validators:[validator],validateOn:['blur']});await blur.setValue('ab');blur.focus();expect((await blur.blur()).status).toBe('invalid');const change=createFormFieldModel({id:'c',label:'Kod',validators:[validator],validateOn:['change']});expect((await change.setValue('ab')).status).toBe('invalid');expect((await change.setValue('abc')).status).toBe('valid');});
 test('keeps warnings distinct and deduplicates bounded issues',async()=>{const issue=warning('same','Uyarı');const model=createFormFieldModel({id:'x',label:'X',validators:[()=>[issue,issue],()=>Array.from({length:30},(_,i)=>error(`e${i}`,`Hata ${i}`))]});const state=await model.validate();expect(state.warningMessage).toBe('Uyarı');expect(state.issues).toHaveLength(12);});
 test('bounds value length and respects disabled/read only',async()=>{const model=createFormFieldModel({id:'x',label:'X',maxLength:5});await model.setValue('123456');expect(model.getState().value).toBe('12345');model.setReadOnly(true);await model.setValue('no');expect(model.getState().value).toBe('12345');model.setReadOnly(false);model.setDisabled(true);await model.setValue('no');expect(model.focus().focused).toBe(false);});
 test('reset establishes a clean baseline and clears validation',async()=>{const model=createFormFieldModel({id:'x',label:'X',initialValue:'a',required:true});await model.setValue('');await model.validate();const state=model.reset('c');expect(state.value).toBe('c');expect(state.dirty).toBe(false);expect(state.touched).toBe(false);expect(state.status).toBe('idle');expect(state.issues).toHaveLength(0);});
 test('converts validator exceptions into field errors',async()=>{const state=await createFormFieldModel({id:'x',label:'X',validators:[()=>{throw new Error('Servis doğrulaması başarısız');}]}).validate();expect(state.status).toBe('invalid');expect(state.errorMessage).toBe('Servis doğrulaması başarısız');});
 test('suppresses stale async validation and aborts previous signal',async()=>{let signal:AbortSignal|undefined;let release:(()=>void)|undefined;const gate=new Promise<void>((resolve)=>{release=resolve;});const validator:FieldValidator=async(context)=>{signal=context.signal;await gate;return context.value==='old'?error('stale','Eski sonuç'):null;};const model=createFormFieldModel({id:'x',label:'X',validators:[validator],validateOn:['change']});const first=model.setValue('old');await Promise.resolve();const second=model.setValue('new');expect(signal?.aborted).toBe(true);release?.();await Promise.all([first,second]);expect(model.getState().value).toBe('new');expect(model.getState().errorMessage).toBeNull();});
 test('dispose aborts active work and prevents later writes',async()=>{let signal:AbortSignal|undefined;let release:(()=>void)|undefined;const gate=new Promise<void>((resolve)=>{release=resolve;});const validator:FieldValidator=async(context)=>{signal=context.signal;await gate;return null;};const model=createFormFieldModel({id:'x',label:'X',initialValue:'a',validators:[validator]});const pending=model.validate();await Promise.resolve();model.dispose();expect(signal?.aborted).toBe(true);await model.setValue('b');expect(model.getState().value).toBe('a');release?.();await pending;});
 test('rejects missing identity metadata',()=>{expect(()=>createFormFieldModel({id:'',label:'X'})).toThrow(/id is required/);expect(()=>createFormFieldModel({id:'x',label:''})).toThrow(/label is required/);});
});
