import assert from 'node:assert/strict';
import test from 'node:test';
import { auditAccessibility } from './accessibility-audit.mts';
import type { FileKind, RepositoryInventory, SourceFile } from './contracts.mts';
function source(path: string, text: string, kind: FileKind = 'typescript'): SourceFile { return { absolutePath: `/repo/${path}`, repositoryPath: path, extension: path.includes('.') ? `.${path.split('.').pop() ?? ''}` : '', kind, bytes: new TextEncoder().encode(text).byteLength, lines: text.split(/\r?\n/).length, text }; }
function inventory(files: readonly SourceFile[]): RepositoryInventory { return { root: '/repo', files, ignoredDirectories: [], languageStats: [], totalFiles: files.length, totalLines: files.reduce((sum, file) => sum + file.lines, 0), totalBytes: files.reduce((sum, file) => sum + file.bytes, 0), generatedAt: '2026-09-16T00:00:00.000Z' }; }
function ids(section: ReturnType<typeof auditAccessibility>): string[] { return section.findings.map(item => item.id); }
test('flags positive tabindex and preserves source line', () => { const section = auditAccessibility(inventory([source('Webclient.app/src/Panel.tsx', `export function Panel() {\n  return <div tabIndex={3}>A</div>;\n}`)])); const item = section.findings.find(candidate => candidate.id === 'a11y-positive-tabindex'); assert.ok(item); assert.equal(item.location?.line, 2); assert.equal(item.severity, 'high'); });
test('flags pointer-only div interactions', () => { assert.ok(ids(auditAccessibility(inventory([source('Webclient.app/src/Card.tsx', `<div onClick={() => open()}>Open</div>`)]))).includes('a11y-nonsemantic-click-target')); });
test('accepts complete nonsemantic keyboard contract', () => { assert.ok(!ids(auditAccessibility(inventory([source('Webclient.app/src/Card.tsx', `<div role="button" tabIndex={0} onClick={open} onKeyDown={key}>Open</div>`)]))).includes('a11y-nonsemantic-click-target')); });
test('flags target blank without opener isolation', () => { assert.ok(ids(auditAccessibility(inventory([source('Webclient.app/src/Link.tsx', `<a href="/help" target="_blank">Help</a>`)]))).includes('a11y-external-link-isolation')); });
test('accepts target blank with noopener', () => { assert.ok(!ids(auditAccessibility(inventory([source('Webclient.app/src/Link.tsx', `<a href="/help" target="_blank" rel="noopener noreferrer">Help</a>`)]))).includes('a11y-external-link-isolation')); });
test('flags image without alt', () => { const section = auditAccessibility(inventory([source('Webclient.app/src/Image.tsx', `<><img src="a.png"/><img src="b.png" alt="" /></>`)])); assert.equal(section.findings.filter(item => item.id === 'a11y-image-alt-contract').length, 1); });
test('flags implicit button type', () => { const section = auditAccessibility(inventory([source('Webclient.app/src/Form.tsx', `<form><button>Reset</button><button type="submit">Save</button></form>`)])); assert.equal(section.findings.filter(item => item.id === 'a11y-button-type-contract').length, 1); });
test('accepts static label association', () => { assert.ok(!ids(auditAccessibility(inventory([source('Webclient.app/src/Form.tsx', `<><label htmlFor="name">Name</label><input id="name" /></>`)]))).includes('a11y-form-control-name')); });
test('flags unnamed form control', () => { assert.ok(ids(auditAccessibility(inventory([source('Webclient.app/src/Form.tsx', `<input value={value} onChange={change} />`)]))).includes('a11y-form-control-name')); });
test('flags autofocus', () => { assert.ok(ids(auditAccessibility(inventory([source('Webclient.app/src/Dialog.tsx', `<input autoFocus aria-label="Search" />`)]))).includes('a11y-autofocus')); });
test('flags focus outline suppression', () => { assert.ok(ids(auditAccessibility(inventory([source('Webclient.app/src/panel.css', `.button:focus { outline: none; }`, 'css')]))).includes('a11y-focus-indicator-suppression')); });
test('accepts replacement focus-visible ring', () => { assert.ok(!ids(auditAccessibility(inventory([source('Webclient.app/src/panel.css', `.button:focus-visible { outline: none; box-shadow: 0 0 0 3px currentColor; }`, 'css')]))).includes('a11y-focus-indicator-suppression')); });
test('flags motion stylesheet without reduced-motion contract', () => { const section = auditAccessibility(inventory([source('Webclient.app/src/panel.css', `.panel { transition: transform 200ms ease; }`, 'css')])); assert.ok(ids(section).includes('a11y-reduced-motion-contract')); assert.equal(section.summary.motionDeclarations, 1); });
test('accepts reduced-motion contract', () => { const section = auditAccessibility(inventory([source('Webclient.app/src/panel.css', `.panel { transition: transform 200ms ease; } @media (prefers-reduced-motion: reduce) { .panel { transition: none; } }`, 'css')])); assert.ok(!ids(section).includes('a11y-reduced-motion-contract')); });
test('counts forced-colors contracts', () => { const section = auditAccessibility(inventory([source('Webclient.app/src/panel.css', `@media (forced-colors: active) { button { border: 1px solid ButtonText; } }`, 'css')])); assert.equal(section.summary.forcedColorContracts, 1); });
test('blocks viewport zoom disabling', () => { const section = auditAccessibility(inventory([source('Webclient.app/index.html', `<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">`, 'html')])); const item = section.findings.find(candidate => candidate.id === 'a11y-viewport-zoom-disabled'); assert.ok(item); assert.equal(item.severity, 'critical'); assert.equal(item.blocking, true); });
test('accepts zoomable viewport', () => { assert.ok(!ids(auditAccessibility(inventory([source('Webclient.app/index.html', `<meta name="viewport" content="width=device-width, initial-scale=1">`, 'html')]))).includes('a11y-viewport-zoom-disabled')); });
test('ignores test fixtures', () => { const section = auditAccessibility(inventory([source('Webclient.app/src/__tests__/bad.fixture.tsx', `<div tabIndex={4} onClick={x}><img src="x" /></div>`)])); assert.equal(section.findings.length, 0); });
test('reports deterministic rule counts', () => { const section = auditAccessibility(inventory([source('Webclient.app/src/Panel.tsx', `<><img src="a"/><img src="b"/><button>Go</button></>`)])); assert.deepEqual(section.summary.findingsByRule, { 'a11y-button-type-contract': 1, 'a11y-image-alt-contract': 2 }); });
