import { stableSortFindings, type AuditSection, type Finding, type RepositoryInventory, type SourceFile } from './contracts.mts';
import { snippetAround } from './inventory.mts';

interface DownloadStep { readonly file: SourceFile; readonly line:number; readonly offset:number; readonly ref:string; readonly body:string }
export interface ArtifactDownloadSummary { readonly workflowFiles:number; readonly downloadSteps:number; readonly findings:readonly Finding[] }
const WF=/^\.github\/workflows\/[^/]+\.ya?ml$/i, USE=/^\s*-\s+uses\s*:\s*actions\/download-artifact@([^\s#]+)/i;
function steps(file:SourceFile):DownloadStep[]{const lines=file.text.split('\n');let offset=0;const out:DownloadStep[]=[];for(let i=0;i<lines.length;i++){const line=lines[i]!,m=line.match(USE);if(m){const indent=line.match(/^\s*/)?.[0].length??0;let j=i+1;while(j<lines.length&&!(/^\s*-\s+/.test(lines[j]!)&&((lines[j]!.match(/^\s*/)?.[0].length??0)<=indent)))j++;out.push({file,line:i+1,offset,ref:m[1]??'',body:lines.slice(i,j).join('\n')});}offset+=line.length+1;}return out;}
function value(body:string,key:string):string|undefined{return body.match(new RegExp(`^\\s*${key}\\s*:\\s*(.+)$`,'im'))?.[1]?.trim().replace(/^['"]|['"]$/g,'');}
function untrusted(v:string|undefined){return Boolean(v&&/\$\{\{[^}]*?(?:github\.event\.|github\.head_ref|inputs\.)/i.test(v));}
function finding(s:DownloadStep,id:string,severity:Finding['severity'],title:string,message:string,blocking:boolean):Finding{return{id,domain:'security',severity,blocking,title,message,location:{file:s.file.repositoryPath,line:s.line},evidence:{excerpt:snippetAround(s.file.text,s.offset,220)},remediation:'Bind artifact consumption to immutable reviewed producer identity, selection, destination and run provenance.',tags:['ci','workflow','artifact','provenance','supply-chain']};}
function auditStep(s:DownloadStep):Finding[]{const r:Finding[]=[];const name=value(s.body,'name'),pattern=value(s.body,'pattern'),path=value(s.body,'path'),repo=value(s.body,'repository'),run=value(s.body,'run-id'),token=value(s.body,'github-token'),merge=value(s.body,'merge-multiple');const privileged=/permissions\s*:\s*write-all|(?:contents|packages|actions|deployments|id-token|checks)\s*:\s*write/i.test(s.file.text);if(!/^[0-9a-f]{40}$/i.test(s.ref))r.push(finding(s,'ci-artifact-download-action-mutable-ref','critical','Artifact download action is mutable','Mutable action identity can replace code at the artifact trust boundary.',true));if(!name&&!pattern)r.push(finding(s,'ci-artifact-download-selection-unbounded',privileged?'critical':'high','Artifact selection is unbounded','Downloading all artifacts makes producer purpose ambiguous.',privileged));if(untrusted(name)||untrusted(pattern))r.push(finding(s,'ci-artifact-download-name-untrusted','critical','Artifact selector is attacker controlled','Untrusted event data can redirect artifact selection.',true));if(untrusted(path))r.push(finding(s,'ci-artifact-download-path-untrusted','critical','Artifact destination is attacker controlled','Untrusted extraction paths can overwrite sensitive workspace state.',true));if(path&&/(?:^|[\\/])(?:\.git|\.ssh|\.gnupg|\.aws)(?:[\\/]|$)/i.test(path))r.push(finding(s,'ci-artifact-download-sensitive-path','critical','Artifact targets sensitive path','Artifact extraction can mutate repository or credential control state.',true));if(/^(true|yes|on|1)$/i.test(merge??''))r.push(finding(s,'ci-artifact-download-merge-multiple',privileged?'high':'medium','Artifacts merge into one directory','Merging erases producer filesystem boundaries.',privileged));if(repo){r.push(finding(s,'ci-artifact-download-cross-repository',privileged?'high':'medium','Artifact crosses repository boundary','Cross-repository consumption requires explicit producer and credential review.',privileged));if(untrusted(repo))r.push(finding(s,'ci-artifact-download-repository-untrusted','critical','Artifact repository is attacker controlled','Untrusted repository selection crosses trust domains.',true));if(!token)r.push(finding(s,'ci-artifact-download-cross-repository-token-missing','high','Cross-repository token is implicit','Credential authority is not explicit.',privileged));if(!run)r.push(finding(s,'ci-artifact-download-run-id-missing',privileged?'critical':'high','Cross-repository run identity is missing','Repository identity does not prove producer execution.',privileged));}if(untrusted(run))r.push(finding(s,'ci-artifact-download-run-id-untrusted','critical','Artifact run id is attacker controlled','Untrusted run selection can consume unreviewed producer output.',true));return r;}
export function auditArtifactDownloadProvenance(inventory:RepositoryInventory):AuditSection<ArtifactDownloadSummary>{const started=performance.now(),files=inventory.files.filter(f=>WF.test(f.repositoryPath)),all=files.flatMap(steps),findings=stableSortFindings(all.flatMap(auditStep));return{domain:'security',title:'Artifact download provenance audit',summary:{workflowFiles:files.length,downloadSteps:all.length,findings},findings,elapsedMs:Math.max(0,performance.now()-started)};}
