import assert from 'node:assert/strict'; import test from 'node:test'; import type {RepositoryInventory,SourceFile} from './contracts.mts'; import {auditArtifactDownloadProvenance} from './artifact-download-provenance-audit.mts';
function src(text:string):SourceFile{return{repositoryPath:'.github/workflows/release.yml',absolutePath:'/repo/.github/workflows/release.yml',extension:'.yml',kind:'yaml',bytes:Buffer.byteLength(text),lines:text.split('\n').length,text};} function inv(f:SourceFile):RepositoryInventory{return{root:'/repo',files:[f],ignoredDirectories:[],languageStats:[],totalFiles:1,totalLines:f.lines,totalBytes:f.bytes,generatedAt:'2026-10-01T00:00:00Z'};} const SHA='0123456789abcdef0123456789abcdef01234567'; function ids(body:string){return auditArtifactDownloadProvenance(inv(src(`on:\n  push:\npermissions:\n  contents: write\njobs:\n  x:\n    steps:\n${body}`))).findings.map(x=>x.id);}
test('accepts pinned named same-run artifact',()=>assert.deepEqual(ids(`      - uses: actions/download-artifact@${SHA}\n        with:\n          name: release`),[]));
test('rejects mutable action',()=>assert.ok(ids('      - uses: actions/download-artifact@v4').includes('ci-artifact-download-action-mutable-ref')));
test('rejects unbounded selection',()=>assert.ok(ids(`      - uses: actions/download-artifact@${SHA}`).includes('ci-artifact-download-selection-unbounded')));
test('rejects untrusted selector',()=>assert.ok(ids(`      - uses: actions/download-artifact@${SHA}\n        with:\n          name: \${{ inputs.name }}`).includes('ci-artifact-download-name-untrusted')));
test('rejects untrusted destination',()=>assert.ok(ids(`      - uses: actions/download-artifact@${SHA}\n        with:\n          name: x\n          path: \${{ github.event.issue.body }}`).includes('ci-artifact-download-path-untrusted')));
test('rejects sensitive extraction path',()=>assert.ok(ids(`      - uses: actions/download-artifact@${SHA}\n        with:\n          name: x\n          path: .git/hooks`).includes('ci-artifact-download-sensitive-path')));
test('reviews merged artifacts',()=>assert.ok(ids(`      - uses: actions/download-artifact@${SHA}\n        with:\n          pattern: release-linux-*\n          merge-multiple: true`).includes('ci-artifact-download-merge-multiple')));
test('requires cross repository token and run identity',()=>{const r=ids(`      - uses: actions/download-artifact@${SHA}\n        with:\n          name: x\n          repository: trusted/producer`);assert.ok(r.includes('ci-artifact-download-cross-repository-token-missing'));assert.ok(r.includes('ci-artifact-download-run-id-missing'));});
test('rejects untrusted repository and run id',()=>{const r=ids(`      - uses: actions/download-artifact@${SHA}\n        with:\n          name: x\n          repository: \${{ inputs.repository }}\n          run-id: \${{ github.event.pull_request.head.sha }}\n          github-token: \${{ secrets.TOKEN }}`);assert.ok(r.includes('ci-artifact-download-repository-untrusted'));assert.ok(r.includes('ci-artifact-download-run-id-untrusted'));});
