import assert from 'node:assert/strict';
import test from 'node:test';
import { auditCompositeActions } from './composite-action-audit.mts';
import { fixtureInventory, type FixtureFileInput } from './test-helpers.mts';
function audit(text: string, path = '.github/actions/release/action.yml') { return auditCompositeActions(fixtureInventory([{ path, text }] as readonly FixtureFileInput[])); }
function finding(text: string, id: string) { return audit(text).findings.find(item => item.id === id); }
const sha = '0123456789abcdef0123456789abcdef01234567';
const header = `name: Release helper\ndescription: Safe release helper\ninputs:\n  value:\n    description: value\n    required: true\nruns:\n  using: composite\n  steps:\n`;
test('blocks composite input interpolation into run', () => { const result = finding(`${header}    - shell: bash\n      run: echo "\${{ inputs.value }}"\n`, 'ci-composite-shell-injection'); assert.equal(result?.severity, 'critical'); assert.equal(result?.blocking, true); });
test('blocks multiline composite input interpolation into run', () => { assert.equal(finding(`${header}    - shell: bash\n      run: |\n        printf '%s\\n' "\${{ inputs.value }}"\n`, 'ci-composite-shell-injection')?.blocking, true); });
for (const [name, expression] of [['PR title','github.event.pull_request.title'],['PR body','github.event.pull_request.body'],['issue title','github.event.issue.title'],['comment','github.event.comment.body'],['review','github.event.review.body'],['review comment','github.event.review_comment.body'],['discussion','github.event.discussion.body'],['head ref','github.head_ref']] as const) test(`blocks ${name} in composite run`, () => { assert.ok(finding(`${header}    - shell: bash\n      run: echo "\${{ ${expression} }}"\n`, 'ci-composite-shell-injection')); });
test('accepts composite input passed as environment data', () => { assert.equal(audit(`${header}    - shell: bash\n      run: printf '%s\\n' "$VALUE"\n      env:\n        VALUE: \${{ inputs.value }}\n`).findings.some(item => item.id === 'ci-composite-shell-injection'), false); });
test('accepts attacker event text passed as environment data', () => { assert.deepEqual(audit(`${header}    - shell: bash\n      run: printf '%s\\n' "$TITLE"\n      env:\n        TITLE: \${{ github.event.pull_request.title }}\n`).findings, []); });
test('blocks dynamic action identity from composite input', () => { assert.equal(finding(`${header}    - uses: \${{ inputs.value }}\n`, 'ci-composite-dynamic-action')?.blocking, true); });
test('blocks expression embedded in action identity', () => { assert.ok(finding(`${header}    - uses: vendor/action@\${{ github.sha }}\n`, 'ci-composite-dynamic-action')); });
test('accepts literal SHA pinned action identity', () => { assert.deepEqual(audit(`${header}    - uses: actions/checkout@${sha}\n`).findings, []); });
test('blocks dynamic shell selection', () => { assert.ok(finding(`${header}    - shell: \${{ inputs.value }}\n      run: echo ok\n`, 'ci-composite-dynamic-shell')); });
test('blocks dynamic image selection', () => { assert.ok(finding(`name: Docker\nruns:\n  using: docker\n  image: \${{ inputs.image }}\n`, 'ci-composite-dynamic-container')); });
test('blocks input spliced into pinned github-script', () => { assert.equal(finding(`${header}    - uses: actions/github-script@${sha}\n      with:\n        script: |\n          console.log("\${{ inputs.value }}");\n`, 'ci-composite-github-script-injection')?.blocking, true); });
test('accepts github-script reading input through env', () => { assert.equal(audit(`${header}    - uses: actions/github-script@${sha}\n      env:\n        VALUE: \${{ inputs.value }}\n      with:\n        script: console.log(process.env.VALUE)\n`).findings.some(item => item.id === 'ci-composite-github-script-injection'), false); });
test('does not leak github-script state into sibling step', () => { assert.equal(audit(`${header}    - uses: actions/github-script@${sha}\n      with:\n        script: console.log('safe')\n    - name: unrelated\n      with:\n        script: \${{ inputs.value }}\n      run: echo safe\n`).findings.some(item => item.id === 'ci-composite-github-script-injection'), false); });
test('ignores workflow yaml', () => { const result = audit(`${header}    - run: echo "\${{ inputs.value }}"\n`, '.github/workflows/release.yml'); assert.equal(result.summary.actionFiles, 0); });
test('ignores action metadata outside canonical directory', () => { assert.equal(audit(`${header}    - run: echo "\${{ inputs.value }}"\n`, 'tools/actions/release/action.yml').summary.actionFiles, 0); });
test('recognizes action.yaml extension', () => { assert.equal(audit(`${header}    - run: echo "\${{ inputs.value }}"\n`, '.github/actions/release/action.yaml').summary.actionFiles, 1); });
test('reports counters deterministically', () => { const result = audit(`${header}    - shell: \${{ inputs.value }}\n      run: echo \${{ inputs.value }}\n    - uses: vendor/action@\${{ github.sha }}\n`); assert.equal(result.summary.executableExpressions, 3); assert.equal(result.summary.actions[0]?.dynamicUses, 1); });
test('sorts findings deterministically', () => { const ids = audit(`${header}    - shell: \${{ inputs.value }}\n      run: echo \${{ inputs.value }}\n    - uses: vendor/action@\${{ github.sha }}\n`).findings.map(item => item.id); assert.deepEqual(ids, [...ids].sort((left, right) => left.localeCompare(right, 'en'))); });
