import { stableSortFindings, type AuditSection, type Finding, type RepositoryInventory } from './contracts.mts';
import { workflowFiles, workflowJobBlocks, workflowTriggerProfile, type WorkflowJobBlock } from './workflow-structure.mts';

export interface JobResourceSignal { readonly file: string; readonly job: string; readonly timeoutMinutes?: number; readonly dynamicTimeout: boolean; readonly externalContribution: boolean; readonly selfHosted: boolean; readonly serviceContainers: boolean; readonly matrix: boolean; readonly maxParallel?: number; readonly dynamicMaxParallel: boolean; readonly networkWait: boolean; readonly backgroundProcess: boolean; }
export interface JobResourceBoundarySummary { readonly workflowFiles: number; readonly jobs: number; readonly boundedJobs: number; readonly unboundedExternalJobs: number; readonly dynamicResourcePolicies: number; readonly signals: readonly JobResourceSignal[]; readonly findings: readonly Finding[]; }
const TIMEOUT = /^\s*timeout-minutes\s*:\s*([^\n#]+).*$/im; const RUNS_ON = /^\s*runs-on\s*:\s*([^\n#]+).*$/im; const SELF_HOSTED = /(?:^|[\[,'"\s])self-hosted(?:$|[\],'"\s])/i; const SERVICES = /^\s*services\s*:/im; const MATRIX = /^\s*matrix\s*:/im; const MAX_PARALLEL = /^\s*max-parallel\s*:\s*([^\n#]+).*$/im; const EXPRESSION = /\$\{\{/; const NETWORK_WAIT = /(?:\bcurl\b|\bwget\b|Invoke-WebRequest|Invoke-RestMethod|\bgh\s+(?:api|release|run|workflow)\b|docker\s+(?:pull|push|login)\b|npm\s+(?:publish|pack)\b|dotnet\s+(?:restore|nuget\s+push)\b)/i; const BACKGROUND_PROCESS = /(?:^|\n)\s*(?:-\s+run:\s*)?(?:nohup\s+)?[^\n]*\s&\s*(?:#.*)?$|\bStart-Process\b|\b(?:docker\s+compose\s+up|docker-compose\s+up)\b/im;
function scalar(block: WorkflowJobBlock, pattern: RegExp): string | undefined { return block.text.match(pattern)?.[1]?.trim(); }
function positiveInteger(value: string | undefined): number | undefined { if (!value || EXPRESSION.test(value) || !/^\d+$/.test(value)) return undefined; const parsed = Number(value); return Number.isSafeInteger(parsed) && parsed > 0 ? parsed : undefined; }
function signal(block: WorkflowJobBlock): JobResourceSignal { const timeoutRaw = scalar(block, TIMEOUT); const maxParallelRaw = scalar(block, MAX_PARALLEL); const trigger = workflowTriggerProfile(block.file); const runner = scalar(block, RUNS_ON) ?? ''; const timeout = positiveInteger(timeoutRaw); const maxParallel = positiveInteger(maxParallelRaw); return { file: block.file.repositoryPath, job: block.name, ...(timeout !== undefined ? { timeoutMinutes: timeout } : {}), dynamicTimeout: Boolean(timeoutRaw && EXPRESSION.test(timeoutRaw)), externalContribution: trigger.externalContribution, selfHosted: SELF_HOSTED.test(runner), serviceContainers: SERVICES.test(block.text), matrix: MATRIX.test(block.text), ...(maxParallel !== undefined ? { maxParallel } : {}), dynamicMaxParallel: Boolean(maxParallelRaw && EXPRESSION.test(maxParallelRaw)), networkWait: NETWORK_WAIT.test(block.text), backgroundProcess: BACKGROUND_PROCESS.test(block.text) }; }
function location(block: WorkflowJobBlock) { return { file: block.file.repositoryPath, line: block.startLine }; }
function findingsFor(block: WorkflowJobBlock): Finding[] { const current = signal(block); const findings: Finding[] = []; const at = location(block); const timeoutRaw = scalar(block, TIMEOUT); const maxParallelRaw = scalar(block, MAX_PARALLEL);
  if (current.dynamicTimeout) findings.push({ id: 'ci-resource-dynamic-timeout', domain: 'build', severity: 'high', title: 'Job timeout is expression-controlled', message: `Job ${block.name} derives timeout-minutes from runtime data, allowing resource and release latency policy to drift outside reviewed source.`, location: at, remediation: 'Use a literal reviewed timeout-minutes value. Split materially different workload classes into separate jobs with explicit budgets.', tags: ['ci','resource','timeout','expression','reliability'] });
  else if (timeoutRaw && current.timeoutMinutes === undefined) findings.push({ id: 'ci-resource-invalid-timeout', domain: 'build', severity: 'high', title: 'Job timeout is not a positive literal integer', message: `Job ${block.name} declares a timeout that cannot be admitted as a positive literal minute budget.`, location: at, remediation: 'Set timeout-minutes to a positive literal integer appropriate for the workload.', tags: ['ci','resource','timeout','validation'] });
  else if ((current.timeoutMinutes ?? 0) > 120) findings.push({ id: 'ci-resource-excessive-timeout', domain: 'build', severity: 'medium', title: 'Job timeout exceeds the bounded CI budget', message: `Job ${block.name} can retain runner capacity for ${current.timeoutMinutes} minutes.`, location: at, remediation: 'Reduce the timeout to at most 120 minutes or split the workload into independently bounded jobs with artifacts/checkpoints.', tags: ['ci','resource','timeout','capacity'] });
  const needsExplicitTimeout = current.externalContribution || current.selfHosted || current.serviceContainers || current.networkWait || current.backgroundProcess;
  if (timeoutRaw === undefined && needsExplicitTimeout) findings.push({ id: 'ci-resource-unbounded-job', domain: 'build', severity: current.externalContribution || current.selfHosted ? 'high' : 'medium', title: 'Resource-sensitive CI job has no explicit timeout', message: `Job ${block.name} performs externally influenced, persistent-runner, service, network, or background-process work without an explicit timeout-minutes budget.`, location: at, remediation: 'Set a literal timeout-minutes budget sized to the expected workload and keep retries/waits independently bounded.', tags: ['ci','resource','timeout','availability'] });
  if (current.dynamicMaxParallel) findings.push({ id: 'ci-resource-dynamic-matrix-parallelism', domain: 'build', severity: 'high', title: 'Matrix concurrency budget is expression-controlled', message: `Job ${block.name} derives max-parallel from runtime data, allowing fan-out pressure to escape reviewed capacity limits.`, location: at, remediation: 'Use a literal max-parallel value and keep matrix cardinality independently bounded.', tags: ['ci','resource','matrix','concurrency','expression'] });
  else if (maxParallelRaw && current.maxParallel === undefined) findings.push({ id: 'ci-resource-invalid-matrix-parallelism', domain: 'build', severity: 'high', title: 'Matrix max-parallel is not a positive literal integer', message: `Job ${block.name} declares a matrix concurrency value that cannot be admitted as a positive literal budget.`, location: at, remediation: 'Set max-parallel to a positive literal integer.', tags: ['ci','resource','matrix','concurrency','validation'] });
  else if ((current.maxParallel ?? 0) > 32) findings.push({ id: 'ci-resource-excessive-matrix-parallelism', domain: 'build', severity: 'medium', title: 'Matrix parallelism exceeds the bounded CI budget', message: `Job ${block.name} permits ${current.maxParallel} concurrent matrix children.`, location: at, remediation: 'Cap max-parallel at 32 or lower based on runner and external-service capacity.', tags: ['ci','resource','matrix','concurrency','capacity'] });
  else if (current.matrix && maxParallelRaw === undefined) findings.push({ id: 'ci-resource-unbounded-matrix-parallelism', domain: 'build', severity: 'low', title: 'Matrix job has no explicit parallelism cap', message: `Job ${block.name} declares a matrix without max-parallel, so fan-out pressure follows matrix cardinality and platform capacity.`, location: at, remediation: 'Declare a literal max-parallel budget sized to repository and external-service capacity.', tags: ['ci','resource','matrix','concurrency'] }); return findings; }
export function auditJobResourceBoundaries(inventory: RepositoryInventory): AuditSection<JobResourceBoundarySummary> { const started = performance.now(); const files = workflowFiles(inventory); const jobs = files.flatMap(file => workflowJobBlocks(file)); const signals = jobs.map(signal); const findings = stableSortFindings(jobs.flatMap(findingsFor)); return { domain: 'build', title: 'CI job resource-boundary audit', summary: { workflowFiles: files.length, jobs: jobs.length, boundedJobs: signals.filter(item => item.timeoutMinutes !== undefined).length, unboundedExternalJobs: signals.filter(item => item.externalContribution && item.timeoutMinutes === undefined).length, dynamicResourcePolicies: signals.filter(item => item.dynamicTimeout || item.dynamicMaxParallel).length, signals, findings }, findings, elapsedMs: Math.max(0, performance.now() - started) }; }
