import assert from 'node:assert/strict';
import test from 'node:test';
import type { RepositoryInventory, SourceFile } from './contracts.mts';
import { auditJobResourceBoundaries } from './job-resource-boundary-audit.mts';
function inventory(text: string): RepositoryInventory { const path = '.github/workflows/ci.yml'; const lines = text.split('\n').length; const bytes = Buffer.byteLength(text); const file: SourceFile = { repositoryPath: path, absolutePath: `/repo/${path}`, extension: '.yml', kind: 'yaml', bytes, lines, text }; return { root: '/repo', files: [file], ignoredDirectories: [], languageStats: [{ kind: 'yaml', files: 1, lines, bytes }], totalFiles: 1, totalLines: lines, totalBytes: bytes, generatedAt: '2026-09-29T00:00:00.000Z' }; }
function audit(text: string) { return auditJobResourceBoundaries(inventory(text)); }
function ids(text: string) { return audit(text).findings.map(item => item.id); }
test('reports externally influenced job without explicit timeout', () => { assert.ok(ids(`on: pull_request\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - run: npm test\n`).includes('ci-resource-unbounded-job')); });
test('accepts bounded externally influenced job', () => { assert.equal(ids(`on: pull_request\njobs:\n  test:\n    runs-on: ubuntu-latest\n    timeout-minutes: 20\n    steps:\n      - run: npm test\n`).includes('ci-resource-unbounded-job'), false); });
test('reports self-hosted job without timeout', () => { assert.ok(ids(`on: push\njobs:\n  build:\n    runs-on: self-hosted\n    steps:\n      - run: npm test\n`).includes('ci-resource-unbounded-job')); });
test('reports network operation without timeout', () => { assert.ok(ids(`on: push\njobs:\n  publish:\n    runs-on: ubuntu-latest\n    steps:\n      - run: npm publish\n`).includes('ci-resource-unbounded-job')); });
test('reports service-container job without timeout', () => { assert.ok(ids(`on: push\njobs:\n  integration:\n    runs-on: ubuntu-latest\n    services:\n      db:\n        image: postgres:17\n    steps:\n      - run: npm test\n`).includes('ci-resource-unbounded-job')); });
test('reports background process without timeout', () => { assert.ok(ids(`on: push\njobs:\n  e2e:\n    runs-on: ubuntu-latest\n    steps:\n      - run: npm start &\n`).includes('ci-resource-unbounded-job')); });
test('reports expression-derived timeout', () => { assert.ok(ids(`on: workflow_dispatch\njobs:\n  test:\n    runs-on: ubuntu-latest\n    timeout-minutes: \${{ inputs.timeout }}\n    steps:\n      - run: npm test\n`).includes('ci-resource-dynamic-timeout')); });
test('reports zero timeout as invalid', () => { assert.ok(ids(`on: push\njobs:\n  test:\n    runs-on: ubuntu-latest\n    timeout-minutes: 0\n    steps:\n      - run: npm test\n`).includes('ci-resource-invalid-timeout')); });
test('reports excessive timeout', () => { assert.ok(ids(`on: push\njobs:\n  test:\n    runs-on: ubuntu-latest\n    timeout-minutes: 360\n    steps:\n      - run: npm test\n`).includes('ci-resource-excessive-timeout')); });
test('accepts timeout at upper budget', () => { assert.equal(ids(`on: push\njobs:\n  test:\n    runs-on: ubuntu-latest\n    timeout-minutes: 120\n    steps:\n      - run: npm test\n`).includes('ci-resource-excessive-timeout'), false); });
test('reports matrix without max-parallel', () => { assert.ok(ids(`on: push\njobs:\n  test:\n    strategy:\n      matrix:\n        node: [20, 22, 24]\n    runs-on: ubuntu-latest\n    timeout-minutes: 20\n    steps:\n      - run: npm test\n`).includes('ci-resource-unbounded-matrix-parallelism')); });
test('reports expression-derived max-parallel', () => { assert.ok(ids(`on: push\njobs:\n  test:\n    strategy:\n      max-parallel: \${{ inputs.parallel }}\n      matrix:\n        node: [20, 22]\n    runs-on: ubuntu-latest\n    timeout-minutes: 20\n    steps:\n      - run: npm test\n`).includes('ci-resource-dynamic-matrix-parallelism')); });
test('reports invalid matrix parallelism', () => { assert.ok(ids(`on: push\njobs:\n  test:\n    strategy:\n      max-parallel: 0\n      matrix:\n        node: [20]\n    runs-on: ubuntu-latest\n    timeout-minutes: 20\n    steps:\n      - run: npm test\n`).includes('ci-resource-invalid-matrix-parallelism')); });
test('reports excessive matrix parallelism', () => { assert.ok(ids(`on: push\njobs:\n  test:\n    strategy:\n      max-parallel: 64\n      matrix:\n        node: [20]\n    runs-on: ubuntu-latest\n    timeout-minutes: 20\n    steps:\n      - run: npm test\n`).includes('ci-resource-excessive-matrix-parallelism')); });
test('accepts bounded matrix policy', () => { const result = audit(`on: push\njobs:\n  test:\n    strategy:\n      max-parallel: 8\n      matrix:\n        node: [20, 22, 24]\n    runs-on: ubuntu-latest\n    timeout-minutes: 30\n    steps:\n      - run: npm test\n`); assert.equal(result.findings.length, 0); assert.equal(result.summary.boundedJobs, 1); });
test('summary tracks dynamic and external resource policy', () => { const result = audit(`on: pull_request\njobs:\n  dynamic:\n    strategy:\n      max-parallel: \${{ inputs.parallel }}\n      matrix:\n        node: [20]\n    runs-on: ubuntu-latest\n    timeout-minutes: \${{ inputs.timeout }}\n    steps:\n      - run: npm test\n  bounded:\n    runs-on: ubuntu-latest\n    timeout-minutes: 15\n    steps:\n      - run: npm test\n`); assert.equal(result.summary.jobs, 2); assert.equal(result.summary.boundedJobs, 1); assert.equal(result.summary.unboundedExternalJobs, 1); assert.equal(result.summary.dynamicResourcePolicies, 1); });
test('finding order is deterministic', () => { const workflow = `on: pull_request\njobs:\n  test:\n    strategy:\n      matrix:\n        node: [20, 22]\n    runs-on: self-hosted\n    steps:\n      - run: npm publish\n`; assert.deepEqual(audit(workflow).findings.map(item => item.id), audit(workflow).findings.map(item => item.id)); });
