import { stableSortFindings, type AuditSection, type Finding, type RepositoryInventory, type SourceFile } from './contracts.mts';

export interface NodeExecutionSignal {
  readonly file: string; readonly evalCalls: number; readonly functionConstructors: number;
  readonly vmExecutions: number; readonly execCalls: number; readonly execSyncCalls: number;
  readonly shellSpawns: number; readonly dynamicImports: number; readonly dynamicRequires: number;
  readonly envCommandReferences: number;
}
export interface NodeExecutionBoundarySummary {
  readonly files: readonly NodeExecutionSignal[]; readonly scannedFiles: number;
  readonly dynamicCodeFiles: number; readonly shellExecutionFiles: number;
  readonly dynamicModuleFiles: number; readonly findings: readonly Finding[];
}
interface Rule { readonly id: string; readonly severity: Finding['severity']; readonly title: string; readonly message: string; readonly remediation: string; readonly pattern: RegExp; readonly blocking: boolean; readonly tag: string; }
const ELIGIBLE_PATH=/^(?:tools\/|quality\/|Webclient\.app\/scripts\/|Webclient\.Admin\/scripts\/|scripts\/)/i;
const SOURCE_EXT=/\.(?:[cm]?[jt]s|[cm]?tsx?)$/i;
const GENERATED=/(^|\/)(?:node_modules|dist|build|coverage|bin|obj|qa-artifacts|fixtures?)(?:\/|$)/i;
const TEST_FILE=/(?:\.test|\.spec)\.[cm]?[jt]s$/i;
const MAX_FINDINGS=32;
const FUNCTION_CONSTRUCTOR = new RegExp(String.raw`(?:\bnew\s+Fun${'ction'}\s*\(|(?<![.$\w])Fun${'ction'}\s*\()`, 'g');
const EXEC_CALL = /(?<![.$\w])exec\s*\(/g;
const EXEC_SYNC_CALL = /(?<![.$\w])execSync\s*\(/g;
const RULES: readonly Rule[]=[
{id:'node-execution-eval',severity:'critical',title:'Node tooling executes source through eval',message:'eval turns data into executable source and defeats static review of the release/tooling boundary.',remediation:'Replace eval with explicit parsing, dispatch tables or a typed interpreter for the bounded input grammar.',pattern:/\beval\s*\(/g,blocking:true,tag:'dynamic-code'},
{id:'node-execution-function-constructor',severity:'critical',title:'Node tooling constructs executable functions from strings',message:'Runtime function construction from source strings creates a code-generation boundary that static TypeScript cannot validate.',remediation:'Use typed functions selected from a closed map; do not compile source strings at runtime.',pattern:FUNCTION_CONSTRUCTOR,blocking:true,tag:'dynamic-code'},
{id:'node-execution-vm-source',severity:'critical',title:'Node tooling executes source through the vm module',message:'vm execution still interprets source text and can cross the release trust boundary when inputs are not immutable.',remediation:'Prefer structured data parsing. If isolation is unavoidable, move execution to a separately sandboxed process with an explicit immutable source allowlist.',pattern:/\b(?:vm\.)?(?:runInContext|runInNewContext|runInThisContext|compileFunction|Script)\s*\(/g,blocking:true,tag:'dynamic-code'},
{id:'node-execution-exec',severity:'medium',title:'Tooling uses shell-string child process execution',message:'Shell-string execution delegates quoting and tokenization to a shell, increasing command-injection and portability risk.',remediation:'Prefer execFile or spawn with an executable plus a typed argument array and shell=false.',pattern:EXEC_CALL,blocking:false,tag:'shell'},
{id:'node-execution-exec-sync',severity:'medium',title:'Tooling uses synchronous shell-string execution',message:'Synchronous shell-string execution combines shell parsing risk with event-loop blocking and is unsuitable for scalable release tooling.',remediation:'Prefer async execFile/spawn with explicit arguments, timeout and bounded output handling.',pattern:EXEC_SYNC_CALL,blocking:false,tag:'shell'},
{id:'node-execution-shell-true',severity:'medium',title:'Child process explicitly enables shell mode',message:'Enabling the child-process shell option reintroduces shell parsing even when safer process APIs are used.',remediation:'Keep shell=false and pass each argument as a separate reviewed value.',pattern:/\bshell\s*:\s*true\b/g,blocking:false,tag:'shell'},
{id:'node-execution-dynamic-require',severity:'low',title:'Tooling dynamically selects a CommonJS module',message:'Dynamic require keeps a CommonJS execution island and makes provenance of loaded code difficult to prove.',remediation:'Migrate to ESM and use a closed literal import map.',pattern:/\brequire\s*\(\s*(?!['"][^'"]+['"]\s*\))[^)]+\)/g,blocking:false,tag:'module-graph'}];
function eligible(f:SourceFile){return ELIGIBLE_PATH.test(f.repositoryPath)&&SOURCE_EXT.test(f.repositoryPath)&&!GENERATED.test(f.repositoryPath)&&!TEST_FILE.test(f.repositoryPath)}
function count(text:string,p:RegExp){const m=new RegExp(p.source,p.flags);let n=0;while(m.exec(text)!==null)n++;return n}
function lineAt(text:string,o:number){let n=1;for(let i=0;i<o;i++)if(text.charCodeAt(i)===10)n++;return n}
function excerpt(text:string,o:number){const s=Math.max(0,text.lastIndexOf('\n',o-1)+1),x=text.indexOf('\n',o),e=x<0?text.length:x,v=text.slice(s,e).trim().replace(/\s+/g,' ');return v.length<=180?v:`${v.slice(0,179)}…`}
function dynamicImportOffsets(text:string):number[]{const offsets:number[]=[];const matcher=/\bimport\s*\(\s*([\s\S]*?)\s*\)/g;let m:RegExpExecArray|null;while((m=matcher.exec(text))!==null){const arg=(m[1]??'').trim();const q=arg[0];const literal=(q==='\''||q==='"')&&arg.endsWith(q);const staticTemplate=q==='`'&&arg.endsWith('`')&&!arg.includes('${');if(!literal&&!staticTemplate)offsets.push(m.index);if(m[0].length===0)matcher.lastIndex++;}return offsets}
function signal(f:SourceFile):NodeExecutionSignal{return{file:f.repositoryPath,evalCalls:count(f.text,/\beval\s*\(/g),functionConstructors:count(f.text,FUNCTION_CONSTRUCTOR),vmExecutions:count(f.text,/\b(?:vm\.)?(?:runInContext|runInNewContext|runInThisContext|compileFunction|Script)\s*\(/g),execCalls:count(f.text,EXEC_CALL),execSyncCalls:count(f.text,EXEC_SYNC_CALL),shellSpawns:count(f.text,/\bshell\s*:\s*true\b/g),dynamicImports:dynamicImportOffsets(f.text).length,dynamicRequires:count(f.text,/\brequire\s*\(\s*(?!['"][^'"]+['"]\s*\))[^)]+\)/g),envCommandReferences:count(f.text,/\bprocess\.env\.[A-Za-z_][A-Za-z0-9_]*\b/g)}}
function makeFinding(f:SourceFile,r:Rule,o:number):Finding{return{id:r.id,domain:'security',severity:r.severity,...(r.blocking?{blocking:true}:{}),title:r.title,message:r.message,location:{file:f.repositoryPath,line:lineAt(f.text,o)},evidence:{excerpt:excerpt(f.text,o)},remediation:r.remediation,tags:['node','tooling','execution',r.tag]}}
function findings(f:SourceFile):Finding[]{const out:Finding[]=[];for(const r of RULES){const m=new RegExp(r.pattern.source,r.pattern.flags);let x:RegExpExecArray|null;while((x=m.exec(f.text))!==null){out.push(makeFinding(f,r,x.index));if(x[0].length===0)m.lastIndex++}}for(const o of dynamicImportOffsets(f.text))out.push(makeFinding(f,{id:'node-execution-dynamic-import',severity:'low',title:'Tooling dynamically selects an imported module',message:'Expression-derived import() makes the executable module graph harder to review and bundle deterministically.',remediation:'Use a literal import or a closed typed map from allowed names to literal imports.',pattern:/$^/,blocking:false,tag:'module-graph'},o));f.text.split(/\r?\n/).forEach((line,i)=>{if(/\bprocess\.env\.[A-Za-z_][A-Za-z0-9_]*\b/.test(line)&&/\b(?:exec|execSync|spawn|spawnSync|execFile|execFileSync)\b/.test(line))out.push({id:'node-execution-env-command-composition',domain:'security',severity:'medium',title:'Environment-derived value participates in child-process invocation',message:'Environment values are runtime input. Passing them directly into process execution requires an allowlist and argument separation.',location:{file:f.repositoryPath,line:i+1},evidence:{excerpt:line.trim().slice(0,180)},remediation:'Validate environment values against a closed allowlist and pass them only as individual arguments with shell=false.',tags:['node','tooling','execution','environment']})});return out}
function pathOrder(a:string,b:string){return a<b?-1:a>b?1:0}
export function auditNodeExecutionBoundaries(inventory:RepositoryInventory):AuditSection<NodeExecutionBoundarySummary>{const started=performance.now();const files=inventory.files.filter(eligible);const signals=files.map(signal).sort((a,b)=>pathOrder(a.file,b.file));const all=stableSortFindings(files.flatMap(findings));const blocking=all.filter(x=>x.blocking===true),review=all.filter(x=>x.blocking!==true);const result=stableSortFindings([...blocking,...review.slice(0,Math.max(0,MAX_FINDINGS-blocking.length))]);return{domain:'security',title:'Typed Node execution boundary audit',summary:{files:signals,scannedFiles:signals.length,dynamicCodeFiles:signals.filter(x=>x.evalCalls+x.functionConstructors+x.vmExecutions>0).length,shellExecutionFiles:signals.filter(x=>x.execCalls+x.execSyncCalls+x.shellSpawns>0).length,dynamicModuleFiles:signals.filter(x=>x.dynamicImports+x.dynamicRequires>0).length,findings:result},findings:result,elapsedMs:Math.max(0,performance.now()-started)}}
