import { stableSortFindings, type AuditSection, type Finding, type RepositoryInventory, type SourceFile } from './contracts.mts';
export interface PageUsabilitySignal { readonly file:string; readonly clickHandlers:number; readonly clickableNonInteractive:number; readonly imageElements:number; readonly imagesWithoutAlt:number; readonly blankTargets:number; readonly blankTargetsWithoutRel:number; readonly outlineSuppressions:number; readonly largeFixedWidths:number; readonly globalOverflowHidden:number; readonly reducedMotionContracts:number; readonly forcedColorContracts:number; readonly focusVisibleContracts:number; }
export interface PageUsabilityGovernanceSummary { readonly files:readonly PageUsabilitySignal[]; readonly componentFiles:number; readonly styleFiles:number; readonly interactionFiles:number; readonly responsiveRiskFiles:number; readonly accessibilityRiskFiles:number; readonly findings:readonly Finding[]; }
const WEB_SOURCE=/^Webclient\.app\/src\//,COMPONENT=/\.(?:tsx|jsx)$/i,STYLE=/\.css$/i,GENERATED=/(^|\/)(?:node_modules|dist|build|coverage|generated|qa-artifacts)(?:\/|$)/i,TEST_FILE=/(?:\.test|\.spec)\.(?:tsx|jsx)$/i;
const NATIVE=new Set(['button','a','input','select','textarea','summary','option']);
const CLICK=/<([A-Za-z][A-Za-z0-9.-]*)\b([^>]*\bonClick\s*=\s*\{[^}]*\}[^>]*)>/g,IMAGE=/<img\b([^>]*)>/gi,BLANK=/<a\b([^>]*\btarget\s*=\s*(?:['"]_blank['"]|\{['"]_blank['"]\})[^>]*)>/gi;
const OUTLINE=/\boutline\s*:\s*(?:none|0(?:px)?)\s*(?:!important)?(?=\s*[;}])/gi;
const WIDTH=/\b(?:width|min-width)\s*:\s*(\d+(?:\.\d+)?)px\s*(?:!important)?(?=\s*[;}])/gi;
const OVERFLOW=/(?:^|[},\s])(?:html|body|#root)\s*(?:,\s*(?:html|body|#root)\s*)*\{[^}]*\boverflow(?:-x)?\s*:\s*hidden\b/gi;
const REDUCED=/@media\s*\([^)]*prefers-reduced-motion\s*:\s*reduce[^)]*\)/gi,FORCED=/@media\s*\([^)]*forced-colors\s*:\s*active[^)]*\)/gi,FOCUS=/:focus-visible\b/gi,MAX=24;
function count(t:string,p:RegExp){const m=new RegExp(p.source,p.flags);let n=0;while(m.exec(t)!==null)n++;return n} function lineAt(t:string,o:number){let n=1;for(let i=0;i<o;i++)if(t.charCodeAt(i)===10)n++;return n} function excerpt(t:string,o:number){const s=Math.max(0,t.lastIndexOf('\n',Math.max(0,o-1))+1),x=t.indexOf('\n',o),e=x<0?t.length:x,v=t.slice(s,e).trim().replace(/\s+/g,' ');return v.length<=180?v:`${v.slice(0,179)}…`}
function components(i:RepositoryInventory){return i.files.filter(f=>WEB_SOURCE.test(f.repositoryPath)&&COMPONENT.test(f.repositoryPath)&&!GENERATED.test(f.repositoryPath)&&!TEST_FILE.test(f.repositoryPath))} function styles(i:RepositoryInventory){return i.files.filter(f=>WEB_SOURCE.test(f.repositoryPath)&&STYLE.test(f.repositoryPath)&&!GENERATED.test(f.repositoryPath))}
function keyboard(a:string){return /\bonKey(?:Down|Up|Press)\s*=/.test(a)||/\btabIndex\s*=/.test(a)||/\brole\s*=\s*(?:['"](?:button|link|menuitem|option|tab|checkbox|switch|radio)['"]|\{['"](?:button|link|menuitem|option|tab|checkbox|switch|radio)['"]\})/.test(a)}
function clickable(f:SourceFile){let n=0,m:RegExpExecArray|null,r=new RegExp(CLICK.source,CLICK.flags);while((m=r.exec(f.text))!==null){const tag=(m[1]??'').toLowerCase(),a=m[2]??'';if(!NATIVE.has(tag)&&!/^[A-Z]/.test(m[1]??'')&&!keyboard(a))n++}return n}
function missingAlt(f:SourceFile){let n=0,m:RegExpExecArray|null,r=new RegExp(IMAGE.source,IMAGE.flags);while((m=r.exec(f.text))!==null)if(!/\balt\s*=/.test(m[1]??''))n++;return n}
function blanks(f:SourceFile){let total=0,unsafe=0,m:RegExpExecArray|null,r=new RegExp(BLANK.source,BLANK.flags);while((m=r.exec(f.text))!==null){total++;const a=m[1]??'',rel=a.match(/\brel\s*=\s*(?:['"]([^'"]*)['"]|\{['"]([^'"]*)['"]\})/i),v=`${rel?.[1]??''} ${rel?.[2]??''}`.toLowerCase();if(!/\bnoopener\b/.test(v))unsafe++}return{total,unsafe}}
function widths(f:SourceFile){let n=0,m:RegExpExecArray|null,r=new RegExp(WIDTH.source,WIDTH.flags);while((m=r.exec(f.text))!==null){const v=Number.parseFloat(m[1]??'0');if(Number.isFinite(v)&&v>=720)n++}return n}
function componentSignal(f:SourceFile):PageUsabilitySignal{const b=blanks(f);return{file:f.repositoryPath,clickHandlers:count(f.text,/\bonClick\s*=/g),clickableNonInteractive:clickable(f),imageElements:count(f.text,IMAGE),imagesWithoutAlt:missingAlt(f),blankTargets:b.total,blankTargetsWithoutRel:b.unsafe,outlineSuppressions:0,largeFixedWidths:0,globalOverflowHidden:0,reducedMotionContracts:0,forcedColorContracts:0,focusVisibleContracts:0}}
function styleSignal(f:SourceFile):PageUsabilitySignal{return{file:f.repositoryPath,clickHandlers:0,clickableNonInteractive:0,imageElements:0,imagesWithoutAlt:0,blankTargets:0,blankTargetsWithoutRel:0,outlineSuppressions:count(f.text,OUTLINE),largeFixedWidths:widths(f),globalOverflowHidden:count(f.text,OVERFLOW),reducedMotionContracts:count(f.text,REDUCED),forcedColorContracts:count(f.text,FORCED),focusVisibleContracts:count(f.text,FOCUS)}}
function finding(id:string,severity:Finding['severity'],title:string,message:string,f:SourceFile,o:number,remediation:string,tags:readonly string[]):Finding{return{id,domain:tags.includes('responsive')?'responsive':'accessibility',severity,title,message,location:{file:f.repositoryPath,line:lineAt(f.text,o)},evidence:{excerpt:excerpt(f.text,o)},remediation,tags}}
function componentFindings(f:SourceFile){const out:Finding[]=[];let m:RegExpExecArray|null,r=new RegExp(CLICK.source,CLICK.flags);while((m=r.exec(f.text))!==null){const tag=(m[1]??'').toLowerCase(),a=m[2]??'';if(!NATIVE.has(tag)&&!/^[A-Z]/.test(m[1]??'')&&!keyboard(a))out.push(finding('page-usability-clickable-noninteractive','low','Clickable non-interactive element lacks an explicit keyboard contract',`A <${tag}> handles click without a native interactive element, role/tabIndex, or keyboard handler visible in the same element.`,f,m.index,'Prefer button/a. If a custom interaction is unavoidable, provide semantic role, keyboard activation, focusability and visible focus.',['page-usability','accessibility','keyboard']))}r=new RegExp(IMAGE.source,IMAGE.flags);while((m=r.exec(f.text))!==null)if(!/\balt\s*=/.test(m[1]??''))out.push(finding('page-usability-image-alt-missing','low','Image element has no explicit alt contract','Every img should declare meaningful alt text or alt="" for a decorative image so screen readers receive deterministic semantics.',f,m.index,'Add a meaningful alt value, or alt="" when the image is purely decorative and redundant with nearby content.',['page-usability','accessibility','image']));r=new RegExp(BLANK.source,BLANK.flags);while((m=r.exec(f.text))!==null){const a=m[1]??'',rel=a.match(/\brel\s*=\s*(?:['"]([^'"]*)['"]|\{['"]([^'"]*)['"]\})/i),v=`${rel?.[1]??''} ${rel?.[2]??''}`.toLowerCase();if(!/\bnoopener\b/.test(v))out.push(finding('page-usability-blank-target-noopener','low','New-tab link omits noopener','target="_blank" should make opener isolation explicit and keep navigation behavior reviewable.',f,m.index,'Add rel="noopener noreferrer" unless a documented same-origin opener relationship is required.',['page-usability','accessibility','navigation']))}return out}
function styleFindings(f:SourceFile){const out:Finding[]=[];let m:RegExpExecArray|null,r=new RegExp(OUTLINE.source,OUTLINE.flags);while((m=r.exec(f.text))!==null)out.push(finding('page-usability-outline-suppressed','info','CSS suppresses the browser outline','Removing outlines is safe only when the same component has an equally visible :focus-visible treatment.',f,m.index,'Keep the default outline or pair the suppression with an obvious focus-visible ring that survives high-contrast modes.',['page-usability','accessibility','focus']));r=new RegExp(WIDTH.source,WIDTH.flags);while((m=r.exec(f.text))!==null){const v=Number.parseFloat(m[1]??'0');if(Number.isFinite(v)&&v>=720)out.push(finding('page-usability-large-fixed-width','info','Large fixed pixel width can constrain responsive layouts',`${v}px is large enough to overflow common mobile/tablet viewports when not bounded by a responsive override.`,f,m.index,'Prefer max-width with relative/clamp units, container queries, or an explicit narrow-viewport override.',['page-usability','responsive','layout']))}r=new RegExp(OVERFLOW.source,OVERFLOW.flags);while((m=r.exec(f.text))!==null)out.push(finding('page-usability-global-overflow-hidden','low','Global root overflow is hidden','Hiding overflow on html/body/root can make keyboard-focused or zoomed content unreachable.',f,m.index,'Avoid global overflow clipping; constrain the specific visual layer and preserve document scrolling/zoom access.',['page-usability','responsive','zoom']));return out}
function pathOrder(a:string,b:string){return a<b?-1:a>b?1:0}
export function auditPageUsabilityGovernance(inventory:RepositoryInventory):AuditSection<PageUsabilityGovernanceSummary>{const started=performance.now(),cs=components(inventory),ss=styles(inventory),signals=[...cs.map(componentSignal),...ss.map(styleSignal)].sort((a,b)=>pathOrder(a.file,b.file)),all=stableSortFindings([...cs.flatMap(componentFindings),...ss.flatMap(styleFindings)]),result=all.slice(0,MAX);return{domain:'accessibility',title:'Whole-page usability governance audit',summary:{files:signals,componentFiles:cs.length,styleFiles:ss.length,interactionFiles:signals.filter(x=>x.clickHandlers>0).length,responsiveRiskFiles:signals.filter(x=>x.largeFixedWidths>0||x.globalOverflowHidden>0).length,accessibilityRiskFiles:signals.filter(x=>x.clickableNonInteractive>0||x.imagesWithoutAlt>0||x.outlineSuppressions>0).length,findings:result},findings:result,elapsedMs:Math.max(0,performance.now()-started)}}
