import type { AuditSection, Finding, RepositoryInventory, SourceFile } from './contracts.mts';
export interface ResponsiveAuditSummary { readonly cssFiles: number; readonly componentFiles: number; readonly mediaQueries: number; readonly containerQueries: number; readonly fixedWidthCandidates: number; readonly viewportHeightCandidates: number; readonly touchTargetCandidates: number; readonly findingsByRule: Readonly<Record<string, number>>; }
interface Located { readonly line: number; readonly excerpt: string; }
const GENERATED = /(^|\/)(dist|build|coverage|node_modules)(\/|$)/i; const TEST = /(^|\/)(__tests__|tests?|fixtures?)(\/|\.|$)/i;
function css(file: SourceFile): boolean { return file.kind === 'css' && !GENERATED.test(file.repositoryPath) && !TEST.test(file.repositoryPath); }
function component(file: SourceFile): boolean { return ['javascript','typescript'].includes(file.kind) && /Webclient\.(?:app|Admin)\/src\//.test(file.repositoryPath) && !GENERATED.test(file.repositoryPath) && !TEST.test(file.repositoryPath); }
function lineAt(text: string, offset: number): number { let line = 1; for (let i=0;i<offset;i+=1) if (text.charCodeAt(i)===10) line+=1; return line; }
function locate(text: string, pattern: RegExp): Located[] { const flags=pattern.flags.includes('g')?pattern.flags:`${pattern.flags}g`; return [...text.matchAll(new RegExp(pattern.source,flags))].map(match=>({line:lineAt(text,match.index??0),excerpt:match[0].replace(/\s+/g,' ').trim().slice(0,200)})); }
function finding(id:string,severity:Finding['severity'],title:string,message:string,file:SourceFile,match:Located,remediation:string,tags:readonly string[]):Finding{return{id,domain:'responsive',severity,title,message,location:{file:file.repositoryPath,line:match.line},evidence:{excerpt:match.excerpt},remediation,tags};}
function auditCss(file:SourceFile):Finding[]{const out:Finding[]=[];for(const match of locate(file.text,/\bwidth\s*:\s*(?:[5-9]\d\d|\d{4,})px\b/gi).slice(0,12))out.push(finding('responsive-large-fixed-width','medium','Large fixed width can overflow narrow viewports','A large fixed CSS width can force horizontal scrolling on mobile, zoomed, split-screen, or embedded layouts.',file,match,'Prefer max-width:100%, fluid sizing, grid/flex constraints, or clamp() with a tested breakpoint.',['mobile','zoom']));for(const match of locate(file.text,/\bheight\s*:\s*100vh\b/gi).slice(0,8))out.push(finding('responsive-legacy-viewport-height','low','100vh may conflict with mobile browser chrome','Legacy vh can size content behind dynamic browser chrome and create clipped controls.',file,match,'Prefer 100dvh with a safe fallback when full viewport height is intentional.',['mobile','viewport']));for(const match of locate(file.text,/\b(?:min-)?(?:width|height)\s*:\s*(?:[0-3]\d)px\b/gi).slice(0,12))out.push(finding('responsive-small-interaction-dimension','low','Small fixed interaction dimension requires touch review','Very small dimensions on interactive surfaces can produce difficult touch targets.',file,match,'Keep actionable controls comfortably touchable and preserve spacing at mobile breakpoints.',['touch','accessibility']));const fixed=locate(file.text,/\bposition\s*:\s*fixed\b/gi);if(fixed.length>=4&&!/@media\b/i.test(file.text)){const first=fixed[0];if(first)out.push(finding('responsive-fixed-overlays-without-breakpoint','medium','Multiple fixed overlays without responsive adaptation','Several fixed-position surfaces exist in a stylesheet with no media query, increasing overlap risk on small viewports.',file,first,'Add responsive placement/stacking rules and verify GIS controls, dialogs, safe areas, and keyboard viewport behavior.',['overlay','mobile','gis']));}return out;}
function auditComponent(file:SourceFile):Finding[]{const out:Finding[]=[];for(const match of locate(file.text,/style\s*=\s*\{\{[^}]*\bwidth\s*:\s*["'`](?:[5-9]\d\d|\d{4,})px["'`]/gi).slice(0,8))out.push(finding('responsive-inline-fixed-width','medium','Large inline fixed width','Inline fixed widths are difficult to adapt with stylesheet breakpoints and can overflow constrained surfaces.',file,match,'Move layout sizing into responsive CSS or use a bounded fluid value.',['react','mobile']));return out;}
function counts(findings:readonly Finding[]):Readonly<Record<string,number>>{const result:Record<string,number>={};for(const item of findings)result[item.id]=(result[item.id]??0)+1;return Object.fromEntries(Object.entries(result).sort(([a],[b])=>a.localeCompare(b,'en')));}
export function auditResponsive(inventory:RepositoryInventory):AuditSection<ResponsiveAuditSummary>{const started=performance.now();const cssFiles=inventory.files.filter(css);const components=inventory.files.filter(component);const findings=[...cssFiles.flatMap(auditCss),...components.flatMap(auditComponent)];return{domain:'responsive',title:'Responsive viewport and touch regression audit',summary:{cssFiles:cssFiles.length,componentFiles:components.length,mediaQueries:cssFiles.reduce((n,f)=>n+locate(f.text,/@media\b/gi).length,0),containerQueries:cssFiles.reduce((n,f)=>n+locate(f.text,/@container\b/gi).length,0),fixedWidthCandidates:findings.filter(f=>f.id.includes('fixed-width')).length,viewportHeightCandidates:findings.filter(f=>f.id==='responsive-legacy-viewport-height').length,touchTargetCandidates:findings.filter(f=>f.id==='responsive-small-interaction-dimension').length,findingsByRule:counts(findings)},findings,elapsedMs:performance.now()-started};}
