import assert from 'node:assert/strict'; import test from 'node:test'; import type {RepositoryInventory,SourceFile} from './contracts.mts'; import {auditRunnerTrustBoundaries} from './runner-trust-boundary-audit.mts';
function audit(text:string){const lines=text.split('\n').length,bytes=Buffer.byteLength(text),file:SourceFile={repositoryPath:'.github/workflows/ci.yml',absolutePath:'/repo/.github/workflows/ci.yml',extension:'.yml',kind:'yaml',bytes,lines,text}; const inventory:RepositoryInventory={root:'/repo',files:[file],ignoredDirectories:[],languageStats:[{kind:'yaml',files:1,lines,bytes}],totalFiles:1,totalLines:lines,totalBytes:bytes,generatedAt:'2026-09-29T00:00:00Z'}; return auditRunnerTrustBoundaries(inventory);}
const ids=(text:string)=>audit(text).findings.map(x=>x.id), PIN='0123456789012345678901234567890123456789';
test('blocks external self-hosted execution',()=>assert.ok(ids(`on: pull_request\njobs:\n  test:\n    runs-on: self-hosted\n    steps:\n      - run: npm test`).includes('ci-runner-self-hosted-external-contribution')));
test('blocks dynamic runner selection',()=>assert.ok(ids(`on: workflow_dispatch\njobs:\n  test:\n    runs-on: \${{ inputs.runner }}\n    steps:\n      - run: npm test`).includes('ci-runner-dynamic-selection')));
test('recognizes multiline self-hosted labels',()=>assert.ok(ids(`on: pull_request\njobs:\n  test:\n    runs-on:\n      - self-hosted\n      - linux\n    steps:\n      - run: npm test`).includes('ci-runner-self-hosted-external-contribution')));
test('reports privileged self-hosted job without environment',()=>assert.ok(ids(`on: push\njobs:\n  release:\n    permissions:\n      contents: write\n    runs-on: self-hosted\n    steps:\n      - run: gh release create v1`).includes('ci-runner-self-hosted-privilege-without-environment')));
test('protected environment suppresses privilege finding',()=>assert.equal(ids(`on: push\njobs:\n  release:\n    permissions:\n      contents: write\n    environment: production\n    runs-on: self-hosted\n    steps:\n      - run: true`).includes('ci-runner-self-hosted-privilege-without-environment'),false));
test('reports host-global tool mutation',()=>assert.ok(ids(`on: push\njobs:\n  build:\n    runs-on: self-hosted\n    steps:\n      - run: sudo apt-get install jq`).includes('ci-runner-self-hosted-host-tool-mutation')));
test('reports docker daemon authority',()=>assert.ok(ids(`on: push\njobs:\n  image:\n    runs-on: self-hosted\n    steps:\n      - run: docker build .`).includes('ci-runner-self-hosted-container-daemon-authority')));
test('blocks privileged container',()=>assert.ok(ids(`on: push\njobs:\n  image:\n    runs-on: self-hosted\n    steps:\n      - run: docker run --privileged alpine true`).includes('ci-runner-self-hosted-privileged-container')));
test('reports host network and pid',()=>{const found=ids(`on: push\njobs:\n  image:\n    runs-on: self-hosted\n    steps:\n      - run: docker run --network host --pid=host alpine true`); assert.ok(found.includes('ci-runner-self-hosted-host-network')); assert.ok(found.includes('ci-runner-self-hosted-host-pid'));});
test('blocks sensitive host mount',()=>assert.ok(ids(`on: push\njobs:\n  image:\n    runs-on: self-hosted\n    steps:\n      - run: docker run -v /etc:/host alpine true`).includes('ci-runner-self-hosted-sensitive-host-mount')));
test('reports persistent workspace mutation',()=>assert.ok(ids(`on: push\njobs:\n  build:\n    runs-on: self-hosted\n    steps:\n      - run: git clean -xffd`).includes('ci-runner-self-hosted-persistent-workspace-mutation')));
test('reports privileged checkout isolation',()=>assert.ok(ids(`on: push\njobs:\n  release:\n    permissions:\n      contents: write\n    runs-on: self-hosted\n    steps:\n      - uses: actions/checkout@${PIN}`).includes('ci-runner-self-hosted-privileged-checkout-isolation')));
test('summary counts host authority',()=>{const result=audit(`on: pull_request\njobs:\n  image:\n    runs-on: self-hosted\n    steps:\n      - run: docker build .`); assert.equal(result.summary.selfHostedJobs,1); assert.equal(result.summary.externalSelfHostedJobs,1); assert.equal(result.summary.hostAuthorityJobs,1);});
