import assert from 'node:assert/strict';
import test from 'node:test';
import { auditWorkflowPromotionIntegrity } from './workflow-promotion-integrity-audit.mts';
import { fixtureInventory, type FixtureFileInput } from './test-helpers.mts';
function audit(text:string){return auditWorkflowPromotionIntegrity(fixtureInventory([{path:'.github/workflows/promote.yml',text}] as readonly FixtureFileInput[]));}
test('ignores non-workflow-run release jobs',()=>{const r=audit(`name: release\non:\n  push:\n    branches: [main]\npermissions:\n  contents: write\njobs:\n  release:\n    runs-on: ubuntu-latest\n    steps:\n      - name: Publish package\n        run: npm publish\n`);assert.equal(r.summary.workflowRunJobs,0);assert.deepEqual(r.findings,[]);});
test('blocks privileged workflow_run publish without successful upstream conclusion',()=>{const r=audit(`name: promote\non:\n  workflow_run:\n    workflows: [CI]\n    types: [completed]\npermissions:\n  contents: write\njobs:\n  release:\n    runs-on: ubuntu-latest\n    steps:\n      - name: Publish package\n        run: npm publish\n`);const f=r.findings.find(x=>x.id==='ci-workflow-run-promotion-without-success-guard');assert.equal(f?.severity,'critical');assert.equal(f?.blocking,true);});
test('accepts job-level explicit success conclusion guard',()=>{const r=audit(`name: promote\non:\n  workflow_run:\n    workflows: [CI]\n    types: [completed]\npermissions:\n  contents: write\njobs:\n  release:\n    if: \${{ github.event.workflow_run.conclusion == 'success' }}\n    runs-on: ubuntu-latest\n    steps:\n      - name: Publish package\n        run: npm publish\n`);assert.ok(!r.findings.some(x=>x.id==='ci-workflow-run-promotion-without-success-guard'));assert.equal(r.summary.guardedPromotionSteps,1);});
test('accepts step-level explicit success conclusion guard',()=>{const r=audit(`name: promote\non:\n  workflow_run:\n    workflows: [CI]\n    types: [completed]\npermissions:\n  packages: write\njobs:\n  package:\n    runs-on: ubuntu-latest\n    steps:\n      - name: Publish package\n        if: \${{ 'success' == github.event.workflow_run.conclusion }}\n        run: npm publish\n`);assert.equal(r.summary.guardedPromotionSteps,1);});
test('blocks cleanup-style failure override on promotion',()=>{const r=audit(`name: deploy\non:\n  workflow_run:\n    workflows: [CI]\n    types: [completed]\npermissions:\n  deployments: write\njobs:\n  deploy:\n    environment: production\n    runs-on: ubuntu-latest\n    steps:\n      - name: Deploy application\n        if: \${{ always() }}\n        run: kubectl apply -f deploy.yml\n`);assert.ok(r.findings.some(x=>x.id==='ci-workflow-run-promotion-failure-override'&&x.blocking));assert.ok(r.findings.some(x=>x.id==='ci-workflow-run-promotion-without-success-guard'&&x.blocking));});
test('recognizes pinned deployment action identity as promotion',()=>{const r=audit(`name: pages\non:\n  workflow_run:\n    workflows: [Build]\n    types: [completed]\npermissions:\n  pages: write\njobs:\n  deploy:\n    runs-on: ubuntu-latest\n    steps:\n      - name: Deploy Pages\n        uses: actions/deploy-pages@0123456789abcdef0123456789abcdef01234567\n`);assert.equal(r.summary.promotionSteps,1);assert.equal(r.summary.unguardedPromotionSteps,1);});
test('recognizes signing as privileged promotion',()=>{const r=audit(`name: attest\non:\n  workflow_run:\n    workflows: [Build]\n    types: [completed]\npermissions:\n  id-token: write\njobs:\n  attest:\n    runs-on: ubuntu-latest\n    steps:\n      - name: Sign release\n        run: cosign sign image@example.invalid/app@sha256:deadbeef\n`);assert.equal(r.summary.promotionSteps,1);assert.ok(r.findings.some(x=>x.blocking));});
test('does not require success guard for read-only diagnostics',()=>{const r=audit(`name: diagnose\non:\n  workflow_run:\n    workflows: [CI]\n    types: [completed]\npermissions:\n  contents: read\njobs:\n  diagnose:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo done\n`);assert.equal(r.summary.privilegedWorkflowRunJobs,0);assert.deepEqual(r.findings,[]);});
test('reviews privileged workflow_run mutation without promotion keyword',()=>{const r=audit(`name: followup\non:\n  workflow_run:\n    workflows: [CI]\n    types: [completed]\npermissions:\n  issues: write\njobs:\n  mutate:\n    runs-on: ubuntu-latest\n    steps:\n      - name: Update metadata\n        run: gh api repos/example/example/issues/1 -X PATCH -f state=closed\n`);assert.ok(r.findings.some(x=>x.id==='ci-workflow-run-privileged-job-success-guard-review'));});
test('does not inspect non-workflow yaml files',()=>{const r=auditWorkflowPromotionIntegrity(fixtureInventory([{path:'config/promote.yml',text:'workflow_run:\n  conclusion: failure\n'}] as readonly FixtureFileInput[]));assert.equal(r.summary.workflowFiles,0);assert.deepEqual(r.findings,[]);});