import { stableSortFindings, type AuditSection, type Finding, type RepositoryInventory } from './contracts.mts';
import { firstWorkflowField, jobHasSecrets, jobHasWriteAuthority, jobUsesProtectedEnvironment, workflowFiles, workflowJobBlocks, workflowTriggerProfile, type WorkflowJobBlock } from './workflow-structure.mts';
import { firstWorkflowStepField, stepDisplayName, stepRunText, workflowStepBlocks, type WorkflowStepBlock } from './workflow-step-structure.mts';
export interface WorkflowPromotionSignal { readonly file:string; readonly job:string; readonly step:string; readonly line:number; readonly privileged:boolean; readonly promotionLike:boolean; readonly jobSuccessGuard:boolean; readonly stepSuccessGuard:boolean; readonly effectiveSuccessGuard:boolean; readonly jobFailureOverride:boolean; readonly stepFailureOverride:boolean; }
export interface WorkflowPromotionIntegritySummary { readonly workflowFiles:number; readonly workflowRunJobs:number; readonly privilegedWorkflowRunJobs:number; readonly promotionSteps:number; readonly guardedPromotionSteps:number; readonly unguardedPromotionSteps:number; readonly signals:readonly WorkflowPromotionSignal[]; readonly findings:readonly Finding[]; }
const SUCCESS_GUARD=/github\.event\.workflow_run\.conclusion\s*==\s*['"]success['"]|['"]success['"]\s*==\s*github\.event\.workflow_run\.conclusion/i;
const FAILURE_OVERRIDE=/\b(?:always|failure)\s*\(\s*\)|!\s*cancelled\s*\(\s*\)|\bcancelled\s*\(\s*\)\s*==\s*false/i;
const PROMOTION_WORD=/(?:^|[^a-z0-9])(?:deploy|deployment|publish|publication|release|promote|promotion|sign|signature|attest|attestation|provenance|push|upload|package|packages|registry|pages)(?:[^a-z0-9]|$)/i;
const PROMOTION_COMMAND=/\b(?:npm\s+publish|pnpm\s+publish|yarn\s+npm\s+publish|dotnet\s+nuget\s+push|nuget\s+push|docker\s+push|podman\s+push|gh\s+release\s+(?:create|upload)|gh\s+api\b[^\n]*(?:releases|deployments|packages)|kubectl\s+(?:apply|set\s+image)|helm\s+(?:upgrade|install)|terraform\s+apply|az\s+(?:webapp|containerapp|deployment)|aws\s+(?:deploy|s3\s+sync|ecr)|gcloud\s+(?:run\s+deploy|app\s+deploy)|cosign\s+sign|gh\s+attestation)/i;
const PROMOTION_ACTION=/^(?:actions\/upload-pages-artifact|actions\/deploy-pages|softprops\/action-gh-release|docker\/build-push-action|sigstore\/cosign-installer|actions\/attest-build-provenance)@/i;
function privileged(b:WorkflowJobBlock){return jobHasWriteAuthority(b)||jobHasSecrets(b)||jobUsesProtectedEnvironment(b);}
function success(v:string){return SUCCESS_GUARD.test(v);} function override(v:string){return FAILURE_OVERRIDE.test(v);}
function promotion(s:WorkflowStepBlock){return PROMOTION_WORD.test(stepDisplayName(s))||PROMOTION_COMMAND.test(stepRunText(s))||PROMOTION_ACTION.test(firstWorkflowStepField(s,'uses')?.value??'');}
function signalFor(b:WorkflowJobBlock,s:WorkflowStepBlock):WorkflowPromotionSignal{const ji=firstWorkflowField(b,'if')?.value??'',si=firstWorkflowStepField(s,'if')?.value??'',jg=success(ji),sg=success(si);return{file:b.file.repositoryPath,job:b.name,step:stepDisplayName(s),line:firstWorkflowStepField(s,'if')?.line??s.startLine,privileged:privileged(b),promotionLike:promotion(s),jobSuccessGuard:jg,stepSuccessGuard:sg,effectiveSuccessGuard:jg||sg,jobFailureOverride:override(ji),stepFailureOverride:override(si)};}
function finding(i:WorkflowPromotionSignal,id:string,severity:Finding['severity'],title:string,message:string,remediation:string,blocking=false):Finding{return{id,domain:'release',severity,...(blocking?{blocking:true}:{}),title,message,location:{file:i.file,line:i.line},evidence:{metadata:{job:i.job,step:i.step,promotionLike:i.promotionLike,privileged:i.privileged,jobSuccessGuard:i.jobSuccessGuard,stepSuccessGuard:i.stepSuccessGuard,jobFailureOverride:i.jobFailureOverride,stepFailureOverride:i.stepFailureOverride}},remediation,tags:['ci','workflow-run','promotion','release-gate','fail-closed']};}
function findingsFor(i:WorkflowPromotionSignal):Finding[]{if(!i.privileged)return[];const out:Finding[]=[];if(i.promotionLike&&!i.effectiveSuccessGuard)out.push(finding(i,'ci-workflow-run-promotion-without-success-guard','critical','Privileged workflow_run promotion lacks an upstream success guard',`Step ${i.step} in ${i.job} can promote without requiring successful upstream validation.`,"Require github.event.workflow_run.conclusion == 'success' plus repository/ref provenance guards.",true));if(i.promotionLike&&(i.jobFailureOverride||i.stepFailureOverride))out.push(finding(i,'ci-workflow-run-promotion-failure-override','critical','Privileged workflow_run promotion uses failure-override semantics',`Step ${i.step} is promotion-like but governed by cleanup-style failure semantics.`,'Use failure overrides only for diagnostics/cleanup, never release mutation.',true));return out;}
function review(b:WorkflowJobBlock,signals:readonly WorkflowPromotionSignal[]):Finding[]{if(!privileged(b)||signals.some(i=>i.promotionLike)||success(firstWorkflowField(b,'if')?.value??'')||signals.length===0)return[];return[{id:'ci-workflow-run-privileged-job-success-guard-review',domain:'release',severity:'high',title:'Privileged workflow_run job does not require upstream success',message:`Job ${b.name} executes after workflow_run with privileged authority but no explicit successful-upstream guard.`,location:{file:b.file.repositoryPath,line:b.startLine},evidence:{metadata:{job:b.name,executableSteps:signals.length}},remediation:"Add a job-level workflow_run conclusion == 'success' guard and retain provenance checks.",tags:['ci','workflow-run','privilege','release-gate','fail-closed']}];}
export function auditWorkflowPromotionIntegrity(inventory:RepositoryInventory):AuditSection<WorkflowPromotionIntegritySummary>{const started=performance.now(),files=workflowFiles(inventory),jobs=files.flatMap(f=>workflowTriggerProfile(f).workflowRun?workflowJobBlocks(f):[]),signals=jobs.flatMap(b=>workflowStepBlocks(b).map(s=>signalFor(b,s))),findings=stableSortFindings([...signals.flatMap(findingsFor),...jobs.flatMap(b=>review(b,signals.filter(i=>i.file===b.file.repositoryPath&&i.job===b.name)))]),promotions=signals.filter(i=>i.promotionLike&&i.privileged);return{domain:'release',title:'workflow_run release-promotion integrity audit',summary:{workflowFiles:files.length,workflowRunJobs:jobs.length,privilegedWorkflowRunJobs:jobs.filter(privileged).length,promotionSteps:promotions.length,guardedPromotionSteps:promotions.filter(i=>i.effectiveSuccessGuard).length,unguardedPromotionSteps:promotions.filter(i=>!i.effectiveSuccessGuard).length,signals,findings},findings,elapsedMs:Math.max(0,performance.now()-started)};}