import assert from 'node:assert/strict';
import test from 'node:test';
import { auditWorkflowFailureIntegrity } from './workflow-failure-integrity-audit.mts';
import { fixtureInventory, type FixtureFileInput } from './test-helpers.mts';
function audit(text:string){return auditWorkflowFailureIntegrity(fixtureInventory([{path:'.github/workflows/ci.yml',text}] as readonly FixtureFileInput[]));}
test('accepts a normal fail-closed validation step',()=>{const r=audit(`name: ci\non: [pull_request]\npermissions:\n  contents: read\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - name: Run tests\n        run: npm test\n`);assert.deepEqual(r.findings,[]);assert.equal(r.summary.gateLikeSteps,1);});
test('blocks literal continue-on-error on validation gates',()=>{const r=audit(`name: ci\non: [push]\njobs:\n  verify:\n    runs-on: ubuntu-latest\n    steps:\n      - name: Typecheck\n        continue-on-error: true\n        run: npm run typecheck\n`);const f=r.findings.find(x=>x.id==='ci-failure-gate-continue-on-error');assert.equal(f?.severity,'critical');assert.equal(f?.blocking,true);});
test('keeps best-effort cleanup visible but non-blocking',()=>{const r=audit(`name: cleanup\non: [push]\njobs:\n  cleanup:\n    runs-on: ubuntu-latest\n    steps:\n      - name: Remove temp files\n        continue-on-error: true\n        run: rm -rf .tmp\n`);const f=r.findings.find(x=>x.id==='ci-failure-continue-on-error');assert.equal(f?.severity,'medium');assert.equal(f?.blocking,undefined);});
test('blocks job-level failure masking when job contains validation',()=>{const r=audit(`name: ci\non: [push]\njobs:\n  quality:\n    continue-on-error: true\n    runs-on: ubuntu-latest\n    steps:\n      - run: npm run lint\n`);assert.ok(r.findings.some(x=>x.id==='ci-failure-gate-continue-on-error'&&x.blocking));});
test('flags expression-controlled failure policy',()=>{const r=audit(`name: ci\non: [pull_request]\njobs:\n  verify:\n    runs-on: ubuntu-latest\n    steps:\n      - name: Regression tests\n        continue-on-error: \${{ matrix.experimental }}\n        run: npm test\n`);const f=r.findings.find(x=>x.id==='ci-failure-dynamic-continue-policy');assert.equal(f?.severity,'high');assert.equal(f?.blocking,true);});
test('blocks shell fail-fast disablement and swallowed validation failures',()=>{const r=audit(`name: ci\non: [push]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - name: Test suite\n        run: |\n          set +e\n          npm test || true\n`);assert.ok(r.findings.some(x=>x.id==='ci-failure-errexit-disabled'&&x.blocking));assert.ok(r.findings.some(x=>x.id==='ci-failure-shell-swallow'&&x.blocking));});
test('blocks PowerShell Continue error policy in validation',()=>{const r=audit(`name: windows\non: [push]\njobs:\n  verify:\n    runs-on: windows-latest\n    steps:\n      - name: Build verification\n        shell: pwsh\n        run: |\n          $ErrorActionPreference = 'Continue'\n          dotnet build\n`);assert.ok(r.findings.some(x=>x.id==='ci-failure-powershell-continue'&&x.blocking));});
test('accepts explicit continue-on-error false',()=>{const r=audit(`name: ci\non: [push]\njobs:\n  lint:\n    runs-on: ubuntu-latest\n    steps:\n      - name: Lint\n        continue-on-error: false\n        run: npm run lint\n`);assert.deepEqual(r.findings,[]);});
test('raises impact for failure masking in secret-bearing jobs',()=>{const r=audit(`name: publish\non: [push]\njobs:\n  publish:\n    runs-on: ubuntu-latest\n    steps:\n      - name: Cleanup staging\n        env:\n          TOKEN: \${{ secrets.RELEASE_TOKEN }}\n        run: rm -rf staging || true\n`);const f=r.findings.find(x=>x.id==='ci-failure-shell-swallow');assert.equal(f?.severity,'high');assert.equal(f?.evidence?.metadata?.privileged,true);});
test('does not inspect ordinary repository yaml',()=>{const r=auditWorkflowFailureIntegrity(fixtureInventory([{path:'config/ci.yml',text:'continue-on-error: true\nrun: npm test || true\n'}] as readonly FixtureFileInput[]));assert.equal(r.summary.workflowFiles,0);assert.deepEqual(r.findings,[]);});