import assert from 'node:assert/strict';
import test from 'node:test';
import { auditWorkflowExpressions } from './workflow-expression-audit.mts';
import { fixtureInventory, type FixtureFileInput } from './test-helpers.mts';
function audit(text: string, path = '.github/workflows/qa.yml') { return auditWorkflowExpressions(fixtureInventory([{ path, text }] as readonly FixtureFileInput[])); }
function finding(text: string, id: string) { return audit(text).findings.find(item => item.id === id); }
const sha = '0123456789abcdef0123456789abcdef01234567';
const header = `name: QA\non: [pull_request]\npermissions:\n  contents: read\njobs:\n  qa:\n    runs-on: ubuntu-latest\n    steps:\n`;
test('blocks pull request title interpolation into run', () => { const result = finding(`${header}      - run: echo "\${{ github.event.pull_request.title }}"\n`, 'ci-expression-shell-injection'); assert.equal(result?.severity, 'critical'); assert.equal(result?.blocking, true); });
test('blocks pull request body interpolation into multiline run', () => { assert.equal(finding(`${header}      - run: |\n          printf '%s\\n' "\${{ github.event.pull_request.body }}"\n`, 'ci-expression-shell-injection')?.blocking, true); });
for (const [name, expression] of [['head ref','github.head_ref'],['issue title','github.event.issue.title'],['issue body','github.event.issue.body'],['comment','github.event.comment.body'],['review','github.event.review.body'],['review comment','github.event.review_comment.body'],['discussion title','github.event.discussion.title'],['discussion body','github.event.discussion.body'],['commit message','github.event.head_commit.message'],['workflow input','inputs.environment']] as const) test(`blocks ${name} interpolation`, () => { assert.ok(finding(`${header}      - run: echo "\${{ ${expression} }}"\n`, 'ci-expression-shell-injection')); });
test('accepts attacker-controlled values passed as environment data', () => { assert.equal(audit(`${header}      - run: printf '%s\\n' "$PR_TITLE"\n        env:\n          PR_TITLE: \${{ github.event.pull_request.title }}\n`).findings.some(item => item.id === 'ci-expression-shell-injection'), false); });
test('accepts trusted immutable pull request head sha in run', () => { assert.equal(audit(`${header}      - run: git cat-file -e \${{ github.event.pull_request.head.sha }}\n`).findings.some(item => item.id === 'ci-expression-shell-injection'), false); });
test('accepts github sha in run', () => { assert.deepEqual(audit(`${header}      - run: echo \${{ github.sha }}\n`).findings, []); });
test('blocks dynamic action identity even for trusted sha expression', () => { assert.equal(finding(`${header}      - uses: vendor/action@\${{ github.sha }}\n`, 'ci-expression-dynamic-action')?.blocking, true); });
test('blocks dynamic action identity from workflow input', () => { assert.ok(finding(`${header}      - uses: \${{ inputs.action }}\n`, 'ci-expression-dynamic-action')); });
test('accepts literal SHA pinned action identity', () => { assert.deepEqual(audit(`${header}      - uses: actions/checkout@${sha}\n`).findings, []); });
test('blocks dynamic shell selection', () => { assert.ok(finding(`${header}      - shell: \${{ inputs.shell }}\n        run: echo ok\n`, 'ci-expression-dynamic-shell')); });
test('blocks dynamic container image selection', () => { assert.ok(finding(`name: Container\non: [push]\njobs:\n  qa:\n    runs-on: ubuntu-latest\n    container:\n      image: \${{ inputs.image }}\n    steps:\n      - run: echo ok\n`, 'ci-expression-dynamic-container')); });
test('blocks pull request title spliced into github-script source', () => { assert.equal(finding(`${header}      - uses: actions/github-script@${sha}\n        with:\n          script: |\n            const title = "\${{ github.event.pull_request.title }}";\n`, 'ci-expression-github-script-injection')?.blocking, true); });
test('accepts github-script reading attacker data through process env', () => { assert.equal(audit(`${header}      - uses: actions/github-script@${sha}\n        env:\n          PR_TITLE: \${{ github.event.pull_request.title }}\n        with:\n          script: |\n            console.log(process.env.PR_TITLE);\n`).findings.some(item => item.id === 'ci-expression-github-script-injection'), false); });
test('does not leak github-script state into sibling step', () => { assert.equal(audit(`${header}      - uses: actions/github-script@${sha}\n        with:\n          script: console.log('safe')\n      - name: other\n        with:\n          script: \${{ inputs.value }}\n        run: echo safe\n`).findings.some(item => item.id === 'ci-expression-github-script-injection'), false); });
test('ignores non workflow yaml', () => { const result = audit('run: echo "${{ inputs.value }}"\n', 'config/app.yml'); assert.equal(result.summary.workflowFiles, 0); assert.deepEqual(result.findings, []); });
test('reports executable expression counts deterministically', () => { const result = audit(`${header}      - run: echo \${{ github.sha }}\n      - shell: \${{ inputs.shell }}\n        run: echo ok\n      - uses: vendor/action@\${{ github.sha }}\n`); assert.equal(result.summary.executableExpressions, 3); assert.equal(result.summary.attackerControlledExpressions, 1); assert.equal(result.summary.workflows[0]?.dynamicUses, 1); });
