import assert from 'node:assert/strict';
import test from 'node:test';
import { auditWorkflowCacheBoundaries } from './workflow-cache-boundary-audit.mts';
import { fixtureInventory, type FixtureFileInput } from './test-helpers.mts';
const sha='0123456789abcdef0123456789abcdef01234567';
function audit(text:string){return auditWorkflowCacheBoundaries(fixtureInventory([{path:'.github/workflows/cache.yml',text}] as readonly FixtureFileInput[]));}
function workflow(on:string,steps:string){return `name: cache\non: ${on}\npermissions:\n  contents: read\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n${steps}`;}
test('accepts content-hash cache key on push',()=>{const r=audit(workflow('[push]',`      - uses: actions/cache@${sha}\n        with:\n          path: ~/.npm\n          key: npm-\${{ runner.os }}-\${{ hashFiles('**/package-lock.json') }}\n`));assert.equal(r.findings.length,0);assert.equal(r.summary.cacheActions,1);});
test('blocks pull request title in cache key',()=>{const r=audit(workflow('[pull_request]',`      - uses: actions/cache@${sha}\n        with:\n          path: ~/.npm\n          key: npm-\${{ github.event.pull_request.title }}\n`));assert.equal(r.findings[0]?.id,'ci-cache-untrusted-key');assert.equal(r.findings[0]?.blocking,true);});
test('blocks mutable head ref in cache key',()=>{const r=audit(workflow('[pull_request]',`      - uses: actions/cache@${sha}\n        with:\n          path: ~/.npm\n          key: npm-\${{ github.head_ref }}\n`));assert.ok(r.findings.some(x=>x.id==='ci-cache-untrusted-key'));});
test('blocks restore prefix on external contribution trigger',()=>{const r=audit(workflow('[pull_request]',`      - uses: actions/cache@${sha}\n        with:\n          path: ~/.npm\n          key: npm-\${{ runner.os }}-\${{ hashFiles('**/package-lock.json') }}\n          restore-keys: npm-\${{ runner.os }}-\n`));assert.ok(r.findings.some(x=>x.id==='ci-cache-broad-restore-on-external-trigger'));});
test('allows restore prefix on trusted push',()=>{const r=audit(workflow('[push]',`      - uses: actions/cache@${sha}\n        with:\n          path: ~/.npm\n          key: npm-\${{ runner.os }}-\${{ hashFiles('**/package-lock.json') }}\n          restore-keys: npm-\${{ runner.os }}-\n`));assert.equal(r.findings.length,0);});
test('blocks cache action on pull_request_target',()=>{const r=audit(workflow('[pull_request_target]',`      - uses: actions/cache@${sha}\n        with:\n          path: ~/.npm\n          key: npm-\${{ runner.os }}\n`));assert.ok(r.findings.some(x=>x.id==='ci-cache-privileged-trigger'&&x.severity==='critical'));});
test('blocks setup-node built in cache on pull_request_target',()=>{const r=audit(workflow('[pull_request_target]',`      - uses: actions/setup-node@${sha}\n        with:\n          node-version: 24\n          cache: npm\n`));assert.ok(r.findings.some(x=>x.id==='ci-cache-privileged-trigger'));assert.equal(r.summary.setupCaches,1);});
test('does not treat setup-node without cache as cache restore',()=>{const r=audit(workflow('[pull_request_target]',`      - uses: actions/setup-node@${sha}\n        with:\n          node-version: 24\n`));assert.equal(r.findings.length,0);assert.equal(r.summary.setupCaches,0);});
test('ignores similarly named nested application fields',()=>{const r=audit(workflow('[pull_request]',`      - run: echo ok\n        env:\n          cache: npm\n          restore-keys: unsafe\n`));assert.equal(r.findings.length,0);});
test('reports deterministic aggregate counts',()=>{const r=audit(workflow('[push]',`      - uses: actions/cache@${sha}\n        with:\n          path: a\n          key: a\n          restore-keys: prefix-\n      - uses: actions/setup-node@${sha}\n        with:\n          node-version: 24\n          cache: npm\n`));assert.equal(r.summary.cacheActions,1);assert.equal(r.summary.setupCaches,1);assert.equal(r.summary.restoreKeys,1);});
