import assert from 'node:assert/strict';
import test from 'node:test';
import { auditWorkflowCacheProvenance } from './workflow-cache-provenance-audit.mts';
import { fixtureInventory, type FixtureFileInput } from './test-helpers.mts';
const PIN='0123456789abcdef0123456789abcdef01234567';
function audit(text:string){return auditWorkflowCacheProvenance(fixtureInventory([{path:'.github/workflows/cache-provenance.yml',text}] as readonly FixtureFileInput[]));}
function workflow(event:string,steps:string):string{return['name: cache provenance',event,'permissions:','  contents: read','jobs:','  build:','    runs-on: ubuntu-latest','    steps:',...steps.split('\n').map(line=>`      ${line}`),''].join('\n');}
function cache(body:string,subaction=''):string{return[`- uses: actions/cache${subaction}@${PIN}`,'  with:',...body.split('\n').map(line=>`    ${line}`)].join('\n');}
function ids(text:string):string[]{return audit(text).findings.map(item=>item.id);}
test('blocks pull request writer sharing a literal namespace',()=>{const result=audit(workflow('on:\n  pull_request:',cache('path: ~/.npm\nkey: npm-linux-lock')));assert.ok(result.findings.some(item=>item.id==='ci-cache-untrusted-writer-shared-namespace'&&item.blocking));assert.equal(result.summary.untrustedTriggerWorkflows,1);assert.equal(result.summary.saveCapableSteps,1);});
test('blocks pull_request_target writer sharing a literal namespace',()=>assert.ok(ids(workflow('on:\n  pull_request_target:',cache('path: ~/.npm\nkey: npm-linux-lock'))).includes('ci-cache-untrusted-writer-shared-namespace')));
test('blocks issue comment writer sharing a namespace',()=>assert.ok(ids(workflow('on:\n  issue_comment:\n    types: [created]',cache('path: ~/.npm\nkey: npm-linux-lock'))).includes('ci-cache-untrusted-writer-shared-namespace')));
test('allows pull request writer isolated by immutable head sha',()=>{const result=audit(workflow('on:\n  pull_request:',cache("path: ~/.npm\nkey: npm-${{ github.event.pull_request.head.sha }}-${{ hashFiles('package-lock.json') }}")));assert.equal(result.findings.some(item=>item.id==='ci-cache-untrusted-writer-shared-namespace'),false);assert.equal(result.summary.workflows[0]?.refIsolatedKeys,1);});
test('restore subaction is not treated as writer',()=>{const result=audit(workflow('on:\n  pull_request:',cache('path: ~/.npm\nkey: npm-linux-lock','/restore')));assert.equal(result.findings.some(item=>item.id==='ci-cache-untrusted-writer-shared-namespace'),false);assert.equal(result.summary.restoreOnlySteps,1);});
test('untrusted writer with restore prefixes is blocking',()=>{const finding=audit(workflow('on:\n  pull_request:',cache("path: ~/.npm\nkey: npm-${{ github.event.pull_request.head.sha }}\nrestore-keys: |\n  npm-linux-"))).findings.find(item=>item.id==='ci-cache-untrusted-writer-fallback-namespace');assert.equal(finding?.blocking,true);assert.equal(finding?.severity,'critical');});
test('protected writer without content hash is high review finding',()=>{const finding=audit(workflow('on:\n  push:\n    branches: [main]',cache('path: ~/.npm\nkey: npm-linux-main'))).findings.find(item=>item.id==='ci-cache-protected-writer-not-content-addressed');assert.equal(finding?.severity,'high');assert.equal(finding?.blocking,false);});
test('content addressed protected writer avoids mutable-key finding',()=>{const result=audit(workflow('on:\n  push:\n    branches: [main]',cache("path: ~/.npm\nkey: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}")));assert.equal(result.findings.some(item=>item.id==='ci-cache-protected-writer-not-content-addressed'),false);assert.equal(result.summary.workflows[0]?.contentAddressedKeys,1);});
test('protected fallback without content address is reported',()=>assert.ok(ids(workflow('on:\n  push:\n    branches: [main]',cache('path: ~/.npm\nkey: npm-linux-main\nrestore-keys: |\n  npm-linux-'))).includes('ci-cache-protected-fallback-without-content-address')));
test('protected writer missing platform identity is reported',()=>assert.ok(ids(workflow('on:\n  push:\n    branches: [main]',cache("path: ~/.npm\nkey: npm-${{ hashFiles('package-lock.json') }}"))).includes('ci-cache-platform-identity-missing')));
test('required hit with fallback is provenance finding',()=>assert.ok(audit(workflow('on:\n  push:\n    branches: [main]',cache("path: ~/.npm\nkey: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}\nrestore-keys: |\n  npm-${{ runner.os }}-\nfail-on-cache-miss: true",'/restore'))).findings.some(item=>item.id==='ci-cache-required-hit-with-fallback')));
test('non-workflow yaml is ignored',()=>{const result=auditWorkflowCacheProvenance(fixtureInventory([{path:'config/cache.yml',text:`on: pull_request\nuses: actions/cache@${PIN}`}] as readonly FixtureFileInput[]));assert.equal(result.summary.workflowFiles,0);assert.deepEqual(result.findings,[]);});
test('findings are deterministic across repeated audits',()=>{const text=workflow('on:\n  push:\n    branches: [main]',cache('path: ~/.npm\nkey: npm-main\nrestore-keys: |\n  npm-\nfail-on-cache-miss: true'));const first=audit(text).findings;const second=audit(text).findings;const signature=(items:typeof first)=>items.map(item=>({id:item.id,severity:item.severity,blocking:item.blocking,location:item.location,title:item.title,message:item.message,remediation:item.remediation,tags:item.tags}));assert.deepEqual(signature(first),signature(second));assert.ok(first.length>1);});
