import { stableSortFindings, type AuditSection, type Finding, type RepositoryInventory } from './contracts.mts';
import { firstWorkflowField, hasExpression, jobHasSecrets, jobHasWriteAuthority, jobUsesProtectedEnvironment, workflowFiles, workflowJobBlocks, workflowTriggerProfile, type WorkflowJobBlock } from './workflow-structure.mts';
import { firstWorkflowStepField, stepDisplayName, stepRunText, workflowStepBlocks, type WorkflowStepBlock } from './workflow-step-structure.mts';

export type FailureMaskScope = 'job' | 'step' | 'shell';
export type FailureMaskKind = 'continue-on-error' | 'errexit-disabled' | 'shell-failure-swallow' | 'powershell-error-continue';
export interface WorkflowFailureIntegritySignal { readonly file:string; readonly job:string; readonly step:string|null; readonly scope:FailureMaskScope; readonly kind:FailureMaskKind; readonly line:number; readonly value:string; readonly gateLike:boolean; readonly privileged:boolean; readonly externalContribution:boolean; readonly dynamic:boolean; }
export interface WorkflowFailureIntegritySummary { readonly workflowFiles:number; readonly jobs:number; readonly runSteps:number; readonly gateLikeSteps:number; readonly failureMaskSignals:number; readonly gateMaskSignals:number; readonly privilegedMaskSignals:number; readonly signals:readonly WorkflowFailureIntegritySignal[]; readonly findings:readonly Finding[]; }
const TRUE=/^true$/i, FALSE=/^false$/i;
const GATE_WORD=/(?:^|[^a-z0-9])(?:test|tests|lint|typecheck|type-check|build|audit|scan|security|verify|verification|validate|validation|quality|regression|smoke|coverage|check|checks)(?:[^a-z0-9]|$)/i;
const SET_PLUS_E=/(?:^|\n)\s*set\s+\+e(?:\s|$)/i, SET_PLUS_ERREXIT=/(?:^|\n)\s*set\s+\+o\s+errexit(?:\s|$)/i;
const SHELL_SWALLOW=/(?:\|\|\s*(?:true\b|:\s*(?:$|[;#\n])|echo\b|printf\b))|(?:\b(?:true|:)\s*;\s*#?\s*(?:ignore|allow|non[- ]blocking|best[- ]effort))/im;
const POWERSHELL_CONTINUE=/\$ErrorActionPreference\s*=\s*['"](?:Continue|SilentlyContinue)['"]|-ErrorAction\s+(?:Continue|SilentlyContinue)\b/i;
function privileged(b:WorkflowJobBlock){return jobHasWriteAuthority(b)||jobHasSecrets(b)||jobUsesProtectedEnvironment(b);}
function gateLikeStep(s:WorkflowStepBlock){return GATE_WORD.test(`${stepDisplayName(s)}\n${stepRunText(s)}\n${firstWorkflowStepField(s,'uses')?.value??''}`);}
function gateLikeJob(b:WorkflowJobBlock){return GATE_WORD.test(b.name)||workflowStepBlocks(b).some(gateLikeStep);}
function signal(b:WorkflowJobBlock,s:WorkflowStepBlock|undefined,scope:FailureMaskScope,kind:FailureMaskKind,line:number,value:string,gateLike:boolean,dynamic=false):WorkflowFailureIntegritySignal{return{file:b.file.repositoryPath,job:b.name,step:s?stepDisplayName(s):null,scope,kind,line,value,gateLike,privileged:privileged(b),externalContribution:workflowTriggerProfile(b.file).externalContribution,dynamic};}
function continueSignals(b:WorkflowJobBlock){const out:WorkflowFailureIntegritySignal[]=[];const jf=firstWorkflowField(b,'continue-on-error');if(jf&&!FALSE.test(jf.value))out.push(signal(b,undefined,'job','continue-on-error',jf.line,jf.value,gateLikeJob(b),hasExpression(jf.value)));for(const s of workflowStepBlocks(b)){const f=firstWorkflowStepField(s,'continue-on-error');if(f&&!FALSE.test(f.value))out.push(signal(b,s,'step','continue-on-error',f.line,f.value,gateLikeStep(s),hasExpression(f.value)));}return out;}
function shellSignals(b:WorkflowJobBlock){const out:WorkflowFailureIntegritySignal[]=[];for(const s of workflowStepBlocks(b)){const f=firstWorkflowStepField(s,'run');if(!f)continue;const run=stepRunText(s),gate=gateLikeStep(s);if(SET_PLUS_E.test(run)||SET_PLUS_ERREXIT.test(run))out.push(signal(b,s,'shell','errexit-disabled',f.line,'set +e / set +o errexit',gate));if(SHELL_SWALLOW.test(run))out.push(signal(b,s,'shell','shell-failure-swallow',f.line,'shell command failure is converted to success',gate));if(POWERSHELL_CONTINUE.test(run))out.push(signal(b,s,'shell','powershell-error-continue',f.line,'PowerShell non-terminating error policy',gate));}return out;}
function finding(i:WorkflowFailureIntegritySignal,id:string,severity:Finding['severity'],title:string,message:string,remediation:string,blocking=false):Finding{return{id,domain:'testing',severity,...(blocking?{blocking:true}:{}),title,message,location:{file:i.file,line:i.line},evidence:{value:i.value,metadata:{job:i.job,step:i.step??'job',scope:i.scope,kind:i.kind,gateLike:i.gateLike,privileged:i.privileged,externalContribution:i.externalContribution,dynamic:i.dynamic}},remediation,tags:['ci','failure-semantics','release-gate','regression','fail-closed']};}
function findingsFor(i:WorkflowFailureIntegritySignal):Finding[]{const impact=i.gateLike||i.privileged||i.externalContribution,critical=i.gateLike&&(i.privileged||i.externalContribution||i.scope==='job');if(i.kind==='continue-on-error'){if(i.dynamic)return[finding(i,'ci-failure-dynamic-continue-policy',impact?'high':'medium','Workflow failure propagation is expression-controlled',`Failure propagation for ${i.job}/${i.step??'job'} is expression-controlled.`,'Use literal continue-on-error: false for release gates and isolate optional diagnostics.',critical)];if(TRUE.test(i.value))return[finding(i,i.gateLike?'ci-failure-gate-continue-on-error':'ci-failure-continue-on-error',i.gateLike?'critical':impact?'high':'medium',i.gateLike?'Validation gate explicitly ignores failure':'Workflow explicitly ignores failure',`Failure in ${i.job}/${i.step??'job'} can be converted to a non-blocking outcome.`,'Remove continue-on-error from required validation and release gates.',i.gateLike)];return[finding(i,'ci-failure-ambiguous-continue-policy',impact?'high':'medium','Workflow uses a non-boolean continue-on-error value',`Failure propagation uses ${i.value||'<empty>'}.`,'Use literal false or remove the field.',critical)];}if(i.kind==='errexit-disabled')return[finding(i,'ci-failure-errexit-disabled',i.gateLike?'critical':impact?'high':'medium','Run script disables fail-fast shell error handling',`Step ${i.step??'unknown'} disables errexit.`,'Keep fail-fast enabled and scope expected failures narrowly.',i.gateLike)];if(i.kind==='powershell-error-continue')return[finding(i,'ci-failure-powershell-continue',i.gateLike?'critical':impact?'high':'medium','PowerShell step weakens error propagation',`Step ${i.step??'unknown'} configures non-terminating error continuation.`,"Use $ErrorActionPreference = 'Stop' for required validation.",i.gateLike)];return[finding(i,'ci-failure-shell-swallow',i.gateLike?'critical':impact?'high':'medium',i.gateLike?'Validation command failure is swallowed by shell fallback':'Shell fallback converts command failure into success',`Step ${i.step??'unknown'} can replace a failing status with success.`,'Remove failure-swallowing fallbacks from required gates.',i.gateLike)];}
export function auditWorkflowFailureIntegrity(inventory:RepositoryInventory):AuditSection<WorkflowFailureIntegritySummary>{const started=performance.now(),files=workflowFiles(inventory),jobs=files.flatMap(workflowJobBlocks),steps=jobs.flatMap(workflowStepBlocks),signals=jobs.flatMap(b=>[...continueSignals(b),...shellSignals(b)]),findings=stableSortFindings(signals.flatMap(findingsFor));return{domain:'testing',title:'Workflow failure propagation and release-gate integrity audit',summary:{workflowFiles:files.length,jobs:jobs.length,runSteps:steps.filter(s=>firstWorkflowStepField(s,'run')).length,gateLikeSteps:steps.filter(gateLikeStep).length,failureMaskSignals:signals.length,gateMaskSignals:signals.filter(i=>i.gateLike).length,privilegedMaskSignals:signals.filter(i=>i.privileged).length,signals,findings},findings,elapsedMs:Math.max(0,performance.now()-started)};}