import {closeLinearRing,dedupeAdjacentCoordinates,ensureRingOrientation,signedRingArea,type Coordinate} from "./coordinateNormalization";
import {normalizeSpatialReference,validateSpatialReference,type SpatialReferenceLike} from "./spatialReferencePolicy";
export interface PointGeometryLike{readonly x:number;readonly y:number;readonly z?:number;readonly spatialReference?:SpatialReferenceLike} export interface MultipointGeometryLike{readonly points:readonly Coordinate[];readonly spatialReference?:SpatialReferenceLike} export interface PolylineGeometryLike{readonly paths:readonly (readonly Coordinate[])[];readonly spatialReference?:SpatialReferenceLike} export interface PolygonGeometryLike{readonly rings:readonly (readonly Coordinate[])[];readonly spatialReference?:SpatialReferenceLike}
export interface GeometrySanitizerLimits{readonly maxParts:number;readonly maxVerticesPerPart:number;readonly maxTotalVertices:number;readonly coordinateTolerance:number;readonly minRingArea:number} export interface GeometrySanitizerIssue{readonly code:string;readonly path:string;readonly severity:"warning"|"error"} export interface SanitizedGeometryResult<T>{readonly geometry:T|null;readonly issues:readonly GeometrySanitizerIssue[];readonly acceptedVertices:number;readonly droppedVertices:number;readonly truncated:boolean}
export const DEFAULT_GEOMETRY_SANITIZER_LIMITS:GeometrySanitizerLimits=Object.freeze({maxParts:2000,maxVerticesPerPart:50000,maxTotalVertices:250000,coordinateTolerance:1e-8,minRingArea:1e-12});
const finite=(v:unknown):v is number=>typeof v==="number"&&Number.isFinite(v);const issue=(code:string,path:string,severity:"warning"|"error"="warning"):GeometrySanitizerIssue=>Object.freeze({code,path,severity});
const limits=(input?:Partial<GeometrySanitizerLimits>):GeometrySanitizerLimits=>{const c={...DEFAULT_GEOMETRY_SANITIZER_LIMITS,...input};const pi=(v:number,f:number)=>Number.isSafeInteger(v)&&v>0?v:f;return Object.freeze({maxParts:pi(c.maxParts,2000),maxVerticesPerPart:pi(c.maxVerticesPerPart,50000),maxTotalVertices:pi(c.maxTotalVertices,250000),coordinateTolerance:finite(c.coordinateTolerance)&&c.coordinateTolerance>=0?c.coordinateTolerance:1e-8,minRingArea:finite(c.minRingArea)&&c.minRingArea>=0?c.minRingArea:1e-12});};
const valid=(c:Coordinate)=>c.length>=2&&c.length<=3&&c.every(finite);const frozen=(c:Coordinate)=>Object.freeze([...c]) as Coordinate;
const part=(coordinates:readonly Coordinate[],path:string,l:GeometrySanitizerLimits,budget:{remaining:number},issues:GeometrySanitizerIssue[])=>{const accepted:Coordinate[]=[];let dropped=0,truncated=false;const cap=Math.min(l.maxVerticesPerPart,budget.remaining);for(let i=0;i<coordinates.length;i++){const c=coordinates[i]!;if(!valid(c)){dropped++;issues.push(issue("coordinate-non-finite",`${path}[${i}]`));continue;}if(accepted.length>=cap){dropped+=coordinates.length-i;truncated=true;issues.push(issue("vertex-budget-exceeded",path,"error"));break;}accepted.push(frozen(c));}const deduped=dedupeAdjacentCoordinates(accepted,l.coordinateTolerance);dropped+=accepted.length-deduped.length;if(accepted.length!==deduped.length)issues.push(issue("adjacent-duplicate-coordinate",path));budget.remaining-=deduped.length;return{coordinates:deduped,dropped,truncated};};
const srIssues=(sr:SpatialReferenceLike|undefined)=>validateSpatialReference(sr).map(code=>issue(code,"spatialReference","error"));
export const sanitizePointGeometry=(g:PointGeometryLike,_?:Partial<GeometrySanitizerLimits>):SanitizedGeometryResult<Readonly<PointGeometryLike>>=>{const issues=[...srIssues(g.spatialReference)];if(!finite(g.x)||!finite(g.y)||(g.z!==undefined&&!finite(g.z))){issues.push(issue("point-coordinate-non-finite","point","error"));return Object.freeze({geometry:null,issues:Object.freeze(issues),acceptedVertices:0,droppedVertices:1,truncated:false});}return Object.freeze({geometry:Object.freeze({x:g.x,y:g.y,...(g.z===undefined?{}:{z:g.z}),spatialReference:normalizeSpatialReference(g.spatialReference)}),issues:Object.freeze(issues),acceptedVertices:1,droppedVertices:0,truncated:false});};
export const sanitizeMultipointGeometry=(g:MultipointGeometryLike,input?:Partial<GeometrySanitizerLimits>):SanitizedGeometryResult<Readonly<MultipointGeometryLike>>=>{const l=limits(input),issues=[...srIssues(g.spatialReference)],budget={remaining:l.maxTotalVertices},p=part(g.points,"points",l,budget,issues);return Object.freeze({geometry:Object.freeze({points:p.coordinates,spatialReference:normalizeSpatialReference(g.spatialReference)}),issues:Object.freeze(issues),acceptedVertices:p.coordinates.length,droppedVertices:p.dropped,truncated:p.truncated});};
export const sanitizePolylineGeometry=(g:PolylineGeometryLike,input?:Partial<GeometrySanitizerLimits>):SanitizedGeometryResult<Readonly<PolylineGeometryLike>>=>{const l=limits(input),issues=[...srIssues(g.spatialReference)],budget={remaining:l.maxTotalVertices},paths:(readonly Coordinate[])[]=[];let dropped=0,truncated=false;const count=Math.min(g.paths.length,l.maxParts);if(g.paths.length>count){truncated=true;issues.push(issue("part-budget-exceeded","paths","error"));}for(let i=0;i<count&&budget.remaining>0;i++){const r=part(g.paths[i]!,`paths[${i}]`,l,budget,issues);dropped+=r.dropped;truncated||=r.truncated;if(r.coordinates.length>=2)paths.push(r.coordinates);else{dropped+=r.coordinates.length;issues.push(issue("polyline-path-degenerate",`paths[${i}]`));}}const acceptedVertices=paths.reduce((s,p)=>s+p.length,0);return Object.freeze({geometry:Object.freeze({paths:Object.freeze(paths),spatialReference:normalizeSpatialReference(g.spatialReference)}),issues:Object.freeze(issues),acceptedVertices,droppedVertices:dropped,truncated});};
export const sanitizePolygonGeometry=(g:PolygonGeometryLike,input?:Partial<GeometrySanitizerLimits>):SanitizedGeometryResult<Readonly<PolygonGeometryLike>>=>{const l=limits(input),issues=[...srIssues(g.spatialReference)],budget={remaining:l.maxTotalVertices},rings:(readonly Coordinate[])[]=[];let dropped=0,truncated=false;const count=Math.min(g.rings.length,l.maxParts);if(g.rings.length>count){truncated=true;issues.push(issue("part-budget-exceeded","rings","error"));}for(let i=0;i<count&&budget.remaining>0;i++){const r=part(g.rings[i]!,`rings[${i}]`,l,budget,issues);dropped+=r.dropped;truncated||=r.truncated;const closed=closeLinearRing(r.coordinates,l.coordinateTolerance);if(closed.length<4||Math.abs(signedRingArea(closed))<l.minRingArea){dropped+=r.coordinates.length;issues.push(issue("polygon-ring-degenerate",`rings[${i}]`));continue;}rings.push(ensureRingOrientation(closed,i===0?"clockwise":"counterclockwise"));}const acceptedVertices=rings.reduce((s,r)=>s+r.length,0);return Object.freeze({geometry:Object.freeze({rings:Object.freeze(rings),spatialReference:normalizeSpatialReference(g.spatialReference)}),issues:Object.freeze(issues),acceptedVertices,droppedVertices:dropped,truncated});};
