import {describe,expect,it} from "vitest";import {sanitizeMultipointGeometry,sanitizePointGeometry,sanitizePolygonGeometry,sanitizePolylineGeometry} from "./geometrySanitizer";
describe("geometrySanitizer",()=>{
it("rejects non-finite points",()=>{const r=sanitizePointGeometry({x:NaN,y:1,spatialReference:{wkid:4326}});expect(r.geometry).toBeNull();expect(r.issues).toEqual(expect.arrayContaining([expect.objectContaining({code:"point-coordinate-non-finite",severity:"error"})]));});
it("preserves z and canonical SR",()=>{const r=sanitizePointGeometry({x:1,y:2,z:3,spatialReference:{wkid:102100}});expect(r.geometry).toMatchObject({x:1,y:2,z:3,spatialReference:{canonicalWkid:3857}});expect(r.acceptedVertices).toBe(1);});
it("drops invalid and duplicate multipoints",()=>{const r=sanitizeMultipointGeometry({points:[[0,0],[0,0],[NaN,2],[3,4]],spatialReference:{wkid:4326}});expect(r.geometry?.points).toEqual([[0,0],[3,4]]);expect(r.droppedVertices).toBe(2);});
it("drops degenerate paths",()=>{const r=sanitizePolylineGeometry({paths:[[[0,0]],[[0,0],[1,1]]],spatialReference:{wkid:4326}});expect(r.geometry?.paths).toHaveLength(1);expect(r.issues).toEqual(expect.arrayContaining([expect.objectContaining({code:"polyline-path-degenerate"})]));});
it("enforces vertex budgets",()=>{const r=sanitizePolylineGeometry({paths:[[[0,0],[1,1],[2,2],[3,3]]],spatialReference:{wkid:4326}},{maxTotalVertices:2});expect(r.truncated).toBe(true);expect(r.acceptedVertices).toBe(2);});
it("closes polygon shells",()=>{const r=sanitizePolygonGeometry({rings:[[[0,0],[2,0],[2,2],[0,2]]],spatialReference:{wkid:4326}});expect(r.geometry?.rings[0]).toHaveLength(5);expect(r.geometry?.rings[0]?.[0]).toEqual(r.geometry?.rings[0]?.at(-1));});
it("drops zero-area rings",()=>{const r=sanitizePolygonGeometry({rings:[[[0,0],[1,1],[2,2]]],spatialReference:{wkid:4326}});expect(r.geometry?.rings).toHaveLength(0);expect(r.issues).toEqual(expect.arrayContaining([expect.objectContaining({code:"polygon-ring-degenerate"})]));});
it("reports missing SR",()=>{const r=sanitizeMultipointGeometry({points:[[1,2]]});expect(r.geometry?.points).toEqual([[1,2]]);expect(r.issues).toEqual(expect.arrayContaining([expect.objectContaining({code:"spatial-reference-missing",severity:"error"})]));});
it("caps part count",()=>{const r=sanitizePolylineGeometry({paths:[[[0,0],[1,1]],[[2,2],[3,3]]],spatialReference:{wkid:4326}},{maxParts:1});expect(r.geometry?.paths).toHaveLength(1);expect(r.truncated).toBe(true);});
});
