import { describe, expect, it } from 'vitest';
import { planLayerVisibility, scaleLayerVisibilityBudget, selectLayerVisibilityBudget, type LayerVisibilityBudget, type LayerVisibilityCandidate } from './layerVisibilityBudgetRuntime';
const budget:LayerVisibilityBudget={maxLayers:2,maxFeatures:1000,maxDrawCalls:20,maxGpuBytes:10_000,maxCpuBytes:20_000};
function layer(overrides:Partial<LayerVisibilityCandidate>={}):LayerVisibilityCandidate{return{id:'a',kind:'feature',priority:'normal',visible:true,estimatedFeatures:100,estimatedDrawCalls:2,estimatedGpuBytes:1000,estimatedCpuBytes:2000,...overrides};}
const context={scale:10_000,now:100,mode:'2d' as const};
describe('planLayerVisibility',()=>{
it('admits eligible layers and reports immutable usage',()=>{const r=planLayerVisibility([layer(),layer({id:'b'})],budget,context);expect(r.admittedIds).toEqual(['a','b']);expect(r.usage).toEqual({layers:2,features:200,drawCalls:4,gpuBytes:2000,cpuBytes:4000});expect(r.pressure).toBe(1);expect(Object.isFrozen(r)).toBe(true);});
it('rejects hidden and out-of-scale layers',()=>{const r=planLayerVisibility([layer({id:'hidden',visible:false}),layer({id:'far',minScale:5000}),layer({id:'close',maxScale:20_000})],budget,context);expect(r.rejectedIds).toEqual(['hidden','far','close']);});
it('prioritizes critical layers deterministically',()=>{const r=planLayerVisibility([layer({id:'low',priority:'low'}),layer({id:'critical',priority:'critical'}),layer({id:'high',priority:'high'})],{...budget,maxLayers:1},context);expect(r.admittedIds).toEqual(['critical']);});
it('uses recency and cost tie breakers',()=>{expect(planLayerVisibility([layer({id:'old',lastVisibleAt:1}),layer({id:'recent',lastVisibleAt:2})],{...budget,maxLayers:1},context).admittedIds).toEqual(['recent']);expect(planLayerVisibility([layer({id:'expensive',estimatedDrawCalls:5}),layer({id:'cheap',estimatedDrawCalls:1})],{...budget,maxLayers:1},context).admittedIds).toEqual(['cheap']);});
it.each([['feature-budget',{estimatedFeatures:1001}],['draw-call-budget',{estimatedDrawCalls:21}],['gpu-budget',{estimatedGpuBytes:10_001}],['cpu-budget',{estimatedCpuBytes:20_001}]] as const)('reports %s independently',(reason,overrides)=>{expect(planLayerVisibility([layer(overrides)],budget,context).decisions[0]).toEqual({id:'a',admitted:false,reason});});
it('does not consume capacity for rejected work',()=>{const r=planLayerVisibility([layer({id:'expensive',priority:'critical',estimatedGpuBytes:20_000}),layer({id:'fit'})],budget,context);expect(r.admittedIds).toEqual(['fit']);});
it('rejects duplicate ids and invalid inputs',()=>{expect(()=>planLayerVisibility([layer(),layer()],budget,context)).toThrow('duplicate layer id');expect(()=>planLayerVisibility([layer({estimatedFeatures:-1})],budget,context)).toThrow(RangeError);expect(()=>planLayerVisibility([layer()],budget,{...context,scale:Number.NaN})).toThrow(RangeError);});
});
describe('budget helpers',()=>{it('selects mode budget',()=>{const mode3d={...budget,maxLayers:1};expect(selectLayerVisibilityBudget({mode2d:budget,mode3d},'3d')).toBe(mode3d);});it('scales without zero capacity',()=>{expect(scaleLayerVisibilityBudget({maxLayers:1,maxFeatures:2,maxDrawCalls:3,maxGpuBytes:4,maxCpuBytes:5},0.1)).toEqual({maxLayers:1,maxFeatures:1,maxDrawCalls:1,maxGpuBytes:1,maxCpuBytes:1});});it('rejects unsafe scaling',()=>{expect(()=>scaleLayerVisibilityBudget(budget,0)).toThrow(RangeError);expect(()=>scaleLayerVisibilityBudget(budget,1.1)).toThrow(RangeError);});});
