import { describe, expect, it } from 'vitest';
import { LayerResidencyRuntime, type LayerResidencyDescriptor } from './layerResidencyRuntime';

const budget = { cpuBytes: 100, gpuBytes: 100, featureCount: 100, drawCalls: 10, maxResidentLayers: 2 };
const layer = (id: string, priority: LayerResidencyDescriptor['priority'] = 'normal', overrides: Partial<LayerResidencyDescriptor> = {}): LayerResidencyDescriptor => {
  const { id: _ignoredId, mode = '2d', priority: overridePriority = priority, cost = { cpuBytes: 40, gpuBytes: 40, featureCount: 40, drawCalls: 2 }, ...optionalOverrides } = overrides;
  return { ...optionalOverrides, id, mode, priority: overridePriority, cost };
};

describe('LayerResidencyRuntime', () => {
  it('bounds all resource dimensions', () => { const runtime = new LayerResidencyRuntime({ budget }); runtime.register(layer('roads')); runtime.register(layer('buildings')); expect(runtime.admit('roads', 1000).admitted).toBe(true); expect(runtime.admit('buildings', 1000).admitted).toBe(true); expect(runtime.snapshot().usage).toEqual({ cpuBytes: 80, gpuBytes: 80, featureCount: 80, drawCalls: 4, residentLayers: 2 }); });
  it('evicts lower-priority LRU work deterministically', () => { let now = 1; const runtime = new LayerResidencyRuntime({ budget, now: () => now++ }); runtime.register(layer('low-a','low')); runtime.register(layer('low-b','low')); runtime.register(layer('critical','critical')); runtime.admit('low-a',1000); runtime.admit('low-b',1000); runtime.touch('low-b'); expect(runtime.admit('critical',1000)).toEqual({ admitted: true, layerId: 'critical', evictedLayerIds: ['low-a'] }); });
  it('protects higher-priority resident work', () => { const runtime = new LayerResidencyRuntime({ budget: { ...budget, maxResidentLayers: 1 } }); runtime.register(layer('critical','critical')); runtime.register(layer('low','low')); runtime.admit('critical',1000); expect(runtime.admit('low',1000).reason).toBe('capacity'); });
  it('rejects a single layer exceeding a resource budget', () => { const runtime = new LayerResidencyRuntime({ budget }); runtime.register(layer('huge','critical',{ cost:{ cpuBytes:101,gpuBytes:1,featureCount:1,drawCalls:1 } })); expect(runtime.admit('huge',1000).reason).toBe('single-layer-budget'); });
  it('honors ArcGIS scale ranges and reconciles residents', () => { const runtime = new LayerResidencyRuntime({ budget }); runtime.register(layer('parcel','normal',{ minScale:5000,maxScale:500 })); expect(runtime.admit('parcel',100).reason).toBe('scale'); expect(runtime.admit('parcel',1000).admitted).toBe(true); expect(runtime.reconcileScale(10000)).toEqual(['parcel']); expect(runtime.snapshot().usage.residentLayers).toBe(0); });
  it('bounds registration metadata', () => { let now=0; const runtime = new LayerResidencyRuntime({ budget,maxEntries:2,now:()=>++now }); runtime.register(layer('a')); runtime.register(layer('b')); runtime.touch('b'); runtime.register(layer('c')); expect(runtime.snapshot().entries.map((entry)=>entry.descriptor.id)).toEqual(['b','c']); });
  it('fails closed when resident metadata exhausts capacity', () => { const runtime = new LayerResidencyRuntime({ budget,maxEntries:1 }); runtime.register(layer('resident')); runtime.admit('resident',1000); expect(()=>runtime.register(layer('new'))).toThrow('capacity exhausted'); });
  it('validates ids costs ranges and budgets', () => { const runtime = new LayerResidencyRuntime({ budget }); expect(runtime.register(layer('  roads  ')).descriptor.id).toBe('roads'); expect(()=>runtime.register(layer('bad','normal',{cost:{cpuBytes:-1,gpuBytes:1,featureCount:1,drawCalls:1}}))).toThrow(); expect(()=>runtime.register(layer('range','normal',{minScale:1000,maxScale:2000}))).toThrow(); expect(()=>new LayerResidencyRuntime({budget:{...budget,maxResidentLayers:0}})).toThrow(); });
  it('returns immutable sorted snapshots', () => { const runtime = new LayerResidencyRuntime({ budget }); runtime.register(layer('z')); runtime.register(layer('a')); const snapshot=runtime.snapshot(); expect(snapshot.entries.map((entry)=>entry.descriptor.id)).toEqual(['a','z']); expect(Object.isFrozen(snapshot)).toBe(true); expect(Object.isFrozen(snapshot.entries)).toBe(true); expect(Object.isFrozen(snapshot.entries[0]?.descriptor.cost)).toBe(true); });
  it('supports suspension and removal without usage leaks', () => { const runtime = new LayerResidencyRuntime({ budget }); runtime.register(layer('a')); runtime.admit('a',1000); expect(runtime.suspend('a')).toBe(true); expect(runtime.suspend('a')).toBe(false); expect(runtime.snapshot().usage.residentLayers).toBe(0); expect(runtime.remove('a')).toBe(true); expect(runtime.admit('a',1000).reason).toBe('not-registered'); });
  it('fails closed after idempotent disposal', () => { const runtime = new LayerResidencyRuntime({ budget }); runtime.register(layer('a')); runtime.dispose(); runtime.dispose(); expect(runtime.snapshot().entries).toEqual([]); expect(()=>runtime.register(layer('b'))).toThrow('disposed'); });
});
