export type GisViewMode = "2d" | "3d";
export type LayerRenderStatus = "hidden" | "loading" | "ready" | "error";
export interface LayerRenderIntent { readonly layerId:string; readonly visible:boolean; readonly opacity:number; readonly minScale?:number; readonly maxScale?:number; readonly selectedObjectIds?:readonly (string|number)[]; readonly highlightedObjectIds?:readonly (string|number)[]; }
export interface RenderFrameFacts { readonly mode:GisViewMode; readonly scale:number; }
export interface LayerRenderState { readonly layerId:string; readonly mode:GisViewMode; readonly status:LayerRenderStatus; readonly visible:boolean; readonly opacity:number; readonly selectedObjectIds:readonly string[]; readonly highlightedObjectIds:readonly string[]; readonly revision:number; readonly error?:string; }
export interface RenderStateSnapshot { readonly mode:GisViewMode; readonly revision:number; readonly layers:readonly LayerRenderState[]; }
export interface RenderStateCoordinator { reconcile(frame:RenderFrameFacts,intents:readonly LayerRenderIntent[]):RenderStateSnapshot; markLoading(layerId:string):RenderStateSnapshot; markReady(layerId:string):RenderStateSnapshot; markError(layerId:string,message:string):RenderStateSnapshot; releaseLayer(layerId:string):RenderStateSnapshot; clearTransientState():RenderStateSnapshot; snapshot():RenderStateSnapshot; dispose():void; }
type StateInput=Omit<LayerRenderState,"revision">;
function ids(values:readonly (string|number)[]|undefined):readonly string[]{const out=new Set<string>();for(const value of values??[]){const v=typeof value==="number"?(Number.isFinite(value)?String(value):""):value.trim();if(v)out.add(v);}return Array.from(out).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));}
function opacity(value:number){return Number.isFinite(value)?Math.max(0,Math.min(1,value)):1;}
function scaleVisible(intent:LayerRenderIntent,scale:number){if(intent.minScale&&scale>intent.minScale)return false;if(intent.maxScale&&scale<intent.maxScale)return false;return true;}
function equal(a:LayerRenderState,b:StateInput){return a.layerId===b.layerId&&a.mode===b.mode&&a.status===b.status&&a.visible===b.visible&&a.opacity===b.opacity&&a.error===b.error&&a.selectedObjectIds.join("\0")===b.selectedObjectIds.join("\0")&&a.highlightedObjectIds.join("\0")===b.highlightedObjectIds.join("\0");}
function input(current:LayerRenderState,patch:Partial<StateInput>):StateInput{return {layerId:patch.layerId??current.layerId,mode:patch.mode??current.mode,status:patch.status??current.status,visible:patch.visible??current.visible,opacity:patch.opacity??current.opacity,selectedObjectIds:patch.selectedObjectIds??current.selectedObjectIds,highlightedObjectIds:patch.highlightedObjectIds??current.highlightedObjectIds,error:Object.prototype.hasOwnProperty.call(patch,"error")?patch.error:current.error};}
export function createRenderStateCoordinator(initialMode:GisViewMode="2d"):RenderStateCoordinator{let mode=initialMode,revision=0,disposed=false;const states=new Map<string,LayerRenderState>();const active=()=>{if(disposed)throw new Error("Render state coordinator is disposed");};const snap=():RenderStateSnapshot=>({mode,revision,layers:Array.from(states.values()).sort((a,b)=>a.layerId.localeCompare(b.layerId))});const replace=(id:string,next:StateInput)=>{const old=states.get(id);if(old&&equal(old,next))return;revision++;states.set(id,{...next,revision});};const status=(id:string,next:LayerRenderStatus,error?:string)=>{active();const old=states.get(id.trim());if(old)replace(old.layerId,input(old,{status:next,error}));return snap();};return {reconcile(frame,intents){active();if((frame.mode!=="2d"&&frame.mode!=="3d")||!Number.isFinite(frame.scale)||frame.scale<=0)throw new Error("Invalid render frame");if(mode!==frame.mode){mode=frame.mode;revision++;}const seen=new Set<string>();for(const intent of intents){const layerId=intent.layerId.trim();if(!layerId)throw new Error("Layer id must not be blank");if(seen.has(layerId))throw new Error(`Duplicate layer render intent: ${layerId}`);seen.add(layerId);const old=states.get(layerId);const visible=intent.visible&&scaleVisible(intent,frame.scale);const nextStatus:LayerRenderStatus=visible?(old?.status==="error"?"error":old?.status??"loading"):"hidden";replace(layerId,{layerId,mode,status:nextStatus,visible,opacity:opacity(intent.opacity),selectedObjectIds:ids(intent.selectedObjectIds),highlightedObjectIds:ids(intent.highlightedObjectIds),error:nextStatus==="error"?old?.error:undefined});}for(const id of states.keys())if(!seen.has(id)){states.delete(id);revision++;}return snap();},markLoading(id){return status(id,"loading");},markReady(id){return status(id,"ready");},markError(id,message){return status(id,"error",message.trim()||"Layer render failed");},releaseLayer(id){active();if(states.delete(id.trim()))revision++;return snap();},clearTransientState(){active();for(const [id,old]of states)if(old.selectedObjectIds.length||old.highlightedObjectIds.length)replace(id,input(old,{selectedObjectIds:[],highlightedObjectIds:[]}));return snap();},snapshot(){active();return snap();},dispose(){if(disposed)return;states.clear();revision++;disposed=true;}};}
