import { describe, expect, it } from 'vitest';
import { SpatialSelectionIndexRuntime } from './spatialSelectionIndexRuntime';

const bounds = (xmin: number, ymin: number, xmax: number, ymax: number) => ({ xmin, ymin, xmax, ymax });
const record = (id: string, layerId = 'places', priority: 'background' | 'normal' | 'high' | 'critical' = 'normal', estimatedBytes = 10) => ({ id, layerId, priority, estimatedBytes, bounds: bounds(0, 0, 10, 10), payload: { id } });

describe('SpatialSelectionIndexRuntime', () => {
  it('indexes and queries deterministically', () => { const runtime = new SpatialSelectionIndexRuntime<{ id: string }>(); runtime.upsert(record('b')); runtime.upsert(record('a', 'places', 'high')); expect(runtime.query({ bounds: bounds(5, 5, 6, 6) }).map((item) => item.id)).toEqual(['a', 'b']); });
  it('bounds query results', () => { const runtime = new SpatialSelectionIndexRuntime<{ id: string }>({ maxQueryResults: 2 }); for (let index = 0; index < 5; index += 1) runtime.upsert(record(`id-${index}`)); expect(runtime.query({ bounds: bounds(0, 0, 10, 10), limit: 99 })).toHaveLength(2); });
  it('evicts lower priority first', () => { const runtime = new SpatialSelectionIndexRuntime<{ id: string }>({ maxEntries: 2 }); runtime.upsert(record('critical', 'a', 'critical')); runtime.upsert(record('background', 'a', 'background')); runtime.upsert(record('high', 'a', 'high')); expect(runtime.has('critical')).toBe(true); expect(runtime.has('high')).toBe(true); expect(runtime.has('background')).toBe(false); });
  it('enforces byte budgets', () => { const runtime = new SpatialSelectionIndexRuntime<{ id: string }>({ maxBytes: 20, maxEntries: 10 }); runtime.upsert(record('a', 'x', 'normal', 10)); runtime.upsert(record('b', 'x', 'normal', 10)); runtime.upsert(record('c', 'x', 'high', 10)); expect(runtime.snapshot().estimatedBytes).toBeLessThanOrEqual(20); });
  it('rejects an oversized entry', () => { const runtime = new SpatialSelectionIndexRuntime<{ id: string }>({ maxBytes: 20 }); expect(runtime.upsert(record('huge', 'x', 'critical', 21))).toBeNull(); expect(runtime.snapshot().rejected).toBe(1); });
  it('enforces per-layer cardinality', () => { const runtime = new SpatialSelectionIndexRuntime<{ id: string }>({ maxEntriesPerLayer: 1, maxEntries: 10 }); runtime.upsert(record('a1', 'a')); runtime.upsert(record('b1', 'b')); runtime.upsert(record('a2', 'a', 'high')); expect(runtime.has('a1')).toBe(false); expect(runtime.has('a2')).toBe(true); expect(runtime.has('b1')).toBe(true); });
  it('replaces without leaking accounting', () => { const runtime = new SpatialSelectionIndexRuntime<{ id: string }>({ maxBytes: 100 }); runtime.upsert(record('same', 'old', 'normal', 40)); runtime.upsert(record('same', 'new', 'high', 15)); expect(runtime.snapshot()).toMatchObject({ entries: 1, estimatedBytes: 15, layers: 1 }); });
  it('removes a complete layer', () => { const runtime = new SpatialSelectionIndexRuntime<{ id: string }>(); runtime.upsert(record('a', 'one')); runtime.upsert(record('b', 'one')); runtime.upsert(record('c', 'two')); expect(runtime.removeLayer('one')).toBe(2); expect(runtime.snapshot().entries).toBe(1); });
  it('returns nearest bounds', () => { const runtime = new SpatialSelectionIndexRuntime<{ id: string }>(); runtime.upsert({ ...record('near'), bounds: bounds(10, 10, 20, 20) }); runtime.upsert({ ...record('far'), bounds: bounds(100, 100, 110, 110) }); expect(runtime.nearest({ x: 0, y: 0 }, 1)[0]?.id).toBe('near'); });
  it('bounds mutation history', () => { const runtime = new SpatialSelectionIndexRuntime<{ id: string }>({ maxHistory: 2 }); runtime.upsert(record('a')); runtime.upsert(record('b')); runtime.remove('a'); expect(runtime.history()).toHaveLength(2); });
  it('normalizes negative zero', () => { const runtime = new SpatialSelectionIndexRuntime<{ id: string }>(); const inserted = runtime.upsert({ ...record('a'), bounds: bounds(-0, -0, 1, 1) }); expect(Object.is(inserted?.bounds.xmin, -0)).toBe(false); });
  it('rejects inverted and non-finite bounds', () => { const runtime = new SpatialSelectionIndexRuntime<{ id: string }>(); expect(() => runtime.upsert({ ...record('bad'), bounds: bounds(2, 0, 1, 1) })).toThrow(/minimum/); expect(() => runtime.query({ bounds: bounds(0, 0, Number.POSITIVE_INFINITY, 1) })).toThrow(/finite/); });
  it('rejects invalid budgets and identifiers', () => { expect(() => new SpatialSelectionIndexRuntime({ maxEntries: 0 })).toThrow(/positive/); const runtime = new SpatialSelectionIndexRuntime<{ id: string }>(); expect(() => runtime.upsert({ ...record('x'), id: ' ' })).toThrow(/empty/); });
  it('increments revisions only for mutations', () => { const runtime = new SpatialSelectionIndexRuntime<{ id: string }>(); runtime.upsert(record('a')); expect(runtime.remove('missing')).toBe(false); expect(runtime.snapshot().revision).toBe(1); runtime.remove('a'); expect(runtime.snapshot().revision).toBe(2); });
  it('disposes deterministically', () => { const runtime = new SpatialSelectionIndexRuntime<{ id: string }>(); runtime.upsert(record('a')); runtime.dispose(); expect(runtime.disposed).toBe(true); expect(() => runtime.get('a')).toThrow(/disposed/); expect(runtime.history()).toEqual([]); expect(() => runtime.dispose()).not.toThrow(); });
});
