import { type Coordinate2D, type Extent2D, type NormalizedSpatialReference, type SpatialReferenceRuntimeOptions, normalizeExtent, projectCoordinate, projectCoordinates, projectExtent, spatialReferencesEquivalent } from "./spatialReferenceRuntime";
export type PointGeometry2D = Readonly<{ type:"point"; x:number; y:number; spatialReference:NormalizedSpatialReference }>;
export type MultipointGeometry2D = Readonly<{ type:"multipoint"; points:readonly Coordinate2D[]; spatialReference:NormalizedSpatialReference }>;
export type PolylineGeometry2D = Readonly<{ type:"polyline"; paths:readonly (readonly Coordinate2D[])[]; spatialReference:NormalizedSpatialReference }>;
export type PolygonGeometry2D = Readonly<{ type:"polygon"; rings:readonly (readonly Coordinate2D[])[]; spatialReference:NormalizedSpatialReference }>;
export type ExtentGeometry2D = Readonly<{ type:"extent"; extent:Extent2D; spatialReference:NormalizedSpatialReference }>;
export type Geometry2D = PointGeometry2D|MultipointGeometry2D|PolylineGeometry2D|PolygonGeometry2D|ExtentGeometry2D;
export type GeometryProjectionOptions = SpatialReferenceRuntimeOptions & Readonly<{signal?:AbortSignal;maxParts?:number;maxVerticesPerPart?:number;closePolygonRings?:boolean}>;
const DEFAULT_MAX_PARTS=10_000, DEFAULT_MAX_VERTICES_PER_PART=100_000;
function positiveBudget(v:number|undefined,f:number,l:string){const r=v??f;if(!Number.isSafeInteger(r)||r<=0)throw new RangeError(`${l} must be a positive safe integer`);return r;}
function throwIfAborted(s?:AbortSignal){if(s?.aborted)throw s.reason??new DOMException("Aborted","AbortError");}
function finite(v:number,l:string){if(!Number.isFinite(v))throw new TypeError(`${l} must be finite`);return v;}
function coordinate(v:Coordinate2D,l:string):Coordinate2D{return Object.freeze([finite(v[0],`${l}.x`),finite(v[1],`${l}.y`)]);}
function validatePart(part:readonly Coordinate2D[],pi:number,max:number,signal?:AbortSignal){if(part.length>max)throw new RangeError(`geometry part ${pi} exceeds vertex budget`);const r:Coordinate2D[]=[];for(let i=0;i<part.length;i++){throwIfAborted(signal);r.push(coordinate(part[i]!,`part[${pi}][${i}]`));}return Object.freeze(r);}
function validateParts(parts:readonly (readonly Coordinate2D[])[],o:GeometryProjectionOptions){const mp=positiveBudget(o.maxParts,DEFAULT_MAX_PARTS,"maxParts"),mv=positiveBudget(o.maxVerticesPerPart,DEFAULT_MAX_VERTICES_PER_PART,"maxVerticesPerPart"),mc=positiveBudget(o.maxCoordinates,100_000,"maxCoordinates");if(parts.length>mp)throw new RangeError("geometry exceeds part budget");let total=0;const r:(readonly Coordinate2D[])[]=[];for(let i=0;i<parts.length;i++){throwIfAborted(o.signal);const n=validatePart(parts[i]!,i,mv,o.signal);total+=n.length;if(total>mc)throw new RangeError("geometry exceeds total coordinate budget");r.push(n);}return Object.freeze(r);}
function same(a:Coordinate2D,b:Coordinate2D){return Object.is(a[0],b[0])&&Object.is(a[1],b[1]);}
function closeRing(r:readonly Coordinate2D[]){return r.length===0||same(r[0]!,r[r.length-1]!)?r:Object.freeze([...r,r[0]!]);}
export function normalizeGeometry2D(g:Geometry2D,o:GeometryProjectionOptions={}):Geometry2D{throwIfAborted(o.signal);switch(g.type){case"point":return Object.freeze({type:"point",x:finite(g.x,"point.x"),y:finite(g.y,"point.y"),spatialReference:g.spatialReference});case"extent":return Object.freeze({type:"extent",extent:normalizeExtent(g.extent),spatialReference:g.spatialReference});case"multipoint":return Object.freeze({type:"multipoint",points:validatePart(g.points,0,positiveBudget(o.maxCoordinates,100_000,"maxCoordinates"),o.signal),spatialReference:g.spatialReference});case"polyline":return Object.freeze({type:"polyline",paths:validateParts(g.paths,o),spatialReference:g.spatialReference});case"polygon":{const rings=validateParts(g.rings,o);return Object.freeze({type:"polygon",rings:o.closePolygonRings===false?rings:Object.freeze(rings.map(closeRing)),spatialReference:g.spatialReference});}}}
function projectPart(p:readonly Coordinate2D[],s:NormalizedSpatialReference,t:NormalizedSpatialReference,o:GeometryProjectionOptions){const base={maxCoordinates:positiveBudget(o.maxVerticesPerPart,100_000,"maxVerticesPerPart")};return projectCoordinates(p,s,t,o.signal?{...base,signal:o.signal}:base);}
export function projectGeometry2D(g:Geometry2D,t:NormalizedSpatialReference,o:GeometryProjectionOptions={}):Geometry2D{const n=normalizeGeometry2D(g,o);throwIfAborted(o.signal);if(spatialReferencesEquivalent(n.spatialReference,t))return Object.freeze({...n,spatialReference:t}) as Geometry2D;switch(n.type){case"point":{const[x,y]=projectCoordinate([n.x,n.y],n.spatialReference,t);return Object.freeze({type:"point",x,y,spatialReference:t});}case"extent":return Object.freeze({type:"extent",extent:projectExtent(n.extent,n.spatialReference,t),spatialReference:t});case"multipoint":return Object.freeze({type:"multipoint",points:projectCoordinates(n.points,n.spatialReference,t,o),spatialReference:t});case"polyline":return Object.freeze({type:"polyline",paths:Object.freeze(n.paths.map(p=>projectPart(p,n.spatialReference,t,o))),spatialReference:t});case"polygon":return Object.freeze({type:"polygon",rings:Object.freeze(n.rings.map(r=>projectPart(r,n.spatialReference,t,o))),spatialReference:t});}}
export function geometryExtent2D(g:Geometry2D,o:GeometryProjectionOptions={}):Extent2D{const n=normalizeGeometry2D(g,o);if(n.type==="extent")return n.extent;if(n.type==="point")return Object.freeze({xmin:n.x,ymin:n.y,xmax:n.x,ymax:n.y});const parts=n.type==="multipoint"?[n.points]:n.type==="polyline"?n.paths:n.rings;let xmin=Infinity,ymin=Infinity,xmax=-Infinity,ymax=-Infinity,count=0;for(const p of parts)for(const[x,y]of p){throwIfAborted(o.signal);xmin=Math.min(xmin,x);ymin=Math.min(ymin,y);xmax=Math.max(xmax,x);ymax=Math.max(ymax,y);count++;}if(!count)throw new RangeError("geometry has no coordinates");return Object.freeze({xmin,ymin,xmax,ymax});}
export function projectGeometryBatch(gs:readonly Geometry2D[],t:NormalizedSpatialReference,o:GeometryProjectionOptions&Readonly<{maxGeometries?:number}>={}):readonly Geometry2D[]{const max=positiveBudget(o.maxGeometries,10_000,"maxGeometries");if(gs.length>max)throw new RangeError("geometry batch exceeds configured budget");const r:Geometry2D[]=[];for(const g of gs){throwIfAborted(o.signal);r.push(projectGeometry2D(g,t,o));}return Object.freeze(r);}
