export interface SpatialReferenceLike { readonly wkid?: number|null; readonly latestWkid?: number|null; readonly wkt?: string|null; readonly vcsWkid?: number|null; readonly latestVcsWkid?: number|null; }
export type SpatialReferenceFamily="wgs84"|"web-mercator"|"projected"|"geographic"|"wkt"|"unknown";
export type ProjectionRequirement="none"|"projection-required"|"unsupported";
export interface NormalizedSpatialReference { readonly wkid:number|null; readonly latestWkid:number|null; readonly canonicalWkid:number|null; readonly wkt:string|null; readonly vcsWkid:number|null; readonly latestVcsWkid:number|null; readonly family:SpatialReferenceFamily; readonly isGeographic:boolean; readonly isWebMercator:boolean; readonly hasVerticalReference:boolean; readonly identity:string; }
export interface ProjectionDecision { readonly requirement:ProjectionRequirement; readonly source:NormalizedSpatialReference; readonly target:NormalizedSpatialReference; readonly reason:"same-reference"|"wgs84-alias"|"web-mercator-alias"|"different-reference"|"unknown-source"|"unknown-target"; }
const WGS84=new Set([4326]); const WEB_MERCATOR=new Set([3857,102100,102113,900913]);
const positive=(v:unknown):v is number=>typeof v==="number"&&Number.isSafeInteger(v)&&v>0;
const wkid=(v:unknown)=>positive(v)?v:null;
const wkt=(v:unknown):string|null=>{ if(typeof v!=="string") return null; const t=v.trim().replace(/\s+/g," "); return t.length>0&&t.length<=32768?t:null; };
const canonical=(a:number|null,b:number|null)=>{const c=b??a;if(c===null)return null;if(WEB_MERCATOR.has(c))return 3857;if(WGS84.has(c))return 4326;return c;};
const family=(c:number|null,text:string|null):SpatialReferenceFamily=>c===4326?"wgs84":c===3857?"web-mercator":c!==null?(c>=4000&&c<5000?"geographic":"projected"):text?"wkt":"unknown";
export const normalizeSpatialReference=(input:SpatialReferenceLike|null|undefined):NormalizedSpatialReference=>{const a=wkid(input?.wkid),b=wkid(input?.latestWkid),c=canonical(a,b),text=wkt(input?.wkt),v=wkid(input?.vcsWkid),lv=wkid(input?.latestVcsWkid),f=family(c,text),identity=c!==null?`wkid:${c}`:text?`wkt:${text}`:"unknown";return Object.freeze({wkid:a,latestWkid:b,canonicalWkid:c,wkt:text,vcsWkid:v,latestVcsWkid:lv,family:f,isGeographic:f==="wgs84"||f==="geographic",isWebMercator:f==="web-mercator",hasVerticalReference:v!==null||lv!==null,identity});};
export const spatialReferencesEquivalent=(left:SpatialReferenceLike|null|undefined,right:SpatialReferenceLike|null|undefined):boolean=>{const a=normalizeSpatialReference(left),b=normalizeSpatialReference(right);return a.identity!=="unknown"&&b.identity!=="unknown"&&a.identity===b.identity;};
export const decideProjectionRequirement=(source:SpatialReferenceLike|null|undefined,target:SpatialReferenceLike|null|undefined):ProjectionDecision=>{const s=normalizeSpatialReference(source),t=normalizeSpatialReference(target);if(s.identity==="unknown")return Object.freeze({requirement:"unsupported",source:s,target:t,reason:"unknown-source"});if(t.identity==="unknown")return Object.freeze({requirement:"unsupported",source:s,target:t,reason:"unknown-target"});if(s.identity===t.identity){const reason=s.family==="wgs84"?"wgs84-alias":s.family==="web-mercator"?"web-mercator-alias":"same-reference";return Object.freeze({requirement:"none",source:s,target:t,reason});}return Object.freeze({requirement:"projection-required",source:s,target:t,reason:"different-reference"});};
export const validateSpatialReference=(input:SpatialReferenceLike|null|undefined):readonly string[]=>{const issues:string[]=[];if(!input)return Object.freeze(["spatial-reference-missing"]);const n=normalizeSpatialReference(input);if(n.identity==="unknown")issues.push("spatial-reference-identity-missing");if(input.wkid!=null&&n.wkid===null)issues.push("wkid-invalid");if(input.latestWkid!=null&&n.latestWkid===null)issues.push("latest-wkid-invalid");if(input.vcsWkid!=null&&n.vcsWkid===null)issues.push("vertical-wkid-invalid");if(input.latestVcsWkid!=null&&n.latestVcsWkid===null)issues.push("latest-vertical-wkid-invalid");if(typeof input.wkt==="string"&&input.wkt.trim().length>0&&n.wkt===null)issues.push("wkt-invalid-or-too-large");return Object.freeze(issues);};
