import { describe, expect, it, vi } from 'vitest';
import { SpatialQueryGovernanceRuntime, SpatialQueryRejectedError, SpatialQueryTimeoutError, normalizeSpatialQueryBudget } from './spatialQueryGovernanceRuntime';
const request = (key: string, priority: 'interactive' | 'foreground' | 'background' = 'foreground') => ({ key, kind: 'search' as const, priority });
describe('SpatialQueryGovernanceRuntime', () => {
  it('normalizes and validates budgets', () => { expect(normalizeSpatialQueryBudget({ maxConcurrent: 2 }).maxConcurrent).toBe(2); expect(() => normalizeSpatialQueryBudget({ maxQueued: 0 })).toThrow(RangeError); });
  it('deduplicates equal in-flight query keys', async () => { const runtime = new SpatialQueryGovernanceRuntime(); let release!: (value: number) => void; const execute = vi.fn(() => new Promise<number>((resolve) => { release = resolve; })); const first = runtime.run(request('same'), execute); const second = runtime.run(request('same'), execute); expect(execute).toHaveBeenCalledTimes(1); expect(runtime.snapshot().deduplicatedSubscribers).toBe(1); release(42); await expect(first).resolves.toBe(42); await expect(second).resolves.toBe(42); });
  it('prioritizes queued interactive work while preserving FIFO', async () => { const runtime = new SpatialQueryGovernanceRuntime({ maxConcurrent: 1 }); let release!: () => void; const first = runtime.run(request('active'), () => new Promise<void>((resolve) => { release = resolve; })); const order: string[] = []; const background = runtime.run(request('bg', 'background'), async () => { order.push('bg'); }); const interactive1 = runtime.run(request('i1', 'interactive'), async () => { order.push('i1'); }); const interactive2 = runtime.run(request('i2', 'interactive'), async () => { order.push('i2'); }); release(); await Promise.all([first, background, interactive1, interactive2]); expect(order).toEqual(['i1', 'i2', 'bg']); });
  it('rejects estimates beyond configured budgets before queue allocation', () => { const runtime = new SpatialQueryGovernanceRuntime({ maxFeaturesPerRequest: 10, maxBytesPerRequest: 100 }); expect(() => runtime.run({ ...request('features'), estimatedFeatures: 11 }, async () => 1)).toThrow(SpatialQueryRejectedError); expect(() => runtime.run({ ...request('bytes'), estimatedBytes: 101 }, async () => 1)).toThrow(SpatialQueryRejectedError); });
  it('bounds queued work', async () => { const runtime = new SpatialQueryGovernanceRuntime({ maxConcurrent: 1, maxQueued: 1 }); let release!: () => void; const active = runtime.run(request('active'), () => new Promise<void>((resolve) => { release = resolve; })); const queued = runtime.run(request('queued'), async () => undefined); await expect(runtime.run(request('rejected'), async () => undefined)).rejects.toBeInstanceOf(SpatialQueryRejectedError); release(); await Promise.all([active, queued]); });
  it('allows one deduplicated subscriber to abort', async () => { const runtime = new SpatialQueryGovernanceRuntime(); const controller = new AbortController(); let release!: (value: string) => void; const execute = () => new Promise<string>((resolve) => { release = resolve; }); const aborted = runtime.run(request('shared'), execute, controller.signal); const survivor = runtime.run(request('shared'), execute); controller.abort(new Error('subscriber left')); await expect(aborted).rejects.toThrow('subscriber left'); release('ok'); await expect(survivor).resolves.toBe('ok'); });
  it('propagates cancellation to executor', async () => { const runtime = new SpatialQueryGovernanceRuntime(); let observed: AbortSignal | undefined; const result = runtime.run(request('cancel'), ({ signal }) => new Promise((_resolve, reject) => { observed = signal; signal.addEventListener('abort', () => reject(signal.reason), { once: true }); })); expect(runtime.cancel('cancel', new Error('manual'))).toBe(true); await expect(result).rejects.toThrow('manual'); expect(observed?.aborted).toBe(true); });
  it('enforces timeout', async () => { vi.useFakeTimers(); try { const runtime = new SpatialQueryGovernanceRuntime({ timeoutMs: 25 }); const result = runtime.run(request('slow'), ({ signal }) => new Promise((_resolve, reject) => signal.addEventListener('abort', () => reject(signal.reason), { once: true }))); await vi.advanceTimersByTimeAsync(25); await expect(result).rejects.toBeInstanceOf(SpatialQueryTimeoutError); } finally { vi.useRealTimers(); } });
  it('disposes queued and active work', async () => { const runtime = new SpatialQueryGovernanceRuntime({ maxConcurrent: 1 }); const active = runtime.run(request('a'), ({ signal }) => new Promise((_resolve, reject) => signal.addEventListener('abort', () => reject(signal.reason), { once: true }))); const queued = runtime.run(request('b'), async () => 2); runtime.dispose(new Error('shutdown')); await expect(active).rejects.toThrow('shutdown'); await expect(queued).rejects.toThrow('shutdown'); });
});
