export type SpatialQueryKind = 'identify' | 'search' | 'selection' | 'statistics' | 'extent' | 'related';
export type SpatialQueryPriority = 'interactive' | 'foreground' | 'background';

export interface SpatialQueryRequest { readonly key: string; readonly kind: SpatialQueryKind; readonly priority: SpatialQueryPriority; readonly estimatedFeatures?: number; readonly estimatedBytes?: number; }
export interface SpatialQueryBudget { readonly maxConcurrent: number; readonly maxQueued: number; readonly maxFeaturesPerRequest: number; readonly maxBytesPerRequest: number; readonly timeoutMs: number; }
export interface SpatialQueryGovernanceSnapshot { readonly active: number; readonly queued: number; readonly deduplicatedSubscribers: number; readonly rejected: number; readonly completed: number; readonly failed: number; }
export interface SpatialQueryExecutionContext { readonly signal: AbortSignal; readonly deadline: number; }
interface QueueEntry<T> { readonly request: SpatialQueryRequest; readonly execute: (context: SpatialQueryExecutionContext) => Promise<T>; readonly controller: AbortController; readonly subscribers: Set<Subscriber<T>>; readonly sequence: number; }
interface Subscriber<T> { resolve(value: T): void; reject(reason: unknown): void; signal?: AbortSignal; abort?: () => void; }
const DEFAULT_BUDGET: SpatialQueryBudget = Object.freeze({ maxConcurrent: 6, maxQueued: 64, maxFeaturesPerRequest: 20_000, maxBytesPerRequest: 16 * 1024 * 1024, timeoutMs: 30_000 });
const PRIORITY: Readonly<Record<SpatialQueryPriority, number>> = Object.freeze({ interactive: 0, foreground: 1, background: 2 });
function positiveInteger(value: number, name: string): number { if (!Number.isSafeInteger(value) || value <= 0) throw new RangeError(`${name} must be a positive safe integer`); return value; }
export function normalizeSpatialQueryBudget(input: Partial<SpatialQueryBudget> = {}): SpatialQueryBudget { return Object.freeze({ maxConcurrent: positiveInteger(input.maxConcurrent ?? DEFAULT_BUDGET.maxConcurrent, 'maxConcurrent'), maxQueued: positiveInteger(input.maxQueued ?? DEFAULT_BUDGET.maxQueued, 'maxQueued'), maxFeaturesPerRequest: positiveInteger(input.maxFeaturesPerRequest ?? DEFAULT_BUDGET.maxFeaturesPerRequest, 'maxFeaturesPerRequest'), maxBytesPerRequest: positiveInteger(input.maxBytesPerRequest ?? DEFAULT_BUDGET.maxBytesPerRequest, 'maxBytesPerRequest'), timeoutMs: positiveInteger(input.timeoutMs ?? DEFAULT_BUDGET.timeoutMs, 'timeoutMs') }); }
export class SpatialQueryRejectedError extends Error { constructor(message: string) { super(message); this.name = 'SpatialQueryRejectedError'; } }
export class SpatialQueryTimeoutError extends Error { constructor(readonly key: string, readonly timeoutMs: number) { super(`Spatial query ${key} exceeded ${timeoutMs}ms`); this.name = 'SpatialQueryTimeoutError'; } }
export class SpatialQueryGovernanceRuntime {
  readonly #budget: SpatialQueryBudget; readonly #queue: QueueEntry<unknown>[] = []; readonly #byKey = new Map<string, QueueEntry<unknown>>(); #active = 0; #sequence = 0; #deduplicatedSubscribers = 0; #rejected = 0; #completed = 0; #failed = 0; #disposed = false;
  constructor(budget: Partial<SpatialQueryBudget> = {}) { this.#budget = normalizeSpatialQueryBudget(budget); }
  get budget(): SpatialQueryBudget { return this.#budget; }
  snapshot(): SpatialQueryGovernanceSnapshot { return Object.freeze({ active: this.#active, queued: this.#queue.length, deduplicatedSubscribers: this.#deduplicatedSubscribers, rejected: this.#rejected, completed: this.#completed, failed: this.#failed }); }
  run<T>(request: SpatialQueryRequest, execute: (context: SpatialQueryExecutionContext) => Promise<T>, signal?: AbortSignal): Promise<T> { this.#validateRequest(request); if (this.#disposed) return Promise.reject(new SpatialQueryRejectedError('Spatial query runtime is disposed')); if (signal?.aborted) return Promise.reject(signal.reason ?? new DOMException('Aborted', 'AbortError')); const existing = this.#byKey.get(request.key) as QueueEntry<T> | undefined; if (existing) { this.#deduplicatedSubscribers += 1; return this.#subscribe(existing, signal); } if (this.#active >= this.#budget.maxConcurrent && this.#queue.length >= this.#budget.maxQueued) { this.#rejected += 1; return Promise.reject(new SpatialQueryRejectedError('Spatial query queue capacity exceeded')); } const entry: QueueEntry<T> = { request: Object.freeze({ ...request }), execute, controller: new AbortController(), subscribers: new Set(), sequence: this.#sequence++ }; this.#byKey.set(request.key, entry as QueueEntry<unknown>); const promise = this.#subscribe(entry, signal); this.#queue.push(entry as QueueEntry<unknown>); this.#sortQueue(); this.#drain(); return promise; }
  cancel(key: string, reason: unknown = new DOMException('Cancelled', 'AbortError')): boolean { const entry = this.#byKey.get(key); if (!entry) return false; entry.controller.abort(reason); const index = this.#queue.indexOf(entry); if (index >= 0) { this.#queue.splice(index, 1); this.#byKey.delete(key); for (const subscriber of entry.subscribers) subscriber.reject(reason); this.#cleanupSubscribers(entry); } return true; }
  dispose(reason: unknown = new DOMException('Disposed', 'AbortError')): void { if (this.#disposed) return; this.#disposed = true; for (const entry of [...this.#byKey.values()]) this.cancel(entry.request.key, reason); }
  #validateRequest(request: SpatialQueryRequest): void { if (!request.key.trim()) throw new TypeError('Spatial query key must not be empty'); if (request.estimatedFeatures !== undefined && (!Number.isSafeInteger(request.estimatedFeatures) || request.estimatedFeatures < 0)) throw new RangeError('estimatedFeatures must be a non-negative safe integer'); if (request.estimatedBytes !== undefined && (!Number.isSafeInteger(request.estimatedBytes) || request.estimatedBytes < 0)) throw new RangeError('estimatedBytes must be a non-negative safe integer'); if ((request.estimatedFeatures ?? 0) > this.#budget.maxFeaturesPerRequest) throw new SpatialQueryRejectedError('Spatial query feature estimate exceeds budget'); if ((request.estimatedBytes ?? 0) > this.#budget.maxBytesPerRequest) throw new SpatialQueryRejectedError('Spatial query byte estimate exceeds budget'); }
  #subscribe<T>(entry: QueueEntry<T>, signal?: AbortSignal): Promise<T> { return new Promise<T>((resolve, reject) => { const subscriber: Subscriber<T> = { resolve, reject, ...(signal ? { signal } : {}) }; if (signal) { subscriber.abort = () => { entry.subscribers.delete(subscriber); reject(signal.reason ?? new DOMException('Aborted', 'AbortError')); if (entry.subscribers.size === 0) this.cancel(entry.request.key, signal.reason); }; signal.addEventListener('abort', subscriber.abort, { once: true }); } entry.subscribers.add(subscriber); }); }
  #sortQueue(): void { this.#queue.sort((a, b) => PRIORITY[a.request.priority] - PRIORITY[b.request.priority] || a.sequence - b.sequence); }
  #drain(): void { while (!this.#disposed && this.#active < this.#budget.maxConcurrent && this.#queue.length > 0) { const entry = this.#queue.shift(); if (!entry || entry.controller.signal.aborted || entry.subscribers.size === 0) continue; this.#active += 1; void this.#execute(entry).finally(() => { this.#active -= 1; this.#drain(); }); } }
  async #execute(entry: QueueEntry<unknown>): Promise<void> { const timeoutError = new SpatialQueryTimeoutError(entry.request.key, this.#budget.timeoutMs); const timer = setTimeout(() => entry.controller.abort(timeoutError), this.#budget.timeoutMs); try { const value = await entry.execute({ signal: entry.controller.signal, deadline: Date.now() + this.#budget.timeoutMs }); if (entry.controller.signal.aborted) throw entry.controller.signal.reason ?? timeoutError; this.#completed += 1; for (const subscriber of entry.subscribers) subscriber.resolve(value); } catch (error) { this.#failed += 1; for (const subscriber of entry.subscribers) subscriber.reject(error); } finally { clearTimeout(timer); this.#byKey.delete(entry.request.key); this.#cleanupSubscribers(entry); } }
  #cleanupSubscribers(entry: QueueEntry<unknown>): void { for (const subscriber of entry.subscribers) if (subscriber.signal && subscriber.abort) subscriber.signal.removeEventListener('abort', subscriber.abort); entry.subscribers.clear(); }
}
