export type ViewMode = "2d" | "3d";

export interface SpatialReferenceLike { readonly wkid?: number; readonly latestWkid?: number; }
export interface ViewCenter { readonly x:number; readonly y:number; readonly z?:number; readonly spatialReference?:SpatialReferenceLike; }
export interface ViewState2D { readonly mode:"2d"; readonly center:ViewCenter; readonly scale:number; readonly rotation:number; }
export interface ViewState3D { readonly mode:"3d"; readonly center:ViewCenter; readonly scale:number; readonly heading:number; readonly tilt:number; }
export type ViewState = ViewState2D | ViewState3D;
export interface ViewStatePolicy { readonly minScale:number; readonly maxScale:number; readonly minTilt:number; readonly maxTilt:number; readonly defaultWkid:number; readonly maxAbsCoordinate:number; readonly maxAbsZ:number; }
export interface ViewTransition { readonly from:ViewMode; readonly to:ViewMode; readonly state:ViewState; readonly changed:boolean; }
export interface SerializedViewState { readonly v:1; readonly mode:ViewMode; readonly x:number; readonly y:number; readonly z?:number; readonly wkid:number; readonly scale:number; readonly heading:number; readonly tilt:number; }
export const DEFAULT_VIEW_STATE_POLICY:ViewStatePolicy=Object.freeze({minScale:50,maxScale:150_000_000,minTilt:0,maxTilt:85,defaultWkid:3857,maxAbsCoordinate:50_000_000,maxAbsZ:100_000});
const WEB_MERCATOR_ALIASES=new Set([102100,102113,900913]);
function finite(value:unknown):value is number{return typeof value==="number"&&Number.isFinite(value);}
function clamp(value:number,min:number,max:number):number{return Math.min(max,Math.max(min,value));}
function normalizeAngle(value:number):number{const normalized=((value%360)+360)%360;return Object.is(normalized,-0)?0:normalized;}
function normalizeWkid(spatialReference:SpatialReferenceLike|undefined,fallback:number):number{const candidate=finite(spatialReference?.latestWkid)?spatialReference.latestWkid:spatialReference?.wkid;if(!finite(candidate)||!Number.isInteger(candidate)||candidate<=0)return fallback;return WEB_MERCATOR_ALIASES.has(candidate)?3857:candidate;}
function sanitizeCoordinate(value:unknown,limit:number):number|null{if(!finite(value)||Math.abs(value)>limit)return null;return Object.is(value,-0)?0:value;}
function sanitizeCenter(center:ViewCenter,policy:ViewStatePolicy):ViewCenter|null{const x=sanitizeCoordinate(center.x,policy.maxAbsCoordinate);const y=sanitizeCoordinate(center.y,policy.maxAbsCoordinate);if(x===null||y===null)return null;let z:number|undefined;if(center.z!==undefined){const sanitizedZ=sanitizeCoordinate(center.z,policy.maxAbsZ);if(sanitizedZ===null)return null;z=sanitizedZ;}const wkid=normalizeWkid(center.spatialReference,policy.defaultWkid);return z===undefined?{x,y,spatialReference:{wkid}}:{x,y,z,spatialReference:{wkid}};}
function validPolicy(policy:ViewStatePolicy):boolean{return finite(policy.minScale)&&finite(policy.maxScale)&&policy.minScale>0&&policy.maxScale>=policy.minScale&&finite(policy.minTilt)&&finite(policy.maxTilt)&&policy.minTilt>=0&&policy.maxTilt<=90&&policy.maxTilt>=policy.minTilt&&Number.isInteger(policy.defaultWkid)&&policy.defaultWkid>0&&finite(policy.maxAbsCoordinate)&&policy.maxAbsCoordinate>0&&finite(policy.maxAbsZ)&&policy.maxAbsZ>=0;}
function requirePolicy(policy:ViewStatePolicy):void{if(!validPolicy(policy))throw new Error("Invalid GIS view-state policy");}
export function normalizeViewState(state:ViewState,policy:ViewStatePolicy=DEFAULT_VIEW_STATE_POLICY):ViewState|null{requirePolicy(policy);const center=sanitizeCenter(state.center,policy);if(!center||!finite(state.scale)||state.scale<=0)return null;const scale=clamp(state.scale,policy.minScale,policy.maxScale);if(state.mode==="2d"){if(!finite(state.rotation))return null;return{mode:"2d",center,scale,rotation:normalizeAngle(state.rotation)};}if(!finite(state.heading)||!finite(state.tilt))return null;return{mode:"3d",center,scale,heading:normalizeAngle(state.heading),tilt:clamp(state.tilt,policy.minTilt,policy.maxTilt)};}
export function transitionViewState(source:ViewState,targetMode:ViewMode,policy:ViewStatePolicy=DEFAULT_VIEW_STATE_POLICY):ViewTransition|null{const normalized=normalizeViewState(source,policy);if(!normalized)return null;if(normalized.mode===targetMode)return{from:normalized.mode,to:targetMode,state:normalized,changed:false};if(normalized.mode==="2d"&&targetMode==="3d")return{from:"2d",to:"3d",changed:true,state:{mode:"3d",center:normalized.center,scale:normalized.scale,heading:normalized.rotation,tilt:policy.minTilt}};if(normalized.mode==="3d"&&targetMode==="2d")return{from:"3d",to:"2d",changed:true,state:{mode:"2d",center:normalized.center,scale:normalized.scale,rotation:normalized.heading}};return null;}
export function serializeViewState(state:ViewState,policy:ViewStatePolicy=DEFAULT_VIEW_STATE_POLICY):SerializedViewState|null{const normalized=normalizeViewState(state,policy);if(!normalized)return null;const wkid=normalized.center.spatialReference?.wkid??policy.defaultWkid;const base={v:1 as const,mode:normalized.mode,x:normalized.center.x,y:normalized.center.y,...(normalized.center.z===undefined?{}:{z:normalized.center.z}),wkid,scale:normalized.scale};return normalized.mode==="2d"?{...base,heading:normalized.rotation,tilt:0}:{...base,heading:normalized.heading,tilt:normalized.tilt};}
function isRecord(value:unknown):value is Record<string,unknown>{return typeof value==="object"&&value!==null&&!Array.isArray(value);}
export function deserializeViewState(value:unknown,policy:ViewStatePolicy=DEFAULT_VIEW_STATE_POLICY):ViewState|null{requirePolicy(policy);if(!isRecord(value)||value.v!==1||(value.mode!=="2d"&&value.mode!=="3d"))return null;if(!finite(value.x)||!finite(value.y)||!finite(value.scale)||!finite(value.heading))return null;if(!finite(value.wkid)||!Number.isInteger(value.wkid)||value.wkid<=0)return null;if(value.z!==undefined&&!finite(value.z))return null;const center:ViewCenter={x:value.x,y:value.y,...(value.z===undefined?{}:{z:value.z}),spatialReference:{wkid:value.wkid}};if(value.mode==="2d")return normalizeViewState({mode:"2d",center,scale:value.scale,rotation:value.heading},policy);if(!finite(value.tilt))return null;return normalizeViewState({mode:"3d",center,scale:value.scale,heading:value.heading,tilt:value.tilt},policy);}
export function viewStatesEquivalent(left:ViewState,right:ViewState,tolerance=1e-7,policy:ViewStatePolicy=DEFAULT_VIEW_STATE_POLICY):boolean{if(!finite(tolerance)||tolerance<0)throw new Error("Invalid view-state tolerance");const a=serializeViewState(left,policy);const b=serializeViewState(right,policy);if(!a||!b||a.mode!==b.mode||a.wkid!==b.wkid)return false;const close=(x:number|undefined,y:number|undefined):boolean=>x===undefined||y===undefined?x===y:Math.abs(x-y)<=tolerance;return close(a.x,b.x)&&close(a.y,b.y)&&close(a.z,b.z)&&close(a.scale,b.scale)&&close(a.heading,b.heading)&&close(a.tilt,b.tilt);}
