export type KentRehberiProfileMode = 'first' | 'union';

export interface KentRehberiFastAccessProfile {
  readonly serviceKey: string;
  readonly title: string;
  readonly probes: readonly string[];
  readonly preferTerms: readonly string[];
  readonly excludeTerms: readonly string[];
  readonly mode: KentRehberiProfileMode;
}

const freezeProfile = (
  profile: KentRehberiFastAccessProfile,
): KentRehberiFastAccessProfile => Object.freeze({
  ...profile,
  probes: Object.freeze([...profile.probes]),
  preferTerms: Object.freeze([...profile.preferTerms]),
  excludeTerms: Object.freeze([...profile.excludeTerms]),
});

const PROFILES: readonly KentRehberiFastAccessProfile[] = Object.freeze([
  freezeProfile({
    serviceKey: 'YeniAileYasamMerkezleriQeryUrl',
    title: 'Aile Yaşam Merkezleri',
    probes: ['aile yaşam', 'aile-yasam'],
    preferTerms: ['aile yaşam'],
    excludeTerms: [],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniAnfaBitkiEviQeryUrl',
    title: 'ANFA Bitki Evleri',
    probes: ['bitki evi', 'bitki-evi'],
    preferTerms: ['anfa', 'bitki'],
    excludeTerms: [],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniAnfaKafelerQeryUrl',
    title: 'ANFA Kafeler',
    probes: ['anfa kafe', 'kafe'],
    preferTerms: ['anfa', 'kafe'],
    excludeTerms: [],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniAnfaOtoparkQeryUrl',
    title: 'ANFA Otoparklar',
    probes: ['anfa otopark', 'otopark'],
    preferTerms: ['anfa', 'otopark'],
    excludeTerms: [],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniAskiAtıkSuTesisleriQeryUrl',
    title: 'ASKİ Atık Su Tesisleri',
    probes: ['atıksu', 'atık su', 'atiksu'],
    preferTerms: ['aski', 'atıksu'],
    excludeTerms: [],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniAskiBarajQeryUrl',
    title: 'ASKİ Barajlar',
    probes: ['baraj'],
    preferTerms: ['aski', 'baraj'],
    excludeTerms: [],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniAskiBolgeMudurlukleriQeryUrl',
    title: 'ASKİ Bölge Müdürlükleri',
    probes: ['bölge müdürlüğü', 'bolge-mudurlugu'],
    preferTerms: ['aski', 'bölge'],
    excludeTerms: [],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniAskiKartDolumOdemeQueryUrl',
    title: 'ASKİ Kart Dolum ve Ödeme',
    probes: ['aski kart', 'su kart', 'kart dolum'],
    preferTerms: ['aski', 'su', 'kart'],
    excludeTerms: ['ego', 'ankarakart'],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniAskiSumatikQueryUrl',
    title: 'ASKİ Sumatik',
    probes: ['sumatik'],
    preferTerms: ['aski', 'sumatik'],
    excludeTerms: [],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniAskiTahsilatSubeQueryUrl',
    title: 'ASKİ Tahsilat Şubeleri',
    probes: ['tahsilat'],
    preferTerms: ['aski', 'tahsilat'],
    excludeTerms: [],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniBaskentMarketQeryUrl',
    title: 'Başkent Market',
    probes: ['başkent market', 'baskent-market'],
    preferTerms: ['başkent', 'market'],
    excludeTerms: [],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniBelkoMeyveSuyuSatisBufeleriQueryUrl',
    title: 'BELKO Meyve Suyu Büfeleri',
    probes: ['belko', 'meyve suyu'],
    preferTerms: ['belko', 'meyve'],
    excludeTerms: [],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniBelmekBeltekQeryUrl',
    title: 'BELMEK / BELTEK',
    probes: ['belmek', 'beltek'],
    preferTerms: [],
    excludeTerms: [],
    mode: 'union',
  }),
  freezeProfile({
    serviceKey: 'YeniCocukEtkinlikMerkezleriQeryUrl',
    title: 'Çocuk Etkinlik Merkezleri',
    probes: ['çocuk etkinlik', 'cocuk-etkinlik'],
    preferTerms: ['çocuk', 'etkinlik'],
    excludeTerms: [],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniKültürSanatQueryUrl',
    title: 'Kültür ve Sanat',
    probes: ['kültür sanat', 'kültür merkezi', 'sanat merkezi', 'kultur-sanat'],
    preferTerms: ['kültür', 'sanat'],
    excludeTerms: [],
    mode: 'union',
  }),
  freezeProfile({
    serviceKey: 'YeniEgoAnkarayDuraklariQueryUrl',
    title: 'ANKARAY Durakları',
    probes: ['ankaray'],
    preferTerms: ['ankaray'],
    excludeTerms: [],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniEgoBaskentrayDuraklariQueryUrl',
    title: 'Başkentray Durakları',
    probes: ['başkentray', 'baskentray'],
    preferTerms: ['başkentray'],
    excludeTerms: [],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniEgoElektrikliBisikletİstasyonlariQueryUrl',
    title: 'Elektrikli Bisiklet İstasyonları',
    probes: ['elektrikli bisiklet', 'bisiklet istasyonu'],
    preferTerms: ['bisiklet'],
    excludeTerms: [],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniEgoKartDolumNoktalariQeryUrl',
    title: 'EGO Kart Dolum Noktaları',
    probes: ['ankarakart dolum', 'ego kart dolum', 'kart dolum'],
    preferTerms: ['ego', 'ankarakart'],
    excludeTerms: ['aski'],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniEgoKartSatisNoktalariQueryUrl',
    title: 'EGO Kart Satış Noktaları',
    probes: ['ankarakart satış', 'ego kart satış', 'kart satış'],
    preferTerms: ['ego', 'ankarakart'],
    excludeTerms: ['aski'],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniEgoMetroDuraklariQueryUrl',
    title: 'Metro Durakları',
    probes: ['metro'],
    preferTerms: ['metro'],
    excludeTerms: [],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniEgoOtobusDuraklariQueryUrl',
    title: 'Otobüs Durakları',
    probes: ['otobüs', 'durak'],
    preferTerms: ['otobüs', 'ego'],
    excludeTerms: ['metro', 'ankaray', 'teleferik', 'başkentray'],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniEgoTeleferikDuraklariQueryUrl',
    title: 'Teleferik Durakları',
    probes: ['teleferik'],
    preferTerms: ['teleferik'],
    excludeTerms: [],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniEngelliBireyQeryUrl',
    title: 'Engelli Birey Hizmetleri',
    probes: ['engelsiz yaşam', 'engelli birey', 'engelli'],
    preferTerms: ['engelsiz yaşam', 'engelli birey'],
    excludeTerms: ['kreş', 'çocuk'],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniEngelliCocukQueryUrl',
    title: 'Engelli Çocuk Hizmetleri',
    probes: ['engelsiz kreş', 'engelli çocuk', 'kreş'],
    preferTerms: ['engelsiz kreş', 'çocuk'],
    excludeTerms: ['yaşam merkezi'],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniGazilerMerkeziQeyUrl',
    title: 'Gaziler Merkezleri',
    probes: ['gaziler', 'gazi'],
    preferTerms: ['gazi'],
    excludeTerms: [],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniHalkEkmekSatisNoktalariQeryUrl',
    title: 'Halk Ekmek Satış Noktaları',
    probes: ['halk ekmek', 'halk-ekmek'],
    preferTerms: ['halk', 'ekmek'],
    excludeTerms: [],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniKadinDanismaQueryUrl',
    title: 'Kadın Danışma Merkezi',
    probes: ['kadın danışma', 'kadın dayanışma', 'kadin-danisma'],
    preferTerms: ['kadın', 'danışma'],
    excludeTerms: [],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniKadinlarLokaliQeryUrl',
    title: 'Kadınlar Lokali',
    probes: ['kadınlar lokali', 'kadın lokali'],
    preferTerms: ['kadın', 'lokali'],
    excludeTerms: [],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniKutuphanelerQueryUrl',
    title: 'Kütüphaneler',
    probes: ['kütüphane', 'kutuphane'],
    preferTerms: ['kütüphane'],
    excludeTerms: [],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniParklarQeryUrl',
    title: 'Parklar',
    probes: ['park'],
    preferTerms: ['park'],
    excludeTerms: ['otopark'],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniPatiDostuQeryUrl',
    title: 'Pati Dostu Uygulamalar',
    probes: ['pati dostu', 'pati', 'veteriner'],
    preferTerms: ['pati'],
    excludeTerms: [],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniPortasAsfaltUretimQeryUrl',
    title: 'PORTAŞ Asfalt Üretim',
    probes: ['portaş asfalt', 'portas asfalt', 'asfalt üretim', 'asfalt'],
    preferTerms: ['portaş', 'asfalt'],
    excludeTerms: [],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniSegmenSuFabrikalarıQeryUrl',
    title: 'Seğmen Su Fabrikaları',
    probes: ['seğmen su', 'segmen su'],
    preferTerms: ['fabrika', 'seğmen'],
    excludeTerms: ['satış', 'bayi'],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniSegmenSuSatisBayileriQeryUrl',
    title: 'Seğmen Su Satış Bayileri',
    probes: ['seğmen su', 'segmen su'],
    preferTerms: ['satış', 'bayi', 'seğmen'],
    excludeTerms: ['fabrika'],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniSosyalHizmetlerQueryUrl',
    title: 'Sosyal Hizmetler',
    probes: ['sosyal hizmet', 'sosyal tesis'],
    preferTerms: ['sosyal'],
    excludeTerms: [],
    mode: 'union',
  }),
  freezeProfile({
    serviceKey: 'YeniSporTesisleriQeryUrl',
    title: 'Spor Tesisleri',
    probes: ['spor tesisi', 'spor'],
    preferTerms: ['spor'],
    excludeTerms: [],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniTeknolojiMerkezleriQueryUrl',
    title: 'Teknoloji Merkezleri',
    probes: ['teknoloji merkezi', 'teknoloji'],
    preferTerms: ['teknoloji'],
    excludeTerms: [],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniWifiNoktalariQeryUrl',
    title: 'WiFi Erişim Noktaları',
    probes: ['wifi', 'wi-fi', 'kablosuz'],
    preferTerms: ['wifi'],
    excludeTerms: [],
    mode: 'first',
  }),
  freezeProfile({
    serviceKey: 'YeniYasliDostuQueryUrl',
    title: 'Yaşlı Dostu Uygulamalar',
    probes: ['yaşlı dostu', 'yaşlı', 'emekli'],
    preferTerms: ['yaşlı'],
    excludeTerms: [],
    mode: 'first',
  }),
]);

const PROFILE_BY_SERVICE_KEY = new Map(
  PROFILES.map((profile) => [profile.serviceKey, profile] as const),
);

export const KENT_REHBERI_FAST_ACCESS_PROFILES = PROFILES;

export const getKentRehberiFastAccessProfile = (
  serviceKey: string,
): KentRehberiFastAccessProfile | null =>
  PROFILE_BY_SERVICE_KEY.get(String(serviceKey ?? '').trim()) ?? null;

export const isKentRehberiFastAccessService = (
  serviceKey: string,
): boolean => PROFILE_BY_SERVICE_KEY.has(String(serviceKey ?? '').trim());
