export type SortDirection = 'asc' | 'desc';
export interface DataTableColumn { id: string; label: string; sortable?: boolean; hideable?: boolean; initiallyHidden?: boolean; }
export interface DataTableRow { id: string; disabled?: boolean; }
export interface DataTableSort { columnId: string; direction: SortDirection; }
export interface DataTableCell { rowId: string; columnId: string; }
export interface DataTableSnapshot { rowCount: number; columnCount: number; visibleColumnIds: readonly string[]; selectedRowIds: readonly string[]; sort: DataTableSort | null; pageIndex: number; pageSize: number; pageCount: number; activeCell: DataTableCell | null; selectionAnnouncement: string; }
export interface DataTableModel { getSnapshot(): DataTableSnapshot; setRows(rows: readonly DataTableRow[]): void; toggleSort(columnId: string): void; clearSort(): void; toggleColumn(columnId: string): void; setPage(index: number): void; setPageSize(size: number): void; toggleRow(rowId: string): void; selectPage(): void; clearSelection(): void; setActiveCell(cell: DataTableCell | null): void; moveActiveCell(rowDelta: number, columnDelta: number): void; moveActiveCellToBoundary(boundary: 'row-start' | 'row-end' | 'table-start' | 'table-end'): void; }
const MAX_ROWS = 10_000; const MAX_COLUMNS = 64; const MIN_PAGE_SIZE = 1; const MAX_PAGE_SIZE = 500;
const cleanId = (value: string, kind: string): string => { const normalized = value.trim(); if (!normalized) throw new Error(`${kind} id is required`); return normalized; };
const uniqueRows = (input: readonly DataTableRow[]): DataTableRow[] => { if (input.length > MAX_ROWS) throw new Error(`Data table row capacity exceeded (${MAX_ROWS})`); const seen = new Set<string>(); return input.map((row) => { const id = cleanId(row.id, 'Row'); if (seen.has(id)) throw new Error(`Duplicate row id: ${id}`); seen.add(id); return { id, ...(row.disabled ? { disabled: true } : {}) }; }); };
const normalizeColumns = (input: readonly DataTableColumn[]): DataTableColumn[] => { if (!input.length) throw new Error('At least one data table column is required'); if (input.length > MAX_COLUMNS) throw new Error(`Data table column capacity exceeded (${MAX_COLUMNS})`); const seen = new Set<string>(); return input.map((column) => { const id = cleanId(column.id, 'Column'); const label = column.label.trim(); if (!label) throw new Error(`Column label is required: ${id}`); if (seen.has(id)) throw new Error(`Duplicate column id: ${id}`); seen.add(id); return { ...column, id, label }; }); };
const clamp = (value: number, min: number, max: number): number => Math.min(max, Math.max(min, value));
const requiredAt = <T>(items: readonly T[], index: number): T => { const item = items[index]; if (item === undefined) throw new Error(`Data table index out of bounds: ${index}`); return item; };
export const createDataTableModel = (options: { columns: readonly DataTableColumn[]; rows?: readonly DataTableRow[]; pageSize?: number; }): DataTableModel => {
 const columns = normalizeColumns(options.columns); let rows = uniqueRows(options.rows ?? []); let pageSize = clamp(Math.floor(options.pageSize ?? 25), MIN_PAGE_SIZE, MAX_PAGE_SIZE); let pageIndex = 0; let sort: DataTableSort | null = null; const hiddenColumns = new Set(columns.filter((column) => column.initiallyHidden).map((column) => column.id)); const selectedRows = new Set<string>(); let activeCell: DataTableCell | null = null;
 const visibleColumns = () => columns.filter((column) => !hiddenColumns.has(column.id)); const pageCount = () => Math.max(1, Math.ceil(rows.length / pageSize)); const pageRows = () => rows.slice(pageIndex * pageSize, (pageIndex + 1) * pageSize); const rowIndex = (id: string) => rows.findIndex((row) => row.id === id); const columnIndex = (id: string) => visibleColumns().findIndex((column) => column.id === id);
 const reconcile = () => { pageIndex = clamp(pageIndex, 0, pageCount() - 1); const rowIds = new Set(rows.map((row) => row.id)); for (const id of selectedRows) if (!rowIds.has(id)) selectedRows.delete(id); if (activeCell && (!rowIds.has(activeCell.rowId) || columnIndex(activeCell.columnId) < 0)) activeCell = null; };
 return { getSnapshot() { const visible = visibleColumns(); const selected = rows.filter((row) => selectedRows.has(row.id)).map((row) => row.id); return Object.freeze({ rowCount: rows.length, columnCount: visible.length, visibleColumnIds: Object.freeze(visible.map((column) => column.id)), selectedRowIds: Object.freeze(selected), sort: sort ? Object.freeze({ ...sort }) : null, pageIndex, pageSize, pageCount: pageCount(), activeCell: activeCell ? Object.freeze({ ...activeCell }) : null, selectionAnnouncement: selected.length ? `${selected.length} satır seçildi.` : 'Seçili satır yok.' }); },
 setRows(next) { rows = uniqueRows(next); reconcile(); },
 toggleSort(columnId) { const id = cleanId(columnId, 'Column'); const column = columns.find((candidate) => candidate.id === id); if (!column) throw new Error(`Unknown column: ${id}`); if (!column.sortable) return; if (sort?.columnId !== id) sort = { columnId: id, direction: 'asc' }; else if (sort.direction === 'asc') sort = { columnId: id, direction: 'desc' }; else sort = null; }, clearSort() { sort = null; },
 toggleColumn(columnId) { const id = cleanId(columnId, 'Column'); const column = columns.find((candidate) => candidate.id === id); if (!column) throw new Error(`Unknown column: ${id}`); if (!column.hideable) return; if (hiddenColumns.has(id)) hiddenColumns.delete(id); else { if (visibleColumns().length === 1) return; hiddenColumns.add(id); } reconcile(); },
 setPage(index) { if (Number.isFinite(index)) pageIndex = clamp(Math.floor(index), 0, pageCount() - 1); }, setPageSize(size) { if (!Number.isFinite(size)) return; const first = pageIndex * pageSize; pageSize = clamp(Math.floor(size), MIN_PAGE_SIZE, MAX_PAGE_SIZE); pageIndex = clamp(Math.floor(first / pageSize), 0, pageCount() - 1); },
 toggleRow(rowId) { const id = cleanId(rowId, 'Row'); const row = rows.find((candidate) => candidate.id === id); if (!row || row.disabled) return; if (selectedRows.has(id)) selectedRows.delete(id); else selectedRows.add(id); }, selectPage() { const selectable = pageRows().filter((row) => !row.disabled); const all = selectable.length > 0 && selectable.every((row) => selectedRows.has(row.id)); for (const row of selectable) { if (all) selectedRows.delete(row.id); else selectedRows.add(row.id); } }, clearSelection() { selectedRows.clear(); },
 setActiveCell(cell) { if (!cell) { activeCell = null; return; } const rowId = cleanId(cell.rowId, 'Row'); const columnId = cleanId(cell.columnId, 'Column'); if (rowIndex(rowId) >= 0 && columnIndex(columnId) >= 0) activeCell = { rowId, columnId }; },
 moveActiveCell(rowDelta, columnDelta) { const visible = visibleColumns(); if (!rows.length || !visible.length) { activeCell = null; return; } const r = activeCell ? Math.max(0, rowIndex(activeCell.rowId)) : 0; const c = activeCell ? Math.max(0, columnIndex(activeCell.columnId)) : 0; activeCell = { rowId: requiredAt(rows, clamp(r + Math.trunc(rowDelta), 0, rows.length - 1)).id, columnId: requiredAt(visible, clamp(c + Math.trunc(columnDelta), 0, visible.length - 1)).id }; },
 moveActiveCellToBoundary(boundary) { const visible = visibleColumns(); if (!rows.length || !visible.length) { activeCell = null; return; } const r = activeCell ? Math.max(0, rowIndex(activeCell.rowId)) : 0; const row = requiredAt(rows, r); if (boundary === 'row-start') activeCell = { rowId: row.id, columnId: requiredAt(visible, 0).id }; else if (boundary === 'row-end') activeCell = { rowId: row.id, columnId: requiredAt(visible, visible.length - 1).id }; else if (boundary === 'table-start') activeCell = { rowId: requiredAt(rows, 0).id, columnId: requiredAt(visible, 0).id }; else activeCell = { rowId: requiredAt(rows, rows.length - 1).id, columnId: requiredAt(visible, visible.length - 1).id }; }
 }; };
