// @vitest-environment jsdom
import { afterEach, describe, expect, it, vi } from 'vitest';
import { createFormAccessibilityController } from './formAccessibilityController';
import { createFormValidationModel } from './formValidationModel';

interface Harness { readonly form: HTMLFormElement; readonly name: HTMLInputElement; readonly district: HTMLSelectElement; readonly nameError: HTMLElement; readonly nameHint: HTMLElement; readonly districtError: HTMLElement; readonly summary: HTMLElement; readonly status: HTMLElement; }
const mounted: HTMLElement[] = [];
const createHarness = (): Harness => { const host=document.createElement('div'); host.innerHTML=`<form><label for="name">Ad</label><div id="name-hint">En az üç karakter girin.</div><input id="name" name="name" /><div id="name-error"></div><label for="district">İlçe</label><select id="district" name="district"><option value="">Seçin</option><option value="cankaya">Çankaya</option></select><div id="district-error"></div><div id="summary"></div><div id="status"></div><button type="submit">Kaydet</button></form>`; document.body.append(host); mounted.push(host); const form=host.querySelector('form'),name=host.querySelector<HTMLInputElement>('#name'),district=host.querySelector<HTMLSelectElement>('#district'),nameError=host.querySelector<HTMLElement>('#name-error'),nameHint=host.querySelector<HTMLElement>('#name-hint'),districtError=host.querySelector<HTMLElement>('#district-error'),summary=host.querySelector<HTMLElement>('#summary'),status=host.querySelector<HTMLElement>('#status'); if(!form||!name||!district||!nameError||!nameHint||!districtError||!summary||!status) throw new Error('Test formu oluşturulamadı.'); return {form,name,district,nameError,nameHint,districtError,summary,status}; };
const tick = async (): Promise<void> => { for(let turn=0;turn<8;turn+=1) await Promise.resolve(); };
afterEach(()=>{ mounted.splice(0).forEach((element)=>element.remove()); vi.restoreAllMocks(); });
describe('FormAccessibilityController',()=>{
it('native form doğrulamasını kapatır ve ipucu ilişkisini korur',()=>{const v=createHarness(),m=createFormValidationModel();m.register({id:'name',label:'Ad',required:true},'');const c=createFormAccessibilityController({form:v.form,model:m,fields:[{id:'name',element:v.name,errorElement:v.nameError,hintElement:v.nameHint}]});expect(v.form.noValidate).toBe(true);expect(v.name.getAttribute('aria-describedby')).toBe('name-hint');expect(v.name.getAttribute('aria-invalid')).toBe('false');expect(v.form.getAttribute('aria-busy')).toBe('false');c.dispose();m.dispose();});
it('input olayını modele aktarır ve dirty durumunu yansıtır',()=>{const v=createHarness(),m=createFormValidationModel();m.register({id:'name',label:'Ad'},'');const c=createFormAccessibilityController({form:v.form,model:m,fields:[{id:'name',element:v.name}]});v.name.value='Ankara';v.name.dispatchEvent(new Event('input',{bubbles:true}));expect(m.snapshot().fields.name?.value).toBe('Ankara');expect(c.snapshot().dirtyFieldIds).toEqual(['name']);c.dispose();m.dispose();});
it('change olayını select değerine uygular',()=>{const v=createHarness(),m=createFormValidationModel();m.register({id:'district',label:'İlçe'},'');const c=createFormAccessibilityController({form:v.form,model:m,fields:[{id:'district',element:v.district}]});v.district.value='cankaya';v.district.dispatchEvent(new Event('change',{bubbles:true}));expect(m.snapshot().fields.district?.value).toBe('cankaya');c.dispose();m.dispose();});
it('blur sonrasında required hatasını görünür ve ilişkili yapar',async()=>{const v=createHarness(),m=createFormValidationModel({mode:'blur'});m.register({id:'name',label:'Ad',required:true},'');const c=createFormAccessibilityController({form:v.form,model:m,fields:[{id:'name',element:v.name,errorElement:v.nameError,hintElement:v.nameHint}]});v.name.dispatchEvent(new FocusEvent('blur'));await tick();expect(v.name.getAttribute('aria-invalid')).toBe('true');expect(v.name.getAttribute('aria-describedby')).toContain('name-hint');expect(v.name.getAttribute('aria-describedby')).toContain('name-error');expect(v.nameError.hidden).toBe(false);expect(v.nameError.textContent).toContain('zorunludur');c.dispose();m.dispose();});
it('hata temizlenince error tokenını kaldırır fakat hint tokenını bırakır',async()=>{const v=createHarness(),m=createFormValidationModel({mode:'blur'});m.register({id:'name',label:'Ad',required:true},'');const c=createFormAccessibilityController({form:v.form,model:m,fields:[{id:'name',element:v.name,errorElement:v.nameError,hintElement:v.nameHint}]});await m.blur('name');v.name.value='Ankara';v.name.dispatchEvent(new Event('input',{bubbles:true}));await m.blur('name');expect(v.name.getAttribute('aria-invalid')).toBe('false');expect(v.name.getAttribute('aria-describedby')).toBe('name-hint');expect(v.nameError.hidden).toBe(true);c.dispose();m.dispose();});
it('tek hata için özet metni ve alert rolü üretir',async()=>{const v=createHarness(),m=createFormValidationModel();m.register({id:'name',label:'Ad',required:true},'');const c=createFormAccessibilityController({form:v.form,model:m,fields:[{id:'name',element:v.name,errorElement:v.nameError}],summary:v.summary});await m.validateAll();expect(v.summary.hidden).toBe(false);expect(v.summary.getAttribute('role')).toBe('alert');expect(v.summary.textContent).toBe('1 alanın düzeltilmesi gerekiyor.');c.dispose();m.dispose();});
it('çoklu hata için sayısal özet üretir',async()=>{const v=createHarness(),m=createFormValidationModel();m.register({id:'name',label:'Ad',required:true},'');m.register({id:'district',label:'İlçe',required:true},'');const c=createFormAccessibilityController({form:v.form,model:m,fields:[{id:'name',element:v.name,errorElement:v.nameError},{id:'district',element:v.district,errorElement:v.districtError}],summary:v.summary});await m.validateAll();expect(v.summary.textContent).toBe('2 alanın düzeltilmesi gerekiyor.');expect(c.snapshot().invalidFieldIds).toEqual(['name','district']);c.dispose();m.dispose();});
it('geçerli formda özeti gizler',async()=>{const v=createHarness(),m=createFormValidationModel();m.register({id:'name',label:'Ad',required:true},'Ankara');const c=createFormAccessibilityController({form:v.form,model:m,fields:[{id:'name',element:v.name}],summary:v.summary});await m.validateAll();expect(v.summary.hidden).toBe(true);expect(v.summary.textContent).toBe('');c.dispose();m.dispose();});
it('focusFirstInvalid ilk hatalı alana odaklanır',async()=>{const v=createHarness(),m=createFormValidationModel();m.register({id:'name',label:'Ad',required:true},'');const c=createFormAccessibilityController({form:v.form,model:m,fields:[{id:'name',element:v.name}]});await m.validateAll();expect(c.focusFirstInvalid()).toBe(true);expect(document.activeElement).toBe(v.name);c.dispose();m.dispose();});
it('hatalı submit varsayılan olarak ilk hatalı alana odaklanır',async()=>{const v=createHarness(),m=createFormValidationModel();m.register({id:'name',label:'Ad',required:true},'');const c=createFormAccessibilityController({form:v.form,model:m,fields:[{id:'name',element:v.name}],status:v.status});v.form.dispatchEvent(new SubmitEvent('submit',{bubbles:true,cancelable:true}));await tick();expect(document.activeElement).toBe(v.name);expect(v.status.textContent).toBe('Formda düzeltilmesi gereken 1 alan var.');c.dispose();m.dispose();});
it('focusInvalidOnSubmit false olduğunda odağı zorlamaz',async()=>{const v=createHarness(),m=createFormValidationModel();m.register({id:'name',label:'Ad',required:true},'');const c=createFormAccessibilityController({form:v.form,model:m,fields:[{id:'name',element:v.name}],focusInvalidOnSubmit:false});v.form.dispatchEvent(new SubmitEvent('submit',{bubbles:true,cancelable:true}));await tick();expect(document.activeElement).not.toBe(v.name);c.dispose();m.dispose();});
it('geçerli submit callbackini çağırır ve submitting durumunu sonlandırır',async()=>{const v=createHarness(),m=createFormValidationModel();m.register({id:'name',label:'Ad',required:true},'Ankara');const onSubmit=vi.fn();const c=createFormAccessibilityController({form:v.form,model:m,fields:[{id:'name',element:v.name}],status:v.status,onSubmit});v.form.dispatchEvent(new SubmitEvent('submit',{bubbles:true,cancelable:true}));await tick();expect(onSubmit).toHaveBeenCalledTimes(1);expect(m.snapshot().submitting).toBe(false);expect(v.form.getAttribute('aria-busy')).toBe('false');expect(v.status.textContent).toBe('Form doğrulandı ve gönderim tamamlandı.');c.dispose();m.dispose();});
it('async submit sürerken aria-busy true kalır',async()=>{const v=createHarness(),m=createFormValidationModel();m.register({id:'name',label:'Ad',required:true},'Ankara');let resolveSubmit:(()=>void)|undefined;const pending=new Promise<void>((resolve)=>{resolveSubmit=resolve;});const c=createFormAccessibilityController({form:v.form,model:m,fields:[{id:'name',element:v.name}],onSubmit:()=>pending});v.form.dispatchEvent(new SubmitEvent('submit',{bubbles:true,cancelable:true}));await tick();expect(v.form.getAttribute('aria-busy')).toBe('true');resolveSubmit?.();await tick();expect(v.form.getAttribute('aria-busy')).toBe('false');c.dispose();m.dispose();});
it('submit hatasını diagnostics ve live status üzerinden raporlar',async()=>{const v=createHarness(),m=createFormValidationModel();m.register({id:'name',label:'Ad'},'Ankara');const error=new Error('network-free injected failure'),onObserverError=vi.fn();const c=createFormAccessibilityController({form:v.form,model:m,fields:[{id:'name',element:v.name}],status:v.status,onSubmit:()=>{throw error;},onObserverError});v.form.dispatchEvent(new SubmitEvent('submit',{bubbles:true,cancelable:true}));await tick();expect(onObserverError).toHaveBeenCalledWith(error);expect(v.status.textContent).toBe('Form gönderilemedi. Lütfen tekrar deneyin.');expect(m.snapshot().submitting).toBe(false);c.dispose();m.dispose();});
it('live status semantiğini announce sırasında kurar',()=>{const v=createHarness(),m=createFormValidationModel(),c=createFormAccessibilityController({form:v.form,model:m,fields:[],status:v.status});c.announce('Kaydedildi');expect(v.status.getAttribute('role')).toBe('status');expect(v.status.getAttribute('aria-live')).toBe('polite');expect(v.status.getAttribute('aria-atomic')).toBe('true');expect(v.status.textContent).toBe('Kaydedildi');c.dispose();m.dispose();});
it('subscriber ilk snapshotı hemen alır',()=>{const v=createHarness(),m=createFormValidationModel(),c=createFormAccessibilityController({form:v.form,model:m,fields:[]}),listener=vi.fn();c.subscribe(listener);expect(listener).toHaveBeenCalledTimes(1);expect(listener.mock.calls[0]?.[0]).toMatchObject({valid:true,submitting:false});c.dispose();m.dispose();});
it('subscriber hatasını diagnostics kanalına izole eder',()=>{const v=createHarness(),m=createFormValidationModel(),onObserverError=vi.fn(),c=createFormAccessibilityController({form:v.form,model:m,fields:[],onObserverError}),error=new Error('observer failed');expect(()=>c.subscribe(()=>{throw error;})).not.toThrow();expect(onObserverError).toHaveBeenCalledWith(error);c.dispose();m.dispose();});
});
