import { describe, expect, it } from 'vitest';
import { RuntimeRecoveryPlanner } from './runtimeRecoveryPlanner';

describe('RuntimeRecoveryPlanner', () => {
  it('throttles pressured work and enforces cooldown', () => { const planner = new RuntimeRecoveryPlanner({ pressuredCooldown: 10 }); expect(planner.evaluate({ lane: 'interactive', overload: 'pressured', pressure: 0.7, now: 100 })).toMatchObject({ action: 'throttle', reason: 'pressure', attempt: 1, eligibleAt: 110 }); expect(planner.evaluate({ lane: 'interactive', overload: 'pressured', pressure: 0.8, now: 105 })).toMatchObject({ action: 'none', reason: 'cooldown', eligibleAt: 110 }); });
  it('drains overloaded lanes with a longer bounded cooldown', () => { const planner = new RuntimeRecoveryPlanner({ overloadedCooldown: 50 }); expect(planner.evaluate({ lane: 'critical', overload: 'overloaded', pressure: 1, now: 20 })).toMatchObject({ action: 'drain', reason: 'overload', eligibleAt: 70 }); });
  it('caps recovery attempts until enough healthy samples arrive', () => { const planner = new RuntimeRecoveryPlanner({ maximumAttempts: 2, pressuredCooldown: 0, stableSamplesForRecovery: 2 }); planner.evaluate({ lane: 'background', overload: 'pressured', pressure: 0.6, now: 1 }); planner.evaluate({ lane: 'background', overload: 'pressured', pressure: 0.6, now: 2 }); expect(planner.evaluate({ lane: 'background', overload: 'pressured', pressure: 0.6, now: 3 })).toMatchObject({ action: 'none', reason: 'attempt-budget', attempt: 2 }); planner.evaluate({ lane: 'background', overload: 'healthy', pressure: 0, now: 4 }); planner.evaluate({ lane: 'background', overload: 'healthy', pressure: 0, now: 5 }); expect(planner.lane('background').attempts).toBe(0); });
  it('uses probes to confirm recovery after an active mitigation', () => { const planner = new RuntimeRecoveryPlanner({ pressuredCooldown: 5, healthyProbeInterval: 20 }); planner.evaluate({ lane: 'interactive', overload: 'pressured', pressure: 0.7, now: 10 }); expect(planner.evaluate({ lane: 'interactive', overload: 'healthy', pressure: 0, now: 15 })).toMatchObject({ action: 'probe', reason: 'recovery-probe', eligibleAt: 35 }); });
  it('keeps event history bounded and snapshots immutable', () => { const planner = new RuntimeRecoveryPlanner({ historyLimit: 2, pressuredCooldown: 0 }); planner.evaluate({ lane: 'critical', overload: 'pressured', pressure: 0.5, now: 1 }); planner.evaluate({ lane: 'interactive', overload: 'pressured', pressure: 0.5, now: 2 }); planner.evaluate({ lane: 'background', overload: 'overloaded', pressure: 1, now: 3 }); const snapshot = planner.snapshot(); expect(snapshot.history.map((event) => event.sequence)).toEqual([2, 3]); expect(Object.isFrozen(snapshot.history)).toBe(true); });
  it('supports lane-scoped reset without erasing other lane ownership', () => { const planner = new RuntimeRecoveryPlanner({ pressuredCooldown: 0 }); planner.evaluate({ lane: 'critical', overload: 'pressured', pressure: 0.7, now: 1 }); planner.evaluate({ lane: 'interactive', overload: 'pressured', pressure: 0.7, now: 2 }); planner.reset('critical'); expect(planner.lane('critical').attempts).toBe(0); expect(planner.lane('interactive').attempts).toBe(1); });
  it('rejects hostile policy, lane, pressure, time and oversized batch inputs', () => { expect(() => new RuntimeRecoveryPlanner({ maximumAttempts: 0 })).toThrow(RangeError); const planner = new RuntimeRecoveryPlanner(); expect(() => planner.evaluate({ lane: 'invalid' as 'critical', overload: 'healthy', pressure: 0, now: 1 })).toThrow(TypeError); expect(() => planner.evaluate({ lane: 'critical', overload: 'healthy', pressure: 2, now: 1 })).toThrow(RangeError); planner.evaluate({ lane: 'critical', overload: 'healthy', pressure: 0, now: 10 }); expect(() => planner.evaluate({ lane: 'critical', overload: 'healthy', pressure: 0, now: 9 })).toThrow(RangeError); });
  it('normalizes and freezes policy diagnostics', () => { const planner = new RuntimeRecoveryPlanner({ maximumAttempts: 4 }); expect(planner.policy()).toMatchObject({ maximumAttempts: 4, historyLimit: 128 }); expect(Object.isFrozen(planner.policy())).toBe(true); });
});
