import { describe, expect, it } from 'vitest';
import { RuntimeSaturationLedger } from './runtimeSaturationLedger';

describe('RuntimeSaturationLedger', () => {
  it('stays cold until the minimum sample count is reached', () => { const ledger = new RuntimeSaturationLedger({ minimumSamples: 3, windowSize: 4 }); ledger.record({ lane: 'interactive', kind: 'admitted', at: 1 }); ledger.record({ lane: 'interactive', kind: 'queued', at: 2 }); expect(ledger.lane('interactive').level).toBe('cold'); ledger.record({ lane: 'interactive', kind: 'admitted', at: 3 }); expect(ledger.lane('interactive').level).toBe('warning'); });
  it('classifies critical queue and rejection pressure', () => { const ledger = new RuntimeSaturationLedger({ minimumSamples: 4, windowSize: 4 }); ledger.recordMany([{ lane: 'critical', kind: 'queued', at: 1 }, { lane: 'critical', kind: 'queued', at: 2 }, { lane: 'critical', kind: 'admitted', at: 3 }, { lane: 'critical', kind: 'admitted', at: 4 }]); expect(ledger.lane('critical')).toMatchObject({ level: 'critical', queueRatio: 0.5 }); });
  it('uses only the bounded rolling window', () => { const ledger = new RuntimeSaturationLedger({ minimumSamples: 2, windowSize: 2 }); ledger.recordMany([{ lane: 'background', kind: 'rejected', at: 1 }, { lane: 'background', kind: 'rejected', at: 2 }, { lane: 'background', kind: 'admitted', at: 3 }, { lane: 'background', kind: 'completed', at: 4 }]); expect(ledger.lane('background')).toMatchObject({ samples: 2, rejected: 0, level: 'healthy' }); });
  it('aggregates the worst mature lane without hiding colder lanes', () => { const ledger = new RuntimeSaturationLedger({ minimumSamples: 2, windowSize: 4 }); ledger.recordMany([{ lane: 'interactive', kind: 'queued', at: 1 }, { lane: 'interactive', kind: 'queued', at: 2 }]); const snapshot = ledger.snapshot(); expect(snapshot.level).toBe('critical'); expect(snapshot.lanes.critical.level).toBe('cold'); });
  it('keeps immutable bounded history', () => { const ledger = new RuntimeSaturationLedger({ historyLimit: 2, minimumSamples: 1 }); ledger.recordMany([{ lane: 'critical', kind: 'admitted', at: 1 }, { lane: 'critical', kind: 'completed', at: 2 }, { lane: 'critical', kind: 'cancelled', at: 3 }]); const snapshot = ledger.snapshot(); expect(snapshot.history.map((event) => event.sequence)).toEqual([2, 3]); expect(Object.isFrozen(snapshot.history)).toBe(true); expect(Object.isFrozen(snapshot.history[0])).toBe(true); });
  it('rejects hostile policies and forged sample values', () => { expect(() => new RuntimeSaturationLedger({ minimumSamples: 5, windowSize: 4 })).toThrow(RangeError); expect(() => new RuntimeSaturationLedger({ warningRejectRatio: 0.8, criticalRejectRatio: 0.2 })).toThrow(RangeError); const ledger = new RuntimeSaturationLedger(); expect(() => ledger.record({ lane: 'forged' as 'critical', kind: 'admitted', at: 1 })).toThrow(TypeError); expect(() => ledger.record({ lane: 'critical', kind: 'forged' as 'admitted', at: 1 })).toThrow(TypeError); expect(() => ledger.record({ lane: 'critical', kind: 'admitted', at: Number.NaN })).toThrow(RangeError); });
  it('requires a monotonic caller clock', () => { const ledger = new RuntimeSaturationLedger(); ledger.record({ lane: 'critical', kind: 'admitted', at: 10 }); expect(() => ledger.record({ lane: 'interactive', kind: 'admitted', at: 9 })).toThrow(RangeError); });
  it('resets one lane without discarding unrelated evidence', () => { const ledger = new RuntimeSaturationLedger({ minimumSamples: 1 }); ledger.record({ lane: 'critical', kind: 'rejected', at: 1 }); ledger.record({ lane: 'interactive', kind: 'queued', at: 2 }); const before = ledger.snapshot().sequence; const after = ledger.reset('critical'); expect(after.sequence).toBe(before + 1); expect(after.lanes.critical.samples).toBe(0); expect(after.lanes.interactive.samples).toBe(1); expect(after.history).toHaveLength(2); });
  it('bounds batch ingestion', () => { const ledger = new RuntimeSaturationLedger(); const sample = { lane: 'critical' as const, kind: 'admitted' as const, at: 1 }; expect(() => ledger.recordMany(Array.from({ length: 10_001 }, () => sample))).toThrow(RangeError); });
});
