import type { RuntimeFailureBudgetLane } from './runtimeFailureBudget';

export type RuntimeHealthEscalationSeverity = 'healthy' | 'watch' | 'degraded' | 'critical';
export type RuntimeHealthSignalKind = 'availability' | 'latency' | 'saturation' | 'integrity';

export interface RuntimeHealthEscalationPolicy { readonly windowSize:number; readonly minimumSamples:number; readonly watchScore:number; readonly degradedScore:number; readonly criticalScore:number; readonly recoverySamples:number; readonly maximumHistory:number; readonly availabilityWeight:number; readonly latencyWeight:number; readonly saturationWeight:number; readonly integrityWeight:number; }
export interface RuntimeHealthSignal { readonly lane:RuntimeFailureBudgetLane; readonly kind:RuntimeHealthSignalKind; readonly pressure:number; readonly at:number; }
export interface RuntimeHealthEscalationTransition { readonly lane:RuntimeFailureBudgetLane; readonly from:RuntimeHealthEscalationSeverity; readonly to:RuntimeHealthEscalationSeverity; readonly score:number; readonly sampleCount:number; readonly at:number; }
export interface RuntimeHealthLaneSnapshot { readonly lane:RuntimeFailureBudgetLane; readonly severity:RuntimeHealthEscalationSeverity; readonly mature:boolean; readonly score:number; readonly sampleCount:number; readonly healthyRecoverySamples:number; readonly signals:Readonly<Record<RuntimeHealthSignalKind,number>>; }
export interface RuntimeHealthEscalationSnapshot { readonly severity:RuntimeHealthEscalationSeverity; readonly lanes:Readonly<Record<RuntimeFailureBudgetLane,RuntimeHealthLaneSnapshot>>; }
interface Sample { readonly kind:RuntimeHealthSignalKind; readonly pressure:number; readonly at:number; }
interface LaneState { severity:RuntimeHealthEscalationSeverity; samples:Sample[]; healthyRecoverySamples:number; }
const LANES:readonly RuntimeFailureBudgetLane[]=Object.freeze(['critical','interactive','background']);
const KINDS:readonly RuntimeHealthSignalKind[]=Object.freeze(['availability','latency','saturation','integrity']);
const ORDER:Readonly<Record<RuntimeHealthEscalationSeverity,number>>=Object.freeze({healthy:0,watch:1,degraded:2,critical:3});
const DEFAULT:RuntimeHealthEscalationPolicy=Object.freeze({windowSize:24,minimumSamples:6,watchScore:.25,degradedScore:.5,criticalScore:.75,recoverySamples:3,maximumHistory:128,availabilityWeight:4,latencyWeight:2,saturationWeight:2,integrityWeight:5});
const integer=(v:number,n:string,min:number,max:number)=>{if(!Number.isSafeInteger(v)||v<min||v>max)throw new RangeError(`${n} must be an integer between ${min} and ${max}`);return v};
const ratio=(v:number,n:string)=>{if(!Number.isFinite(v)||v<0||v>1)throw new RangeError(`${n} must be between 0 and 1`);return v};
const normalize=(i:Partial<RuntimeHealthEscalationPolicy>):RuntimeHealthEscalationPolicy=>{const p=Object.freeze({windowSize:integer(i.windowSize??DEFAULT.windowSize,'windowSize',1,10000),minimumSamples:integer(i.minimumSamples??DEFAULT.minimumSamples,'minimumSamples',1,10000),watchScore:ratio(i.watchScore??DEFAULT.watchScore,'watchScore'),degradedScore:ratio(i.degradedScore??DEFAULT.degradedScore,'degradedScore'),criticalScore:ratio(i.criticalScore??DEFAULT.criticalScore,'criticalScore'),recoverySamples:integer(i.recoverySamples??DEFAULT.recoverySamples,'recoverySamples',1,10000),maximumHistory:integer(i.maximumHistory??DEFAULT.maximumHistory,'maximumHistory',0,10000),availabilityWeight:integer(i.availabilityWeight??DEFAULT.availabilityWeight,'availabilityWeight',1,1000),latencyWeight:integer(i.latencyWeight??DEFAULT.latencyWeight,'latencyWeight',1,1000),saturationWeight:integer(i.saturationWeight??DEFAULT.saturationWeight,'saturationWeight',1,1000),integrityWeight:integer(i.integrityWeight??DEFAULT.integrityWeight,'integrityWeight',1,1000)});if(p.minimumSamples>p.windowSize)throw new RangeError('minimumSamples must not exceed windowSize');if(!(p.watchScore<p.degradedScore&&p.degradedScore<p.criticalScore))throw new RangeError('health thresholds must be strictly increasing');return p};
const lane=(v:RuntimeFailureBudgetLane)=>{if(!LANES.includes(v))throw new TypeError(`unsupported health lane: ${String(v)}`)}; const kind=(v:RuntimeHealthSignalKind)=>{if(!KINDS.includes(v))throw new TypeError(`unsupported health signal kind: ${String(v)}`)};
export class RuntimeHealthEscalationMatrix {
 readonly #policy:RuntimeHealthEscalationPolicy; readonly #lanes:Record<RuntimeFailureBudgetLane,LaneState>={critical:{severity:'healthy',samples:[],healthyRecoverySamples:0},interactive:{severity:'healthy',samples:[],healthyRecoverySamples:0},background:{severity:'healthy',samples:[],healthyRecoverySamples:0}}; readonly #history:RuntimeHealthEscalationTransition[]=[]; #lastAt:number|null=null;
 constructor(policy:Partial<RuntimeHealthEscalationPolicy>={}){this.#policy=normalize(policy)} policy(){return this.#policy}
 record(s:RuntimeHealthSignal){lane(s.lane);kind(s.kind);if(!Number.isSafeInteger(s.at)||s.at<0)throw new RangeError('at must be a non-negative safe integer');ratio(s.pressure,'pressure');if(this.#lastAt!==null&&s.at<this.#lastAt)throw new RangeError('health matrix time must be monotonic');this.#lastAt=s.at;const st=this.#lanes[s.lane];st.samples.push(Object.freeze({kind:s.kind,pressure:s.pressure,at:s.at}));if(st.samples.length>this.#policy.windowSize)st.samples.splice(0,st.samples.length-this.#policy.windowSize);this.#evaluate(s.lane,s.at);return this.#snapshotLane(s.lane)}
 recordBatch(signals:readonly RuntimeHealthSignal[]){if(!Array.isArray(signals))throw new TypeError('signals must be an array');if(signals.length>10000)throw new RangeError('signals batch exceeds 10000 entries');for(const s of signals)this.record(s);return this.snapshot()}
 snapshot(){const lanes=Object.freeze({critical:this.#snapshotLane('critical'),interactive:this.#snapshotLane('interactive'),background:this.#snapshotLane('background')});let severity:RuntimeHealthEscalationSeverity='healthy';for(const l of LANES)if(ORDER[lanes[l].severity]>ORDER[severity])severity=lanes[l].severity;return Object.freeze({severity,lanes})}
 history(){return Object.freeze(this.#history.map(e=>Object.freeze({...e})))} reset(l?:RuntimeFailureBudgetLane){if(l===undefined){for(const x of LANES)this.#clear(x);this.#history.length=0;this.#lastAt=null;return}lane(l);this.#clear(l)}
 #clear(l:RuntimeFailureBudgetLane){const s=this.#lanes[l];s.severity='healthy';s.samples.length=0;s.healthyRecoverySamples=0}
 #weight(k:RuntimeHealthSignalKind){return k==='availability'?this.#policy.availabilityWeight:k==='latency'?this.#policy.latencyWeight:k==='saturation'?this.#policy.saturationWeight:this.#policy.integrityWeight}
 #score(s:LaneState){let pressure=0,weight=0;for(const x of s.samples){const w=this.#weight(x.kind);pressure+=x.pressure*w;weight+=w}return weight===0?0:pressure/weight}
 #target(score:number):RuntimeHealthEscalationSeverity{return score>=this.#policy.criticalScore?'critical':score>=this.#policy.degradedScore?'degraded':score>=this.#policy.watchScore?'watch':'healthy'}
 #evaluate(l:RuntimeFailureBudgetLane,at:number){const s=this.#lanes[l];if(s.samples.length<this.#policy.minimumSamples)return;const score=this.#score(s),target=this.#target(score),current=ORDER[s.severity],next=ORDER[target];if(next>current){s.healthyRecoverySamples=0;this.#transition(l,target,score,at);return}if(next===current){s.healthyRecoverySamples=0;return}s.healthyRecoverySamples++;if(s.healthyRecoverySamples<this.#policy.recoverySamples)return;s.healthyRecoverySamples=0;const rank=Math.max(next,current-1);const severity=(Object.keys(ORDER) as RuntimeHealthEscalationSeverity[]).find(x=>ORDER[x]===rank)??'healthy';this.#transition(l,severity,score,at)}
 #transition(l:RuntimeFailureBudgetLane,to:RuntimeHealthEscalationSeverity,score:number,at:number){const s=this.#lanes[l],from=s.severity;if(from===to)return;s.severity=to;if(this.#policy.maximumHistory>0){this.#history.push(Object.freeze({lane:l,from,to,score,sampleCount:s.samples.length,at}));if(this.#history.length>this.#policy.maximumHistory)this.#history.splice(0,this.#history.length-this.#policy.maximumHistory)}}
 #snapshotLane(l:RuntimeFailureBudgetLane):RuntimeHealthLaneSnapshot{const s=this.#lanes[l],sums:Record<RuntimeHealthSignalKind,{total:number;count:number}>={availability:{total:0,count:0},latency:{total:0,count:0},saturation:{total:0,count:0},integrity:{total:0,count:0}};for(const x of s.samples){sums[x.kind].total+=x.pressure;sums[x.kind].count++}const mean=(k:RuntimeHealthSignalKind)=>sums[k].count===0?0:sums[k].total/sums[k].count;return Object.freeze({lane:l,severity:s.severity,mature:s.samples.length>=this.#policy.minimumSamples,score:this.#score(s),sampleCount:s.samples.length,healthyRecoverySamples:s.healthyRecoverySamples,signals:Object.freeze({availability:mean('availability'),latency:mean('latency'),saturation:mean('saturation'),integrity:mean('integrity')})})}
}
