import { describe, expect, it } from 'vitest';
import { RuntimeBackpressureCoordinator } from './runtimeBackpressureCoordinator';

describe('RuntimeBackpressureCoordinator', () => {
  it('admits cold and healthy signals without manufacturing queue pressure', () => { const coordinator = new RuntimeBackpressureCoordinator(); expect(coordinator.decide({ lane: 'critical', saturation: 'cold', overloaded: false, at: 1 })).toMatchObject({ action: 'admit', reason: 'healthy' }); expect(coordinator.decide({ lane: 'critical', saturation: 'healthy', overloaded: false, at: 2 })).toMatchObject({ action: 'admit' }); expect(coordinator.snapshot().lanes.critical.deferred).toBe(0); });
  it('defers warning pressure up to the configured lane ceiling', () => { const coordinator = new RuntimeBackpressureCoordinator({ maxDeferred: { background: 2 } }); expect(coordinator.decide({ lane: 'background', saturation: 'warning', overloaded: false, at: 1 }).action).toBe('defer'); expect(coordinator.decide({ lane: 'background', saturation: 'warning', overloaded: false, at: 2 }).action).toBe('defer'); expect(coordinator.snapshot().lanes.background.deferred).toBe(2); });
  it('sheds after a warning queue reaches its bounded ceiling', () => { const coordinator = new RuntimeBackpressureCoordinator({ maxDeferred: { interactive: 1 }, maxShedPerWindow: { interactive: 2 } }); coordinator.decide({ lane: 'interactive', saturation: 'warning', overloaded: false, at: 1 }); expect(coordinator.decide({ lane: 'interactive', saturation: 'warning', overloaded: false, at: 2 })).toMatchObject({ action: 'shed', reason: 'queue-limit' }); });
  it('sheds immediately for critical saturation and explicit overload', () => { const coordinator = new RuntimeBackpressureCoordinator(); expect(coordinator.decide({ lane: 'critical', saturation: 'critical', overloaded: false, at: 1 })).toMatchObject({ action: 'shed', reason: 'saturation' }); expect(coordinator.decide({ lane: 'background', saturation: 'healthy', overloaded: true, at: 2 })).toMatchObject({ action: 'shed', reason: 'overload' }); });
  it('does not exceed the per-lane shedding budget', () => { const coordinator = new RuntimeBackpressureCoordinator({ maxShedPerWindow: { background: 1 } }); expect(coordinator.decide({ lane: 'background', saturation: 'critical', overloaded: false, at: 1 }).action).toBe('shed'); expect(coordinator.decide({ lane: 'background', saturation: 'critical', overloaded: false, at: 2 })).toMatchObject({ action: 'defer', reason: 'shed-limit' }); expect(coordinator.snapshot().lanes.background.shed).toBe(1); });
  it('recovers shedding budget only after sustained healthy evidence', () => { const coordinator = new RuntimeBackpressureCoordinator({ recoverySamples: 2, maxShedPerWindow: { interactive: 1 } }); coordinator.decide({ lane: 'interactive', saturation: 'critical', overloaded: false, at: 1 }); coordinator.decide({ lane: 'interactive', saturation: 'healthy', overloaded: false, at: 2 }); expect(coordinator.snapshot().lanes.interactive.shed).toBe(1); coordinator.decide({ lane: 'interactive', saturation: 'healthy', overloaded: false, at: 3 }); expect(coordinator.snapshot().lanes.interactive.shed).toBe(0); });
  it('releases deferred ownership without allowing negative counts', () => { const coordinator = new RuntimeBackpressureCoordinator(); coordinator.decide({ lane: 'interactive', saturation: 'warning', overloaded: false, at: 1 }); coordinator.releaseDeferred('interactive', 10); expect(coordinator.snapshot().lanes.interactive.deferred).toBe(0); });
  it('keeps immutable bounded decision history', () => { const coordinator = new RuntimeBackpressureCoordinator({ historyLimit: 2 }); coordinator.decide({ lane: 'critical', saturation: 'healthy', overloaded: false, at: 1 }); coordinator.decide({ lane: 'critical', saturation: 'warning', overloaded: false, at: 2 }); coordinator.decide({ lane: 'critical', saturation: 'critical', overloaded: false, at: 3 }); const snapshot = coordinator.snapshot(); expect(snapshot.history.map((entry) => entry.sequence)).toEqual([2, 3]); expect(Object.isFrozen(snapshot.history)).toBe(true); expect(Object.isFrozen(snapshot.history[0])).toBe(true); });
  it('requires monotonic caller time', () => { const coordinator = new RuntimeBackpressureCoordinator(); coordinator.decide({ lane: 'critical', saturation: 'healthy', overloaded: false, at: 10 }); expect(() => coordinator.decide({ lane: 'critical', saturation: 'healthy', overloaded: false, at: 9 })).toThrow(RangeError); });
  it('rejects forged runtime values and hostile policy bounds', () => { expect(() => new RuntimeBackpressureCoordinator({ recoverySamples: 0 })).toThrow(RangeError); expect(() => new RuntimeBackpressureCoordinator({ maxDeferred: { critical: -1 } })).toThrow(RangeError); const coordinator = new RuntimeBackpressureCoordinator(); expect(() => coordinator.decide({ lane: 'forged' as 'critical', saturation: 'healthy', overloaded: false, at: 1 })).toThrow(TypeError); expect(() => coordinator.decide({ lane: 'critical', saturation: 'forged' as 'healthy', overloaded: false, at: 1 })).toThrow(TypeError); expect(() => coordinator.decide({ lane: 'critical', saturation: 'healthy', overloaded: false, at: Number.NaN })).toThrow(RangeError); });
  it('resets one lane without destroying unrelated evidence', () => { const coordinator = new RuntimeBackpressureCoordinator(); coordinator.decide({ lane: 'critical', saturation: 'warning', overloaded: false, at: 1 }); coordinator.decide({ lane: 'background', saturation: 'warning', overloaded: false, at: 2 }); coordinator.reset('critical'); const snapshot = coordinator.snapshot(); expect(snapshot.lanes.critical.deferred).toBe(0); expect(snapshot.lanes.background.deferred).toBe(1); expect(snapshot.history).toHaveLength(2); });
  it('exposes a frozen normalized policy', () => { const coordinator = new RuntimeBackpressureCoordinator({ maxDeferred: { critical: 7 } }); const policy = coordinator.policy(); expect(policy.maxDeferred.critical).toBe(7); expect(Object.isFrozen(policy)).toBe(true); expect(Object.isFrozen(policy.maxDeferred)).toBe(true); });
});
