import type { RuntimeFailureBudgetLane } from './runtimeFailureBudget';

export type RuntimeFairSharePriority = 'urgent' | 'standard' | 'opportunistic';
export type RuntimeFairShareDisposition = 'granted' | 'queued' | 'rejected' | 'cancelled' | 'released';

export interface RuntimeFairSharePolicy { readonly capacity: number; readonly maximumQueue: number; readonly maximumPerLaneQueue: number; readonly maximumHistory: number; readonly criticalWeight: number; readonly interactiveWeight: number; readonly backgroundWeight: number; readonly maximumRequestUnits: number; }
export interface RuntimeFairShareRequest { readonly id: string; readonly lane: RuntimeFailureBudgetLane; readonly priority: RuntimeFairSharePriority; readonly units: number; readonly at: number; }
export interface RuntimeFairShareGrant { readonly id: string; readonly lane: RuntimeFailureBudgetLane; readonly units: number; readonly grantedAt: number; }
export interface RuntimeFairShareDecision { readonly id: string; readonly lane: RuntimeFailureBudgetLane; readonly disposition: RuntimeFairShareDisposition; readonly reason: 'capacity' | 'queued' | 'queue-full' | 'lane-queue-full' | 'duplicate' | 'oversized' | 'cancelled' | 'released'; readonly at: number; }
export interface RuntimeFairShareLaneSnapshot { readonly lane: RuntimeFailureBudgetLane; readonly activeUnits: number; readonly queuedRequests: number; readonly queuedUnits: number; readonly deficit: number; }
export interface RuntimeFairShareSnapshot { readonly capacity: number; readonly activeUnits: number; readonly availableUnits: number; readonly activeRequests: number; readonly queuedRequests: number; readonly lanes: Readonly<Record<RuntimeFailureBudgetLane, RuntimeFairShareLaneSnapshot>>; }
interface QueuedRequest extends RuntimeFairShareRequest { sequence: number }
interface LaneState { activeUnits: number; deficit: number; queue: QueuedRequest[] }
const LANES: readonly RuntimeFailureBudgetLane[] = Object.freeze(['critical', 'interactive', 'background']);
const PRIORITY_WEIGHT: Readonly<Record<RuntimeFairSharePriority, number>> = Object.freeze({ urgent: 0, standard: 1, opportunistic: 2 });
const DEFAULT_POLICY: RuntimeFairSharePolicy = Object.freeze({ capacity: 32, maximumQueue: 128, maximumPerLaneQueue: 64, maximumHistory: 128, criticalWeight: 4, interactiveWeight: 3, backgroundWeight: 1, maximumRequestUnits: 16 });
const boundedInteger = (value: number, name: string, minimum: number, maximum: number): number => { if (!Number.isSafeInteger(value) || value < minimum || value > maximum) throw new RangeError(`${name} must be an integer between ${minimum} and ${maximum}`); return value; };
const normalizePolicy = (input: Partial<RuntimeFairSharePolicy>): RuntimeFairSharePolicy => { const policy = Object.freeze({ capacity: boundedInteger(input.capacity ?? DEFAULT_POLICY.capacity, 'capacity', 1, 100_000), maximumQueue: boundedInteger(input.maximumQueue ?? DEFAULT_POLICY.maximumQueue, 'maximumQueue', 0, 100_000), maximumPerLaneQueue: boundedInteger(input.maximumPerLaneQueue ?? DEFAULT_POLICY.maximumPerLaneQueue, 'maximumPerLaneQueue', 0, 100_000), maximumHistory: boundedInteger(input.maximumHistory ?? DEFAULT_POLICY.maximumHistory, 'maximumHistory', 0, 10_000), criticalWeight: boundedInteger(input.criticalWeight ?? DEFAULT_POLICY.criticalWeight, 'criticalWeight', 1, 1_000), interactiveWeight: boundedInteger(input.interactiveWeight ?? DEFAULT_POLICY.interactiveWeight, 'interactiveWeight', 1, 1_000), backgroundWeight: boundedInteger(input.backgroundWeight ?? DEFAULT_POLICY.backgroundWeight, 'backgroundWeight', 1, 1_000), maximumRequestUnits: boundedInteger(input.maximumRequestUnits ?? DEFAULT_POLICY.maximumRequestUnits, 'maximumRequestUnits', 1, 100_000) }); if (policy.maximumRequestUnits > policy.capacity) throw new RangeError('maximumRequestUnits must not exceed capacity'); if (policy.maximumPerLaneQueue > policy.maximumQueue) throw new RangeError('maximumPerLaneQueue must not exceed maximumQueue'); return policy; };
const assertLane = (lane: RuntimeFailureBudgetLane): void => { if (!LANES.includes(lane)) throw new TypeError(`unsupported fair-share lane: ${String(lane)}`); };
const assertPriority = (priority: RuntimeFairSharePriority): void => { if (!(priority in PRIORITY_WEIGHT)) throw new TypeError(`unsupported fair-share priority: ${String(priority)}`); };
const assertId = (id: string): void => { if (typeof id !== 'string' || id.length === 0 || id.length > 256) throw new TypeError('request id must contain between 1 and 256 characters'); };
const assertAt = (at: number): void => { if (!Number.isSafeInteger(at) || at < 0) throw new RangeError('at must be a non-negative safe integer'); };
export class RuntimeFairShareAllocator {
  readonly #policy: RuntimeFairSharePolicy; readonly #lanes: Record<RuntimeFailureBudgetLane, LaneState> = { critical: { activeUnits: 0, deficit: 0, queue: [] }, interactive: { activeUnits: 0, deficit: 0, queue: [] }, background: { activeUnits: 0, deficit: 0, queue: [] } }; readonly #active = new Map<string, RuntimeFairShareGrant>(); readonly #queuedIds = new Set<string>(); readonly #history: RuntimeFairShareDecision[] = []; #sequence = 0; #lastAt: number | null = null; #cursor = 0;
  constructor(policy: Partial<RuntimeFairSharePolicy> = {}) { this.#policy = normalizePolicy(policy); }
  policy(): RuntimeFairSharePolicy { return this.#policy; }
  request(input: RuntimeFairShareRequest): RuntimeFairShareDecision { this.#validateRequest(input); this.#advanceClock(input.at); if (this.#active.has(input.id) || this.#queuedIds.has(input.id)) return this.#decision(input.id, input.lane, 'rejected', 'duplicate', input.at); if (input.units > this.#policy.maximumRequestUnits) return this.#decision(input.id, input.lane, 'rejected', 'oversized', input.at); if (this.#queuedCount() === 0 && input.units <= this.#available()) { this.#grant(input); return this.#decision(input.id, input.lane, 'granted', 'capacity', input.at); } const lane = this.#lanes[input.lane]; if (this.#queuedCount() >= this.#policy.maximumQueue) return this.#decision(input.id, input.lane, 'rejected', 'queue-full', input.at); if (lane.queue.length >= this.#policy.maximumPerLaneQueue) return this.#decision(input.id, input.lane, 'rejected', 'lane-queue-full', input.at); lane.queue.push({ ...input, sequence: ++this.#sequence }); lane.queue.sort((left, right) => PRIORITY_WEIGHT[left.priority] - PRIORITY_WEIGHT[right.priority] || left.sequence - right.sequence); this.#queuedIds.add(input.id); return this.#decision(input.id, input.lane, 'queued', 'queued', input.at); }
  release(id: string, at: number): readonly RuntimeFairShareGrant[] { assertId(id); assertAt(at); this.#advanceClock(at); const grant = this.#active.get(id); if (!grant) return Object.freeze([]); this.#active.delete(id); this.#lanes[grant.lane].activeUnits -= grant.units; this.#decision(id, grant.lane, 'released', 'released', at); return this.#promote(at); }
  cancel(id: string, at: number): boolean { assertId(id); assertAt(at); this.#advanceClock(at); for (const laneName of LANES) { const lane = this.#lanes[laneName]; const index = lane.queue.findIndex((entry) => entry.id === id); if (index < 0) continue; lane.queue.splice(index, 1); this.#queuedIds.delete(id); this.#decision(id, laneName, 'cancelled', 'cancelled', at); return true; } return false; }
  snapshot(): RuntimeFairShareSnapshot { const lanes = Object.freeze({ critical: this.#laneSnapshot('critical'), interactive: this.#laneSnapshot('interactive'), background: this.#laneSnapshot('background') }); const activeUnits = this.#activeUnits(); return Object.freeze({ capacity: this.#policy.capacity, activeUnits, availableUnits: this.#policy.capacity - activeUnits, activeRequests: this.#active.size, queuedRequests: this.#queuedCount(), lanes }); }
  active(): readonly RuntimeFairShareGrant[] { return Object.freeze([...this.#active.values()].map((entry) => Object.freeze({ ...entry }))); }
  history(): readonly RuntimeFairShareDecision[] { return Object.freeze(this.#history.map((entry) => Object.freeze({ ...entry }))); }
  reset(): void { this.#active.clear(); this.#queuedIds.clear(); this.#history.length = 0; for (const lane of LANES) { this.#lanes[lane].activeUnits = 0; this.#lanes[lane].deficit = 0; this.#lanes[lane].queue.length = 0; } this.#sequence = 0; this.#lastAt = null; this.#cursor = 0; }
  #validateRequest(input: RuntimeFairShareRequest): void { assertId(input.id); assertLane(input.lane); assertPriority(input.priority); assertAt(input.at); boundedInteger(input.units, 'units', 1, 100_000); }
  #advanceClock(at: number): void { if (this.#lastAt !== null && at < this.#lastAt) throw new RangeError('allocator time must be monotonic'); this.#lastAt = at; }
  #activeUnits(): number { let total = 0; for (const lane of LANES) total += this.#lanes[lane].activeUnits; return total; }
  #available(): number { return this.#policy.capacity - this.#activeUnits(); }
  #queuedCount(): number { return this.#queuedIds.size; }
  #weight(lane: RuntimeFailureBudgetLane): number { if (lane === 'critical') return this.#policy.criticalWeight; if (lane === 'interactive') return this.#policy.interactiveWeight; return this.#policy.backgroundWeight; }
  #grant(input: RuntimeFairShareRequest, at = input.at): RuntimeFairShareGrant { const grant = Object.freeze({ id: input.id, lane: input.lane, units: input.units, grantedAt: at }); this.#active.set(input.id, grant); this.#lanes[input.lane].activeUnits += input.units; this.#queuedIds.delete(input.id); return grant; }
  #promote(at: number): readonly RuntimeFairShareGrant[] { const promoted: RuntimeFairShareGrant[] = []; let visitsWithoutGrant = 0; const maxVisits = LANES.length * 2 + this.#queuedCount() * LANES.length; while (this.#queuedCount() > 0 && this.#available() > 0 && visitsWithoutGrant < maxVisits) { const laneName = LANES[this.#cursor] as RuntimeFailureBudgetLane; this.#cursor = (this.#cursor + 1) % LANES.length; const lane = this.#lanes[laneName]; lane.deficit = Math.min(this.#policy.capacity, lane.deficit + this.#weight(laneName)); const next = lane.queue[0]; if (!next || next.units > lane.deficit || next.units > this.#available()) { visitsWithoutGrant += 1; continue; } lane.queue.shift(); lane.deficit -= next.units; const grant = this.#grant(next, at); promoted.push(grant); this.#decision(next.id, next.lane, 'granted', 'capacity', at); visitsWithoutGrant = 0; } return Object.freeze(promoted); }
  #laneSnapshot(laneName: RuntimeFailureBudgetLane): RuntimeFairShareLaneSnapshot { const lane = this.#lanes[laneName]; let queuedUnits = 0; for (const request of lane.queue) queuedUnits += request.units; return Object.freeze({ lane: laneName, activeUnits: lane.activeUnits, queuedRequests: lane.queue.length, queuedUnits, deficit: lane.deficit }); }
  #decision(id: string, lane: RuntimeFailureBudgetLane, disposition: RuntimeFairShareDisposition, reason: RuntimeFairShareDecision['reason'], at: number): RuntimeFairShareDecision { const decision = Object.freeze({ id, lane, disposition, reason, at }); if (this.#policy.maximumHistory > 0) { this.#history.push(decision); if (this.#history.length > this.#policy.maximumHistory) this.#history.splice(0, this.#history.length - this.#policy.maximumHistory); } return decision; }
}
