import { describe, expect, it } from 'vitest';
import { RuntimeOverloadGuard } from './runtimeOverloadGuard';

describe('RuntimeOverloadGuard', () => {
  it('stays healthy before the maturity threshold', () => { const guard = new RuntimeOverloadGuard({ minimumSamples: 3 }); expect(guard.record({ lane: 'interactive', pressure: 1 }).state).toBe('healthy'); expect(guard.record({ lane: 'interactive', pressure: 1 }).state).toBe('healthy'); });
  it('enters pressured and overloaded states from rolling average pressure', () => { const guard = new RuntimeOverloadGuard({ minimumSamples: 2, windowSize: 4, pressureThreshold: 0.5, overloadThreshold: 0.8 }); guard.record({ lane: 'critical', pressure: 0.7 }); expect(guard.record({ lane: 'critical', pressure: 0.7 }).state).toBe('pressured'); guard.record({ lane: 'critical', pressure: 1 }); expect(guard.record({ lane: 'critical', pressure: 1 }).state).toBe('overloaded'); });
  it('uses hysteresis while recovering from overload', () => { const guard = new RuntimeOverloadGuard({ minimumSamples: 2, windowSize: 2, pressureThreshold: 0.6, overloadThreshold: 0.8, recoveryThreshold: 0.3 }); guard.recordMany([{ lane: 'background', pressure: 1 }, { lane: 'background', pressure: 1 }]); expect(guard.lane('background').state).toBe('overloaded'); guard.record({ lane: 'background', pressure: 0.4 }); expect(guard.record({ lane: 'background', pressure: 0.4 }).state).toBe('pressured'); guard.record({ lane: 'background', pressure: 0.1 }); expect(guard.record({ lane: 'background', pressure: 0.1 }).state).toBe('healthy'); });
  it('bounds the rolling window', () => { const guard = new RuntimeOverloadGuard({ minimumSamples: 1, windowSize: 3 }); guard.recordMany([{ lane: 'interactive', pressure: 1 }, { lane: 'interactive', pressure: 1 }, { lane: 'interactive', pressure: 0 }, { lane: 'interactive', pressure: 0 }]); const lane = guard.lane('interactive'); expect(lane.samples).toBe(3); expect(lane.averagePressure).toBeCloseTo(1 / 3); });
  it('reports the worst lane as aggregate state', () => { const guard = new RuntimeOverloadGuard({ minimumSamples: 1 }); guard.record({ lane: 'critical', pressure: 0.65 }); guard.record({ lane: 'background', pressure: 0.9 }); expect(guard.snapshot().state).toBe('overloaded'); });
  it('returns frozen snapshots and policy', () => { const guard = new RuntimeOverloadGuard(); const snapshot = guard.snapshot(); expect(Object.isFrozen(snapshot)).toBe(true); expect(Object.isFrozen(snapshot.lanes)).toBe(true); expect(Object.isFrozen(snapshot.lanes.critical)).toBe(true); expect(Object.isFrozen(guard.policy())).toBe(true); });
  it('rejects malformed policy and forged samples', () => { expect(() => new RuntimeOverloadGuard({ recoveryThreshold: 0.7, pressureThreshold: 0.6 })).toThrow(RangeError); expect(() => new RuntimeOverloadGuard({ pressureThreshold: 0.9, overloadThreshold: 0.8 })).toThrow(RangeError); expect(() => new RuntimeOverloadGuard({ minimumSamples: 5, windowSize: 4 })).toThrow(RangeError); const guard = new RuntimeOverloadGuard(); expect(() => guard.record({ lane: 'unknown' as never, pressure: 0 })).toThrow(TypeError); expect(() => guard.record({ lane: 'critical', pressure: Number.NaN })).toThrow(RangeError); expect(() => guard.recordMany(Array.from({ length: 10_001 }, () => ({ lane: 'critical' as const, pressure: 0 })))).toThrow(RangeError); });
  it('resets one lane without erasing unrelated pressure history', () => { const guard = new RuntimeOverloadGuard({ minimumSamples: 1 }); guard.record({ lane: 'critical', pressure: 1 }); guard.record({ lane: 'interactive', pressure: 0.7 }); guard.reset('critical'); expect(guard.lane('critical').samples).toBe(0); expect(guard.lane('interactive').samples).toBe(1); guard.reset(); expect(guard.snapshot().state).toBe('healthy'); });
});
