import type { RuntimeFailureBudgetLane } from './runtimeFailureBudget';

export type RuntimeSaturationKind = 'admitted' | 'queued' | 'rejected' | 'completed' | 'cancelled';
export type RuntimeSaturationLevel = 'cold' | 'healthy' | 'warning' | 'critical';

export interface RuntimeSaturationPolicy { readonly windowSize: number; readonly minimumSamples: number; readonly warningQueueRatio: number; readonly criticalQueueRatio: number; readonly warningRejectRatio: number; readonly criticalRejectRatio: number; readonly historyLimit: number; }
export interface RuntimeSaturationSample { readonly lane: RuntimeFailureBudgetLane; readonly kind: RuntimeSaturationKind; readonly at: number; }
export interface RuntimeSaturationLaneSnapshot { readonly lane: RuntimeFailureBudgetLane; readonly samples: number; readonly admitted: number; readonly queued: number; readonly rejected: number; readonly completed: number; readonly cancelled: number; readonly queueRatio: number; readonly rejectRatio: number; readonly level: RuntimeSaturationLevel; }
export interface RuntimeSaturationEvent extends RuntimeSaturationSample { readonly sequence: number; }
export interface RuntimeSaturationSnapshot { readonly sequence: number; readonly level: RuntimeSaturationLevel; readonly lanes: Readonly<Record<RuntimeFailureBudgetLane, RuntimeSaturationLaneSnapshot>>; readonly history: readonly RuntimeSaturationEvent[]; }

const LANES: readonly RuntimeFailureBudgetLane[] = Object.freeze(['critical', 'interactive', 'background']);
const KINDS: readonly RuntimeSaturationKind[] = Object.freeze(['admitted', 'queued', 'rejected', 'completed', 'cancelled']);
const DEFAULT_POLICY: RuntimeSaturationPolicy = Object.freeze({ windowSize: 128, minimumSamples: 12, warningQueueRatio: 0.25, criticalQueueRatio: 0.5, warningRejectRatio: 0.1, criticalRejectRatio: 0.25, historyLimit: 256 });
const assertLane = (value: RuntimeFailureBudgetLane): void => { if (!LANES.includes(value)) throw new TypeError(`unsupported saturation lane: ${String(value)}`); };
const assertKind = (value: RuntimeSaturationKind): void => { if (!KINDS.includes(value)) throw new TypeError(`unsupported saturation kind: ${String(value)}`); };
const positiveInteger = (value: number, name: string, maximum: number): number => { if (!Number.isSafeInteger(value) || value <= 0 || value > maximum) throw new RangeError(`${name} must be a positive safe integer <= ${maximum}`); return value; };
const ratio = (value: number, name: string): number => { if (!Number.isFinite(value) || value < 0 || value > 1) throw new RangeError(`${name} must be between 0 and 1`); return value; };
const normalizePolicy = (value: Partial<RuntimeSaturationPolicy>): RuntimeSaturationPolicy => { const policy = { windowSize: positiveInteger(value.windowSize ?? DEFAULT_POLICY.windowSize, 'windowSize', 10_000), minimumSamples: positiveInteger(value.minimumSamples ?? DEFAULT_POLICY.minimumSamples, 'minimumSamples', 10_000), warningQueueRatio: ratio(value.warningQueueRatio ?? DEFAULT_POLICY.warningQueueRatio, 'warningQueueRatio'), criticalQueueRatio: ratio(value.criticalQueueRatio ?? DEFAULT_POLICY.criticalQueueRatio, 'criticalQueueRatio'), warningRejectRatio: ratio(value.warningRejectRatio ?? DEFAULT_POLICY.warningRejectRatio, 'warningRejectRatio'), criticalRejectRatio: ratio(value.criticalRejectRatio ?? DEFAULT_POLICY.criticalRejectRatio, 'criticalRejectRatio'), historyLimit: positiveInteger(value.historyLimit ?? DEFAULT_POLICY.historyLimit, 'historyLimit', 10_000) }; if (policy.minimumSamples > policy.windowSize) throw new RangeError('minimumSamples must be <= windowSize'); if (policy.warningQueueRatio > policy.criticalQueueRatio) throw new RangeError('warningQueueRatio must be <= criticalQueueRatio'); if (policy.warningRejectRatio > policy.criticalRejectRatio) throw new RangeError('warningRejectRatio must be <= criticalRejectRatio'); return Object.freeze(policy); };
const severity: Readonly<Record<RuntimeSaturationLevel, number>> = Object.freeze({ cold: 0, healthy: 1, warning: 2, critical: 3 });

export class RuntimeSaturationLedger {
  readonly #policy: RuntimeSaturationPolicy;
  readonly #windows: Record<RuntimeFailureBudgetLane, RuntimeSaturationKind[]> = { critical: [], interactive: [], background: [] };
  readonly #history: RuntimeSaturationEvent[] = [];
  #sequence = 0; #lastAt = 0;
  constructor(policy: Partial<RuntimeSaturationPolicy> = {}) { this.#policy = normalizePolicy(policy); }
  record(sample: RuntimeSaturationSample): RuntimeSaturationSnapshot { assertLane(sample.lane); assertKind(sample.kind); if (!Number.isFinite(sample.at) || sample.at < 0) throw new RangeError('at must be a finite non-negative number'); if (sample.at < this.#lastAt) throw new RangeError('at must be monotonic'); this.#lastAt = sample.at; const window = this.#windows[sample.lane]; window.push(sample.kind); const overflow = window.length - this.#policy.windowSize; if (overflow > 0) window.splice(0, overflow); this.#sequence += 1; this.#history.push(Object.freeze({ ...sample, sequence: this.#sequence })); const historyOverflow = this.#history.length - this.#policy.historyLimit; if (historyOverflow > 0) this.#history.splice(0, historyOverflow); return this.snapshot(); }
  recordMany(samples: readonly RuntimeSaturationSample[]): RuntimeSaturationSnapshot { if (!Array.isArray(samples)) throw new TypeError('samples must be an array'); if (samples.length > 10_000) throw new RangeError('samples must contain at most 10000 entries'); for (const sample of samples) this.record(sample); return this.snapshot(); }
  lane(lane: RuntimeFailureBudgetLane): RuntimeSaturationLaneSnapshot { assertLane(lane); const window = this.#windows[lane]; const counts: Record<RuntimeSaturationKind, number> = { admitted: 0, queued: 0, rejected: 0, completed: 0, cancelled: 0 }; for (const kind of window) counts[kind] += 1; const samples = window.length; const queueRatio = samples === 0 ? 0 : counts.queued / samples; const rejectRatio = samples === 0 ? 0 : counts.rejected / samples; let level: RuntimeSaturationLevel = samples < this.#policy.minimumSamples ? 'cold' : 'healthy'; if (samples >= this.#policy.minimumSamples) { if (queueRatio >= this.#policy.criticalQueueRatio || rejectRatio >= this.#policy.criticalRejectRatio) level = 'critical'; else if (queueRatio >= this.#policy.warningQueueRatio || rejectRatio >= this.#policy.warningRejectRatio) level = 'warning'; } return Object.freeze({ lane, samples, ...counts, queueRatio, rejectRatio, level }); }
  snapshot(): RuntimeSaturationSnapshot { const lanes = Object.freeze({ critical: this.lane('critical'), interactive: this.lane('interactive'), background: this.lane('background') }); let level: RuntimeSaturationLevel = 'cold'; for (const lane of LANES) if (severity[lanes[lane].level] > severity[level]) level = lanes[lane].level; return Object.freeze({ sequence: this.#sequence, level, lanes, history: Object.freeze(this.#history.map((event) => Object.freeze({ ...event }))) }); }
  policy(): RuntimeSaturationPolicy { return this.#policy; }
  reset(lane?: RuntimeFailureBudgetLane): RuntimeSaturationSnapshot { if (lane !== undefined) { assertLane(lane); this.#windows[lane].length = 0; } else { for (const current of LANES) this.#windows[current].length = 0; this.#history.length = 0; this.#lastAt = 0; } this.#sequence += 1; return this.snapshot(); }
}
