import { describe, expect, it } from 'vitest';
import { WorkBudgetCancelledError, WorkBudgetRejectedError, createWorkBudgetCoordinator } from './workBudgetCoordinator';

const policy = () => ({ maxActive: 2, maxQueued: 8, maxUnits: 8, maxBytes: 1024, maxQueueAgeMs: 100, maxLeaseAgeMs: 200, maxScopes: 4, maxKeys: 16 });

describe('createWorkBudgetCoordinator', () => {
  it('admits and releases work within aggregate budgets', async () => { const coordinator = createWorkBudgetCoordinator(policy()); const first = await coordinator.acquire({ key: 'a', units: 2, bytes: 100 }); const second = await coordinator.acquire({ key: 'b', units: 3, bytes: 200 }); expect(coordinator.snapshot()).toMatchObject({ active: 2, activeUnits: 5, activeBytes: 300, admitted: 2 }); first.release(); second.release(); expect(coordinator.snapshot()).toMatchObject({ active: 0, completed: 2 }); });
  it('queues on active saturation and pumps on release', async () => { const coordinator = createWorkBudgetCoordinator({ ...policy(), maxActive: 1 }); const first = await coordinator.acquire({ key: 'first' }); const pending = coordinator.acquire({ key: 'second' }); expect(coordinator.snapshot()).toMatchObject({ active: 1, queued: 1 }); first.release(); const second = await pending; expect(second.key).toBe('second'); second.release(); });
  it('orders queued work by priority', async () => { const coordinator = createWorkBudgetCoordinator({ ...policy(), maxActive: 1 }); const blocker = await coordinator.acquire({ key: 'blocker' }); const background = coordinator.acquire({ key: 'background', priority: 'background' }); const high = coordinator.acquire({ key: 'high', priority: 'high' }); const critical = coordinator.acquire({ key: 'critical', priority: 'critical' }); blocker.release(); const a = await critical; expect(a.key).toBe('critical'); a.release(); const b = await high; expect(b.key).toBe('high'); b.release(); (await background).release(); });
  it('allows fitting work to bypass a temporarily oversized candidate', async () => { const coordinator = createWorkBudgetCoordinator({ ...policy(), maxActive: 3, maxUnits: 4 }); const blocker = await coordinator.acquire({ key: 'blocker', units: 3 }); const heavy = coordinator.acquire({ key: 'heavy', priority: 'high', units: 3 }); const light = await coordinator.acquire({ key: 'light', units: 1 }); expect(light.key).toBe('light'); expect(coordinator.snapshot().queued).toBe(1); light.release(); blocker.release(); (await heavy).release(); });
  it('enforces per-scope active, unit, and byte budgets', async () => { const coordinator = createWorkBudgetCoordinator({ ...policy(), maxActive: 5, scopeMaxActive: { map: 1 }, scopeMaxUnits: { map: 3 }, scopeMaxBytes: { map: 300 } }); const first = await coordinator.acquire({ key: 'a', scope: 'map', units: 2, bytes: 200 }); const pending = coordinator.acquire({ key: 'b', scope: 'map', units: 2, bytes: 200 }); const other = await coordinator.acquire({ key: 'c', scope: 'search' }); expect(coordinator.snapshot().scopes.map).toMatchObject({ active: 1, queued: 1, units: 2, bytes: 200 }); first.release(); (await pending).release(); other.release(); });
  it('rejects blank keys fail closed', async () => { const coordinator = createWorkBudgetCoordinator(policy()); await expect(coordinator.acquire({ key: '   ' })).rejects.toBeInstanceOf(WorkBudgetRejectedError); });
  it('normalizes identifiers and request costs', async () => { const coordinator = createWorkBudgetCoordinator(policy()); const lease = await coordinator.acquire({ key: ` ${'x'.repeat(200)} `, scope: ` ${'s'.repeat(200)} `, units: Number.NaN, bytes: -4 }); expect(lease.key).toHaveLength(128); expect(lease.scope).toHaveLength(128); expect(lease.units).toBe(1); expect(lease.bytes).toBe(1); lease.release(); });
  it('clamps request costs to global maxima', async () => { const coordinator = createWorkBudgetCoordinator(policy()); const lease = await coordinator.acquire({ key: 'huge', units: 1000, bytes: 999999 }); expect(lease.units).toBe(8); expect(lease.bytes).toBe(1024); lease.release(); });
  it('rejects already aborted requests without queue retention', async () => { const coordinator = createWorkBudgetCoordinator(policy()); const controller = new AbortController(); controller.abort(); await expect(coordinator.acquire({ key: 'aborted', signal: controller.signal })).rejects.toBeInstanceOf(WorkBudgetCancelledError); expect(coordinator.snapshot()).toMatchObject({ queued: 0, cancelled: 1 }); });
  it('cancels queued work through AbortSignal', async () => { const coordinator = createWorkBudgetCoordinator({ ...policy(), maxActive: 1 }); const blocker = await coordinator.acquire({ key: 'blocker' }); const controller = new AbortController(); const pending = coordinator.acquire({ key: 'pending', signal: controller.signal }); controller.abort(); await expect(pending).rejects.toBeInstanceOf(WorkBudgetCancelledError); expect(coordinator.snapshot()).toMatchObject({ queued: 0, cancelled: 1 }); blocker.release(); });
  it('supports predicate cancellation', async () => { const coordinator = createWorkBudgetCoordinator({ ...policy(), maxActive: 1 }); const blocker = await coordinator.acquire({ key: 'blocker' }); const first = coordinator.acquire({ key: 'first', scope: 'map' }); const second = coordinator.acquire({ key: 'second', scope: 'search' }); expect(coordinator.cancelQueued((request) => request.scope === 'map')).toBe(1); await expect(first).rejects.toBeInstanceOf(WorkBudgetCancelledError); blocker.release(); (await second).release(); });
  it('rejects queue overflow', async () => { const coordinator = createWorkBudgetCoordinator({ ...policy(), maxActive: 1, maxQueued: 1 }); const blocker = await coordinator.acquire({ key: 'blocker' }); const pending = coordinator.acquire({ key: 'pending' }); await expect(coordinator.acquire({ key: 'overflow' })).rejects.toBeInstanceOf(WorkBudgetRejectedError); blocker.release(); (await pending).release(); });
  it('expires queued work by age and explicit deadline', async () => { let clock = 0; const coordinator = createWorkBudgetCoordinator({ ...policy(), maxActive: 1 }, () => clock); const blocker = await coordinator.acquire({ key: 'blocker' }); const aged = coordinator.acquire({ key: 'aged' }); clock = 101; coordinator.sweep(); await expect(aged).rejects.toBeInstanceOf(WorkBudgetRejectedError); blocker.release(); const blocker2 = await coordinator.acquire({ key: 'blocker2' }); const deadline = coordinator.acquire({ key: 'deadline', deadlineMs: 120 }); clock = 121; coordinator.sweep(); await expect(deadline).rejects.toBeInstanceOf(WorkBudgetRejectedError); blocker2.release(); });
  it('expires stale leases and admits queued work without expiring the queue first', async () => { let clock = 0; const coordinator = createWorkBudgetCoordinator({ ...policy(), maxActive: 1, maxQueueAgeMs: 1_000 }, () => clock); await coordinator.acquire({ key: 'stale' }); const pending = coordinator.acquire({ key: 'next' }); clock = 201; coordinator.sweep(); const next = await pending; expect(coordinator.snapshot()).toMatchObject({ active: 1, expiredLeases: 1, admitted: 2 }); next.release(); });
  it('renews active leases and rejects renewal after release', async () => { let clock = 0; const coordinator = createWorkBudgetCoordinator({ ...policy(), maxActive: 1 }, () => clock); const lease = await coordinator.acquire({ key: 'renewable' }); clock = 150; expect(lease.renew()).toBe(true); clock = 250; coordinator.sweep(); expect(coordinator.snapshot().active).toBe(1); lease.release(); expect(lease.renew()).toBe(false); });
  it('release is idempotent', async () => { const coordinator = createWorkBudgetCoordinator(policy()); const lease = await coordinator.acquire({ key: 'once' }); lease.release(); lease.release(); expect(coordinator.snapshot().completed).toBe(1); });
  it('releases a normalized scope', async () => { const coordinator = createWorkBudgetCoordinator({ ...policy(), maxActive: 4 }); await coordinator.acquire({ key: 'a', scope: ' map ' }); await coordinator.acquire({ key: 'b', scope: 'map' }); const other = await coordinator.acquire({ key: 'c', scope: 'search' }); expect(coordinator.releaseScope(' map ')).toBe(2); expect(coordinator.snapshot()).toMatchObject({ active: 1, completed: 2 }); other.release(); });
  it('bounds distinct scope and key cardinality', async () => { const coordinator = createWorkBudgetCoordinator({ ...policy(), maxScopes: 2, maxKeys: 2, maxActive: 4 }); const a = await coordinator.acquire({ key: 'a', scope: 'one' }); const b = await coordinator.acquire({ key: 'b', scope: 'two' }); await expect(coordinator.acquire({ key: 'c', scope: 'three' })).rejects.toBeInstanceOf(WorkBudgetRejectedError); a.release(); b.release(); });
  it('produces detached frozen payload-free snapshots', async () => { const coordinator = createWorkBudgetCoordinator(policy()); const controller = new AbortController(); const lease = await coordinator.acquire({ key: 'a', scope: 'map', units: 2, bytes: 40, signal: controller.signal }); const snapshot = coordinator.snapshot(); expect(snapshot.scopes.map).toEqual({ active: 1, queued: 0, units: 2, bytes: 40 }); expect(Object.isFrozen(snapshot)).toBe(true); expect(Object.isFrozen(snapshot.scopes)).toBe(true); expect(Object.isFrozen(snapshot.scopes.map)).toBe(true); expect(JSON.stringify(snapshot)).not.toContain('signal'); lease.release(); expect(snapshot.scopes.map.active).toBe(1); });
  it('disposes queued and active state terminally and idempotently', async () => { const coordinator = createWorkBudgetCoordinator({ ...policy(), maxActive: 1 }); const active = await coordinator.acquire({ key: 'active' }); const pending = coordinator.acquire({ key: 'pending' }); coordinator.dispose(); coordinator.dispose(); await expect(pending).rejects.toBeInstanceOf(WorkBudgetCancelledError); expect(coordinator.snapshot()).toMatchObject({ active: 0, queued: 0 }); expect(active.renew()).toBe(false); await expect(coordinator.acquire({ key: 'after' })).rejects.toBeInstanceOf(WorkBudgetRejectedError); });
});
