import { AppError, isAbortError } from '../errors/appError';

export const BootstrapStage = Object.freeze({
  IDLE: 'idle', LOAD: 'load', VALIDATE: 'validate', PREPARE: 'prepare', PROXY: 'proxy', COMMIT: 'commit', COMPLETED: 'completed', CANCELLED: 'cancelled', FAILED: 'failed',
} as const);
export type BootstrapStageValue = typeof BootstrapStage[keyof typeof BootstrapStage];
export const BootstrapErrorCode = Object.freeze({
  INVALID_DEPENDENCY:'BOOTSTRAP_INVALID_DEPENDENCY', MAP_REQUEST_FAILED:'BOOTSTRAP_MAP_REQUEST_FAILED', SERVICE_REQUEST_FAILED:'BOOTSTRAP_SERVICE_REQUEST_FAILED', MAP_PAYLOAD_MISSING:'BOOTSTRAP_MAP_PAYLOAD_MISSING', MAP_PAYLOAD_INVALID:'BOOTSTRAP_MAP_PAYLOAD_INVALID', SERVICE_PAYLOAD_INVALID:'BOOTSTRAP_SERVICE_PAYLOAD_INVALID', SERVICE_URL_INVALID:'BOOTSTRAP_SERVICE_URL_INVALID', PROXY_SETUP_FAILED:'BOOTSTRAP_PROXY_SETUP_FAILED', COMMIT_FAILED:'BOOTSTRAP_COMMIT_FAILED', ABORTED:'BOOTSTRAP_ABORTED', UNEXPECTED:'BOOTSTRAP_UNEXPECTED',
} as const);
export type BootstrapErrorCodeValue = typeof BootstrapErrorCode[keyof typeof BootstrapErrorCode];
export type MapConfiguration = Readonly<Record<string, unknown>>;
export type ConfigurationService = Readonly<Record<string, unknown>>;
export interface ServiceResult { readonly isSuccess?: boolean; readonly data?: unknown; readonly message?: unknown; readonly type?: unknown; readonly resultType?: unknown; }
export interface BootstrapProxyRule { readonly url:string; readonly source:string; readonly serviceIndex:number; readonly serviceIdentity:string; }
export interface BootstrapPlan { readonly mapConfiguration:MapConfiguration; readonly configurationServices:readonly ConfigurationService[]; readonly proxyRules:readonly BootstrapProxyRule[]; readonly summary:Readonly<{serviceCount:number;proxyRuleCount:number}>; }
export interface BootstrapResult { readonly status:typeof BootstrapStage.COMPLETED; readonly durationMs:number; readonly mapConfiguration:MapConfiguration; readonly configurationServices:readonly ConfigurationService[]; readonly proxyRuleCount:number; readonly serviceCount:number; }
export interface BootstrapDiagnostics { record(event:string,payload?:Readonly<Record<string,unknown>>):void; }
export interface BootstrapDependencies { readonly loadMapConfiguration:(options?:{readonly signal?:AbortSignal})=>Promise<ServiceResult>|ServiceResult; readonly loadConfigurationServices:(options?:{readonly signal?:AbortSignal})=>Promise<ServiceResult>|ServiceResult; readonly generateServiceUrl:(service:ConfigurationService)=>unknown; readonly addProxyRule:(url:string,source:string)=>Promise<unknown>|unknown; readonly setMapConfiguration:(configuration:MapConfiguration)=>Promise<unknown>|unknown; readonly setConfigurationServices:(services:readonly ConfigurationService[])=>Promise<unknown>|unknown; }
export interface BootstrapOptions { readonly signal?:AbortSignal; readonly diagnostics?:BootstrapDiagnostics|null; }
const DEFAULT_SOURCE='ApplicationBootstrap'; const SERVICE_ID_KEYS=Object.freeze(['id','Id','code','Code','title','Title','name','Name'] as const); type AnyFunction=(...args:any[])=>any;
const asFiniteNumber=(value:unknown,fallback=0):number=>{const parsed=Number(value);return Number.isFinite(parsed)?parsed:fallback;}; const now=():number=>Date.now();
const requiredFunction=<TFunction extends AnyFunction>(dependencies:Partial<Record<keyof BootstrapDependencies,unknown>>|null|undefined,key:keyof BootstrapDependencies):TFunction=>{const value=dependencies?.[key];if(typeof value!=='function')throw new AppError(`Bootstrap bağımlılığı eksik: ${key}`,{code:BootstrapErrorCode.INVALID_DEPENDENCY,retryable:false,details:{dependency:key}});return value as TFunction;};
const createAbortError=(stage:BootstrapStageValue):AppError=>new AppError('Uygulama başlatma işlemi iptal edildi.',{code:BootstrapErrorCode.ABORTED,retryable:true,details:{stage}});
export const throwIfBootstrapAborted=(signal?:AbortSignal,stage:BootstrapStageValue=BootstrapStage.IDLE):void=>{if(signal?.aborted)throw createAbortError(stage);};
export const isBootstrapAbortError=(error:unknown):boolean=>(error instanceof AppError&&error.code===BootstrapErrorCode.ABORTED)||isAbortError(error);
const resultCandidate=(value:unknown):ServiceResult|null=>value&&typeof value==='object'?value as ServiceResult:null;
const normalizeServiceResultError=(result:ServiceResult|null,code:BootstrapErrorCodeValue,fallbackMessage:string):AppError=>{const candidateMessage=typeof result?.message==='string'?result.message.trim():'';return new AppError(candidateMessage||fallbackMessage,{code,retryable:true,details:{resultType:result?.type??result?.resultType??null}});};
export const assertSuccessfulServiceResult=(result:unknown,options:{readonly code?:BootstrapErrorCodeValue;readonly message?:string}={}):ServiceResult=>{const code=options.code??BootstrapErrorCode.UNEXPECTED;const message=options.message??'Yapılandırma servisi başarısız oldu.';const candidate=resultCandidate(result);if(!candidate)throw new AppError(message,{code,retryable:true,details:{reason:'missing-result'}});if(candidate.isSuccess!==true)throw normalizeServiceResultError(candidate,code,message);return candidate;};
const isPlainObject=(value:unknown):value is Record<string,unknown>=>{if(value===null||typeof value!=='object'||Array.isArray(value))return false;const prototype=Object.getPrototypeOf(value);return prototype===Object.prototype||prototype===null;};
const normalizeJsonText=(value:unknown):unknown=>{if(typeof value!=='string')return value;const trimmed=value.trim();return trimmed.length?trimmed:null;};
export const parseMapConfiguration=(result:unknown):MapConfiguration=>{const successful=assertSuccessfulServiceResult(result,{code:BootstrapErrorCode.MAP_REQUEST_FAILED,message:'Harita yapılandırması alınamadı.'});const data=isPlainObject(successful.data)?successful.data:null;const rawValue=data?.configValue??data?.ConfigValue;const normalized=normalizeJsonText(rawValue);if(normalized===null||normalized===undefined)throw new AppError('Harita yapılandırması boş döndü.',{code:BootstrapErrorCode.MAP_PAYLOAD_MISSING,retryable:true});if(isPlainObject(normalized))return normalized;if(typeof normalized!=='string')throw new AppError('Harita yapılandırması desteklenmeyen biçimde döndü.',{code:BootstrapErrorCode.MAP_PAYLOAD_INVALID,retryable:false,details:{payloadType:typeof normalized}});try{const parsed:unknown=JSON.parse(normalized);if(!isPlainObject(parsed))throw new Error('Map configuration must be an object');return Object.freeze({...parsed});}catch(error){throw new AppError('Harita yapılandırması geçerli JSON değil.',{code:BootstrapErrorCode.MAP_PAYLOAD_INVALID,retryable:false,cause:error});}};
const serviceIdentity=(service:ConfigurationService,index:number):string=>{for(const key of SERVICE_ID_KEYS){const value=service[key];if(value!==null&&value!==undefined&&String(value).trim())return `${key.toLowerCase()}:${String(value).trim()}`;}return `index:${index}`;};
export const normalizeConfigurationServices=(result:unknown):readonly ConfigurationService[]=>{const successful=assertSuccessfulServiceResult(result,{code:BootstrapErrorCode.SERVICE_REQUEST_FAILED,message:'CBS servis yapılandırması alınamadı.'});if(successful.data===null||successful.data===undefined)return [];if(!Array.isArray(successful.data))throw new AppError('CBS servis yapılandırması liste biçiminde değil.',{code:BootstrapErrorCode.SERVICE_PAYLOAD_INVALID,retryable:false});const seen=new Set<string>();const services:ConfigurationService[]=[];successful.data.forEach((value,index)=>{if(!isPlainObject(value))throw new AppError('CBS servis kaydı geçersiz.',{code:BootstrapErrorCode.SERVICE_PAYLOAD_INVALID,retryable:false,details:{index}});const identity=serviceIdentity(value,index);if(!seen.has(identity)){seen.add(identity);services.push(value);}});return services;};
export const normalizeProxyUrl=(value:unknown):string=>{if(typeof value!=='string'||!value.trim())throw new AppError('CBS servis URL bilgisi geçersiz.',{code:BootstrapErrorCode.SERVICE_URL_INVALID,retryable:false});try{const url=new URL(value.trim());if(url.protocol!=='http:'&&url.protocol!=='https:')throw new Error('unsupported protocol');return url.toString();}catch(cause){throw new AppError('CBS servis URL bilgisi geçersiz.',{code:BootstrapErrorCode.SERVICE_URL_INVALID,retryable:false,cause});}};
export const createBootstrapPlan=(mapConfiguration:MapConfiguration,configurationServices:readonly ConfigurationService[],generateServiceUrl:(service:ConfigurationService)=>unknown):BootstrapPlan=>{const proxyRules=configurationServices.map((service,index)=>({url:normalizeProxyUrl(generateServiceUrl(service)),source:DEFAULT_SOURCE,serviceIndex:index,serviceIdentity:serviceIdentity(service,index)}));return Object.freeze({mapConfiguration,configurationServices,proxyRules:Object.freeze(proxyRules),summary:Object.freeze({serviceCount:configurationServices.length,proxyRuleCount:proxyRules.length})});};
export const createBootstrapDependencies=(dependencies:Partial<BootstrapDependencies>):BootstrapDependencies=>({loadMapConfiguration:requiredFunction(dependencies,'loadMapConfiguration'),loadConfigurationServices:requiredFunction(dependencies,'loadConfigurationServices'),generateServiceUrl:requiredFunction(dependencies,'generateServiceUrl'),addProxyRule:requiredFunction(dependencies,'addProxyRule'),setMapConfiguration:requiredFunction(dependencies,'setMapConfiguration'),setConfigurationServices:requiredFunction(dependencies,'setConfigurationServices')});
export const bootstrapDurationBucket=(durationMs:unknown):string=>{const value=Math.max(0,asFiniteNumber(durationMs));if(value<250)return 'lt-250ms';if(value<1000)return '250-999ms';if(value<3000)return '1-3s';return 'gte-3s';};
export const runApplicationBootstrap=async(dependenciesInput:Partial<BootstrapDependencies>,options:BootstrapOptions={}):Promise<BootstrapResult>=>{const startedAt=now();const dependencies=createBootstrapDependencies(dependenciesInput);const signal=options.signal;const diagnostics=options.diagnostics;let stage:BootstrapStageValue=BootstrapStage.LOAD;try{throwIfBootstrapAborted(signal,stage);diagnostics?.record('bootstrap:start',{stage});const [mapResult,servicesResult]=await Promise.all([dependencies.loadMapConfiguration({signal}),dependencies.loadConfigurationServices({signal})]);stage=BootstrapStage.VALIDATE;throwIfBootstrapAborted(signal,stage);const mapConfiguration=parseMapConfiguration(mapResult);const configurationServices=normalizeConfigurationServices(servicesResult);stage=BootstrapStage.PREPARE;const plan=createBootstrapPlan(mapConfiguration,configurationServices,dependencies.generateServiceUrl);stage=BootstrapStage.PROXY;for(const rule of plan.proxyRules){throwIfBootstrapAborted(signal,stage);await dependencies.addProxyRule(rule.url,rule.source);}stage=BootstrapStage.COMMIT;throwIfBootstrapAborted(signal,stage);await dependencies.setMapConfiguration(plan.mapConfiguration);await dependencies.setConfigurationServices(plan.configurationServices);const durationMs=Math.max(0,now()-startedAt);diagnostics?.record('bootstrap:completed',{durationBucket:bootstrapDurationBucket(durationMs),serviceCount:plan.summary.serviceCount,proxyRuleCount:plan.summary.proxyRuleCount});return {status:BootstrapStage.COMPLETED,durationMs,mapConfiguration:plan.mapConfiguration,configurationServices:plan.configurationServices,proxyRuleCount:plan.summary.proxyRuleCount,serviceCount:plan.summary.serviceCount};}catch(error){if(isBootstrapAbortError(error)||signal?.aborted)throw createAbortError(stage);if(error instanceof AppError)throw error;throw new AppError('Uygulama başlatılırken beklenmeyen hata oluştu.',{code:stage===BootstrapStage.COMMIT?BootstrapErrorCode.COMMIT_FAILED:BootstrapErrorCode.UNEXPECTED,retryable:true,cause:error,details:{stage}});}};
