//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="HatDurakBilgiServisSoap")]
public interface HatDurakBilgiServisSoap
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AktifHatlar", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<Hat[]> AktifHatlarAsync(string token);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AktifDuraklar", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<MasterDurak[]> AktifDuraklarAsync(string token);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DuraktanGecenHatlar", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<DuraktanGecenHatlar[]> DuraktanGecenHatlarAsync(string token);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HatBilgisi", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<HatGuzergahDuraklar> HatBilgisiAsync(string token, string hat_no);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AktifHatlarBilgisi", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<HatGuzergahDuraklar[]> AktifHatlarBilgisiAsync(string token);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class Hat
{
    
    private string hAT_TIPIField;
    
    private string hAT_NOField;
    
    private string hAT_ADIField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string HAT_TIPI
    {
        get
        {
            return this.hAT_TIPIField;
        }
        set
        {
            this.hAT_TIPIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string HAT_NO
    {
        get
        {
            return this.hAT_NOField;
        }
        set
        {
            this.hAT_NOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string HAT_ADI
    {
        get
        {
            return this.hAT_ADIField;
        }
        set
        {
            this.hAT_ADIField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class HatDurak
{
    
    private string dURAK_NOField;
    
    private string dURAK_SIRASIField;
    
    private string dURAK_ADIField;
    
    private string lATField;
    
    private string lNGField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string DURAK_NO
    {
        get
        {
            return this.dURAK_NOField;
        }
        set
        {
            this.dURAK_NOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string DURAK_SIRASI
    {
        get
        {
            return this.dURAK_SIRASIField;
        }
        set
        {
            this.dURAK_SIRASIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string DURAK_ADI
    {
        get
        {
            return this.dURAK_ADIField;
        }
        set
        {
            this.dURAK_ADIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string LAT
    {
        get
        {
            return this.lATField;
        }
        set
        {
            this.lATField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string LNG
    {
        get
        {
            return this.lNGField;
        }
        set
        {
            this.lNGField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class HatGuzergahDuraklar
{
    
    private string hAT_TIPIField;
    
    private string hAT_NOField;
    
    private string hAT_ADIField;
    
    private string gUZERGAHField;
    
    private HatDurak[] dURAKLARField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string HAT_TIPI
    {
        get
        {
            return this.hAT_TIPIField;
        }
        set
        {
            this.hAT_TIPIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string HAT_NO
    {
        get
        {
            return this.hAT_NOField;
        }
        set
        {
            this.hAT_NOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string HAT_ADI
    {
        get
        {
            return this.hAT_ADIField;
        }
        set
        {
            this.hAT_ADIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string GUZERGAH
    {
        get
        {
            return this.gUZERGAHField;
        }
        set
        {
            this.gUZERGAHField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
    public HatDurak[] DURAKLAR
    {
        get
        {
            return this.dURAKLARField;
        }
        set
        {
            this.dURAKLARField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class DuraktanGecenHatlar
{
    
    private string dURAK_NOField;
    
    private string dURAKTAN_GECEN_HATLARField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string DURAK_NO
    {
        get
        {
            return this.dURAK_NOField;
        }
        set
        {
            this.dURAK_NOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string DURAKTAN_GECEN_HATLAR
    {
        get
        {
            return this.dURAKTAN_GECEN_HATLARField;
        }
        set
        {
            this.dURAKTAN_GECEN_HATLARField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class MasterDurak
{
    
    private string dURAK_NOField;
    
    private string dURAK_ADIField;
    
    private string dURAKTAN_GECEN_HATLARField;
    
    private string lATField;
    
    private string lNGField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string DURAK_NO
    {
        get
        {
            return this.dURAK_NOField;
        }
        set
        {
            this.dURAK_NOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string DURAK_ADI
    {
        get
        {
            return this.dURAK_ADIField;
        }
        set
        {
            this.dURAK_ADIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string DURAKTAN_GECEN_HATLAR
    {
        get
        {
            return this.dURAKTAN_GECEN_HATLARField;
        }
        set
        {
            this.dURAKTAN_GECEN_HATLARField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string LAT
    {
        get
        {
            return this.lATField;
        }
        set
        {
            this.lATField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string LNG
    {
        get
        {
            return this.lNGField;
        }
        set
        {
            this.lNGField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
public interface HatDurakBilgiServisSoapChannel : HatDurakBilgiServisSoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
public partial class HatDurakBilgiServisSoapClient : System.ServiceModel.ClientBase<HatDurakBilgiServisSoap>, HatDurakBilgiServisSoap
{
    
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public HatDurakBilgiServisSoapClient(EndpointConfiguration endpointConfiguration) : 
            base(HatDurakBilgiServisSoapClient.GetBindingForEndpoint(endpointConfiguration), HatDurakBilgiServisSoapClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public HatDurakBilgiServisSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(HatDurakBilgiServisSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public HatDurakBilgiServisSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(HatDurakBilgiServisSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public HatDurakBilgiServisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Threading.Tasks.Task<Hat[]> AktifHatlarAsync(string token)
    {
        return base.Channel.AktifHatlarAsync(token);
    }
    
    public System.Threading.Tasks.Task<MasterDurak[]> AktifDuraklarAsync(string token)
    {
        return base.Channel.AktifDuraklarAsync(token);
    }
    
    public System.Threading.Tasks.Task<DuraktanGecenHatlar[]> DuraktanGecenHatlarAsync(string token)
    {
        return base.Channel.DuraktanGecenHatlarAsync(token);
    }
    
    public System.Threading.Tasks.Task<HatGuzergahDuraklar> HatBilgisiAsync(string token, string hat_no)
    {
        return base.Channel.HatBilgisiAsync(token, hat_no);
    }
    
    public System.Threading.Tasks.Task<HatGuzergahDuraklar[]> AktifHatlarBilgisiAsync(string token)
    {
        return base.Channel.AktifHatlarBilgisiAsync(token);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.HatDurakBilgiServisSoap))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
            return result;
        }
        if ((endpointConfiguration == EndpointConfiguration.HatDurakBilgiServisSoap12))
        {
            System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
            System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
            textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
            result.Elements.Add(textBindingElement);
            System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
            httpsBindingElement.AllowCookies = true;
            httpsBindingElement.MaxBufferSize = int.MaxValue;
            httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
            result.Elements.Add(httpsBindingElement);
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.HatDurakBilgiServisSoap))
        {
            return new System.ServiceModel.EndpointAddress("https://baskentmblws.ego.gov.tr/WSDL/IMAR_CBS/HatDurakBilgiServis.asmx");
        }
        if ((endpointConfiguration == EndpointConfiguration.HatDurakBilgiServisSoap12))
        {
            return new System.ServiceModel.EndpointAddress("https://baskentmblws.ego.gov.tr/WSDL/IMAR_CBS/HatDurakBilgiServis.asmx");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    public enum EndpointConfiguration
    {
        
        HatDurakBilgiServisSoap,
        
        HatDurakBilgiServisSoap12,
    }
}
