import { describe,expect,it } from 'vitest'
import { ArcGisFeatureHydrationLifecyclePolicy,type ArcGisFeatureHydrationBudget,type ArcGisFeatureHydrationRequest } from './ArcGisFeatureHydrationLifecyclePolicy'
const budget:ArcGisFeatureHydrationBudget={maxJobs:6,maxJobsPerLayer:4,maxLoading:2,maxReady:3,maxObjectIdsPerJob:100,maxEstimatedBytesPerJob:10000,maxAggregateReadyBytes:20000,queueTtlMs:100,loadLeaseMs:200,readyTtlMs:300}
const request=(o:Partial<ArcGisFeatureHydrationRequest>={}):ArcGisFeatureHydrationRequest=>({layerId:'layer-1',jobId:'job-1',revision:1,intent:'visible',requestedAt:10,objectIdCount:20,fieldCount:5,estimatedBytes:1000,...o})
const ready=(p:ArcGisFeatureHydrationLifecyclePolicy,job='job-1',bytes=1000,now=30)=>{p.takeNext(20);return p.complete('layer-1',job,1,20,bytes,now)}
describe('ArcGisFeatureHydrationLifecyclePolicy',()=>{
 it('prioritizes hydration intent deterministically',()=>{const p=new ArcGisFeatureHydrationLifecyclePolicy(budget);p.enqueue(request({jobId:'b',intent:'background',requestedAt:1}));p.enqueue(request({jobId:'v',requestedAt:2}));p.enqueue(request({jobId:'i',intent:'interactive',requestedAt:3}));expect(p.takeNext(20)?.jobId).toBe('i');expect(p.takeNext(21)?.jobId).toBe('v')})
 it('bounds global and per-layer cardinality',()=>{const p=new ArcGisFeatureHydrationLifecyclePolicy({...budget,maxJobs:2,maxJobsPerLayer:1,maxLoading:1,maxReady:1});expect(p.enqueue(request({jobId:'a'}))).toBe(true);expect(p.enqueue(request({jobId:'b'}))).toBe(false);expect(p.enqueue(request({layerId:'layer-2',jobId:'c'}))).toBe(true);expect(p.enqueue(request({layerId:'layer-3',jobId:'d'}))).toBe(false)})
 it('atomically admits a superseding revision at full capacity',()=>{const p=new ArcGisFeatureHydrationLifecyclePolicy({...budget,maxJobs:1,maxJobsPerLayer:1,maxLoading:1,maxReady:1});p.enqueue(request());expect(p.enqueue(request({revision:2,requestedAt:11}))).toBe(true);expect(p.snapshot()[0]?.revision).toBe(2)})
 it('preserves ownership when replacement admission fails',()=>{const p=new ArcGisFeatureHydrationLifecyclePolicy({...budget,maxJobs:1,maxJobsPerLayer:1,maxLoading:1,maxReady:1});p.enqueue(request());expect(p.enqueue(request({revision:2,objectIdCount:101}))).toBe(false);expect(p.snapshot()[0]?.revision).toBe(1)})
 it('bounds loading concurrency',()=>{const p=new ArcGisFeatureHydrationLifecyclePolicy({...budget,maxLoading:1});p.enqueue(request({jobId:'a'}));p.enqueue(request({jobId:'b'}));expect(p.takeNext(20)?.jobId).toBe('a');expect(p.takeNext(20)).toBeUndefined()})
 it('reconciles actual ready residency',()=>{const p=new ArcGisFeatureHydrationLifecyclePolicy(budget);p.enqueue(request());expect(ready(p,'job-1',1234)).toBe(true);expect(p.snapshot()[0]).toMatchObject({phase:'ready',featureCount:20,actualBytes:1234,expiresAt:330})})
 it('rejects impossible response shape and late completion',()=>{const p=new ArcGisFeatureHydrationLifecyclePolicy(budget);p.enqueue(request({objectIdCount:5}));p.takeNext(20);expect(p.complete('layer-1','job-1',1,6,100,30)).toBe(false);p.enqueue(request({jobId:'late'}));p.takeNext(31);expect(p.complete('layer-1','late',1,1,100,231)).toBe(false)})
 it('bounds aggregate ready bytes',()=>{const p=new ArcGisFeatureHydrationLifecyclePolicy({...budget,maxAggregateReadyBytes:10000});p.enqueue(request({jobId:'a'}));p.enqueue(request({jobId:'b'}));p.takeNext(20);p.takeNext(20);expect(p.complete('layer-1','a',1,1,7000,30)).toBe(true);expect(p.complete('layer-1','b',1,1,4000,30)).toBe(false)})
 it('purges expired ready bytes before completion admission',()=>{const p=new ArcGisFeatureHydrationLifecyclePolicy({...budget,maxAggregateReadyBytes:10000,readyTtlMs:50});p.enqueue(request({jobId:'old'}));p.takeNext(20);expect(p.complete('layer-1','old',1,1,9000,30)).toBe(true);p.enqueue(request({jobId:'fresh',requestedAt:40}));p.takeNext(70);expect(p.complete('layer-1','fresh',1,1,9000,80)).toBe(true);expect(p.snapshot().map(x=>x.jobId)).toEqual(['fresh'])})
 it('purges expired ready cardinality before completion admission',()=>{const p=new ArcGisFeatureHydrationLifecyclePolicy({...budget,maxReady:1,readyTtlMs:50});p.enqueue(request({jobId:'old'}));p.takeNext(20);p.complete('layer-1','old',1,1,100,30);p.enqueue(request({jobId:'fresh',requestedAt:40}));p.takeNext(70);expect(p.complete('layer-1','fresh',1,1,100,80)).toBe(true)})
 it('consumes and cancels only matching revisions',()=>{const p=new ArcGisFeatureHydrationLifecyclePolicy(budget);p.enqueue(request());ready(p);expect(p.consume('layer-1','job-1',2)).toBe(false);expect(p.consume('layer-1','job-1',1)).toBe(true);p.enqueue(request({jobId:'next'}));expect(p.cancel('layer-1','next',1)).toBe(true)})
 it('invalidates stale jobs monotonically',()=>{const p=new ArcGisFeatureHydrationLifecyclePolicy(budget);p.enqueue(request({jobId:'a'}));p.enqueue(request({jobId:'b'}));expect(p.invalidateLayer('layer-1',2)).toBe(2);expect(p.enqueue(request({jobId:'stale'}))).toBe(false);expect(p.enqueue(request({jobId:'fresh',revision:2}))).toBe(true)})
 it('expires ownership at exact boundaries',()=>{const p=new ArcGisFeatureHydrationLifecyclePolicy(budget);p.enqueue(request());expect(p.expire(109)).toBe(0);expect(p.expire(110)).toBe(1)})
 it('releases layer revision ownership',()=>{const p=new ArcGisFeatureHydrationLifecyclePolicy(budget);p.enqueue(request({revision:3}));expect(p.releaseLayer('layer-1')).toBe(1);expect(p.enqueue(request({revision:1}))).toBe(true)})
 it('returns detached payload-free snapshots',()=>{const p=new ArcGisFeatureHydrationLifecyclePolicy(budget);p.enqueue(request());const s=p.snapshot()[0]!;s.jobId='mutated';expect(p.snapshot()[0]?.jobId).toBe('job-1');expect(JSON.stringify(p.snapshot())).not.toMatch(/geometry|attributes|credential/)})
 it('rejects malformed identifiers and scalars',()=>{const p=new ArcGisFeatureHydrationLifecyclePolicy(budget);expect(()=>p.enqueue(request({jobId:'bad:id'}))).toThrow();expect(()=>p.enqueue(request({revision:0}))).toThrow();expect(()=>p.enqueue(request({requestedAt:Number.NaN}))).toThrow()})
 it('validates budget relationships fail closed',()=>{expect(()=>new ArcGisFeatureHydrationLifecyclePolicy({...budget,maxJobsPerLayer:7})).toThrow(RangeError);expect(()=>new ArcGisFeatureHydrationLifecyclePolicy({...budget,maxAggregateReadyBytes:9999})).toThrow(RangeError)})
 it('fails closed after idempotent disposal',()=>{const p=new ArcGisFeatureHydrationLifecyclePolicy(budget);p.enqueue(request());p.dispose();p.dispose();expect(()=>p.snapshot()).toThrow(/disposed/)})
})
