import { describe, expect, it } from 'vitest'
import { ArcGisSpatialQueryWindowLifecyclePolicy, type SpatialQueryWindowBudget, type SpatialQueryWindowKey } from './ArcGisSpatialQueryWindowLifecyclePolicy'

const budget: SpatialQueryWindowBudget = { maxWindows: 6, maxWindowsPerLayer: 4, maxResident: 3, maxResidentBytes: 3000, ttlMs: 100 }
const key = (layerId='parcels', revision=1, level=12, column=100, row=200): SpatialQueryWindowKey => ({ layerId, revision, level, column, row })
const policy = (custom: Partial<SpatialQueryWindowBudget> = {}) => new ArcGisSpatialQueryWindowLifecyclePolicy({ ...budget, ...custom })

describe('ArcGisSpatialQueryWindowLifecyclePolicy', () => {
  it('rejects invalid budgets', () => { expect(() => policy({ maxWindows: 0 })).toThrow(); expect(() => policy({ maxWindowsPerLayer: 7 })).toThrow(); expect(() => policy({ maxResident: 7 })).toThrow(); expect(() => policy({ ttlMs: 0 })).toThrow() })
  it('requires a current layer revision', () => { const p=policy(); expect(p.admit('a',key(),'visible',500,0)).toBe(false); expect(p.setRevision('parcels',1)).toBe(0); expect(p.admit('a',key(),'visible',500,0)).toBe(true) })
  it('keeps revisions monotonic and invalidates stale windows', () => { const p=policy(); p.setRevision('parcels',1); p.admit('a',key(),'visible',500,0); expect(p.setRevision('parcels',2)).toBe(1); expect(p.setRevision('parcels',1)).toBe(-1); expect(p.snapshot().windows).toBe(0) })
  it('rejects duplicate ids and duplicate spatial coordinates', () => { const p=policy(); p.setRevision('parcels',1); expect(p.admit('a',key(),'visible',500,0)).toBe(true); expect(p.admit('a',key('parcels',1,12,101,200),'visible',500,1)).toBe(false); expect(p.admit('b',key(),'visible',500,1)).toBe(false) })
  it('enforces per-layer cardinality', () => { const p=policy({maxWindowsPerLayer:2,maxResident:3}); p.setRevision('p',1); expect(p.admit('a',key('p',1,1,1,1),'visible',100,0)).toBe(true); expect(p.admit('b',key('p',1,1,2,1),'visible',100,0)).toBe(true); expect(p.admit('c',key('p',1,1,3,1),'visible',100,0)).toBe(false) })
  it('evicts lower-intent windows before interactive work', () => { const p=policy({maxResident:2}); p.setRevision('p',1); p.admit('prefetch',key('p',1,1,1,1),'prefetch',500,0); p.admit('visible',key('p',1,1,2,1),'visible',500,1); expect(p.admit('interactive',key('p',1,1,3,1),'interactive',500,2)).toBe(true); expect(p.consume('prefetch',1)).toBeNull(); expect(p.consume('interactive',1)?.column).toBe(3) })
  it('evicts least recently touched ties deterministically', () => { const p=policy({maxResident:2}); p.setRevision('p',1); p.admit('old',key('p',1,1,1,1),'visible',500,0); p.admit('newer',key('p',1,1,2,1),'visible',500,1); expect(p.admit('new',key('p',1,1,3,1),'visible',500,2)).toBe(true); expect(p.consume('old',1)).toBeNull() })
  it('enforces aggregate resident bytes', () => { const p=policy({maxResidentBytes:1000}); p.setRevision('p',1); p.admit('a',key('p',1,1,1,1),'prefetch',600,0); expect(p.admit('b',key('p',1,1,2,1),'interactive',600,1)).toBe(true); expect(p.consume('a',1)).toBeNull(); expect(p.snapshot().bytes).toBe(600) })
  it('rejects a single window larger than aggregate capacity', () => { const p=policy({maxResidentBytes:1000}); p.setRevision('p',1); expect(p.admit('a',key('p'), 'visible',1001,0)).toBe(false) })
  it('touch extends ttl only for a live revision', () => { const p=policy(); p.setRevision('p',1); p.admit('a',key('p'),'visible',500,0); expect(p.touch('a',1,50)).toBe(true); expect(p.expire(100)).toBe(0); expect(p.expire(150)).toBe(1) })
  it('does not resurrect an already expired window via touch', () => { const p=policy(); p.setRevision('p',1); p.admit('a',key('p'),'visible',500,0); expect(p.touch('a',1,100)).toBe(false) })
  it('consumes only matching current revisions', () => { const p=policy(); p.setRevision('p',1); p.admit('a',key('p'),'visible',500,0); expect(p.consume('a',2)).toBeNull(); expect(p.consume('a',1)).toEqual({layerId:'p',revision:1,level:12,column:100,row:200,bytes:500}) })
  it('expires windows at the ttl boundary', () => { const p=policy(); p.setRevision('p',1); p.admit('a',key('p'),'visible',500,0); expect(p.expire(99)).toBe(0); expect(p.expire(100)).toBe(1) })
  it('releases one layer without disturbing another', () => { const p=policy(); p.setRevision('a',1); p.setRevision('b',1); p.admit('a1',key('a'),'visible',100,0); p.admit('b1',key('b'),'visible',100,0); expect(p.releaseLayer('a')).toBe(1); expect(p.snapshot()).toEqual({layers:1,windows:1,bytes:100}) })
  it('returns frozen aggregate snapshots', () => { const p=policy(); p.setRevision('p',1); p.admit('a',key('p'),'visible',123,0); const snapshot=p.snapshot(); expect(snapshot).toEqual({layers:1,windows:1,bytes:123}); expect(Object.isFrozen(snapshot)).toBe(true) })
  it('builds deterministic payload-free fingerprints', () => { const p=policy(); p.setRevision('b',1); p.setRevision('a',1); p.admit('b',key('b',1,2,2,2),'prefetch',100,0); p.admit('a',key('a',1,1,1,1),'interactive',100,0); expect(p.fingerprint()).toBe('a:1:1/1/1:interactive|b:1:2/2/2:prefetch') })
  it('validates scalar identifiers, coordinates, bytes and clocks', () => { const p=policy(); p.setRevision('p',1); expect(()=>p.admit('',key('p'),'visible',1,0)).toThrow(); expect(()=>p.admit('a',key('p',1,-1,0,0),'visible',1,0)).toThrow(); expect(()=>p.admit('a',key('p'),'visible',0,0)).toThrow(); expect(()=>p.admit('a',key('p'),'visible',1,-1)).toThrow() })
  it('rejects unknown intent values', () => { const p=policy(); p.setRevision('p',1); expect(()=>p.admit('a',key('p'),'other' as never,1,0)).toThrow() })
  it('disposes terminally and idempotently', () => { const p=policy(); p.setRevision('p',1); p.admit('a',key('p'),'visible',100,0); p.dispose(); p.dispose(); expect(()=>p.snapshot()).toThrow(/disposed/); expect(()=>p.admit('b',key('p'),'visible',100,1)).toThrow(/disposed/) })
})
