import { describe, expect, it } from 'vitest';
import { ArcGisCoordinateTransformCoordinator } from './ArcGisCoordinateTransformCoordinator';
const policy={maxTransforms:2,maxIdLength:32,maxFailureCodeLength:32,maxAbsCoordinate:1_000_000,retentionMs:100,maxClockSkewMs:5};
const point=(x=1,y=2,z:number|null=null)=>({x,y,z});
describe('ArcGisCoordinateTransformCoordinator',()=>{
 it('tracks a completed transform without retaining ArcGIS runtime objects',()=>{const c=new ArcGisCoordinateTransformCoordinator(policy);expect(c.create({id:'a',sourceWkid:4326,targetWkid:3857,point:point()},10).status).toBe('queued');c.transition('a','running',11);const done=c.transition('a','completed',12,{output:point(3,4,5)});expect(done.output).toEqual(point(3,4,5));expect(done.revision).toBe(3);expect(Object.isFrozen(done)).toBe(true)});
 it('fails closed on malformed coordinates and terminal payloads',()=>{const c=new ArcGisCoordinateTransformCoordinator(policy);expect(()=>c.create({id:'bad',sourceWkid:4326,targetWkid:3857,point:point(Infinity)},1)).toThrow();c.create({id:'a',sourceWkid:4326,targetWkid:3857,point:point()},1);expect(()=>c.transition('a','completed',2,{output:point()})).toThrow();c.transition('a','running',2);expect(()=>c.transition('a','failed',3)).toThrow();expect(()=>c.transition('a','completed',3,{output:point(2_000_000)})).toThrow()});
 it('evicts deterministically and prunes terminal retention',()=>{const c=new ArcGisCoordinateTransformCoordinator(policy);c.create({id:'a',sourceWkid:4326,targetWkid:3857,point:point()},1);c.transition('a','running',2);c.transition('a','completed',3,{output:point()});c.create({id:'b',sourceWkid:4326,targetWkid:3857,point:point()},4);c.create({id:'c',sourceWkid:4326,targetWkid:3857,point:point()},5);expect(c.snapshot(5).transforms.map(x=>x.id)).toEqual(['b','c']);c.transition('b','running',6);c.transition('b','cancelled',7);expect(c.snapshot(108).transforms.map(x=>x.id)).toEqual(['c'])});
 it('rejects stale updates',()=>{const c=new ArcGisCoordinateTransformCoordinator(policy);c.create({id:'a',sourceWkid:4326,targetWkid:3857,point:point()},100);expect(()=>c.transition('a','running',94)).toThrow('stale')});
 it('restores atomically and rejects future, duplicate and dangling active state',()=>{const c=new ArcGisCoordinateTransformCoordinator(policy);c.create({id:'safe',sourceWkid:4326,targetWkid:3857,point:point()},10);const before=c.snapshot(10);const state=before.transforms[0]!;expect(()=>c.restore({activeId:'safe',transforms:[{...state,updatedAtMs:999}]},20)).toThrow('future');expect(c.snapshot(20).transforms.map(x=>x.id)).toEqual(['safe']);expect(()=>c.restore({activeId:null,transforms:[state,state]},20)).toThrow('duplicate');expect(()=>c.restore({activeId:'missing',transforms:[state]},20)).toThrow('active transform is missing')});
 it('validates restored terminal payload integrity',()=>{const c=new ArcGisCoordinateTransformCoordinator(policy);const base={id:'x',sourceWkid:4326,targetWkid:3857,status:'completed' as const,createdAtMs:1,updatedAtMs:2,revision:2,input:point(),output:null,failureCode:null};expect(()=>c.restore({activeId:null,transforms:[base]},3)).toThrow('invalid payload')});
 it('disposes idempotently and blocks later use',()=>{const c=new ArcGisCoordinateTransformCoordinator(policy);c.dispose();c.dispose();expect(()=>c.snapshot(1)).toThrow('disposed')});
});
