import { describe, expect, it } from 'vitest'
import { ArcGisSceneLayerPrefetchLifecyclePolicy, type ArcGisScenePrefetchBudget, type ArcGisScenePrefetchRequest } from './ArcGisSceneLayerPrefetchLifecyclePolicy'

const budget:ArcGisScenePrefetchBudget={maxTiles:6,maxTilesPerView:4,maxLoading:2,maxResident:3,maxTrianglesPerTile:1000,maxEstimatedBytesPerTile:10000,maxAggregateResidentBytes:20000,queueTtlMs:100,loadLeaseMs:200,residentTtlMs:300}
const request=(overrides:Partial<ArcGisScenePrefetchRequest>={}):ArcGisScenePrefetchRequest=>({viewId:'view-1',layerId:'scene-1',tileId:'tile-1',revision:1,intent:'navigation',requestedAt:10,lod:4,estimatedTriangles:100,estimatedBytes:1000,...overrides})
const resident=(policy:ArcGisSceneLayerPrefetchLifecyclePolicy,id='tile-1',bytes=1000)=>{policy.takeNext(20);return policy.complete('view-1','scene-1',id,1,100,bytes,30)}

describe('ArcGisSceneLayerPrefetchLifecyclePolicy',()=>{
  it('prioritizes visible, navigation, background',()=>{const p=new ArcGisSceneLayerPrefetchLifecyclePolicy(budget);p.enqueue(request({tileId:'b',intent:'background'}));p.enqueue(request({tileId:'n',intent:'navigation'}));p.enqueue(request({tileId:'v',intent:'visible'}));expect(p.takeNext(20)?.tileId).toBe('v');expect(p.takeNext(20)?.tileId).toBe('n')})
  it('uses higher lod then request order as deterministic ties',()=>{const p=new ArcGisSceneLayerPrefetchLifecyclePolicy(budget);p.enqueue(request({tileId:'low',lod:2,requestedAt:1}));p.enqueue(request({tileId:'high',lod:8,requestedAt:2}));expect(p.takeNext(20)?.tileId).toBe('high')})
  it('bounds global and per-view cardinality',()=>{const p=new ArcGisSceneLayerPrefetchLifecyclePolicy({...budget,maxTiles:2,maxTilesPerView:1,maxLoading:1,maxResident:1});expect(p.enqueue(request({tileId:'a'}))).toBe(true);expect(p.enqueue(request({tileId:'b'}))).toBe(false);expect(p.enqueue(request({viewId:'view-2',tileId:'c'}))).toBe(true);expect(p.enqueue(request({viewId:'view-3',tileId:'d'}))).toBe(false)})
  it('bounds admission estimates',()=>{const p=new ArcGisSceneLayerPrefetchLifecyclePolicy(budget);expect(p.enqueue(request({estimatedTriangles:1001}))).toBe(false);expect(p.enqueue(request({estimatedBytes:10001}))).toBe(false)})
  it('bounds concurrent loads',()=>{const p=new ArcGisSceneLayerPrefetchLifecyclePolicy({...budget,maxLoading:1});p.enqueue(request({tileId:'a'}));p.enqueue(request({tileId:'b'}));expect(p.takeNext(20)?.tileId).toBe('a');expect(p.takeNext(20)).toBeUndefined()})
  it('records actual residency',()=>{const p=new ArcGisSceneLayerPrefetchLifecyclePolicy(budget);p.enqueue(request());expect(resident(p)).toBe(true);expect(p.snapshot()[0]).toMatchObject({phase:'resident',actualBytes:1000,actualTriangles:100,expiresAt:330})})
  it('rejects late completion',()=>{const p=new ArcGisSceneLayerPrefetchLifecyclePolicy(budget);p.enqueue(request());p.takeNext(20);expect(p.complete('view-1','scene-1','tile-1',1,100,100,220)).toBe(false);expect(p.snapshot()).toHaveLength(0)})
  it('rejects oversized completion',()=>{const p=new ArcGisSceneLayerPrefetchLifecyclePolicy(budget);p.enqueue(request());p.takeNext(20);expect(p.complete('view-1','scene-1','tile-1',1,1001,100,30)).toBe(false)})
  it('bounds aggregate resident bytes',()=>{const p=new ArcGisSceneLayerPrefetchLifecyclePolicy({...budget,maxAggregateResidentBytes:10000});p.enqueue(request({tileId:'a'}));p.enqueue(request({tileId:'b'}));p.takeNext(20);p.takeNext(20);expect(p.complete('view-1','scene-1','a',1,100,7000,30)).toBe(true);expect(p.complete('view-1','scene-1','b',1,100,4000,30)).toBe(false)})
  it('bounds resident cardinality',()=>{const p=new ArcGisSceneLayerPrefetchLifecyclePolicy({...budget,maxResident:1});p.enqueue(request({tileId:'a'}));p.enqueue(request({tileId:'b'}));p.takeNext(20);p.takeNext(20);expect(p.complete('view-1','scene-1','a',1,100,100,30)).toBe(true);expect(p.complete('view-1','scene-1','b',1,100,100,30)).toBe(false)})
  it('touch extends live residency only',()=>{const p=new ArcGisSceneLayerPrefetchLifecyclePolicy(budget);p.enqueue(request());resident(p);expect(p.touch('view-1','scene-1','tile-1',1,40)).toBe(true);expect(p.snapshot()[0]?.expiresAt).toBe(340);expect(p.touch('view-1','scene-1','tile-1',2,50)).toBe(false)})
  it('consume releases resident ownership',()=>{const p=new ArcGisSceneLayerPrefetchLifecyclePolicy(budget);p.enqueue(request());resident(p);expect(p.consume('view-1','scene-1','tile-1',2)).toBe(false);expect(p.consume('view-1','scene-1','tile-1',1)).toBe(true);expect(p.snapshot()).toHaveLength(0)})
  it('cancel requires matching revision',()=>{const p=new ArcGisSceneLayerPrefetchLifecyclePolicy(budget);p.enqueue(request());expect(p.cancel('view-1','scene-1','tile-1',2)).toBe(false);expect(p.cancel('view-1','scene-1','tile-1',1)).toBe(true)})
  it('rejects stale and replaces newer duplicate revision',()=>{const p=new ArcGisSceneLayerPrefetchLifecyclePolicy(budget);expect(p.enqueue(request({revision:2}))).toBe(true);expect(p.enqueue(request({revision:1}))).toBe(false);expect(p.enqueue(request({revision:3}))).toBe(true);expect(p.snapshot()[0]?.revision).toBe(3)})
  it('invalidates stale view work',()=>{const p=new ArcGisSceneLayerPrefetchLifecyclePolicy(budget);p.enqueue(request({tileId:'a'}));p.enqueue(request({tileId:'b'}));expect(p.invalidateView('view-1',2)).toBe(2);expect(p.enqueue(request({tileId:'old',revision:1}))).toBe(false);expect(p.enqueue(request({tileId:'new',revision:2}))).toBe(true)})
  it('does not regress watermark',()=>{const p=new ArcGisSceneLayerPrefetchLifecyclePolicy(budget);p.enqueue(request({revision:3}));expect(p.invalidateView('view-1',2)).toBe(0);expect(p.enqueue(request({tileId:'old',revision:2}))).toBe(false)})
  it('expires queue and resident at exact boundaries',()=>{const q=new ArcGisSceneLayerPrefetchLifecyclePolicy(budget);q.enqueue(request());expect(q.expire(109)).toBe(0);expect(q.expire(110)).toBe(1);const r=new ArcGisSceneLayerPrefetchLifecyclePolicy(budget);r.enqueue(request());resident(r);expect(r.expire(329)).toBe(0);expect(r.expire(330)).toBe(1)})
  it('releases a layer without affecting siblings',()=>{const p=new ArcGisSceneLayerPrefetchLifecyclePolicy(budget);p.enqueue(request({tileId:'a'}));p.enqueue(request({layerId:'scene-2',tileId:'b'}));expect(p.releaseLayer('view-1','scene-1')).toBe(1);expect(p.snapshot()[0]?.layerId).toBe('scene-2')})
  it('releaseView resets revision watermark',()=>{const p=new ArcGisSceneLayerPrefetchLifecyclePolicy(budget);p.enqueue(request({revision:3}));expect(p.releaseView('view-1')).toBe(1);expect(p.enqueue(request({tileId:'fresh',revision:1}))).toBe(true)})
  it('normalizes identifiers and rejects unsafe ids',()=>{const p=new ArcGisSceneLayerPrefetchLifecyclePolicy(budget);expect(p.enqueue(request({viewId:' view ',layerId:' layer ',tileId:' tile '}))).toBe(true);expect(p.snapshot()[0]).toMatchObject({viewId:'view',layerId:'layer',tileId:'tile'});expect(p.enqueue(request({tileId:'bad|tile'}))).toBe(false)})
  it('rejects invalid numerics',()=>{const p=new ArcGisSceneLayerPrefetchLifecyclePolicy(budget);expect(p.enqueue(request({revision:0}))).toBe(false);expect(p.enqueue(request({requestedAt:Number.NaN}))).toBe(false);expect(p.enqueue(request({lod:-1}))).toBe(false)})
  it('returns detached snapshots',()=>{const p=new ArcGisSceneLayerPrefetchLifecyclePolicy(budget);p.enqueue(request());const s=p.snapshot()[0]!;s.tileId='mutated';expect(p.snapshot()[0]?.tileId).toBe('tile-1')})
  it('fingerprint is scalar and deterministic',()=>{const p=new ArcGisSceneLayerPrefetchLifecyclePolicy(budget);p.enqueue(request());expect(p.fingerprint()).toContain('view-1:scene-1:tile-1:1:queued:navigation:4');expect(p.fingerprint()).not.toContain('[object Object]')})
  it('validates budget construction fail closed',()=>{expect(()=>new ArcGisSceneLayerPrefetchLifecyclePolicy({...budget,maxTiles:0})).toThrow(RangeError);expect(()=>new ArcGisSceneLayerPrefetchLifecyclePolicy({...budget,maxTiles:2,maxTilesPerView:3})).toThrow(RangeError)})
  it('dispose clears all ownership',()=>{const p=new ArcGisSceneLayerPrefetchLifecyclePolicy(budget);p.enqueue(request());p.dispose();expect(p.snapshot()).toHaveLength(0)})
})