export type ArcGisViewMode='2d'|'3d'
export type ArcGisLodMode='hidden'|'cluster'|'feature'|'detail'
export interface ArcGisLodBand{readonly id:string;readonly minScale:number;readonly maxScale:number;readonly mode:ArcGisLodMode;readonly maxFeatures:number;readonly maxVertices:number;readonly maxGpuBytes:number;readonly clusterRadius?:number}
export interface ArcGisLodPolicyBudget{readonly maxBands:number;readonly maxFeatures:number;readonly maxVertices:number;readonly maxGpuBytes:number;readonly maxClusterRadius:number}
export interface ArcGisLodDecision{readonly bandId:string;readonly mode:ArcGisLodMode;readonly scale:number;readonly maxFeatures:number;readonly maxVertices:number;readonly maxGpuBytes:number;readonly clusterRadius:number;readonly viewMode:ArcGisViewMode}
const MAX_SCALE=1_000_000_000
function integer(value:number,name:string,min:number,max:number){if(!Number.isSafeInteger(value)||value<min||value>max)throw new Error(`${name} must be an integer in [${min}, ${max}]`);return value}
function scale(value:number,name:string){if(!Number.isFinite(value)||value<0||value>MAX_SCALE)throw new Error(`${name} must be finite in [0, ${MAX_SCALE}]`);return value}
function identifier(value:string){const normalized=value.trim();if(!normalized||normalized.length>128||/[\u0000-\u001f\u007f]/.test(normalized))throw new Error('invalid LOD band id');return normalized}
function contains(band:ArcGisLodBand,currentScale:number){const withinMin=band.minScale===0||currentScale<=band.minScale;const withinMax=band.maxScale===0||currentScale>=band.maxScale;return withinMin&&withinMax}
export class ArcGisLodPolicy{
 private readonly bands:readonly ArcGisLodBand[]
 constructor(bands:readonly ArcGisLodBand[],budget:ArcGisLodPolicyBudget){const maxBands=integer(budget.maxBands,'maxBands',1,128),maxFeatures=integer(budget.maxFeatures,'maxFeatures',1,1_000_000),maxVertices=integer(budget.maxVertices,'maxVertices',1,50_000_000),maxGpuBytes=integer(budget.maxGpuBytes,'maxGpuBytes',1,1_073_741_824),maxClusterRadius=integer(budget.maxClusterRadius,'maxClusterRadius',0,512);if(!bands.length||bands.length>maxBands)throw new Error('LOD band budget exceeded');const seen=new Set<string>();const normalized=bands.map(input=>{const id=identifier(input.id);if(seen.has(id))throw new Error(`duplicate LOD band id:${id}`);seen.add(id);const minScale=scale(input.minScale,'minScale'),maxScaleValue=scale(input.maxScale,'maxScale');if(minScale>0&&maxScaleValue>0&&minScale<maxScaleValue)throw new Error(`invalid ArcGIS scale range:${id}`);const maxFeatureValue=integer(input.maxFeatures,'maxFeatures',0,maxFeatures),maxVertexValue=integer(input.maxVertices,'maxVertices',0,maxVertices),maxGpuValue=integer(input.maxGpuBytes,'maxGpuBytes',0,maxGpuBytes),clusterRadius=integer(input.clusterRadius??0,'clusterRadius',0,maxClusterRadius);if(input.mode==='cluster'&&clusterRadius===0)throw new Error(`cluster radius required:${id}`);if(input.mode==='hidden'&&(maxFeatureValue!==0||maxVertexValue!==0||maxGpuValue!==0))throw new Error(`hidden band must have zero resource budgets:${id}`);return Object.freeze({...input,id,minScale,maxScale:maxScaleValue,maxFeatures:maxFeatureValue,maxVertices:maxVertexValue,maxGpuBytes:maxGpuValue,clusterRadius})});normalized.sort((a,b)=>(b.minScale||MAX_SCALE)-(a.minScale||MAX_SCALE)||(b.maxScale||0)-(a.maxScale||0)||a.id.localeCompare(b.id));for(let i=0;i<normalized.length;i++)for(let j=i+1;j<normalized.length;j++){const a=normalized[i],b=normalized[j];const probe=Math.max(a.maxScale||0,b.maxScale||0,1);if(contains(a,probe)&&contains(b,probe))throw new Error(`overlapping LOD bands:${a.id}:${b.id}`)}this.bands=Object.freeze(normalized)}
 decide(currentScale:number,viewMode:ArcGisViewMode):ArcGisLodDecision{const normalizedScale=scale(currentScale,'scale');if(viewMode!=='2d'&&viewMode!=='3d')throw new Error('invalid view mode');const band=this.bands.find(candidate=>contains(candidate,normalizedScale));if(!band)return Object.freeze({bandId:'none',mode:'hidden',scale:normalizedScale,maxFeatures:0,maxVertices:0,maxGpuBytes:0,clusterRadius:0,viewMode});return Object.freeze({bandId:band.id,mode:band.mode,scale:normalizedScale,maxFeatures:band.maxFeatures,maxVertices:band.maxVertices,maxGpuBytes:band.maxGpuBytes,clusterRadius:band.clusterRadius??0,viewMode})}
 snapshot(){return this.bands}
}
