export type ArcGisGeometryKind='point'|'multipoint'|'polyline'|'polygon'|'extent'
export interface ArcGisSpatialReference{readonly wkid?:number;readonly latestWkid?:number;readonly wkt?:string}
export interface ArcGisExtent{readonly xmin:number;readonly ymin:number;readonly xmax:number;readonly ymax:number;readonly spatialReference:ArcGisSpatialReference}
export interface ArcGisSpatialIntegrityBudget{readonly maxCoordinates:number;readonly maxRings:number;readonly maxPaths:number;readonly maxParts:number;readonly maxWktLength:number;readonly maxAbsoluteCoordinate:number;readonly allowUnknownWkid:boolean}
export type ArcGisSpatialDecision={readonly accepted:true;readonly spatialReference:Readonly<ArcGisSpatialReference>;readonly extent?:Readonly<ArcGisExtent>}|{readonly accepted:false;readonly reason:string}
const KNOWN_WKIDS=new Set([4326,3857,102100,102113])
const finite=(value:number,name:string)=>{if(!Number.isFinite(value))throw new Error(`${name} must be finite`);return value}
const integer=(value:number,name:string,min:number,max:number)=>{if(!Number.isSafeInteger(value)||value<min||value>max)throw new Error(`${name} must be an integer in [${min}, ${max}]`);return value}
const cleanWkt=(value:string,max:number)=>{const normalized=value.trim().replace(/[\u0000-\u001f\u007f]/g,' ');if(!normalized||normalized.length>max)throw new Error(`wkt must contain 1..${max} characters`);return normalized}
export class ArcGisSpatialIntegrityPolicy{
 private readonly budget:ArcGisSpatialIntegrityBudget
 constructor(budget:ArcGisSpatialIntegrityBudget){this.budget=Object.freeze({...budget,maxCoordinates:integer(budget.maxCoordinates,'maxCoordinates',1,10_000_000),maxRings:integer(budget.maxRings,'maxRings',1,100_000),maxPaths:integer(budget.maxPaths,'maxPaths',1,100_000),maxParts:integer(budget.maxParts,'maxParts',1,100_000),maxWktLength:integer(budget.maxWktLength,'maxWktLength',1,1_000_000),maxAbsoluteCoordinate:finite(budget.maxAbsoluteCoordinate,'maxAbsoluteCoordinate')});if(this.budget.maxAbsoluteCoordinate<=0)throw new Error('maxAbsoluteCoordinate must be positive')}
 admitSpatialReference(input:ArcGisSpatialReference):ArcGisSpatialDecision{try{const wkid=input.wkid===undefined?undefined:integer(input.wkid,'wkid',1,Number.MAX_SAFE_INTEGER);const latestWkid=input.latestWkid===undefined?undefined:integer(input.latestWkid,'latestWkid',1,Number.MAX_SAFE_INTEGER);const wkt=input.wkt===undefined?undefined:cleanWkt(input.wkt,this.budget.maxWktLength);if(wkid===undefined&&latestWkid===undefined&&wkt===undefined)return Object.freeze({accepted:false,reason:'spatial-reference-identity-required'});const effective=latestWkid??wkid;if(effective!==undefined&&!this.budget.allowUnknownWkid&&!KNOWN_WKIDS.has(effective))return Object.freeze({accepted:false,reason:`unknown-wkid:${effective}`});return Object.freeze({accepted:true,spatialReference:Object.freeze({wkid,latestWkid,wkt})})}catch(error){return Object.freeze({accepted:false,reason:error instanceof Error?error.message:'invalid-spatial-reference'})}}
 admitExtent(input:ArcGisExtent):ArcGisSpatialDecision{const sr=this.admitSpatialReference(input.spatialReference);if(!sr.accepted)return sr;try{const xmin=this.coordinate(input.xmin,'xmin'),ymin=this.coordinate(input.ymin,'ymin'),xmax=this.coordinate(input.xmax,'xmax'),ymax=this.coordinate(input.ymax,'ymax');if(xmin>xmax||ymin>ymax)return Object.freeze({accepted:false,reason:'extent-minimum-exceeds-maximum'});return Object.freeze({accepted:true,spatialReference:sr.spatialReference,extent:Object.freeze({xmin,ymin,xmax,ymax,spatialReference:sr.spatialReference})})}catch(error){return Object.freeze({accepted:false,reason:error instanceof Error?error.message:'invalid-extent'})}}
 validateCardinality(kind:ArcGisGeometryKind,facts:{readonly coordinates:number;readonly rings?:number;readonly paths?:number;readonly parts?:number}):ArcGisSpatialDecision{try{const coordinates=integer(facts.coordinates,'coordinates',0,this.budget.maxCoordinates),rings=integer(facts.rings??0,'rings',0,this.budget.maxRings),paths=integer(facts.paths??0,'paths',0,this.budget.maxPaths),parts=integer(facts.parts??0,'parts',0,this.budget.maxParts);if(kind==='point'&&coordinates!==1)return Object.freeze({accepted:false,reason:'point-requires-one-coordinate'});if(kind==='multipoint'&&rings+paths!==0)return Object.freeze({accepted:false,reason:'multipoint-cannot-contain-rings-or-paths'});if(kind==='polyline'&&(paths<1||rings!==0))return Object.freeze({accepted:false,reason:'polyline-requires-paths-only'});if(kind==='polygon'&&(rings<1||paths!==0))return Object.freeze({accepted:false,reason:'polygon-requires-rings-only'});if(kind==='extent'&&coordinates!==2)return Object.freeze({accepted:false,reason:'extent-requires-two-corner-coordinates'});if(parts>coordinates&&coordinates>0)return Object.freeze({accepted:false,reason:'parts-exceed-coordinate-count'});return Object.freeze({accepted:true,spatialReference:Object.freeze({})})}catch(error){return Object.freeze({accepted:false,reason:error instanceof Error?error.message:'invalid-geometry-cardinality'})}}
 private coordinate(value:number,name:string){const result=finite(value,name);if(Math.abs(result)>this.budget.maxAbsoluteCoordinate)throw new Error(`${name} exceeds absolute coordinate budget`);return result}
}
