import { describe, expect, it } from 'vitest'
import { ArcGisSceneLodResidencyPolicy, type ArcGisSceneLodBudget } from './ArcGisSceneLodResidencyPolicy'

const budget: ArcGisSceneLodBudget = { maxTiles: 8, maxTilesPerView: 5, maxTilesPerLayer: 5, maxLoading: 2, maxLoadingPerView: 1, maxResident: 3, maxEstimatedTrianglesPerTile: 100, maxActualTrianglesPerTile: 200, maxResidentTriangles: 400, maxEstimatedBytesPerTile: 1000, maxActualBytesPerTile: 2000, maxResidentBytes: 4000, minLevel: 0, maxLevel: 12, queueTtlMs: 50, loadTtlMs: 50, residentTtlMs: 100 }
const request = (tileId: string, overrides = {}) => ({ tileId, viewId: 'view-1', layerId: 'scene-1', revision: 1, level: 4, intent: 'visible' as const, requestedAt: 10, estimatedTriangles: 50, estimatedBytes: 500, ...overrides })
const completion = (tileId: string, overrides = {}) => ({ tileId, viewId: 'view-1', layerId: 'scene-1', revision: 1, level: 4, actualTriangles: 80, actualBytes: 800, completedAt: 20, ...overrides })

describe('ArcGisSceneLodResidencyPolicy', () => {
  it('schedules interactive and finer LOD work deterministically', () => { const p = new ArcGisSceneLodResidencyPolicy(budget); p.enqueue(request('background', { viewId: 'v1', intent: 'background', level: 8 })); p.enqueue(request('visible', { viewId: 'v2', intent: 'visible', level: 4 })); p.enqueue(request('interactive-coarse', { viewId: 'v3', intent: 'interactive', level: 3 })); p.enqueue(request('interactive-fine', { viewId: 'v4', intent: 'interactive', level: 9 })); expect(p.takeNext(11)?.tileId).toBe('interactive-fine'); expect(p.takeNext(11)?.tileId).toBe('interactive-coarse') })
  it('enforces per-view loading concurrency without starving other views', () => { const p = new ArcGisSceneLodResidencyPolicy(budget); p.enqueue(request('a', { viewId: 'same', intent: 'interactive' })); p.enqueue(request('b', { viewId: 'same', intent: 'interactive' })); p.enqueue(request('c', { viewId: 'other', intent: 'visible' })); expect(p.takeNext(11)?.tileId).toBe('a'); expect(p.takeNext(11)?.tileId).toBe('c'); expect(p.takeNext(11)).toBeUndefined() })
  it('reconciles estimates to actual residency budgets', () => { const p = new ArcGisSceneLodResidencyPolicy(budget); p.enqueue(request('a')); p.takeNext(11); expect(p.complete(completion('a')).phase).toBe('resident') })
  it('rejects actual work exceeding per-tile budgets and releases authority', () => { const p = new ArcGisSceneLodResidencyPolicy(budget); p.enqueue(request('a')); p.takeNext(11); expect(() => p.complete(completion('a', { actualTriangles: 201 }))).toThrow('actual triangle budget exceeded'); expect(p.snapshot()).toHaveLength(0) })
  it('invalidates stale work when layer revision advances', () => { const p = new ArcGisSceneLodResidencyPolicy(budget); p.enqueue(request('old')); p.takeNext(11); expect(p.advanceLayerRevision('scene-1', 2)).toBe(1); expect(() => p.enqueue(request('stale'))).toThrow('stale layer revision') })
  it('rejects late completions and removes expired loading authority', () => { const p = new ArcGisSceneLodResidencyPolicy(budget); p.enqueue(request('a')); p.takeNext(11); expect(() => p.complete(completion('a', { completedAt: 62 }))).toThrow('LOD load lease expired') })
  it('sweeps expired residents before admitting fresh GPU residency', () => { const p = new ArcGisSceneLodResidencyPolicy({ ...budget, maxResident: 1, maxResidentTriangles: 100, maxResidentBytes: 1000 }); p.enqueue(request('old', { viewId: 'v1' })); p.takeNext(11); p.complete(completion('old')); p.enqueue(request('fresh', { viewId: 'v2', requestedAt: 130 })); p.takeNext(131); expect(p.complete(completion('fresh', { viewId: 'v2', completedAt: 132 })).phase).toBe('resident'); expect(p.snapshot().map(x => x.tileId)).toEqual(['fresh']) })
  it('touch extends only live resident leases', () => { const p = new ArcGisSceneLodResidencyPolicy(budget); p.enqueue(request('a')); p.takeNext(11); p.complete(completion('a')); expect(p.touch('a', 30)).toBe(true); expect(p.touch('a', 131)).toBe(false) })
  it('consume returns a detached immutable scalar view', () => { const p = new ArcGisSceneLodResidencyPolicy(budget); p.enqueue(request('a')); p.takeNext(11); p.complete(completion('a')); const consumed = p.consume('a'); expect(Object.isFrozen(consumed)).toBe(true); expect(p.snapshot()).toHaveLength(0) })
  it('tears down view and layer authority without retaining payload graphs', () => { const p = new ArcGisSceneLodResidencyPolicy(budget); p.enqueue(request('a', { viewId: 'v1' })); p.enqueue(request('b', { viewId: 'v2' })); expect(p.releaseView('v1')).toBe(1); expect(p.releaseLayer('scene-1')).toBe(1) })
  it('evicts lower-intent coarse residents under GPU pressure', () => { const p = new ArcGisSceneLodResidencyPolicy({ ...budget, maxResident: 1, maxResidentTriangles: 100, maxResidentBytes: 1000 }); p.enqueue(request('background', { viewId: 'v1', intent: 'background' })); p.takeNext(11); p.complete(completion('background')); p.enqueue(request('interactive', { viewId: 'v2', intent: 'interactive', requestedAt: 30 })); p.takeNext(31); p.complete(completion('interactive', { viewId: 'v2', completedAt: 32 })); expect(p.snapshot().map(x => x.tileId)).toEqual(['interactive']) })
  it('fails closed after disposal', () => { const p = new ArcGisSceneLodResidencyPolicy(budget); p.dispose(); expect(() => p.snapshot()).toThrow('disposed') })
})
