import { describe,expect,it } from 'vitest'
import { ArcGisFeaturePageCachePolicy,type ArcGisFeaturePageCacheBudget } from './ArcGisFeaturePageCachePolicy'
const budget:ArcGisFeaturePageCacheBudget={maxEntries:3,maxEntriesPerLayer:2,maxObjectIdsPerPage:100,maxBytesPerPage:1000,maxAggregateBytes:2000,ttlMs:100}
const page=(o:Partial<Parameters<ArcGisFeaturePageCachePolicy['put']>[0]>={})=>({layerId:'parcels',pageKey:'page-1',revision:1,intent:'visible' as const,objectIdCount:25,byteSize:400,storedAt:10,fingerprint:'fp-1',...o})
describe('ArcGisFeaturePageCachePolicy',()=>{
 it('returns detached bounded metadata',()=>{const c=new ArcGisFeaturePageCachePolicy(budget);expect(c.put(page())).toBe(true);const h=c.get('parcels','page-1',1,20);expect(h?.byteSize).toBe(400);if(h)h.byteSize=999;expect(c.get('parcels','page-1',1,21)?.byteSize).toBe(400)})
 it('invalidates stale pages when revision advances',()=>{const c=new ArcGisFeaturePageCachePolicy(budget);c.put(page());c.put(page({pageKey:'page-2'}));expect(c.put(page({pageKey:'page-3',revision:2}))).toBe(true);expect(c.snapshot().map(x=>x.pageKey)).toEqual(['page-3'])})
 it('rejects stale revisions without mutation',()=>{const c=new ArcGisFeaturePageCachePolicy(budget);c.put(page({revision:2}));const f=c.fingerprint();expect(c.put(page({pageKey:'old',revision:1}))).toBe(false);expect(c.fingerprint()).toBe(f)})
 it('preserves replacement target when oversized replacement is rejected',()=>{const c=new ArcGisFeaturePageCachePolicy(budget);c.put(page());const f=c.fingerprint();expect(c.put(page({objectIdCount:101}))).toBe(false);expect(c.fingerprint()).toBe(f)})
 it('expires at ttl boundary',()=>{const c=new ArcGisFeaturePageCachePolicy(budget);c.put(page({storedAt:50}));expect(c.get('parcels','page-1',1,149)).toBeDefined();expect(c.get('parcels','page-1',1,150)).toBeUndefined()})
 it('purges dead cardinality before admission',()=>{const c=new ArcGisFeaturePageCachePolicy({...budget,maxEntries:2,maxEntriesPerLayer:2});c.put(page({pageKey:'a'}));c.put(page({pageKey:'b',storedAt:11}));expect(c.put(page({pageKey:'fresh',storedAt:111}))).toBe(true);expect(c.snapshot().map(x=>x.pageKey)).toEqual(['fresh'])})
 it('purges dead bytes before admission',()=>{const c=new ArcGisFeaturePageCachePolicy({...budget,maxEntriesPerLayer:3,maxAggregateBytes:1000});c.put(page({pageKey:'old',byteSize:1000}));expect(c.put(page({pageKey:'fresh',byteSize:1000,storedAt:110}))).toBe(true)})
 it('keeps live residency before ttl boundary',()=>{const c=new ArcGisFeaturePageCachePolicy({...budget,maxEntries:1,maxEntriesPerLayer:1});c.put(page({pageKey:'live'}));expect(c.put(page({pageKey:'candidate',storedAt:109}))).toBe(false);expect(c.snapshot()[0]?.pageKey).toBe('live')})
 it('evicts background before visible for interactive pressure',()=>{const c=new ArcGisFeaturePageCachePolicy({...budget,maxEntriesPerLayer:3});c.put(page({pageKey:'v',byteSize:700}));c.put(page({pageKey:'b',intent:'background',byteSize:700}));expect(c.put(page({pageKey:'i',intent:'interactive',byteSize:900}))).toBe(true);expect(c.snapshot().map(x=>x.pageKey)).toEqual(['v','i'])})
 it('does not evict higher priority for background pressure',()=>{const c=new ArcGisFeaturePageCachePolicy({...budget,maxEntriesPerLayer:3});c.put(page({pageKey:'i',intent:'interactive',byteSize:1000}));c.put(page({pageKey:'v',byteSize:1000}));const f=c.fingerprint();expect(c.put(page({pageKey:'b',intent:'background',byteSize:100}))).toBe(false);expect(c.fingerprint()).toBe(f)})
 it('uses access recency tie-break',()=>{const c=new ArcGisFeaturePageCachePolicy({...budget,maxEntriesPerLayer:3});c.put(page({pageKey:'old',intent:'background',byteSize:700}));c.put(page({pageKey:'recent',intent:'background',byteSize:700,storedAt:11}));c.get('parcels','recent',1,40);expect(c.put(page({pageKey:'new',intent:'visible',byteSize:900,storedAt:50}))).toBe(true);expect(c.snapshot().map(x=>x.pageKey)).toEqual(['recent','new'])})
 it('enforces per-layer cardinality',()=>{const c=new ArcGisFeaturePageCachePolicy(budget);c.put(page({pageKey:'a'}));c.put(page({pageKey:'b'}));expect(c.put(page({pageKey:'c'}))).toBe(false)})
 it('releases layer ownership only',()=>{const c=new ArcGisFeaturePageCachePolicy(budget);c.put(page());c.put(page({layerId:'roads',pageKey:'r'}));expect(c.releaseLayer('parcels')).toBe(1);expect(c.snapshot().map(x=>x.layerId)).toEqual(['roads'])})
 it('fails closed for malformed input and budgets',()=>{expect(()=>new ArcGisFeaturePageCachePolicy({...budget,maxEntriesPerLayer:4})).toThrow();const c=new ArcGisFeaturePageCachePolicy(budget);expect(()=>c.put(page({layerId:'bad:id'}))).toThrow();expect(()=>c.put(page({byteSize:-1}))).toThrow()})
 it('rejects oversized page before mutation',()=>{const c=new ArcGisFeaturePageCachePolicy(budget);expect(c.put(page({byteSize:1001}))).toBe(false);expect(c.snapshot()).toEqual([])})
 it('disposes residency fail closed',()=>{const c=new ArcGisFeaturePageCachePolicy(budget);c.put(page());c.dispose();expect(()=>c.snapshot()).toThrow(/disposed/);expect(()=>c.put(page())).toThrow(/disposed/)})
})
