import { describe, expect, it, vi } from 'vitest'
import { ArcGisQueryCoordinator, type ArcGisQueryBudget, type ArcGisQueryKey } from './ArcGisQueryCoordinator'
const budget: ArcGisQueryBudget = { maxEntries: 2, maxInflight: 2, maxWaitersPerQuery: 3, maxCacheAgeMs: 1000, maxCachedBytes: 100, maxResponseBytes: 80, maxWhereLength: 100, maxOutFields: 4 }
const key = (where = '1=1'): ArcGisQueryKey => ({ serviceId: 'parcels', layerId: 0, where, outFields: ['OBJECTID'], returnGeometry: true })
describe('ArcGisQueryCoordinator', () => {
  it('caches identical normalized queries', async () => { let calls=0; const c=new ArcGisQueryCoordinator(async () => { calls++; return { value: calls, estimatedBytes: 10 } }, budget); expect((await c.query(key())).value).toBe(1); expect((await c.query(key(' 1=1 '))).value).toBe(1); expect(calls).toBe(1); expect(c.diagnostics().cacheHits).toBe(1) })
  it('deduplicates concurrent queries', async () => { let release!:()=>void; const gate=new Promise<void>(r=>release=r); let calls=0; const c=new ArcGisQueryCoordinator(async () => { calls++; await gate; return { value: 7, estimatedBytes: 10 } }, budget); const a=c.query(key()); const b=c.query(key()); release(); expect((await a).value).toBe(7); expect((await b).value).toBe(7); expect(calls).toBe(1); expect(c.diagnostics().dedupedWaiters).toBe(1) })
  it('aborting one waiter does not abort shared upstream', async () => { let release!:()=>void; const gate=new Promise<void>(r=>release=r); let upstreamAborted=false; const c=new ArcGisQueryCoordinator(async ({signal}) => { signal.addEventListener('abort',()=>upstreamAborted=true); await gate; return { value: 9, estimatedBytes: 10 } }, budget); const ac=new AbortController(); const a=c.query(key(),ac.signal); const b=c.query(key()); ac.abort(); await expect(a).rejects.toMatchObject({name:'AbortError'}); release(); await expect(b).resolves.toMatchObject({value:9}); expect(upstreamAborted).toBe(false) })
  it('aborts upstream when final waiter leaves', async () => { let aborted=false; const c=new ArcGisQueryCoordinator(async ({signal}) => new Promise((_,reject)=>signal.addEventListener('abort',()=>{aborted=true; reject(new Error('upstream aborted'))},{once:true})), budget); const ac=new AbortController(); const pending=c.query(key(),ac.signal); ac.abort(); await expect(pending).rejects.toMatchObject({name:'AbortError'}); expect(aborted).toBe(true) })
  it('expires stale cache entries', async () => { let now=0,calls=0; const c=new ArcGisQueryCoordinator(async()=>({value:++calls,estimatedBytes:10}),budget,()=>now); await c.query(key()); now=1001; expect((await c.query(key())).value).toBe(2) })
  it('invalidates future-clock entries', async () => { let now=100,calls=0; const c=new ArcGisQueryCoordinator(async()=>({value:++calls,estimatedBytes:10}),budget,()=>now); await c.query(key()); now=99; expect((await c.query(key())).value).toBe(2) })
  it('evicts least recently used entries by byte budget', async () => { let n=0,now=0; const c=new ArcGisQueryCoordinator(async()=>({value:++n,estimatedBytes:60}),budget,()=>++now); await c.query(key('a=1')); await c.query(key('b=1')); expect(c.diagnostics().cacheEntries).toBe(1); expect(c.diagnostics().evictions).toBe(1) })
  it('rejects response byte overflow', async () => { const c=new ArcGisQueryCoordinator(async()=>({value:1,estimatedBytes:81}),budget); await expect(c.query(key())).rejects.toThrow('estimatedBytes') })
  it('rejects inflight overflow', async () => { const c=new ArcGisQueryCoordinator(async()=>new Promise(()=>{}),budget); void c.query(key('a=1')); void c.query(key('b=1')); await expect(c.query(key('c=1'))).rejects.toThrow('inflight budget') })
  it('rejects waiter overflow', async () => { const c=new ArcGisQueryCoordinator(async()=>new Promise(()=>{}),budget); void c.query(key()); void c.query(key()); void c.query(key()); await expect(c.query(key())).rejects.toThrow('waiter budget') })
  it('normalizes out-field order for dedupe', async () => { const executor=vi.fn(async()=>({value:1,estimatedBytes:1})); const c=new ArcGisQueryCoordinator(executor,budget); await c.query({...key(),outFields:['NAME','OBJECTID']}); await c.query({...key(),outFields:['OBJECTID','NAME']}); expect(executor).toHaveBeenCalledTimes(1) })
  it('rejects control characters and overlong where', async () => { const c=new ArcGisQueryCoordinator(async()=>({value:1,estimatedBytes:1}),budget); await expect(c.query(key('x\u0000=1'))).rejects.toThrow('invalid where'); await expect(c.query(key('x'.repeat(101)))).rejects.toThrow('invalid where') })
  it('supports service-scoped invalidation', async () => { let calls=0; const c=new ArcGisQueryCoordinator(async()=>({value:++calls,estimatedBytes:1}),budget); await c.query(key()); expect(c.invalidateService('parcels')).toBe(1); await c.query(key()); expect(calls).toBe(2) })
  it('clears all cached state without touching diagnostics counters', async () => { const c=new ArcGisQueryCoordinator(async()=>({value:1,estimatedBytes:1}),budget); await c.query(key()); c.invalidateAll(); expect(c.diagnostics().cacheEntries).toBe(0); expect(c.diagnostics().cachedBytes).toBe(0) })
})
