import { describe, expect, it } from 'vitest'
import { ArcGisSpatialExecutionLifecyclePolicy, type ArcGisSpatialExecutionBudget, type ArcGisSpatialExecutionRequest } from './ArcGisSpatialExecutionLifecyclePolicy'
const budget: ArcGisSpatialExecutionBudget={maxExecutions:8,maxExecutionsPerView:5,maxExecutionsPerLayer:6,maxRunning:2,maxRunningPerView:1,maxReady:4,maxEstimatedVerticesPerExecution:500,maxActualVerticesPerExecution:1000,maxReadyVertices:2000,maxEstimatedBytesPerExecution:5000,maxActualBytesPerExecution:10000,maxReadyBytes:20000,queueTtlMs:100,runTtlMs:200,readyTtlMs:300}
const request=(o:Partial<ArcGisSpatialExecutionRequest>={}):ArcGisSpatialExecutionRequest=>({executionId:'exec-1',viewId:'view-1',layerId:'layer-1',revision:1,kind:'query',intent:'visible',requestedAt:10,estimatedVertices:100,estimatedBytes:1000,...o})
const run=(p:ArcGisSpatialExecutionLifecyclePolicy,o:Partial<ArcGisSpatialExecutionRequest>={})=>{p.enqueue(request(o));return p.takeNext(20)}
const complete=(p:ArcGisSpatialExecutionLifecyclePolicy,id='exec-1',o:Partial<{viewId:string;layerId:string;revision:number;actualVertices:number;actualBytes:number;completedAt:number}>={})=>p.complete({executionId:id,viewId:'view-1',layerId:'layer-1',revision:1,actualVertices:120,actualBytes:1200,completedAt:30,...o})
describe('ArcGisSpatialExecutionLifecyclePolicy',()=>{
 it('prioritizes interactive then visible then background deterministically',()=>{const p=new ArcGisSpatialExecutionLifecyclePolicy({...budget,maxRunningPerView:2});p.enqueue(request({executionId:'b',intent:'background',requestedAt:1}));p.enqueue(request({executionId:'v',intent:'visible',requestedAt:2}));p.enqueue(request({executionId:'i',intent:'interactive',requestedAt:3}));expect(p.takeNext(10)?.executionId).toBe('i');expect(p.takeNext(11)?.executionId).toBe('v')})
 it('bounds global and per-view concurrency',()=>{const p=new ArcGisSpatialExecutionLifecyclePolicy(budget);p.enqueue(request({executionId:'a',viewId:'v1'}));p.enqueue(request({executionId:'b',viewId:'v1'}));p.enqueue(request({executionId:'c',viewId:'v2'}));expect(p.takeNext(20)?.executionId).toBe('a');expect(p.takeNext(20)?.executionId).toBe('c');expect(p.takeNext(20)).toBeUndefined()})
 it('rejects duplicate and oversized estimates',()=>{const p=new ArcGisSpatialExecutionLifecyclePolicy(budget);p.enqueue(request());expect(()=>p.enqueue(request())).toThrow(/duplicate/);const q=new ArcGisSpatialExecutionLifecyclePolicy(budget);expect(()=>q.enqueue(request({estimatedVertices:501}))).toThrow(/vertex/);expect(q.snapshot()).toHaveLength(0)})
 it('reconciles estimates to actual residency',()=>{const p=new ArcGisSpatialExecutionLifecyclePolicy(budget);run(p);expect(complete(p)).toEqual(expect.objectContaining({phase:'ready',actualVertices:120,actualBytes:1200}))})
 it('releases authority on oversized actual results',()=>{const p=new ArcGisSpatialExecutionLifecyclePolicy(budget);run(p);expect(()=>complete(p,'exec-1',{actualBytes:10001})).toThrow(/byte/);expect(p.snapshot()).toHaveLength(0)})
 it('bounds aggregate ready residency',()=>{const p=new ArcGisSpatialExecutionLifecyclePolicy({...budget,maxReadyVertices:1100});run(p,{executionId:'a',viewId:'v1'});complete(p,'a',{viewId:'v1',actualVertices:800});run(p,{executionId:'b',viewId:'v2'});expect(()=>complete(p,'b',{viewId:'v2',actualVertices:400})).toThrow(/vertex residency/)})
 it('invalidates stale work on revision advance',()=>{const p=new ArcGisSpatialExecutionLifecyclePolicy(budget);p.enqueue(request());expect(p.advanceLayerRevision('layer-1',2)).toBe(1);expect(()=>p.enqueue(request({executionId:'stale',revision:1}))).toThrow(/stale/)})
 it('expires queue run and ready leases',()=>{const q=new ArcGisSpatialExecutionLifecyclePolicy(budget);q.enqueue(request({requestedAt:0}));expect(q.expire(101)).toBe(1);const r=new ArcGisSpatialExecutionLifecyclePolicy(budget);r.enqueue(request({requestedAt:0}));r.takeNext(10);expect(r.expire(211)).toBe(1);const d=new ArcGisSpatialExecutionLifecyclePolicy(budget);run(d);complete(d);expect(d.expire(331)).toBe(1)})
 it('touch consume cancel and teardown are bounded',()=>{const p=new ArcGisSpatialExecutionLifecyclePolicy(budget);run(p);complete(p);expect(p.touch('exec-1',40)).toBe(true);expect(p.consume('exec-1')?.phase).toBe('ready');p.enqueue(request({executionId:'a'}));p.enqueue(request({executionId:'b',viewId:'v2'}));expect(p.releaseView('view-1')).toBe(1);expect(p.releaseLayer('layer-1')).toBe(1)})
 it('governs all execution kinds without payload graphs',()=>{const p=new ArcGisSpatialExecutionLifecyclePolicy(budget);(['query','identify','buffer','nearest','projection','measurement'] as const).forEach((kind,i)=>p.enqueue(request({executionId:`e-${i}`,viewId:`v-${i}`,kind})));const s=p.snapshot();expect(s.map(x=>x.kind)).toEqual(['query','identify','buffer','nearest','projection','measurement']);expect(s[0]).not.toHaveProperty('geometry');expect(s[0]).not.toHaveProperty('features');expect(s[0]).not.toHaveProperty('credential');expect(s[0]).not.toHaveProperty('abortController')})
 it('rejects malformed inputs and impossible budgets',()=>{const p=new ArcGisSpatialExecutionLifecyclePolicy(budget);expect(()=>p.enqueue(request({executionId:'bad id'}))).toThrow(/invalid/);expect(()=>p.enqueue(request({requestedAt:NaN}))).toThrow(/finite/);expect(()=>new ArcGisSpatialExecutionLifecyclePolicy({...budget,maxRunningPerView:3,maxRunning:2})).toThrow(/impossible/)})
 it('fingerprints deterministically and fails closed after dispose',()=>{const a=new ArcGisSpatialExecutionLifecyclePolicy(budget),b=new ArcGisSpatialExecutionLifecyclePolicy(budget);a.enqueue(request({executionId:'b'}));a.enqueue(request({executionId:'a'}));b.enqueue(request({executionId:'a'}));b.enqueue(request({executionId:'b'}));expect(a.fingerprint()).toBe(b.fingerprint());a.dispose();expect(()=>a.snapshot()).toThrow(/disposed/)})
})
