import { describe, expect, it } from 'vitest'
import { ArcGisFeatureEditLockLifecyclePolicy, type FeatureEditLockBudget, type FeatureEditLockIntent } from './ArcGisFeatureEditLockLifecyclePolicy'

const budget = (overrides: Partial<FeatureEditLockBudget> = {}): FeatureEditLockBudget => ({ maxLayers: 4, maxLocks: 8, maxLocksPerLayer: 4, maxHeld: 2, maxHeldPerLayer: 1, waitTtlMs: 100, leaseMs: 50, ...overrides })
const request = (lockId: string, layerId = 'layer-a', featureId = lockId, revision = 1, intent: FeatureEditLockIntent = 'visible', requestedAt = 0) => ({ lockId, layerId, featureId, revision, intent, requestedAt })
const ready = (overrides: Partial<FeatureEditLockBudget> = {}) => { const p = new ArcGisFeatureEditLockLifecyclePolicy(budget(overrides)); p.setRevision('layer-a', 1); return p }

describe('ArcGisFeatureEditLockLifecyclePolicy', () => {
  it('rejects zero global cardinality', () => { expect(() => new ArcGisFeatureEditLockLifecyclePolicy(budget({ maxLocks: 0 }))).toThrow() })
  it('rejects zero layer cardinality', () => { expect(() => new ArcGisFeatureEditLockLifecyclePolicy(budget({ maxLayers: 0 }))).toThrow() })
  it('rejects per-layer lock budget above global', () => { expect(() => new ArcGisFeatureEditLockLifecyclePolicy(budget({ maxLocksPerLayer: 9 }))).toThrow() })
  it('rejects held budget above lock budget', () => { expect(() => new ArcGisFeatureEditLockLifecyclePolicy(budget({ maxHeld: 9 }))).toThrow() })
  it('rejects per-layer held budget above global held budget', () => { expect(() => new ArcGisFeatureEditLockLifecyclePolicy(budget({ maxHeldPerLayer: 3 }))).toThrow() })
  it('rejects per-layer held budget above per-layer locks', () => { expect(() => new ArcGisFeatureEditLockLifecyclePolicy(budget({ maxLocksPerLayer: 1, maxHeldPerLayer: 2 }))).toThrow() })
  it('rejects non-finite ttl', () => { expect(() => new ArcGisFeatureEditLockLifecyclePolicy(budget({ waitTtlMs: Number.NaN }))).toThrow() })
  it('rejects negative lease', () => { expect(() => new ArcGisFeatureEditLockLifecyclePolicy(budget({ leaseMs: -1 }))).toThrow() })
  it('admits a known revision', () => { const p = ready(); expect(p.enqueue(request('a'))).toBe(true) })
  it('rejects an unknown revision', () => { const p = new ArcGisFeatureEditLockLifecyclePolicy(budget()); expect(p.enqueue(request('a'))).toBe(false) })
  it('rejects a stale revision', () => { const p = ready(); expect(p.enqueue(request('a', 'layer-a', 'a', 0))).toBe(false) })
  it('rejects duplicate lock ids', () => { const p = ready(); expect(p.enqueue(request('a'))).toBe(true); expect(p.enqueue(request('a', 'layer-a', 'b'))).toBe(false) })
  it('rejects duplicate feature authority', () => { const p = ready(); expect(p.enqueue(request('a', 'layer-a', 'f'))).toBe(true); expect(p.enqueue(request('b', 'layer-a', 'f'))).toBe(false) })
  it('allows the same feature id on distinct layers', () => { const p = ready(); p.setRevision('layer-b', 1); expect(p.enqueue(request('a', 'layer-a', 'f'))).toBe(true); expect(p.enqueue(request('b', 'layer-b', 'f'))).toBe(true) })
  it('trims safe identifiers deterministically', () => { const p = ready(); expect(p.enqueue(request(' a ', ' layer-a ', ' f '))).toBe(true); expect(p.fingerprint()).toContain('layer-a:f:a') })
  it('rejects blank lock id', () => { const p = ready(); expect(() => p.enqueue(request(' '))).toThrow() })
  it('rejects blank feature id', () => { const p = ready(); expect(() => p.enqueue(request('a', 'layer-a', ' '))).toThrow() })
  it('rejects control characters', () => { const p = ready(); expect(() => p.enqueue(request('a\u0000'))).toThrow() })
  it('rejects overlong identifiers', () => { const p = ready(); expect(() => p.enqueue(request('x'.repeat(193)))).toThrow() })
  it('rejects malformed revision', () => { const p = ready(); expect(() => p.enqueue(request('a', 'layer-a', 'a', -1))).toThrow() })
  it('rejects malformed request time', () => { const p = ready(); expect(() => p.enqueue(request('a', 'layer-a', 'a', 1, 'visible', Infinity))).toThrow() })
  it('rejects unknown runtime intent', () => { const p = ready(); expect(() => p.enqueue({ ...request('a'), intent: 'urgent' as never })).toThrow() })
  it('enforces global lock cardinality', () => { const p = ready({ maxLocks: 2, maxLocksPerLayer: 2 }); expect(p.enqueue(request('a'))).toBe(true); expect(p.enqueue(request('b'))).toBe(true); expect(p.enqueue(request('c'))).toBe(false) })
  it('enforces per-layer lock cardinality', () => { const p = ready({ maxLocksPerLayer: 1 }); expect(p.enqueue(request('a'))).toBe(true); expect(p.enqueue(request('b'))).toBe(false) })
  it('enforces revision layer cardinality', () => { const p = new ArcGisFeatureEditLockLifecyclePolicy(budget({ maxLayers: 1 })); expect(p.setRevision('a', 1)).toBe(0); expect(p.setRevision('b', 1)).toBe(-1) })
  it('rejects revision rollback', () => { const p = ready(); expect(p.setRevision('layer-a', 0)).toBe(-1) })
  it('keeps locks on an idempotent revision set', () => { const p = ready(); p.enqueue(request('a')); expect(p.setRevision('layer-a', 1)).toBe(0); expect(p.snapshot().locks).toBe(1) })
  it('invalidates waiting locks on revision advance', () => { const p = ready(); p.enqueue(request('a')); expect(p.setRevision('layer-a', 2)).toBe(1); expect(p.snapshot().locks).toBe(0) })
  it('invalidates held locks on revision advance', () => { const p = ready(); p.enqueue(request('a')); p.acquireNext(1); expect(p.setRevision('layer-a', 2)).toBe(1); expect(p.snapshot().held).toBe(0) })
  it('prioritizes interactive intent', () => { const p = ready(); p.setRevision('layer-b', 1); p.enqueue(request('bg', 'layer-a', 'bg', 1, 'background')); p.enqueue(request('ui', 'layer-b', 'ui', 1, 'interactive')); expect(p.acquireNext(1)?.lockId).toBe('ui') })
  it('prioritizes visible over background', () => { const p = ready(); p.setRevision('layer-b', 1); p.enqueue(request('bg', 'layer-a', 'bg', 1, 'background')); p.enqueue(request('v', 'layer-b', 'v', 1, 'visible')); expect(p.acquireNext(1)?.lockId).toBe('v') })
  it('uses oldest request time for equal intent', () => { const p = ready(); p.setRevision('layer-b', 1); p.enqueue(request('late', 'layer-a', 'late', 1, 'visible', 9)); p.enqueue(request('early', 'layer-b', 'early', 1, 'visible', 2)); expect(p.acquireNext(10)?.lockId).toBe('early') })
  it('uses insertion sequence as final tie break', () => { const p = ready(); p.setRevision('layer-b', 1); p.enqueue(request('first')); p.enqueue(request('second', 'layer-b')); expect(p.acquireNext(1)?.lockId).toBe('first') })
  it('enforces global held concurrency', () => { const p = ready({ maxHeld: 1, maxHeldPerLayer: 1 }); p.setRevision('layer-b', 1); p.enqueue(request('a')); p.enqueue(request('b', 'layer-b')); expect(p.acquireNext(1)).not.toBeNull(); expect(p.acquireNext(2)).toBeNull() })
  it('enforces per-layer held concurrency', () => { const p = ready({ maxHeld: 2, maxHeldPerLayer: 1 }); p.enqueue(request('a')); p.enqueue(request('b')); expect(p.acquireNext(1)).not.toBeNull(); expect(p.acquireNext(2)).toBeNull() })
  it('allows another layer while first layer is saturated', () => { const p = ready({ maxHeld: 2, maxHeldPerLayer: 1 }); p.setRevision('layer-b', 1); p.enqueue(request('a')); p.enqueue(request('b')); p.enqueue(request('c', 'layer-b')); expect(p.acquireNext(1)?.lockId).toBe('a'); expect(p.acquireNext(2)?.lockId).toBe('c') })
  it('transitions acquired lock to held', () => { const p = ready(); p.enqueue(request('a')); expect(p.acquireNext(1)?.phase).toBe('held'); expect(p.snapshot()).toMatchObject({ waiting: 0, held: 1 }) })
  it('sets a deterministic lease deadline', () => { const p = ready({ leaseMs: 50 }); p.enqueue(request('a')); expect(p.acquireNext(10)?.expiresAt).toBe(60) })
  it('renews a live held lease', () => { const p = ready({ leaseMs: 50 }); p.enqueue(request('a')); p.acquireNext(1); expect(p.renew('a', 1, 10)).toBe(true); expect(p.expire(59)).toBe(0); expect(p.expire(60)).toBe(1) })
  it('rejects renewal of waiting lock', () => { const p = ready(); p.enqueue(request('a')); expect(p.renew('a', 1, 1)).toBe(false) })
  it('rejects renewal with stale revision', () => { const p = ready(); p.enqueue(request('a')); p.acquireNext(1); expect(p.renew('a', 0, 2)).toBe(false) })
  it('rejects renewal after lease expiry', () => { const p = ready({ leaseMs: 5 }); p.enqueue(request('a')); p.acquireNext(1); expect(p.renew('a', 1, 6)).toBe(false) })
  it('expires waiting authority at ttl boundary', () => { const p = ready({ waitTtlMs: 5 }); p.enqueue(request('a')); expect(p.expire(4)).toBe(0); expect(p.expire(5)).toBe(1) })
  it('expires held authority at lease boundary', () => { const p = ready({ leaseMs: 5 }); p.enqueue(request('a')); p.acquireNext(1); expect(p.expire(5)).toBe(0); expect(p.expire(6)).toBe(1) })
  it('expire validates time', () => { const p = ready(); expect(() => p.expire(Number.NaN)).toThrow() })
  it('release removes waiting authority', () => { const p = ready(); p.enqueue(request('a')); expect(p.release('a')).toBe(true); expect(p.release('a')).toBe(false) })
  it('release removes held authority', () => { const p = ready(); p.enqueue(request('a')); p.acquireNext(1); expect(p.release('a')).toBe(true); expect(p.snapshot().held).toBe(0) })
  it('releaseLayer removes all layer locks and revision', () => { const p = ready(); p.enqueue(request('a')); p.enqueue(request('b')); expect(p.releaseLayer('layer-a')).toBe(2); expect(p.enqueue(request('c'))).toBe(false) })
  it('releaseLayer preserves other layers', () => { const p = ready(); p.setRevision('layer-b', 1); p.enqueue(request('a')); p.enqueue(request('b', 'layer-b')); expect(p.releaseLayer('layer-a')).toBe(1); expect(p.snapshot()).toMatchObject({ layers: 1, locks: 1 }) })
  it('snapshot is frozen and detached', () => { const p = ready(); p.enqueue(request('a')); const value = p.snapshot(); expect(Object.isFrozen(value)).toBe(true); expect(value).toEqual({ layers: 1, locks: 1, waiting: 1, held: 0 }) })
  it('fingerprint is deterministic across equivalent authorities', () => { const a = ready(); const b = ready(); a.enqueue(request('x')); b.enqueue(request('x')); expect(a.fingerprint()).toBe(b.fingerprint()) })
  it('fingerprint is insertion-independent across layers', () => { const a = ready(); const b = ready(); for (const p of [a, b]) p.setRevision('layer-b', 1); a.enqueue(request('x', 'layer-a')); a.enqueue(request('y', 'layer-b')); b.enqueue(request('y', 'layer-b')); b.enqueue(request('x', 'layer-a')); expect(a.fingerprint()).toBe(b.fingerprint()) })
  it('fingerprint exposes scalar metadata only', () => { const p = ready(); p.enqueue(request('a', 'layer-a', 'feature-1')); expect(p.fingerprint()).toBe('layer-a:feature-1:a:1:visible:waiting') })
  it('acquired view is frozen', () => { const p = ready(); p.enqueue(request('a')); const view = p.acquireNext(1); expect(Object.isFrozen(view)).toBe(true) })
  it('acquired view contains bounded scalar authority', () => { const p = ready(); p.enqueue(request('a', 'layer-a', 'feature-1')); expect(p.acquireNext(1)).toMatchObject({ lockId: 'a', layerId: 'layer-a', featureId: 'feature-1', revision: 1, intent: 'visible', phase: 'held' }) })
  it('does not acquire expired waiting work', () => { const p = ready({ waitTtlMs: 1 }); p.enqueue(request('a')); expect(p.acquireNext(1)).toBeNull() })
  it('releases feature authority for a later request', () => { const p = ready(); p.enqueue(request('a', 'layer-a', 'f')); p.release('a'); expect(p.enqueue(request('b', 'layer-a', 'f'))).toBe(true) })
  it('expiry releases feature authority for a later request', () => { const p = ready({ waitTtlMs: 1 }); p.enqueue(request('a', 'layer-a', 'f')); p.expire(1); expect(p.enqueue(request('b', 'layer-a', 'f', 1, 'visible', 1))).toBe(true) })
  it('revision invalidation releases feature authority for new revision', () => { const p = ready(); p.enqueue(request('a', 'layer-a', 'f')); p.setRevision('layer-a', 2); expect(p.enqueue(request('b', 'layer-a', 'f', 2))).toBe(true) })
  it('dispose is idempotent', () => { const p = ready(); p.dispose(); p.dispose() })
  it('dispose clears and terminates snapshot access', () => { const p = ready(); p.enqueue(request('a')); p.dispose(); expect(() => p.snapshot()).toThrow(/disposed/) })
  it('dispose terminates enqueue', () => { const p = ready(); p.dispose(); expect(() => p.enqueue(request('a'))).toThrow(/disposed/) })
  it('dispose terminates revision mutation', () => { const p = ready(); p.dispose(); expect(() => p.setRevision('layer-a', 2)).toThrow(/disposed/) })
  it('dispose terminates acquisition', () => { const p = ready(); p.dispose(); expect(() => p.acquireNext(1)).toThrow(/disposed/) })
  it('dispose terminates renewal', () => { const p = ready(); p.dispose(); expect(() => p.renew('a', 1, 1)).toThrow(/disposed/) })
  it('dispose terminates release', () => { const p = ready(); p.dispose(); expect(() => p.release('a')).toThrow(/disposed/) })
  it('dispose terminates expiry', () => { const p = ready(); p.dispose(); expect(() => p.expire(1)).toThrow(/disposed/) })
  it('dispose terminates fingerprinting', () => { const p = ready(); p.dispose(); expect(() => p.fingerprint()).toThrow(/disposed/) })
})
