export type ArcGisRefreshIntent = 'interactive' | 'visible' | 'background'
export type ArcGisRefreshState = 'queued' | 'loading' | 'ready'

export interface ArcGisLayerRefreshBudget { maxJobs:number; maxJobsPerLayer:number; maxConcurrent:number; maxConcurrentPerLayer:number; maxReadyBytes:number; maxReadyBytesPerLayer:number; maxBytesPerJob:number; queueLeaseMs:number; loadingLeaseMs:number; readyTtlMs:number }
export interface ArcGisLayerRefreshRequest { layerId:string; refreshKey:string; revision:number; intent:ArcGisRefreshIntent; estimatedBytes:number; requestedAt:number }
export interface ArcGisLayerRefreshSnapshot extends ArcGisLayerRefreshRequest { state:ArcGisRefreshState; actualBytes:number; sequence:number; expiresAt:number }
type Job = ArcGisLayerRefreshSnapshot
const intentRank:Record<ArcGisRefreshIntent,number>={interactive:0,visible:1,background:2}
const separator='\u0000'

/** Payload-free authority for bounded ArcGIS layer refresh work. */
export class ArcGisLayerRefreshCoordinator {
 private readonly jobs=new Map<string,Job>(); private readonly revisions=new Map<string,number>(); private sequence=0; private disposed=false
 constructor(private readonly budget:ArcGisLayerRefreshBudget){this.validateBudget()}
 enqueue(input:ArcGisLayerRefreshRequest):boolean{this.active();const r=this.normalize(input);this.expire(r.requestedAt);const watermark=this.revisions.get(r.layerId)??0;if(r.revision<watermark)return false;const key=this.key(r.layerId,r.refreshKey),previous=this.jobs.get(key);if(previous&&r.revision<previous.revision)return false;const advances=r.revision>watermark;const survives=(j:Job)=>j!==previous&&!(advances&&j.layerId===r.layerId&&j.revision<r.revision);if(this.count(j=>survives(j)&&j.layerId===r.layerId)+1>this.budget.maxJobsPerLayer||this.count(survives)+1>this.budget.maxJobs)return false;if(advances)this.invalidateLayer(r.layerId,r.revision);else if(previous)this.jobs.delete(key);this.revisions.set(r.layerId,Math.max(watermark,r.revision));this.jobs.set(key,{...r,state:'queued',actualBytes:0,sequence:this.sequence++,expiresAt:r.requestedAt+this.budget.queueLeaseMs});return true}
 takeNext(now:number):ArcGisLayerRefreshSnapshot|undefined{this.active();this.timestamp(now);this.expire(now);if(this.count(j=>j.state==='loading')>=this.budget.maxConcurrent)return;const c=[...this.jobs.values()].filter(j=>j.state==='queued'&&this.count(o=>o.state==='loading'&&o.layerId===j.layerId)<this.budget.maxConcurrentPerLayer).sort((a,b)=>intentRank[a.intent]-intentRank[b.intent]||a.requestedAt-b.requestedAt||a.sequence-b.sequence)[0];if(!c)return;c.state='loading';c.expiresAt=now+this.budget.loadingLeaseMs;return this.detach(c)}
 complete(layerId:string,refreshKey:string,revision:number,actualBytes:number,now:number):boolean{this.active();this.timestamp(now);this.positive(revision,'revision');this.nonNegative(actualBytes,'actualBytes');const layer=this.id(layerId,'layerId'),key=this.key(layer,this.id(refreshKey,'refreshKey')),job=this.jobs.get(key);if(!job||job.state!=='loading'||job.revision!==revision)return false;if(revision<(this.revisions.get(layer)??0)||now>=job.expiresAt||actualBytes>this.budget.maxBytesPerJob){this.jobs.delete(key);return false}this.expire(now);const layerReady=this.sumBytes(j=>j!==job&&j.state==='ready'&&j.layerId===layer),totalReady=this.sumBytes(j=>j!==job&&j.state==='ready');if(layerReady+actualBytes>this.budget.maxReadyBytesPerLayer||totalReady+actualBytes>this.budget.maxReadyBytes){this.jobs.delete(key);return false}job.state='ready';job.actualBytes=actualBytes;job.expiresAt=now+this.budget.readyTtlMs;return true}
 consume(layerId:string,refreshKey:string,revision:number,now:number):ArcGisLayerRefreshSnapshot|undefined{this.active();this.timestamp(now);this.positive(revision,'revision');const key=this.key(this.id(layerId,'layerId'),this.id(refreshKey,'refreshKey')),job=this.jobs.get(key);if(!job||job.state!=='ready'||job.revision!==revision||now>=job.expiresAt){if(job&&now>=job.expiresAt)this.jobs.delete(key);return}this.jobs.delete(key);return this.detach(job)}
 cancel(layerId:string,refreshKey:string):boolean{this.active();return this.jobs.delete(this.key(this.id(layerId,'layerId'),this.id(refreshKey,'refreshKey')))}
 invalidateLayer(layerId:string,revision:number):number{this.active();const layer=this.id(layerId,'layerId');this.positive(revision,'revision');const current=this.revisions.get(layer)??0;if(revision<=current)return 0;this.revisions.set(layer,revision);return this.release(j=>j.layerId===layer&&j.revision<revision)}
 releaseLayer(layerId:string):number{this.active();const layer=this.id(layerId,'layerId');this.revisions.delete(layer);return this.release(j=>j.layerId===layer)}
 expire(now:number):number{this.active();this.timestamp(now);return this.release(j=>now>=j.expiresAt)}
 snapshot():ArcGisLayerRefreshSnapshot[]{this.active();return [...this.jobs.values()].sort((a,b)=>a.sequence-b.sequence).map(j=>this.detach(j))}
 dispose():void{if(!this.disposed){this.jobs.clear();this.revisions.clear();this.disposed=true}}
 private normalize(i:ArcGisLayerRefreshRequest){if(!(i.intent in intentRank))throw new Error('intent is invalid');this.positive(i.revision,'revision');this.nonNegative(i.estimatedBytes,'estimatedBytes');this.timestamp(i.requestedAt);if(i.estimatedBytes>this.budget.maxBytesPerJob)throw new RangeError('estimatedBytes exceeds per-job budget');return{...i,layerId:this.id(i.layerId,'layerId'),refreshKey:this.id(i.refreshKey,'refreshKey')}}
 private validateBudget(){for(const [n,v] of Object.entries(this.budget))this.positive(v,n);if(this.budget.maxJobsPerLayer>this.budget.maxJobs)throw new RangeError('per-layer jobs exceed global jobs');if(this.budget.maxConcurrentPerLayer>this.budget.maxConcurrent)throw new RangeError('per-layer concurrency exceeds global concurrency');if(this.budget.maxReadyBytesPerLayer>this.budget.maxReadyBytes)throw new RangeError('per-layer ready bytes exceed global ready bytes');if(this.budget.maxBytesPerJob>this.budget.maxReadyBytesPerLayer)throw new RangeError('job bytes exceed per-layer ready bytes')}
 private detach(j:Job){return{...j}} private count(p:(j:Job)=>boolean){let n=0;for(const j of this.jobs.values())if(p(j))n++;return n} private sumBytes(p:(j:Job)=>boolean){let n=0;for(const j of this.jobs.values())if(p(j))n+=j.actualBytes;return n} private release(p:(j:Job)=>boolean){let n=0;for(const [k,j] of this.jobs)if(p(j)){this.jobs.delete(k);n++}return n}
 private key(a:string,b:string){return`${a}${separator}${b}`} private id(v:string,n:string){const x=v.trim();if(!x||x.length>160||x.includes(separator))throw new Error(`${n} is invalid`);return x} private positive(v:number,n:string){if(!Number.isSafeInteger(v)||v<=0)throw new RangeError(`${n} must be a positive safe integer`)} private nonNegative(v:number,n:string){if(!Number.isSafeInteger(v)||v<0)throw new RangeError(`${n} must be a non-negative safe integer`)} private timestamp(v:number){if(!Number.isFinite(v)||v<0)throw new RangeError('timestamp must be finite and non-negative')} private active(){if(this.disposed)throw new Error('ArcGisLayerRefreshCoordinator is disposed')}
}
