export type TopologySeverity = 'warning' | 'error';
export type TopologyIssueKind = 'duplicate-vertex' | 'zero-length-segment' | 'unclosed-ring' | 'self-intersection' | 'minimum-cardinality';
export interface TopologyPoint { readonly x:number; readonly y:number; readonly z:number|null; readonly wkid:number; }
export interface TopologyGeometry { readonly id:string; readonly kind:'polyline'|'polygon'; readonly points:readonly TopologyPoint[]; }
export interface TopologyIssue { readonly id:string; readonly geometryId:string; readonly kind:TopologyIssueKind; readonly severity:TopologySeverity; readonly segmentA:number|null; readonly segmentB:number|null; }
export interface TopologyPolicy { readonly maxGeometries:number; readonly maxPointsPerGeometry:number; readonly maxIssues:number; readonly maxIdLength:number; readonly coordinateTolerance:number; }
export interface TopologySnapshot { readonly generation:number; readonly geometries:readonly TopologyGeometry[]; readonly issues:readonly TopologyIssue[]; }
const freezePoint=(p:TopologyPoint)=>Object.freeze({...p});
const finite=(n:number,name:string)=>{if(!Number.isFinite(n))throw new Error(`${name} must be finite`);};
const validId=(v:string,max:number,name:string)=>{if(!v.trim()||v.length>max||v.includes('\0'))throw new Error(`${name} outside bounds`);return v;};
const same=(a:TopologyPoint,b:TopologyPoint,t:number)=>a.wkid===b.wkid&&Math.abs(a.x-b.x)<=t&&Math.abs(a.y-b.y)<=t&&(a.z===null&&b.z===null||a.z!==null&&b.z!==null&&Math.abs(a.z-b.z)<=t);
const orient=(a:TopologyPoint,b:TopologyPoint,c:TopologyPoint)=>(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);
const intersects=(a:TopologyPoint,b:TopologyPoint,c:TopologyPoint,d:TopologyPoint,t:number)=>{const o1=orient(a,b,c),o2=orient(a,b,d),o3=orient(c,d,a),o4=orient(c,d,b);return ((o1>t&&o2< -t)||(o1< -t&&o2>t))&&((o3>t&&o4< -t)||(o3< -t&&o4>t));};
export class ArcGisTopologyValidationCoordinator {
 private readonly policy:TopologyPolicy; private geometries=new Map<string,TopologyGeometry>(); private generation=0; private disposed=false;
 constructor(policy:TopologyPolicy){if(!Number.isInteger(policy.maxGeometries)||policy.maxGeometries<1||!Number.isInteger(policy.maxPointsPerGeometry)||policy.maxPointsPerGeometry<3||!Number.isInteger(policy.maxIssues)||policy.maxIssues<1||!Number.isInteger(policy.maxIdLength)||policy.maxIdLength<1||!Number.isFinite(policy.coordinateTolerance)||policy.coordinateTolerance<0)throw new Error('invalid topology policy');this.policy=Object.freeze({...policy});}
 upsert(input:TopologyGeometry):TopologyGeometry{this.live();validId(input.id,this.policy.maxIdLength,'geometry id');if(input.points.length<2||input.points.length>this.policy.maxPointsPerGeometry)throw new Error('point cardinality outside bounds');const points=input.points.map(p=>{finite(p.x,'x');finite(p.y,'y');if(p.z!==null)finite(p.z,'z');if(!Number.isSafeInteger(p.wkid)||p.wkid<=0)throw new Error('invalid wkid');return freezePoint(p);});const value=Object.freeze({id:input.id,kind:input.kind,points:Object.freeze(points)});if(!this.geometries.has(input.id)&&this.geometries.size>=this.policy.maxGeometries){const first=[...this.geometries.keys()].sort()[0];if(first)this.geometries.delete(first);}this.geometries.set(input.id,value);this.generation++;return value;}
 remove(id:string){this.live();const changed=this.geometries.delete(id);if(changed)this.generation++;return changed;}
 validate():TopologySnapshot{this.live();const issues:TopologyIssue[]=[];const push=(geometryId:string,kind:TopologyIssueKind,severity:TopologySeverity,a:number|null=null,b:number|null=null)=>{if(issues.length<this.policy.maxIssues)issues.push(Object.freeze({id:`${geometryId}:${kind}:${a??'x'}:${b??'x'}`,geometryId,kind,severity,segmentA:a,segmentB:b}));};for(const g of [...this.geometries.values()].sort((a,b)=>a.id.localeCompare(b.id))){const p=g.points;if(g.kind==='polygon'&&p.length<4)push(g.id,'minimum-cardinality','error');if(g.kind==='polygon'&&p.length>=2&&!same(p[0]!,p[p.length-1]!,this.policy.coordinateTolerance))push(g.id,'unclosed-ring','error');for(let i=1;i<p.length;i++){if(same(p[i-1]!,p[i]!,this.policy.coordinateTolerance)){push(g.id,'duplicate-vertex','warning',i-1,i);push(g.id,'zero-length-segment','error',i-1,i);}}for(let i=0;i<p.length-1;i++)for(let j=i+2;j<p.length-1;j++){if(g.kind==='polygon'&&i===0&&j===p.length-2)continue;if(intersects(p[i]!,p[i+1]!,p[j]!,p[j+1]!,this.policy.coordinateTolerance))push(g.id,'self-intersection','error',i,j);}}
 return Object.freeze({generation:this.generation,geometries:Object.freeze([...this.geometries.values()].sort((a,b)=>a.id.localeCompare(b.id))),issues:Object.freeze(issues)});}
 restore(snapshot:Pick<TopologySnapshot,'geometries'>){this.live();const staged=new ArcGisTopologyValidationCoordinator(this.policy);for(const g of snapshot.geometries){if(staged.geometries.has(g.id))throw new Error('duplicate geometry id');staged.upsert(g);}this.geometries=new Map(staged.geometries);this.generation++;}
 dispose(){this.geometries.clear();this.disposed=true;this.generation++;}
 private live(){if(this.disposed)throw new Error('topology coordinator disposed');}
}
