export type IdentifyQueryIntent = 'interactive' | 'visible' | 'background'
export type IdentifyQueryPhase = 'queued' | 'running' | 'resident'

export interface IdentifyQueryBudget { maxLayers:number; maxQueries:number; maxQueriesPerLayer:number; maxRunning:number; maxRunningPerLayer:number; maxResident:number; maxResidentPerLayer:number; maxFeaturesPerQuery:number; maxBytesPerQuery:number; maxResidentFeatures:number; maxResidentBytes:number; queueTtlMs:number; requestLeaseMs:number; residentTtlMs:number }
export interface IdentifyQueryRequest { queryId:string; layerId:string; revision:number; intent:IdentifyQueryIntent; estimatedFeatures:number; estimatedBytes:number; requestedAt:number }
export interface IdentifyQueryView extends IdentifyQueryRequest { readonly phase:IdentifyQueryPhase; readonly sequence:number; readonly touchedAt:number; readonly expiresAt:number; readonly features:number; readonly bytes:number }
interface Query extends IdentifyQueryRequest { phase:IdentifyQueryPhase; sequence:number; touchedAt:number; expiresAt:number; features:number; bytes:number }

const intents:readonly IdentifyQueryIntent[]=['interactive','visible','background']
const rank:Readonly<Record<IdentifyQueryIntent,number>>=Object.freeze({interactive:2,visible:1,background:0})
function identifier(name:string,value:string):string{const v=value.trim();if(!v||v.length>192||/[\u0000-\u001f]/.test(v))throw new Error(`${name} is invalid`);return v}
function count(name:string,value:number,min=0):void{if(!Number.isSafeInteger(value)||value<min)throw new Error(`${name} must be a safe integer >= ${min}`)}
function clock(name:string,value:number):void{if(!Number.isFinite(value)||value<0)throw new Error(`${name} must be finite and non-negative`)}

/** Payload-free bounded authority for ArcGIS identify/query work. SDK payloads remain request-local. */
export class ArcGisIdentifyQueryLifecyclePolicy {
  readonly #budget:Readonly<IdentifyQueryBudget>; readonly #queries=new Map<string,Query>(); readonly #revisions=new Map<string,number>(); #sequence=0; #disposed=false
  constructor(budget:IdentifyQueryBudget){
    for(const key of ['maxLayers','maxQueries','maxQueriesPerLayer','maxRunning','maxRunningPerLayer','maxResident','maxResidentPerLayer','maxFeaturesPerQuery','maxBytesPerQuery','maxResidentFeatures','maxResidentBytes'] as const)count(key,budget[key],1)
    clock('queueTtlMs',budget.queueTtlMs);clock('requestLeaseMs',budget.requestLeaseMs);clock('residentTtlMs',budget.residentTtlMs)
    if(budget.maxQueriesPerLayer>budget.maxQueries)throw new Error('maxQueriesPerLayer cannot exceed maxQueries')
    if(budget.maxRunning>budget.maxQueries||budget.maxResident>budget.maxQueries)throw new Error('phase budget cannot exceed maxQueries')
    if(budget.maxRunningPerLayer>budget.maxRunning||budget.maxRunningPerLayer>budget.maxQueriesPerLayer)throw new Error('maxRunningPerLayer exceeds parent budget')
    if(budget.maxResidentPerLayer>budget.maxResident||budget.maxResidentPerLayer>budget.maxQueriesPerLayer)throw new Error('maxResidentPerLayer exceeds parent budget')
    if(budget.maxResidentFeatures<budget.maxFeaturesPerQuery||budget.maxResidentBytes<budget.maxBytesPerQuery)throw new Error('resident aggregate budget must fit one query')
    this.#budget=Object.freeze({...budget})
  }
  setRevision(layerId:string,next:number):number{this.#live();const layer=identifier('layerId',layerId);count('revision',next);const current=this.#revisions.get(layer);if(current!==undefined&&next<current)return -1;if(current===undefined&&this.#revisions.size>=this.#budget.maxLayers)return -1;this.#revisions.set(layer,next);if(current===undefined||current===next)return 0;let removed=0;for(const[key,q]of this.#queries)if(q.layerId===layer&&q.revision!==next){this.#queries.delete(key);removed++}return removed}
  admit(request:IdentifyQueryRequest):boolean{this.#live();const queryId=identifier('queryId',request.queryId),layerId=identifier('layerId',request.layerId);count('revision',request.revision);count('estimatedFeatures',request.estimatedFeatures,1);count('estimatedBytes',request.estimatedBytes,1);clock('requestedAt',request.requestedAt);if(!intents.includes(request.intent))throw new Error('intent is invalid');if(request.estimatedFeatures>this.#budget.maxFeaturesPerQuery||request.estimatedBytes>this.#budget.maxBytesPerQuery)return false;if(this.#revisions.get(layerId)!==request.revision||this.#queries.has(queryId))return false;if(this.#queries.size>=this.#budget.maxQueries||this.#layerCount(layerId)>=this.#budget.maxQueriesPerLayer)return false;const sequence=++this.#sequence;this.#queries.set(queryId,{...request,queryId,layerId,phase:'queued',sequence,touchedAt:request.requestedAt,expiresAt:request.requestedAt+this.#budget.queueTtlMs,features:request.estimatedFeatures,bytes:request.estimatedBytes});return true}
  startNext(now:number):IdentifyQueryView|null{this.#live();clock('now',now);this.expire(now);if(this.#phaseCount('running')>=this.#budget.maxRunning)return null;let candidate:Query|undefined;for(const q of this.#queries.values()){if(q.phase!=='queued'||this.#layerPhaseCount(q.layerId,'running')>=this.#budget.maxRunningPerLayer)continue;if(!candidate||rank[q.intent]>rank[candidate.intent]||(rank[q.intent]===rank[candidate.intent]&&(q.requestedAt<candidate.requestedAt||(q.requestedAt===candidate.requestedAt&&q.sequence<candidate.sequence))))candidate=q}if(!candidate)return null;candidate.phase='running';candidate.touchedAt=now;candidate.expiresAt=now+this.#budget.requestLeaseMs;return this.#view(candidate)}
  renew(queryId:string,revision:number,now:number):boolean{this.#live();const q=this.#queries.get(identifier('queryId',queryId));count('revision',revision);clock('now',now);this.expire(now);if(!q||q.phase!=='running'||q.revision!==revision||this.#revisions.get(q.layerId)!==revision)return false;q.touchedAt=now;q.expiresAt=now+this.#budget.requestLeaseMs;return true}
  complete(queryId:string,revision:number,features:number,bytes:number,now:number):IdentifyQueryView|null{this.#live();const key=identifier('queryId',queryId);count('revision',revision);count('features',features);count('bytes',bytes);clock('now',now);this.expire(now);const q=this.#queries.get(key);if(!q||q.phase!=='running'||q.revision!==revision||this.#revisions.get(q.layerId)!==revision)return null;if(features>this.#budget.maxFeaturesPerQuery||bytes>this.#budget.maxBytesPerQuery){this.#queries.delete(key);return null}q.features=features;q.bytes=bytes;while(this.#phaseCount('resident')>=this.#budget.maxResident||this.#layerPhaseCount(q.layerId,'resident')>=this.#budget.maxResidentPerLayer||this.#residentFeatures()+features>this.#budget.maxResidentFeatures||this.#residentBytes()+bytes>this.#budget.maxResidentBytes){const victim=this.#residentVictim(q.layerId);if(!victim){this.#queries.delete(key);return null}this.#queries.delete(victim.queryId)}q.phase='resident';q.touchedAt=now;q.expiresAt=now+this.#budget.residentTtlMs;return this.#view(q)}
  touch(queryId:string,revision:number,now:number):boolean{this.#live();const q=this.#queries.get(identifier('queryId',queryId));count('revision',revision);clock('now',now);this.expire(now);if(!q||q.phase!=='resident'||q.revision!==revision||this.#revisions.get(q.layerId)!==revision)return false;q.touchedAt=now;q.expiresAt=now+this.#budget.residentTtlMs;return true}
  consume(queryId:string,revision:number):IdentifyQueryView|null{this.#live();const key=identifier('queryId',queryId);count('revision',revision);const q=this.#queries.get(key);if(!q||q.phase!=='resident'||q.revision!==revision||this.#revisions.get(q.layerId)!==revision)return null;this.#queries.delete(key);return this.#view(q)}
  cancel(queryId:string):boolean{this.#live();return this.#queries.delete(identifier('queryId',queryId))}
  releaseLayer(layerId:string):number{this.#live();const layer=identifier('layerId',layerId);let removed=0;for(const[key,q]of this.#queries)if(q.layerId===layer){this.#queries.delete(key);removed++}this.#revisions.delete(layer);return removed}
  expire(now:number):number{this.#live();clock('now',now);let removed=0;for(const[key,q]of this.#queries)if(q.expiresAt<=now){this.#queries.delete(key);removed++}return removed}
  snapshot():Readonly<{layers:number;queries:number;queued:number;running:number;resident:number;residentFeatures:number;residentBytes:number}>{this.#live();return Object.freeze({layers:this.#revisions.size,queries:this.#queries.size,queued:this.#phaseCount('queued'),running:this.#phaseCount('running'),resident:this.#phaseCount('resident'),residentFeatures:this.#residentFeatures(),residentBytes:this.#residentBytes()})}
  fingerprint():string{this.#live();return[...this.#queries.values()].sort((a,b)=>a.layerId.localeCompare(b.layerId)||a.sequence-b.sequence).map(q=>`${q.layerId}:${q.queryId}:${q.revision}:${q.intent}:${q.phase}:${q.features}:${q.bytes}`).join('|')}
  dispose():void{if(this.#disposed)return;this.#queries.clear();this.#revisions.clear();this.#disposed=true}
  #residentVictim(preferredLayer:string):Query|undefined{const residents=[...this.#queries.values()].filter(q=>q.phase==='resident');residents.sort((a,b)=>(a.layerId===preferredLayer?0:1)-(b.layerId===preferredLayer?0:1)||rank[a.intent]-rank[b.intent]||a.touchedAt-b.touchedAt||a.sequence-b.sequence);return residents[0]}
  #layerCount(layerId:string):number{let n=0;for(const q of this.#queries.values())if(q.layerId===layerId)n++;return n}
  #phaseCount(phase:IdentifyQueryPhase):number{let n=0;for(const q of this.#queries.values())if(q.phase===phase)n++;return n}
  #layerPhaseCount(layerId:string,phase:IdentifyQueryPhase):number{let n=0;for(const q of this.#queries.values())if(q.layerId===layerId&&q.phase===phase)n++;return n}
  #residentFeatures():number{let n=0;for(const q of this.#queries.values())if(q.phase==='resident')n+=q.features;return n}
  #residentBytes():number{let n=0;for(const q of this.#queries.values())if(q.phase==='resident')n+=q.bytes;return n}
  #view(q:Query):IdentifyQueryView{return Object.freeze({queryId:q.queryId,layerId:q.layerId,revision:q.revision,intent:q.intent,estimatedFeatures:q.estimatedFeatures,estimatedBytes:q.estimatedBytes,requestedAt:q.requestedAt,phase:q.phase,sequence:q.sequence,touchedAt:q.touchedAt,expiresAt:q.expiresAt,features:q.features,bytes:q.bytes})}
  #live():void{if(this.#disposed)throw new Error('identify query lifecycle policy is disposed')}
}
