import { describe, expect, it } from 'vitest'
import { ArcGisIdentifyQueryLifecyclePolicy, type IdentifyQueryBudget, type IdentifyQueryRequest } from './ArcGisIdentifyQueryLifecyclePolicy'

const budget: IdentifyQueryBudget = { maxLayers:3,maxQueries:6,maxQueriesPerLayer:4,maxRunning:2,maxRunningPerLayer:1,maxResident:3,maxResidentPerLayer:2,maxFeaturesPerQuery:20,maxBytesPerQuery:2000,maxResidentFeatures:40,maxResidentBytes:4000,queueTtlMs:100,requestLeaseMs:50,residentTtlMs:200 }
const request=(queryId:string,layerId='parcels',revision=1,intent:IdentifyQueryRequest['intent']='visible',requestedAt=0):IdentifyQueryRequest=>({queryId,layerId,revision,intent,estimatedFeatures:5,estimatedBytes:500,requestedAt})
const policy=(custom:Partial<IdentifyQueryBudget>={})=>new ArcGisIdentifyQueryLifecyclePolicy({...budget,...custom})

describe('ArcGisIdentifyQueryLifecyclePolicy',()=>{
  it('validates bounded budgets',()=>{ expect(()=>policy({maxLayers:0})).toThrow(); expect(()=>policy({maxQueriesPerLayer:7})).toThrow(); expect(()=>policy({maxRunningPerLayer:3})).toThrow(); expect(()=>policy({maxResidentPerLayer:4})).toThrow(); expect(()=>policy({maxResidentBytes:1000})).toThrow() })
  it('requires current revision before admission',()=>{const s=policy();expect(s.admit(request('a'))).toBe(false);expect(s.setRevision('parcels',1)).toBe(0);expect(s.admit(request('a'))).toBe(true)})
  it('rejects unsafe scalar input',()=>{const s=policy();s.setRevision('parcels',1);expect(()=>s.admit(request(''))).toThrow();expect(()=>s.admit(request('bad\nvalue'))).toThrow();expect(()=>s.admit({...request('a'),estimatedFeatures:0})).toThrow();expect(()=>s.admit({...request('a'),estimatedBytes:Number.NaN})).toThrow();expect(()=>s.admit({...request('a'),intent:'other' as never})).toThrow()})
  it('rejects over-budget requests',()=>{const s=policy();s.setRevision('parcels',1);expect(s.admit({...request('a'),estimatedFeatures:21})).toBe(false);expect(s.admit({...request('b'),estimatedBytes:2001})).toBe(false)})
  it('enforces global and layer cardinality',()=>{const s=policy({maxQueries:3,maxQueriesPerLayer:2});s.setRevision('a',1);s.setRevision('b',1);expect(s.admit(request('a1','a'))).toBe(true);expect(s.admit(request('a2','a'))).toBe(true);expect(s.admit(request('a3','a'))).toBe(false);expect(s.admit(request('b1','b'))).toBe(true);expect(s.admit(request('b2','b'))).toBe(false)})
  it('schedules intent deterministically',()=>{const s=policy({maxRunning:3,maxRunningPerLayer:3});s.setRevision('p',1);s.admit(request('b','p',1,'background'));s.admit(request('v','p',1,'visible'));s.admit(request('i','p',1,'interactive'));expect(s.startNext(1)?.queryId).toBe('i');expect(s.startNext(2)?.queryId).toBe('v');expect(s.startNext(3)?.queryId).toBe('b')})
  it('honors FIFO ties',()=>{const s=policy({maxRunning:2,maxRunningPerLayer:2});s.setRevision('p',1);s.admit(request('first','p',1,'visible',3));s.admit(request('second','p',1,'visible',3));expect(s.startNext(4)?.queryId).toBe('first');expect(s.startNext(5)?.queryId).toBe('second')})
  it('enforces running concurrency',()=>{const s=policy({maxRunning:1});s.setRevision('a',1);s.setRevision('b',1);s.admit(request('a','a'));s.admit(request('b','b'));expect(s.startNext(1)?.queryId).toBe('a');expect(s.startNext(2)).toBeNull()})
  it('enforces per-layer running concurrency',()=>{const s=policy({maxRunning:2,maxRunningPerLayer:1});s.setRevision('a',1);s.setRevision('b',1);s.admit(request('a1','a'));s.admit(request('a2','a'));s.admit(request('b1','b'));expect(s.startNext(1)?.queryId).toBe('a1');expect(s.startNext(2)?.queryId).toBe('b1')})
  it('invalidates stale revision work',()=>{const s=policy();s.setRevision('p',1);s.admit(request('a','p'));s.startNext(1);expect(s.setRevision('p',2)).toBe(1);expect(s.complete('a',1,1,1,2)).toBeNull();expect(s.setRevision('p',1)).toBe(-1)})
  it('reconciles actual feature and byte counts',()=>{const s=policy();s.setRevision('p',1);s.admit(request('a','p'));s.startNext(1);const done=s.complete('a',1,7,777,2);expect(done?.phase).toBe('resident');expect(done?.features).toBe(7);expect(done?.bytes).toBe(777);expect(s.snapshot().residentBytes).toBe(777)})
  it('drops oversized actual results',()=>{const s=policy();s.setRevision('p',1);s.admit(request('a','p'));s.startNext(1);expect(s.complete('a',1,21,500,2)).toBeNull();expect(s.snapshot().queries).toBe(0)})
  it('evicts resident pressure deterministically',()=>{const s=policy({maxResident:1,maxResidentPerLayer:1});s.setRevision('p',1);s.admit(request('old','p',1,'background'));s.startNext(1);s.complete('old',1,5,500,2);s.admit(request('new','p',1,'interactive',3));s.startNext(3);expect(s.complete('new',1,5,500,4)?.queryId).toBe('new');expect(s.consume('old',1)).toBeNull();expect(s.consume('new',1)?.queryId).toBe('new')})
  it('renews only live running work',()=>{const s=policy();s.setRevision('p',1);s.admit(request('a','p'));s.startNext(1);expect(s.renew('a',1,10)).toBe(true);expect(s.renew('a',2,11)).toBe(false)})
  it('touches resident TTL',()=>{const s=policy();s.setRevision('p',1);s.admit(request('a','p'));s.startNext(1);s.complete('a',1,5,500,2);expect(s.touch('a',1,100)).toBe(true);expect(s.expire(250)).toBe(0);expect(s.expire(301)).toBe(1)})
  it('expires queued and running leases',()=>{const s=policy();s.setRevision('p',1);s.admit(request('q','p'));expect(s.expire(100)).toBe(1);s.admit(request('r','p',1,'visible',101));s.startNext(102);expect(s.expire(152)).toBe(1)})
  it('supports cancellation and layer release',()=>{const s=policy();s.setRevision('a',1);s.setRevision('b',1);s.admit(request('a1','a'));s.admit(request('a2','a'));s.admit(request('b1','b'));expect(s.cancel('a1')).toBe(true);expect(s.releaseLayer('a')).toBe(1);expect(s.snapshot().layers).toBe(1)})
  it('keeps snapshots aggregate and fingerprints scalar',()=>{const s=policy();s.setRevision('p',1);s.admit(request('a','p'));const snap=s.snapshot();expect(snap).toEqual({layers:1,queries:1,queued:1,running:0,resident:0,residentFeatures:0,residentBytes:0});expect(Object.isFrozen(snap)).toBe(true);expect(s.fingerprint()).toContain('p:a:1:visible:queued')})
  it('disposes terminally',()=>{const s=policy();s.setRevision('p',1);s.admit(request('a','p'));s.dispose();s.dispose();expect(()=>s.snapshot()).toThrow(/disposed/);expect(()=>s.admit(request('b','p'))).toThrow(/disposed/)})
})
