import { describe, expect, it } from 'vitest'
import { ArcGisEditValidationPolicy, type ArcGisEditLayerSchema, type ArcGisEditFeatureMutation } from './ArcGisEditValidationPolicy'
const budget={maxSchemas:3,maxFieldsPerSchema:12,maxFeaturesPerBatch:3,maxAttributesPerFeature:6,maxStringLength:32,maxFieldNameLength:32,maxAttributeBytesPerFeature:128,maxBatchAttributeBytes:256,maxVerticesPerFeature:100,maxBatchVertices:150}
const schema=(x:Partial<ArcGisEditLayerSchema>={}):ArcGisEditLayerSchema=>({layerId:'parcels',revision:1,geometryType:'polygon',wkid:102100,objectIdField:'OBJECTID',globalIdField:'GlobalID',operations:['add','update','delete'],fields:[{name:'OBJECTID',type:'oid',editable:false,nullable:false},{name:'GlobalID',type:'globalid',editable:false,nullable:false},{name:'NAME',type:'string',editable:true,nullable:false,maxLength:10},{name:'SCORE',type:'double',editable:true,nullable:true},{name:'ENABLED',type:'boolean',editable:true,nullable:false,hasDefaultValue:true},{name:'UPDATED',type:'date',editable:true,nullable:true},{name:'CODE',type:'guid',editable:true,nullable:true}],...x})
const add=(x:Partial<ArcGisEditFeatureMutation>={}):ArcGisEditFeatureMutation=>({clientId:'a',geometryType:'polygon',wkid:3857,vertexCount:10,attributes:[{field:'NAME',value:'Parcel'}],...x})
const update=(x:Partial<ArcGisEditFeatureMutation>={}):ArcGisEditFeatureMutation=>({clientId:'u',objectId:42,geometryType:'none',wkid:0,vertexCount:0,attributes:[{field:'SCORE',value:2}],...x})
const policy=()=>{const p=new ArcGisEditValidationPolicy(budget);p.registerSchema(schema());return p}
describe('ArcGisEditValidationPolicy',()=>{
 it('registers canonical bounded schema',()=>{const p=new ArcGisEditValidationPolicy(budget);expect(p.registerSchema(schema())).toEqual(expect.objectContaining({layerId:'parcels',revision:1,fieldCount:7}));expect(p.snapshot()).toEqual([{layerId:'parcels',revision:1,fieldCount:7}])})
 it('requires monotonic schema revisions',()=>{const p=policy();expect(()=>p.registerSchema(schema())).toThrow(/revision/);expect(()=>p.registerSchema(schema({revision:2}))).not.toThrow();expect(p.currentRevision('parcels')).toBe(2)})
 it('rejects duplicate fields and bad identity metadata',()=>{expect(()=>new ArcGisEditValidationPolicy(budget).registerSchema(schema({fields:[...schema().fields,{name:'name',type:'string',editable:true,nullable:true}]}))).toThrow(/duplicate/);expect(()=>new ArcGisEditValidationPolicy(budget).registerSchema(schema({objectIdField:'NAME'}))).toThrow(/oid/)})
 it('requires mutation identity metadata',()=>{expect(()=>new ArcGisEditValidationPolicy(budget).registerSchema(schema({objectIdField:undefined,globalIdField:undefined}))).toThrow(/identity/)})
 it('creates immutable payload-free plans',()=>{const plan=policy().validate({layerId:'parcels',revision:1,operation:'add',features:[add()]});expect(plan.featureCount).toBe(1);expect(plan.vertexCount).toBe(10);expect(Object.isFrozen(plan)).toBe(true);expect(plan).not.toHaveProperty('features');expect(plan).not.toHaveProperty('geometry')})
 it('is deterministic across feature ordering',()=>{const p=policy(),a=add({clientId:'a'}),b=add({clientId:'b'});const x=p.validate({layerId:'parcels',revision:1,operation:'add',features:[b,a]}),y=p.validate({layerId:'parcels',revision:1,operation:'add',features:[a,b]});expect(x.fingerprint).toBe(y.fingerprint)})
 it('rejects stale revision and unsupported operation',()=>{const p=new ArcGisEditValidationPolicy(budget);p.registerSchema(schema({operations:['add']}));expect(()=>p.validate({layerId:'parcels',revision:0,operation:'add',features:[add()]})).toThrow(/stale/);expect(()=>p.validate({layerId:'parcels',revision:1,operation:'delete',features:[update({attributes:[]})]})).toThrow(/advertised/)})
 it('bounds feature cardinality and duplicate client ids',()=>{const p=policy();expect(()=>p.validate({layerId:'parcels',revision:1,operation:'add',features:[add({clientId:'x'}),add({clientId:'x'})]})).toThrow(/duplicate/);expect(()=>p.validate({layerId:'parcels',revision:1,operation:'add',features:[add({clientId:'a'}),add({clientId:'b'}),add({clientId:'c'}),add({clientId:'d'})]})).toThrow(/feature-budget/)})
 it('requires identity on update and forbids server identity on add',()=>{const p=policy();expect(()=>p.validate({layerId:'parcels',revision:1,operation:'update',features:[update({objectId:undefined})]})).toThrow(/identity-required/);expect(()=>p.validate({layerId:'parcels',revision:1,operation:'add',features:[add({objectId:1})]})).toThrow(/add-cannot/)})
 it('accepts global id identity transiently',()=>{const plan=policy().validate({layerId:'parcels',revision:1,operation:'update',features:[update({objectId:undefined,globalId:'{550e8400-e29b-41d4-a716-446655440000}'})]});expect(plan.featureCount).toBe(1);expect(plan).not.toHaveProperty('globalId')})
 it('enforces geometry and spatial reference',()=>{const p=policy();expect(()=>p.validate({layerId:'parcels',revision:1,operation:'add',features:[add({geometryType:'polyline'})]})).toThrow(/geometry/);expect(()=>p.validate({layerId:'parcels',revision:1,operation:'add',features:[add({wkid:4326})]})).toThrow(/spatial/);expect(()=>p.validate({layerId:'parcels',revision:1,operation:'add',features:[add({wkid:102113})]})).not.toThrow()})
 it('bounds vertex residency',()=>{const p=policy();expect(()=>p.validate({layerId:'parcels',revision:1,operation:'add',features:[add({vertexCount:101})]})).toThrow(/vertex/)})
 it('rejects unknown duplicate and noneditable fields',()=>{const p=policy();expect(()=>p.validate({layerId:'parcels',revision:1,operation:'update',features:[update({attributes:[{field:'MISSING',value:1}]})]})).toThrow(/schema/);expect(()=>p.validate({layerId:'parcels',revision:1,operation:'update',features:[update({attributes:[{field:'SCORE',value:1},{field:'score',value:2}]})]})).toThrow(/duplicate/);expect(()=>p.validate({layerId:'parcels',revision:1,operation:'update',features:[update({attributes:[{field:'OBJECTID',value:1}]})]})).toThrow(/editable|identity/)})
 it.each([['NAME',4],['SCORE','bad'],['ENABLED',1],['UPDATED',1.5],['CODE','bad']])('rejects invalid scalar %s',(field,value)=>{expect(()=>policy().validate({layerId:'parcels',revision:1,operation:'update',features:[update({attributes:[{field,value:value as string|number}]})]})).toThrow()})
 it('requires non-nullable add fields',()=>{expect(()=>policy().validate({layerId:'parcels',revision:1,operation:'add',features:[add({attributes:[{field:'SCORE',value:1}]})]})).toThrow(/required/)})
 it('rejects nonfinite numeric values',()=>{expect(()=>policy().validate({layerId:'parcels',revision:1,operation:'update',features:[update({attributes:[{field:'SCORE',value:Infinity}]})]})).toThrow(/double/)})
 it('supports release and fail-closed disposal',()=>{const p=policy();expect(p.releaseLayer('parcels')).toBe(true);expect(()=>p.validate({layerId:'parcels',revision:1,operation:'add',features:[add()]})).toThrow(/registered/);p.dispose();expect(()=>p.snapshot()).toThrow(/disposed/)})
})
