export type ArcGisLayerKind='feature'|'map-image'|'scene'|'graphics'
export type ArcGisLayerPhase='declared'|'loading'|'ready'|'suspended'|'failed'|'disposed'
export interface ArcGisLayerDescriptor{readonly id:string;readonly kind:ArcGisLayerKind;readonly serviceId?:string;readonly layerId?:number;readonly minScale?:number;readonly maxScale?:number;readonly visible:boolean;readonly opacity:number;readonly order:number;readonly estimatedGpuBytes:number;readonly estimatedCpuBytes:number}
export interface ArcGisLayerLifecycleBudget{readonly maxLayers:number;readonly maxActiveLayers:number;readonly maxGpuBytes:number;readonly maxCpuBytes:number;readonly maxObservers:number;readonly maxFailureMessageLength:number}
export interface ArcGisLayerSnapshot{readonly revision:number;readonly layers:readonly ArcGisLayerState[];readonly activeCount:number;readonly gpuBytes:number;readonly cpuBytes:number}
export interface ArcGisLayerState extends ArcGisLayerDescriptor{readonly phase:ArcGisLayerPhase;readonly failure?:string;readonly generation:number}
export interface ArcGisLayerLoadToken{readonly id:string;readonly generation:number}
export type ArcGisLayerObserver=(snapshot:ArcGisLayerSnapshot)=>void
const MAX_BYTES=1024*1024*1024,MAX_LAYERS=10000
function int(v:number,n:string,min:number,max:number){if(!Number.isSafeInteger(v)||v<min||v>max)throw new Error(`${n} must be an integer in [${min}, ${max}]`);return v}
function finite(v:number,n:string,min:number,max:number){if(!Number.isFinite(v)||v<min||v>max)throw new Error(`${n} must be finite in [${min}, ${max}]`);return v}
function id(v:string){const x=v.trim();if(!x||x.length>256||/[\u0000-\u001f\u007f]/.test(x))throw new Error('invalid layer id');return x}
function active(phase:ArcGisLayerPhase){return phase==='loading'||phase==='ready'}
function normalize(d:ArcGisLayerDescriptor):ArcGisLayerDescriptor{const normalizedId=id(d.id);if(d.serviceId!==undefined)id(d.serviceId);if(d.layerId!==undefined)int(d.layerId,'layerId',0,100000);if(d.minScale!==undefined)finite(d.minScale,'minScale',0,Number.MAX_SAFE_INTEGER);if(d.maxScale!==undefined)finite(d.maxScale,'maxScale',0,Number.MAX_SAFE_INTEGER);if(d.minScale!==undefined&&d.maxScale!==undefined&&d.minScale>0&&d.maxScale>0&&d.minScale<d.maxScale)throw new Error('minScale must be >= maxScale for ArcGIS scale semantics');finite(d.opacity,'opacity',0,1);int(d.order,'order',-100000,100000);int(d.estimatedGpuBytes,'estimatedGpuBytes',0,MAX_BYTES);int(d.estimatedCpuBytes,'estimatedCpuBytes',0,MAX_BYTES);if((d.kind==='feature'||d.kind==='map-image'||d.kind==='scene')&&!d.serviceId)throw new Error(`${d.kind} layer requires serviceId`);return Object.freeze({...d,id:normalizedId})}
export class ArcGisLayerLifecycle{private readonly budget:ArcGisLayerLifecycleBudget;private readonly states=new Map<string,ArcGisLayerState>();private readonly observers=new Set<ArcGisLayerObserver>();private revision=0;private disposed=false
constructor(budget:ArcGisLayerLifecycleBudget){this.budget=Object.freeze({maxLayers:int(budget.maxLayers,'maxLayers',1,MAX_LAYERS),maxActiveLayers:int(budget.maxActiveLayers,'maxActiveLayers',1,MAX_LAYERS),maxGpuBytes:int(budget.maxGpuBytes,'maxGpuBytes',1,MAX_BYTES),maxCpuBytes:int(budget.maxCpuBytes,'maxCpuBytes',1,MAX_BYTES),maxObservers:int(budget.maxObservers,'maxObservers',1,10000),maxFailureMessageLength:int(budget.maxFailureMessageLength,'maxFailureMessageLength',16,4096)})}
declare(descriptor:ArcGisLayerDescriptor){this.assertAlive();const d=normalize(descriptor);if(this.states.has(d.id))throw new Error(`duplicate layer id:${d.id}`);if(this.states.size>=this.budget.maxLayers)throw new Error('layer budget exceeded');this.states.set(d.id,Object.freeze({...d,phase:'declared' as const,generation:0}));this.commit();return this.require(d.id)}
remove(layerId:string){this.assertAlive();const key=id(layerId),current=this.states.get(key);if(!current)return false;this.states.delete(key);this.commit();return true}
beginLoad(layerId:string):ArcGisLayerLoadToken{this.assertAlive();const current=this.require(id(layerId));if(current.phase==='disposed')throw new Error('layer disposed');const next=Object.freeze({...current,phase:'loading' as const,failure:undefined,generation:current.generation+1});this.assertResources(next,current);this.states.set(current.id,next);this.commit();return Object.freeze({id:current.id,generation:next.generation})}
resolve(token:ArcGisLayerLoadToken){this.assertAlive();const current=this.requireToken(token);if(current.phase!=='loading')return false;const next=Object.freeze({...current,phase:'ready' as const});this.states.set(current.id,next);this.commit();return true}
fail(token:ArcGisLayerLoadToken,message:string){this.assertAlive();const current=this.requireToken(token);if(current.phase!=='loading')return false;const failure=message.trim().replace(/[\u0000-\u001f\u007f]/g,' ').slice(0,this.budget.maxFailureMessageLength)||'ArcGIS layer load failed';this.states.set(current.id,Object.freeze({...current,phase:'failed' as const,failure}));this.commit();return true}
suspend(layerId:string){this.assertAlive();const current=this.require(id(layerId));if(current.phase==='disposed')return false;if(current.phase==='suspended')return true;this.states.set(current.id,Object.freeze({...current,phase:'suspended' as const,generation:current.generation+1,failure:undefined}));this.commit();return true}
resume(layerId:string){return this.beginLoad(layerId)}
setVisibility(layerId:string,visible:boolean){this.assertAlive();const current=this.require(id(layerId));if(current.visible===visible)return current;const next=Object.freeze({...current,visible});this.states.set(current.id,next);this.commit();return next}
setOpacity(layerId:string,opacity:number){this.assertAlive();const current=this.require(id(layerId));const value=finite(opacity,'opacity',0,1);if(current.opacity===value)return current;const next=Object.freeze({...current,opacity:value});this.states.set(current.id,next);this.commit();return next}
reorder(layerId:string,order:number){this.assertAlive();const current=this.require(id(layerId));const value=int(order,'order',-100000,100000);if(current.order===value)return current;const next=Object.freeze({...current,order:value});this.states.set(current.id,next);this.commit();return next}
replaceResourceEstimate(layerId:string,gpuBytes:number,cpuBytes:number){this.assertAlive();const current=this.require(id(layerId));const next=Object.freeze({...current,estimatedGpuBytes:int(gpuBytes,'gpuBytes',0,MAX_BYTES),estimatedCpuBytes:int(cpuBytes,'cpuBytes',0,MAX_BYTES)});this.assertResources(next,current);this.states.set(current.id,next);this.commit();return next}
snapshot():ArcGisLayerSnapshot{let activeCount=0,gpuBytes=0,cpuBytes=0;const layers=[...this.states.values()].sort((a,b)=>a.order-b.order||a.id.localeCompare(b.id));for(const layer of layers)if(active(layer.phase)){activeCount++;gpuBytes+=layer.estimatedGpuBytes;cpuBytes+=layer.estimatedCpuBytes}return Object.freeze({revision:this.revision,layers:Object.freeze(layers),activeCount,gpuBytes,cpuBytes})}
subscribe(observer:ArcGisLayerObserver){this.assertAlive();if(this.observers.size>=this.budget.maxObservers)throw new Error('observer budget exceeded');this.observers.add(observer);return()=>this.observers.delete(observer)}
dispose(){if(this.disposed)return;this.disposed=true;this.states.clear();this.observers.clear();this.revision++}
private assertResources(next:ArcGisLayerState,previous:ArcGisLayerState){let count=0,gpu=0,cpu=0;for(const state of this.states.values()){const candidate=state.id===previous.id?next:state;if(active(candidate.phase)){count++;gpu+=candidate.estimatedGpuBytes;cpu+=candidate.estimatedCpuBytes}}if(count>this.budget.maxActiveLayers)throw new Error('active layer budget exceeded');if(gpu>this.budget.maxGpuBytes)throw new Error('GPU layer budget exceeded');if(cpu>this.budget.maxCpuBytes)throw new Error('CPU layer budget exceeded')}
private require(layerId:string){const state=this.states.get(layerId);if(!state)throw new Error(`unknown layer:${layerId}`);return state}
private requireToken(token:ArcGisLayerLoadToken){const current=this.require(id(token.id));if(current.generation!==token.generation)throw new Error('stale layer load token');return current}
private assertAlive(){if(this.disposed)throw new Error('layer lifecycle disposed')}
private commit(){this.revision++;if(!this.observers.size)return;const snapshot=this.snapshot();for(const observer of [...this.observers]){try{observer(snapshot)}catch{}}}}
