export type ArcGisFeaturePageIntent = 'interactive' | 'visible' | 'background'
export interface ArcGisFeaturePageCacheBudget { maxEntries:number; maxEntriesPerLayer:number; maxObjectIdsPerPage:number; maxBytesPerPage:number; maxAggregateBytes:number; ttlMs:number }
export interface ArcGisFeaturePageDescriptor { layerId:string; pageKey:string; revision:number; intent:ArcGisFeaturePageIntent; objectIdCount:number; byteSize:number; storedAt:number; expiresAt:number; fingerprint:string }
type Entry=ArcGisFeaturePageDescriptor&{sequence:number;lastAccessedAt:number}
const rank:Record<ArcGisFeaturePageIntent,number>={interactive:0,visible:1,background:2};const SEP='\u0000'
/** Scalar-only bounded authority for FeatureServer page-cache metadata. */
export class ArcGisFeaturePageCachePolicy{
 private readonly entries=new Map<string,Entry>();private readonly revisions=new Map<string,number>();private sequence=0;private disposed=false
 constructor(private readonly budget:ArcGisFeaturePageCacheBudget){for(const [n,v] of Object.entries(budget))this.positive(v,n);if(budget.maxEntriesPerLayer>budget.maxEntries)throw new RangeError('per-layer entries exceed global entries');if(budget.maxBytesPerPage>budget.maxAggregateBytes)throw new RangeError('page bytes exceed aggregate bytes')}
 put(input:Omit<ArcGisFeaturePageDescriptor,'expiresAt'>):boolean{this.active();const p=this.normalize(input),watermark=this.revisions.get(p.layerId)??0;if(p.revision<watermark)return false;const key=this.key(p.layerId,p.pageKey),old=this.entries.get(key);if(old&&p.revision<old.revision)return false;if(p.objectIdCount>this.budget.maxObjectIdsPerPage||p.byteSize>this.budget.maxBytesPerPage)return false;this.release(e=>p.storedAt>=e.expiresAt);const current=this.entries.get(key),advances=p.revision>watermark,survives=(e:Entry)=>e!==current&&!(advances&&e.layerId===p.layerId&&e.revision<p.revision);if(this.count(e=>survives(e)&&e.layerId===p.layerId)+1>this.budget.maxEntriesPerLayer)return false;if(!this.canFit(p,survives))return false;if(advances)this.invalidateLayer(p.layerId,p.revision);else if(current)this.entries.delete(key);this.revisions.set(p.layerId,Math.max(watermark,p.revision));this.evictUntilFits(p);if(this.entries.size>=this.budget.maxEntries)this.evictOne(p);if(this.entries.size>=this.budget.maxEntries||this.totalBytes()+p.byteSize>this.budget.maxAggregateBytes)return false;this.entries.set(key,{...p,expiresAt:p.storedAt+this.budget.ttlMs,lastAccessedAt:p.storedAt,sequence:this.sequence++});return true}
 get(layerId:string,pageKey:string,revision:number,now:number):ArcGisFeaturePageDescriptor|undefined{this.active();this.timestamp(now);this.positive(revision,'revision');const l=this.id(layerId,'layerId'),p=this.id(pageKey,'pageKey'),e=this.entries.get(this.key(l,p));if(!e||e.revision!==revision||revision<(this.revisions.get(l)??0))return undefined;if(now>=e.expiresAt){this.entries.delete(this.key(l,p));return undefined}e.lastAccessedAt=Math.max(e.lastAccessedAt,now);return this.detach(e)}
 invalidateLayer(layerId:string,revision:number):number{this.active();const l=this.id(layerId,'layerId');this.positive(revision,'revision');const current=this.revisions.get(l)??0;if(revision<=current)return 0;this.revisions.set(l,revision);return this.release(e=>e.layerId===l&&e.revision<revision)}
 expire(now:number){this.active();this.timestamp(now);return this.release(e=>now>=e.expiresAt)} releaseLayer(layerId:string){this.active();const l=this.id(layerId,'layerId');this.revisions.delete(l);return this.release(e=>e.layerId===l)} snapshot(){this.active();return [...this.entries.values()].sort((a,b)=>a.sequence-b.sequence).map(e=>this.detach(e))} fingerprint(){return this.snapshot().map(e=>`${e.layerId}:${e.pageKey}:${e.revision}:${e.intent}:${e.objectIdCount}:${e.byteSize}:${e.fingerprint}`).join('|')} dispose(){if(!this.disposed){this.entries.clear();this.revisions.clear();this.disposed=true}}
 private canFit(c:Omit<ArcGisFeaturePageDescriptor,'expiresAt'>,survives:(e:Entry)=>boolean){let count=this.count(survives),bytes=this.sumBytes(survives);if(count+1<=this.budget.maxEntries&&bytes+c.byteSize<=this.budget.maxAggregateBytes)return true;for(const e of this.order(c).filter(survives)){count--;bytes-=e.byteSize;if(count+1<=this.budget.maxEntries&&bytes+c.byteSize<=this.budget.maxAggregateBytes)return true}return false}
 private evictUntilFits(c:Omit<ArcGisFeaturePageDescriptor,'expiresAt'>){for(const e of this.order(c)){if(this.entries.size<this.budget.maxEntries&&this.totalBytes()+c.byteSize<=this.budget.maxAggregateBytes)return;this.entries.delete(this.key(e.layerId,e.pageKey))}} private evictOne(c:Omit<ArcGisFeaturePageDescriptor,'expiresAt'>){const v=this.order(c)[0];if(v)this.entries.delete(this.key(v.layerId,v.pageKey))} private order(c:Omit<ArcGisFeaturePageDescriptor,'expiresAt'>){return [...this.entries.values()].filter(e=>rank[e.intent]>=rank[c.intent]).sort((a,b)=>rank[b.intent]-rank[a.intent]||a.lastAccessedAt-b.lastAccessedAt||a.sequence-b.sequence)}
 private normalize(i:Omit<ArcGisFeaturePageDescriptor,'expiresAt'>){if(!(i.intent in rank))throw new Error('intent is invalid');this.positive(i.revision,'revision');this.positive(i.objectIdCount,'objectIdCount');this.nonnegative(i.byteSize,'byteSize');this.timestamp(i.storedAt);return{...i,layerId:this.id(i.layerId,'layerId'),pageKey:this.id(i.pageKey,'pageKey'),fingerprint:this.id(i.fingerprint,'fingerprint')}} private detach(e:Entry):ArcGisFeaturePageDescriptor{const{sequence:_s,lastAccessedAt:_a,...p}=e;return{...p}} private count(fn:(e:Entry)=>boolean){let n=0;for(const e of this.entries.values())if(fn(e))n++;return n} private sumBytes(fn:(e:Entry)=>boolean){let n=0;for(const e of this.entries.values())if(fn(e))n+=e.byteSize;return n} private totalBytes(){return this.sumBytes(()=>true)} private release(fn:(e:Entry)=>boolean){let n=0;for(const[k,e]of this.entries)if(fn(e)){this.entries.delete(k);n++}return n} private key(l:string,p:string){return`${l}${SEP}${p}`} private id(v:string,n:string){const x=v.trim();if(!x||x.length>160||x.includes(SEP)||x.includes(':'))throw new Error(`${n} must contain safe characters`);return x} private positive(v:number,n:string){if(!Number.isSafeInteger(v)||v<=0)throw new RangeError(`${n} must be a positive safe integer`)} private nonnegative(v:number,n:string){if(!Number.isSafeInteger(v)||v<0)throw new RangeError(`${n} must be a non-negative safe integer`)} private timestamp(v:number){if(!Number.isFinite(v)||v<0)throw new RangeError('timestamp must be finite and non-negative')} private active(){if(this.disposed)throw new Error('ArcGisFeaturePageCachePolicy is disposed')}
}
