import { describe, expect, it } from 'vitest'
import { ArcGisQueryRetryLifecyclePolicy, type QueryRetryBudget, type QueryRetryRequest } from './ArcGisQueryRetryLifecyclePolicy'

const budget: QueryRetryBudget = { maxLayers:3,maxEntries:6,maxEntriesPerLayer:4,maxRunning:2,maxRunningPerLayer:1,maxAttempts:3,baseDelayMs:10,maxDelayMs:100,maxTotalDelayMs:150,runningLeaseMs:50,entryTtlMs:200 }
const request=(retryId:string,layerId='parcels',revision=1,intent:QueryRetryRequest['intent']='visible',requestedAt=0):QueryRetryRequest=>({retryId,queryKey:`q-${retryId}`,layerId,revision,intent,requestedAt})
const policy=(custom:Partial<QueryRetryBudget>={})=>new ArcGisQueryRetryLifecyclePolicy({...budget,...custom})

describe('ArcGisQueryRetryLifecyclePolicy',()=>{
  it('validates nested budgets',()=>{expect(()=>policy({maxLayers:0})).toThrow();expect(()=>policy({maxEntriesPerLayer:7})).toThrow();expect(()=>policy({maxRunning:7})).toThrow();expect(()=>policy({maxRunningPerLayer:3})).toThrow();expect(()=>policy({baseDelayMs:101})).toThrow();expect(()=>policy({maxDelayMs:151})).toThrow()})
  it('requires current revision',()=>{const s=policy();expect(s.admit(request('a'))).toBe(false);expect(s.setRevision('parcels',1)).toBe(0);expect(s.admit(request('a'))).toBe(true)})
  it('rejects unsafe scalar input',()=>{const s=policy();s.setRevision('parcels',1);expect(()=>s.admit(request(''))).toThrow();expect(()=>s.admit({...request('a'),queryKey:'bad\nkey'})).toThrow();expect(()=>s.admit({...request('a'),requestedAt:Number.NaN})).toThrow();expect(()=>s.admit({...request('a'),intent:'other' as never})).toThrow()})
  it('dedupes logical query keys',()=>{const s=policy();s.setRevision('parcels',1);expect(s.admit(request('a'))).toBe(true);expect(s.admit({...request('b'),queryKey:'q-a'})).toBe(false)})
  it('enforces global and per-layer cardinality',()=>{const s=policy({maxEntries:3,maxEntriesPerLayer:2});s.setRevision('a',1);s.setRevision('b',1);expect(s.admit(request('a1','a'))).toBe(true);expect(s.admit(request('a2','a'))).toBe(true);expect(s.admit(request('a3','a'))).toBe(false);expect(s.admit(request('b1','b'))).toBe(true);expect(s.admit(request('b2','b'))).toBe(false)})
  it('schedules intent deterministically',()=>{const s=policy({maxRunning:3,maxRunningPerLayer:3});s.setRevision('p',1);s.admit(request('b','p',1,'background'));s.admit(request('v','p',1,'visible'));s.admit(request('i','p',1,'interactive'));expect(s.startNext(1)?.retryId).toBe('i');expect(s.startNext(2)?.retryId).toBe('v');expect(s.startNext(3)?.retryId).toBe('b')})
  it('honors FIFO ties',()=>{const s=policy({maxRunning:2,maxRunningPerLayer:2});s.setRevision('p',1);s.admit(request('first','p'));s.admit(request('second','p'));expect(s.startNext(1)?.retryId).toBe('first');expect(s.startNext(2)?.retryId).toBe('second')})
  it('enforces global running concurrency',()=>{const s=policy({maxRunning:1});s.setRevision('a',1);s.setRevision('b',1);s.admit(request('a','a'));s.admit(request('b','b'));expect(s.startNext(1)?.retryId).toBe('a');expect(s.startNext(2)).toBeNull()})
  it('enforces per-layer running concurrency',()=>{const s=policy({maxRunning:2,maxRunningPerLayer:1});s.setRevision('a',1);s.setRevision('b',1);s.admit(request('a1','a'));s.admit(request('a2','a'));s.admit(request('b1','b'));expect(s.startNext(1)?.retryId).toBe('a1');expect(s.startNext(2)?.retryId).toBe('b1')})
  it('invalidates stale revisions',()=>{const s=policy();s.setRevision('p',1);s.admit(request('a','p'));s.startNext(1);expect(s.setRevision('p',2)).toBe(1);expect(s.succeed('a',1)).toBeNull();expect(s.setRevision('p',1)).toBe(-1)})
  it('backs off retryable failures exponentially',()=>{const s=policy();s.setRevision('p',1);s.admit(request('a','p'));s.startNext(0);const first=s.fail('a',1,503,1);expect(first?.phase).toBe('waiting');expect(first?.readyAt).toBe(11);expect(s.startNext(10)).toBeNull();expect(s.startNext(11)?.attempt).toBe(2);const second=s.fail('a',1,503,12);expect(second?.readyAt).toBe(32);expect(second?.totalDelayMs).toBe(30)})
  it('honors bounded retry-after hints',()=>{const s=policy();s.setRevision('p',1);s.admit(request('a','p'));s.startNext(0);const v=s.fail('a',1,429,1,80);expect(v?.readyAt).toBe(81);expect(v?.totalDelayMs).toBe(80)})
  it('caps retry-after at max delay',()=>{const s=policy();s.setRevision('p',1);s.admit(request('a','p'));s.startNext(0);expect(s.fail('a',1,429,1,999)?.readyAt).toBe(101)})
  it('does not retry terminal HTTP status',()=>{const s=policy();s.setRevision('p',1);s.admit(request('a','p'));s.startNext(0);expect(s.fail('a',1,400,1)?.phase).toBe('exhausted');expect(s.startNext(2)).toBeNull()})
  it('exhausts max attempts',()=>{const s=policy({baseDelayMs:0});s.setRevision('p',1);s.admit(request('a','p'));s.startNext(0);s.fail('a',1,503,1);s.startNext(1);s.fail('a',1,503,2);s.startNext(2);expect(s.fail('a',1,503,3)?.phase).toBe('exhausted')})
  it('exhausts total delay budget',()=>{const s=policy({baseDelayMs:80,maxDelayMs:100,maxTotalDelayMs:150});s.setRevision('p',1);s.admit(request('a','p'));s.startNext(0);s.fail('a',1,503,1);s.startNext(81);expect(s.fail('a',1,503,82)?.phase).toBe('exhausted')})
  it('renews only current running work',()=>{const s=policy();s.setRevision('p',1);s.admit(request('a','p'));s.startNext(1);expect(s.renew('a',1,10)).toBe(true);expect(s.renew('a',2,11)).toBe(false)})
  it('removes successful retry authority',()=>{const s=policy();s.setRevision('p',1);s.admit(request('a','p'));s.startNext(1);expect(s.succeed('a',1)?.attempt).toBe(1);expect(s.snapshot().entries).toBe(0)})
  it('expires abandoned running work',()=>{const s=policy();s.setRevision('p',1);s.admit(request('a','p'));s.startNext(1);expect(s.expire(50)).toBe(0);expect(s.expire(51)).toBe(1)})
  it('supports cancellation and layer release',()=>{const s=policy();s.setRevision('a',1);s.setRevision('b',1);s.admit(request('a1','a'));s.admit(request('a2','a'));s.admit(request('b1','b'));expect(s.cancel('a1')).toBe(true);expect(s.releaseLayer('a')).toBe(1);expect(s.snapshot().layers).toBe(1)})
  it('keeps snapshots aggregate and fingerprints scalar',()=>{const s=policy();s.setRevision('p',1);s.admit(request('a','p'));const snap=s.snapshot();expect(snap).toEqual({layers:1,entries:1,waiting:0,ready:1,running:0,exhausted:0,attempts:0,totalDelayMs:0});expect(Object.isFrozen(snap)).toBe(true);expect(s.fingerprint()).toContain('p:q-a:1:visible:ready')})
  it('disposes terminally',()=>{const s=policy();s.setRevision('p',1);s.admit(request('a','p'));s.dispose();s.dispose();expect(()=>s.snapshot()).toThrow(/disposed/);expect(()=>s.admit(request('b','p'))).toThrow(/disposed/)})
})
