export type ArcGisLabelPlacementIntent='selected'|'visible'|'background'
export type ArcGisLabelPlacementPhase='queued'|'placing'|'resident'
export interface ArcGisLabelPlacementBudget{maxBatches:number;maxBatchesPerView:number;maxPlacing:number;maxResident:number;maxLabelsPerBatch:number;maxGlyphsPerBatch:number;maxEstimatedBytesPerBatch:number;maxAggregateResidentBytes:number;queueTtlMs:number;placeLeaseMs:number;residentTtlMs:number}
export interface ArcGisLabelPlacementRequest{viewId:string;layerId:string;batchId:string;revision:number;intent:ArcGisLabelPlacementIntent;requestedAt:number;lod:number;labelCount:number;glyphCount:number;estimatedBytes:number}
export interface ArcGisLabelPlacementEntry extends ArcGisLabelPlacementRequest{phase:ArcGisLabelPlacementPhase;sequence:number;expiresAt:number;placedLabels?:number;actualBytes?:number}
const rank:Record<ArcGisLabelPlacementIntent,number>={selected:0,visible:1,background:2};const safe=/^[A-Za-z0-9_.:@/-]{1,180}$/;const pos=(v:number)=>Number.isSafeInteger(v)&&v>0;const nn=(v:number)=>Number.isSafeInteger(v)&&v>=0
export class ArcGisLabelPlacementLifecyclePolicy{
 private entries=new Map<string,ArcGisLabelPlacementEntry>();private revisions=new Map<string,number>();private sequence=0
 constructor(private budget:ArcGisLabelPlacementBudget){const v=[budget.maxBatches,budget.maxBatchesPerView,budget.maxPlacing,budget.maxResident,budget.maxLabelsPerBatch,budget.maxGlyphsPerBatch,budget.maxEstimatedBytesPerBatch,budget.maxAggregateResidentBytes,budget.queueTtlMs,budget.placeLeaseMs,budget.residentTtlMs];if(!v.every(pos))throw new RangeError('label budgets must be positive safe integers');if(budget.maxBatchesPerView>budget.maxBatches||budget.maxPlacing>budget.maxBatches||budget.maxResident>budget.maxBatches)throw new RangeError('label sub-budget exceeds aggregate')}
 enqueue(raw:ArcGisLabelPlacementRequest):boolean{const r=this.normalize(raw);if(!r)return false;const w=this.revisions.get(r.viewId)??0;if(r.revision<w)return false;const k=this.key(r.viewId,r.layerId,r.batchId),old=this.entries.get(k);if(old&&r.revision<=old.revision)return false;const count=[...this.entries.values()].filter(e=>e.viewId===r.viewId&&this.key(e.viewId,e.layerId,e.batchId)!==k).length;if(count>=this.budget.maxBatchesPerView||(!old&&this.entries.size>=this.budget.maxBatches))return false;if(old)this.entries.delete(k);this.revisions.set(r.viewId,Math.max(w,r.revision));this.entries.set(k,{...r,phase:'queued',sequence:++this.sequence,expiresAt:r.requestedAt+this.budget.queueTtlMs});return true}
 takeNext(now:number):ArcGisLabelPlacementEntry|undefined{if(!Number.isFinite(now))return;this.expire(now);if([...this.entries.values()].filter(e=>e.phase==='placing').length>=this.budget.maxPlacing)return;const n=[...this.entries.values()].filter(e=>e.phase==='queued').sort((a,b)=>rank[a.intent]-rank[b.intent]||b.lod-a.lod||a.requestedAt-b.requestedAt||a.sequence-b.sequence)[0];if(!n)return;n.phase='placing';n.expiresAt=now+this.budget.placeLeaseMs;return{...n}}
 complete(viewId:string,layerId:string,batchId:string,revision:number,placedLabels:number,actualBytes:number,now:number):boolean{const e=this.get(viewId,layerId,batchId);if(!e||e.phase!=='placing'||e.revision!==revision||!nn(placedLabels)||placedLabels>e.labelCount||!nn(actualBytes)||!Number.isFinite(now))return false;const k=this.key(e.viewId,e.layerId,e.batchId);if(now>=e.expiresAt||revision<(this.revisions.get(e.viewId)??0)){this.entries.delete(k);return false}if(actualBytes>this.budget.maxEstimatedBytesPerBatch){this.entries.delete(k);return false}const resident=[...this.entries.values()].filter(x=>x.phase==='resident');if(resident.length>=this.budget.maxResident||resident.reduce((s,x)=>s+(x.actualBytes??0),0)+actualBytes>this.budget.maxAggregateResidentBytes){this.entries.delete(k);return false}e.phase='resident';e.placedLabels=placedLabels;e.actualBytes=actualBytes;e.expiresAt=now+this.budget.residentTtlMs;return true}
 touch(viewId:string,layerId:string,batchId:string,revision:number,now:number):boolean{const e=this.get(viewId,layerId,batchId);if(!e||e.phase!=='resident'||e.revision!==revision||!Number.isFinite(now)||now>=e.expiresAt)return false;e.expiresAt=now+this.budget.residentTtlMs;return true}
 consume(viewId:string,layerId:string,batchId:string,revision:number):boolean{const e=this.get(viewId,layerId,batchId);return!!e&&e.phase==='resident'&&e.revision===revision&&this.entries.delete(this.key(e.viewId,e.layerId,e.batchId))}
 cancel(viewId:string,layerId:string,batchId:string,revision:number):boolean{const e=this.get(viewId,layerId,batchId);return!!e&&e.revision===revision&&this.entries.delete(this.key(e.viewId,e.layerId,e.batchId))}
 invalidateView(viewId:string,revision:number):number{const v=viewId.trim();if(!safe.test(v)||!pos(revision)||revision<=(this.revisions.get(v)??0))return 0;this.revisions.set(v,revision);let n=0;for(const[k,e]of this.entries)if(e.viewId===v&&e.revision<revision){this.entries.delete(k);n++}return n}
 expire(now:number):number{if(!Number.isFinite(now))return 0;let n=0;for(const[k,e]of this.entries)if(now>=e.expiresAt){this.entries.delete(k);n++}return n}
 releaseLayer(viewId:string,layerId:string):number{const v=viewId.trim(),l=layerId.trim();if(!safe.test(v)||!safe.test(l))return 0;let n=0;for(const[k,e]of this.entries)if(e.viewId===v&&e.layerId===l){this.entries.delete(k);n++}return n}
 releaseView(viewId:string):number{const v=viewId.trim();if(!safe.test(v))return 0;let n=0;for(const[k,e]of this.entries)if(e.viewId===v){this.entries.delete(k);n++}this.revisions.delete(v);return n}
 snapshot():ArcGisLabelPlacementEntry[]{return[...this.entries.values()].map(e=>({...e}))}
 fingerprint():string{return this.snapshot().sort((a,b)=>a.sequence-b.sequence).map(e=>`${e.viewId}:${e.layerId}:${e.batchId}:${e.revision}:${e.phase}:${e.intent}:${e.lod}:${e.placedLabels??0}:${e.actualBytes??0}`).join('|')}
 dispose(){this.entries.clear();this.revisions.clear();this.sequence=0}
 private key(v:string,l:string,b:string){return`${v}|${l}|${b}`}
 private get(v:string,l:string,b:string){const a=v.trim(),c=l.trim(),d=b.trim();return safe.test(a)&&safe.test(c)&&safe.test(d)?this.entries.get(this.key(a,c,d)):undefined}
 private normalize(r:ArcGisLabelPlacementRequest):ArcGisLabelPlacementRequest|undefined{const v=r.viewId.trim(),l=r.layerId.trim(),b=r.batchId.trim();if(!safe.test(v)||!safe.test(l)||!safe.test(b)||!pos(r.revision)||!Number.isFinite(r.requestedAt)||!nn(r.lod)||!nn(r.labelCount)||r.labelCount>this.budget.maxLabelsPerBatch||!nn(r.glyphCount)||r.glyphCount>this.budget.maxGlyphsPerBatch||!nn(r.estimatedBytes)||r.estimatedBytes>this.budget.maxEstimatedBytesPerBatch||!(r.intent in rank))return;return{...r,viewId:v,layerId:l,batchId:b}}
}