import { describe, expect, it } from 'vitest'
import { ArcGisQuerySpatialRelationLifecyclePolicy, type QuerySpatialRelationRequest } from './ArcGisQuerySpatialRelationLifecyclePolicy'

const budget = { maxLayers: 3, maxPlans: 4, maxPlansPerLayer: 3, maxAggregateDistance: 100, maxDistance: 60, maxUnitsLength: 16, planTtlMs: 100 }
const request = (overrides: Partial<QuerySpatialRelationRequest> = {}): QuerySpatialRelationRequest => ({ planId:'p1',layerId:'parcels',revision:1,intent:'visible',relation:'intersects',distance:0,units:null,returnGeometry:true,createdAt:10,...overrides })

describe('ArcGisQuerySpatialRelationLifecyclePolicy', () => {
  it('requires an active exact layer revision', () => { const p=new ArcGisQuerySpatialRelationLifecyclePolicy(budget);expect(p.admit(request())).toBeNull();expect(p.setRevision('parcels',1)).toBe(0);expect(p.admit(request())?.relation).toBe('intersects') })
  it('invalidates plans when revision advances', () => { const p=new ArcGisQuerySpatialRelationLifecyclePolicy(budget);p.setRevision('parcels',1);p.admit(request());expect(p.setRevision('parcels',2)).toBe(1);expect(p.snapshot().plans).toBe(0);expect(p.setRevision('parcels',1)).toBe(-1) })
  it('deduplicates logical plans independent of plan id', () => { const p=new ArcGisQuerySpatialRelationLifecyclePolicy(budget);p.setRevision('parcels',1);expect(p.admit(request())).not.toBeNull();expect(p.admit(request({planId:'p2'}))).toBeNull() })
  it('normalizes units deterministically', () => { const p=new ArcGisQuerySpatialRelationLifecyclePolicy(budget);p.setRevision('parcels',1);expect(p.admit(request({distance:5,units:' METERS '}))?.units).toBe('meters') })
  it('rejects unpaired distance and units', () => { const p=new ArcGisQuerySpatialRelationLifecyclePolicy(budget);p.setRevision('parcels',1);expect(()=>p.admit(request({distance:5,units:null}))).toThrow();expect(()=>p.admit(request({distance:0,units:'meters'}))).toThrow() })
  it('rejects unsafe unit tokens', () => { const p=new ArcGisQuerySpatialRelationLifecyclePolicy(budget);p.setRevision('parcels',1);expect(()=>p.admit(request({distance:1,units:'m<script>'}))).toThrow() })
  it('rejects unsupported relation values fail closed', () => { const p=new ArcGisQuerySpatialRelationLifecyclePolicy(budget);p.setRevision('parcels',1);expect(()=>p.admit(request({relation:'equals' as never}))).toThrow('relation is invalid') })
  it('bounds individual distance', () => { const p=new ArcGisQuerySpatialRelationLifecyclePolicy(budget);p.setRevision('parcels',1);expect(p.admit(request({distance:61,units:'meters'}))).toBeNull() })
  it('enforces per-layer cardinality', () => { const p=new ArcGisQuerySpatialRelationLifecyclePolicy({...budget,maxPlansPerLayer:1});p.setRevision('parcels',1);p.admit(request());expect(p.admit(request({planId:'p2',relation:'within'}))).toBeNull() })
  it('evicts lower intent under aggregate distance pressure', () => { const p=new ArcGisQuerySpatialRelationLifecyclePolicy(budget);p.setRevision('parcels',1);p.setRevision('roads',1);p.admit(request({distance:55,units:'meters',intent:'background'}));expect(p.admit(request({planId:'p2',layerId:'roads',distance:55,units:'meters',intent:'interactive',createdAt:20}))).not.toBeNull();expect(p.snapshot()).toEqual({layers:2,plans:1,aggregateDistance:55}) })
  it('does not evict higher intent for background work', () => { const p=new ArcGisQuerySpatialRelationLifecyclePolicy({...budget,maxAggregateDistance:60});p.setRevision('parcels',1);p.setRevision('roads',1);p.admit(request({distance:50,units:'meters',intent:'interactive'}));expect(p.admit(request({planId:'p2',layerId:'roads',distance:20,units:'meters',intent:'background',createdAt:20}))).toBeNull();expect(p.snapshot().plans).toBe(1) })
  it('expires plans at the ttl boundary', () => { const p=new ArcGisQuerySpatialRelationLifecyclePolicy(budget);p.setRevision('parcels',1);p.admit(request());expect(p.expire(109)).toBe(0);expect(p.expire(110)).toBe(1) })
  it('touch extends ttl without changing sequence', () => { const p=new ArcGisQuerySpatialRelationLifecyclePolicy(budget);p.setRevision('parcels',1);const first=p.admit(request())!;expect(p.touch('p1',1,50)).toBe(true);expect(p.consume('p1',1,149)?.sequence).toBe(first.sequence) })
  it('consume removes logical signature for reuse', () => { const p=new ArcGisQuerySpatialRelationLifecyclePolicy(budget);p.setRevision('parcels',1);p.admit(request());expect(p.consume('p1',1,20)).not.toBeNull();expect(p.admit(request({planId:'p2',createdAt:21}))).not.toBeNull() })
  it('releaseLayer clears revision and resident plans', () => { const p=new ArcGisQuerySpatialRelationLifecyclePolicy(budget);p.setRevision('parcels',1);p.admit(request());expect(p.releaseLayer('parcels')).toBe(1);expect(p.snapshot()).toEqual({layers:0,plans:0,aggregateDistance:0}) })
  it('produces deterministic payload-free fingerprints', () => { const p=new ArcGisQuerySpatialRelationLifecyclePolicy(budget);p.setRevision('parcels',1);p.admit(request({distance:5,units:'meters'}));expect(p.fingerprint()).toBe('parcels:1:visible:intersects:5:meters:1') })
  it('returns frozen scalar views', () => { const p=new ArcGisQuerySpatialRelationLifecyclePolicy(budget);p.setRevision('parcels',1);const view=p.admit(request())!;expect(Object.isFrozen(view)).toBe(true);expect(Object.keys(view).sort()).toEqual(['createdAt','distance','expiresAt','intent','layerId','planId','relation','returnGeometry','revision','sequence','touchedAt','units'].sort()) })
  it('becomes terminal after disposal', () => { const p=new ArcGisQuerySpatialRelationLifecyclePolicy(budget);p.dispose();p.dispose();expect(()=>p.snapshot()).toThrow('disposed') })
})
