import { describe, expect, it } from 'vitest'
import { ArcGisRendererStateLifecyclePolicy, type ArcGisRendererStateBudget, type ArcGisRendererStateRequest } from './ArcGisRendererStateLifecyclePolicy'
const budget:ArcGisRendererStateBudget={maxStates:8,maxStatesPerView:5,maxStatesPerLayer:6,maxCompiling:2,maxCompilingPerView:1,maxResident:4,maxEstimatedSymbolsPerState:100,maxActualSymbolsPerState:200,maxResidentSymbols:500,maxEstimatedBytesPerState:5000,maxActualBytesPerState:10000,maxResidentBytes:20000,queueTtlMs:100,compileTtlMs:200,residentTtlMs:300}
const request=(o:Partial<ArcGisRendererStateRequest>={}):ArcGisRendererStateRequest=>({stateId:'state-1',viewId:'view-1',layerId:'layer-1',revision:1,mode:'2d',intent:'visible',requestedAt:10,estimatedSymbols:10,estimatedBytes:1000,...o})
const run=(p:ArcGisRendererStateLifecyclePolicy,o:Partial<ArcGisRendererStateRequest>={})=>{p.enqueue(request(o));return p.takeNext(20)}
const complete=(p:ArcGisRendererStateLifecyclePolicy,id='state-1',o:Partial<{viewId:string;layerId:string;revision:number;actualSymbols:number;actualBytes:number;completedAt:number}>={})=>p.complete({stateId:id,viewId:'view-1',layerId:'layer-1',revision:1,actualSymbols:20,actualBytes:1200,completedAt:30,...o})
describe('ArcGisRendererStateLifecyclePolicy',()=>{
 it('prioritizes interactive then visible then background deterministically',()=>{const p=new ArcGisRendererStateLifecyclePolicy({...budget,maxCompilingPerView:2});p.enqueue(request({stateId:'b',intent:'background',requestedAt:1}));p.enqueue(request({stateId:'v',intent:'visible',requestedAt:2}));p.enqueue(request({stateId:'i',intent:'interactive',requestedAt:3}));expect(p.takeNext(10)?.stateId).toBe('i');expect(p.takeNext(11)?.stateId).toBe('v')})
 it('bounds global and per-view compile concurrency',()=>{const p=new ArcGisRendererStateLifecyclePolicy(budget);p.enqueue(request({stateId:'a',viewId:'v1'}));p.enqueue(request({stateId:'b',viewId:'v1'}));p.enqueue(request({stateId:'c',viewId:'v2'}));expect(p.takeNext(20)?.stateId).toBe('a');expect(p.takeNext(20)?.stateId).toBe('c');expect(p.takeNext(20)).toBeUndefined()})
 it('rejects duplicate and oversized estimates',()=>{const p=new ArcGisRendererStateLifecyclePolicy(budget);p.enqueue(request());expect(()=>p.enqueue(request())).toThrow(/duplicate/);const q=new ArcGisRendererStateLifecyclePolicy(budget);expect(()=>q.enqueue(request({estimatedSymbols:101}))).toThrow(/symbol/);expect(q.snapshot()).toHaveLength(0)})
 it('reconciles estimates to actual residency',()=>{const p=new ArcGisRendererStateLifecyclePolicy(budget);run(p);expect(complete(p)).toEqual(expect.objectContaining({phase:'resident',actualSymbols:20,actualBytes:1200}))})
 it('releases authority on oversized actual results',()=>{const p=new ArcGisRendererStateLifecyclePolicy(budget);run(p);expect(()=>complete(p,'state-1',{actualBytes:10001})).toThrow(/byte/);expect(p.snapshot()).toHaveLength(0)})
 it('bounds aggregate resident resources',()=>{const p=new ArcGisRendererStateLifecyclePolicy({...budget,maxResidentSymbols:210});run(p,{stateId:'a',viewId:'v1'});complete(p,'a',{viewId:'v1',actualSymbols:180});run(p,{stateId:'b',viewId:'v2'});expect(()=>complete(p,'b',{viewId:'v2',actualSymbols:40})).toThrow(/symbol/)})
 it('cleans expired resident pressure before completion admission',()=>{const p=new ArcGisRendererStateLifecyclePolicy({...budget,maxResident:1,maxResidentSymbols:200,maxResidentBytes:5000,residentTtlMs:10});run(p,{stateId:'old',viewId:'v1'});complete(p,'old',{viewId:'v1',actualSymbols:180,actualBytes:4000,completedAt:30});run(p,{stateId:'fresh',viewId:'v2',requestedAt:31});expect(complete(p,'fresh',{viewId:'v2',actualSymbols:20,actualBytes:1000,completedAt:41})).toEqual(expect.objectContaining({phase:'resident',stateId:'fresh'}));expect(p.snapshot().map(x=>x.stateId)).toEqual(['fresh'])})
 it('invalidates stale renderer work on revision advance',()=>{const p=new ArcGisRendererStateLifecyclePolicy(budget);p.enqueue(request());expect(p.advanceLayerRevision('layer-1',2)).toBe(1);expect(()=>p.enqueue(request({stateId:'stale',revision:1}))).toThrow(/stale/)})
 it('expires queue compile and resident leases',()=>{const q=new ArcGisRendererStateLifecyclePolicy(budget);q.enqueue(request({requestedAt:0}));expect(q.expire(101)).toBe(1);const r=new ArcGisRendererStateLifecyclePolicy(budget);r.enqueue(request({requestedAt:0}));r.takeNext(10);expect(r.expire(211)).toBe(1);const d=new ArcGisRendererStateLifecyclePolicy(budget);run(d);complete(d);expect(d.expire(331)).toBe(1)})
 it('touch consume cancel and teardown remain bounded',()=>{const p=new ArcGisRendererStateLifecyclePolicy(budget);run(p);complete(p);expect(p.touch('state-1',40)).toBe(true);expect(p.consume('state-1')?.phase).toBe('resident');p.enqueue(request({stateId:'a'}));p.enqueue(request({stateId:'b',viewId:'v2'}));expect(p.releaseView('view-1')).toBe(1);expect(p.releaseLayer('layer-1')).toBe(1)})
 it('governs 2d and 3d without retaining renderer payload graphs',()=>{const p=new ArcGisRendererStateLifecyclePolicy(budget);p.enqueue(request({stateId:'2d',mode:'2d'}));p.enqueue(request({stateId:'3d',viewId:'v2',mode:'3d'}));const s=p.snapshot();expect(s.map(x=>x.mode)).toEqual(['2d','3d']);expect(s[0]).not.toHaveProperty('renderer');expect(s[0]).not.toHaveProperty('symbol');expect(s[0]).not.toHaveProperty('layerView');expect(s[0]).not.toHaveProperty('credential')})
 it('rejects malformed identifiers, time and impossible budgets',()=>{const p=new ArcGisRendererStateLifecyclePolicy(budget);expect(()=>p.enqueue(request({stateId:'bad id'}))).toThrow(/invalid/);expect(()=>p.enqueue(request({requestedAt:NaN}))).toThrow(/finite/);expect(()=>new ArcGisRendererStateLifecyclePolicy({...budget,maxCompilingPerView:3,maxCompiling:2})).toThrow(/impossible/)})
 it('fingerprints deterministically and fails closed after dispose',()=>{const a=new ArcGisRendererStateLifecyclePolicy(budget),b=new ArcGisRendererStateLifecyclePolicy(budget);a.enqueue(request({stateId:'b'}));a.enqueue(request({stateId:'a'}));b.enqueue(request({stateId:'a'}));b.enqueue(request({stateId:'b'}));expect(a.fingerprint()).toBe(b.fingerprint());a.dispose();expect(()=>a.snapshot()).toThrow(/disposed/)})
})
