import { describe, expect, it } from 'vitest'
import { ArcGisTopologyValidationLifecyclePolicy, type TopologyValidationBudget, type TopologyValidationRequest } from './ArcGisTopologyValidationLifecyclePolicy'

const budget: TopologyValidationBudget = { maxLayers:3,maxJobs:8,maxJobsPerLayer:5,maxValidating:2,maxValidatingPerLayer:1,maxResident:3,maxResidentPerLayer:2,maxVerticesPerJob:1000,maxBytesPerJob:4000,maxResidentErrors:20,maxResidentBytes:8000,queueTtlMs:100,validationLeaseMs:200,residentTtlMs:300 }
const request=(o:Partial<TopologyValidationRequest>={}):TopologyValidationRequest=>({jobId:'j1',layerId:'parcels',revision:1,intent:'interactive',vertexCount:20,estimatedBytes:500,requestedAt:10,...o})
const policy=()=>{const p=new ArcGisTopologyValidationLifecyclePolicy(budget);p.setRevision('parcels',1);return p}

describe('ArcGisTopologyValidationLifecyclePolicy',()=>{
  it('admits bounded payload-free metadata',()=>{const p=policy();expect(p.admit(request())).toBe(true);expect(p.snapshot()).toEqual({layers:1,jobs:1,queued:1,validating:0,resident:0,residentErrors:0,residentBytes:0})})
  it('requires authoritative layer revision',()=>{const p=new ArcGisTopologyValidationLifecyclePolicy(budget);expect(p.admit(request())).toBe(false)})
  it('rejects stale request revisions',()=>{const p=policy();expect(p.admit(request({revision:0}))).toBe(false)})
  it('revision advance invalidates stale jobs',()=>{const p=policy();p.admit(request());expect(p.setRevision('parcels',2)).toBe(1);expect(p.snapshot().jobs).toBe(0)})
  it('never rolls revision backwards',()=>{const p=policy();expect(p.setRevision('parcels',0)).toBe(-1)})
  it('bounds tracked layers',()=>{const p=new ArcGisTopologyValidationLifecyclePolicy({...budget,maxLayers:1});expect(p.setRevision('a',1)).toBe(0);expect(p.setRevision('b',1)).toBe(-1)})
  it('deduplicates job ids',()=>{const p=policy();expect(p.admit(request())).toBe(true);expect(p.admit(request())).toBe(false)})
  it('rejects excessive vertex estimates',()=>{const p=policy();expect(p.admit(request({vertexCount:1001}))).toBe(false)})
  it('rejects excessive byte estimates',()=>{const p=policy();expect(p.admit(request({estimatedBytes:4001}))).toBe(false)})
  it('bounds global job cardinality',()=>{const p=new ArcGisTopologyValidationLifecyclePolicy({...budget,maxJobs:2,maxJobsPerLayer:2});p.setRevision('parcels',1);expect(p.admit(request({jobId:'a'}))).toBe(true);expect(p.admit(request({jobId:'b'}))).toBe(true);expect(p.admit(request({jobId:'c'}))).toBe(false)})
  it('bounds per-layer job cardinality',()=>{const p=new ArcGisTopologyValidationLifecyclePolicy({...budget,maxJobsPerLayer:1});p.setRevision('parcels',1);expect(p.admit(request({jobId:'a'}))).toBe(true);expect(p.admit(request({jobId:'b'}))).toBe(false)})
  it('schedules interactive before visible before background',()=>{const p=policy();p.admit(request({jobId:'b',intent:'background'}));p.admit(request({jobId:'v',intent:'visible'}));p.admit(request({jobId:'i',intent:'interactive'}));expect(p.startNext(20)?.jobId).toBe('i')})
  it('preserves fifo within equal priority',()=>{const p=policy();p.admit(request({jobId:'a'}));p.admit(request({jobId:'b'}));expect(p.startNext(20)?.jobId).toBe('a')})
  it('bounds validating globally',()=>{const p=new ArcGisTopologyValidationLifecyclePolicy({...budget,maxValidating:1,maxValidatingPerLayer:1});p.setRevision('parcels',1);p.admit(request({jobId:'a'}));p.admit(request({jobId:'b'}));expect(p.startNext(20)?.jobId).toBe('a');expect(p.startNext(21)).toBeNull()})
  it('bounds validating per layer but permits another layer',()=>{const p=policy();p.setRevision('roads',1);p.admit(request({jobId:'a'}));p.admit(request({jobId:'b'}));p.admit(request({jobId:'r',layerId:'roads'}));expect(p.startNext(20)?.jobId).toBe('a');expect(p.startNext(20)?.jobId).toBe('r')})
  it('reconciles actual completion accounting',()=>{const p=policy();p.admit(request());p.startNext(20);expect(p.complete('j1',1,4,900,30)).toBe(true);expect(p.snapshot().residentErrors).toBe(4);expect(p.snapshot().residentBytes).toBe(900)})
  it('rejects stale completion after revision advance',()=>{const p=policy();p.admit(request());p.startNext(20);p.setRevision('parcels',2);expect(p.complete('j1',1,1,500,30)).toBe(false)})
  it('rejects oversized actual byte result and drops job',()=>{const p=policy();p.admit(request());p.startNext(20);expect(p.complete('j1',1,1,4001,30)).toBe(false);expect(p.snapshot().jobs).toBe(0)})
  it('rejects impossible error residency and drops job',()=>{const p=policy();p.admit(request());p.startNext(20);expect(p.complete('j1',1,21,500,30)).toBe(false);expect(p.snapshot().jobs).toBe(0)})
  it('evicts background residency for interactive pressure',()=>{const p=new ArcGisTopologyValidationLifecyclePolicy({...budget,maxResident:1,maxResidentPerLayer:1});p.setRevision('parcels',1);p.admit(request({jobId:'old',intent:'background'}));p.startNext(20);p.complete('old',1,1,500,30);p.admit(request({jobId:'new',intent:'interactive'}));p.startNext(40);expect(p.complete('new',1,1,500,50)).toBe(true);expect(p.fingerprint()).toContain(':new:')})
  it('does not evict higher-priority residency for background work',()=>{const p=new ArcGisTopologyValidationLifecyclePolicy({...budget,maxResident:1,maxResidentPerLayer:1});p.setRevision('parcels',1);p.admit(request({jobId:'hot'}));p.startNext(20);p.complete('hot',1,1,500,30);p.admit(request({jobId:'cold',intent:'background'}));p.startNext(40);expect(p.complete('cold',1,1,500,50)).toBe(false);expect(p.fingerprint()).toContain(':hot:')})
  it('uses least-recently-touched eviction within equal intent',()=>{const p=new ArcGisTopologyValidationLifecyclePolicy({...budget,maxResident:2,maxResidentPerLayer:2,maxResidentBytes:1000});p.setRevision('parcels',1);for(const j of ['a','b']){p.admit(request({jobId:j,estimatedBytes:500}));p.startNext(20);p.complete(j,1,1,500,30)}p.touch('b',40);p.admit(request({jobId:'c',estimatedBytes:500}));p.startNext(50);expect(p.complete('c',1,1,500,60)).toBe(true);expect(p.fingerprint()).not.toContain(':a:')})
  it('evicts to satisfy aggregate error budget',()=>{const p=new ArcGisTopologyValidationLifecyclePolicy({...budget,maxResidentErrors:4});p.setRevision('parcels',1);p.admit(request({jobId:'a',intent:'background'}));p.startNext(20);p.complete('a',1,3,500,30);p.admit(request({jobId:'b'}));p.startNext(40);expect(p.complete('b',1,3,500,50)).toBe(true);expect(p.snapshot().residentErrors).toBe(3)})
  it('expires queued jobs at ttl boundary',()=>{const p=policy();p.admit(request());expect(p.expire(110)).toBe(1)})
  it('expires validation leases',()=>{const p=policy();p.admit(request());p.startNext(20);expect(p.expire(220)).toBe(1)})
  it('expires resident results',()=>{const p=policy();p.admit(request());p.startNext(20);p.complete('j1',1,1,500,30);expect(p.expire(330)).toBe(1)})
  it('touch extends resident ttl',()=>{const p=policy();p.admit(request());p.startNext(20);p.complete('j1',1,1,500,30);expect(p.touch('j1',300)).toBe(true);expect(p.expire(330)).toBe(0)})
  it('consumes a resident result once',()=>{const p=policy();p.admit(request());p.startNext(20);p.complete('j1',1,1,500,30);expect(p.consume('j1',1)?.phase).toBe('resident');expect(p.consume('j1',1)).toBeNull()})
  it('does not consume wrong revision',()=>{const p=policy();p.admit(request());p.startNext(20);p.complete('j1',1,1,500,30);expect(p.consume('j1',2)).toBeNull()})
  it('cancels queued metadata',()=>{const p=policy();p.admit(request());expect(p.cancel('j1')).toBe(true);expect(p.snapshot().jobs).toBe(0)})
  it('releases layer metadata and watermark',()=>{const p=policy();p.admit(request());expect(p.releaseLayer('parcels')).toBe(1);expect(p.snapshot().layers).toBe(0)})
  it('fingerprint is deterministic across insertion order',()=>{const a=policy(),b=policy();a.admit(request({jobId:'b'}));a.admit(request({jobId:'a'}));b.admit(request({jobId:'a'}));b.admit(request({jobId:'b'}));expect(a.fingerprint()).toBe(b.fingerprint())})
  it('normalizes identifiers',()=>{const p=policy();expect(p.admit(request({jobId:' j1 ',layerId:' parcels '}))).toBe(true);expect(p.fingerprint()).toContain('parcels:j1')})
  it('rejects control characters in identifiers',()=>{const p=policy();expect(()=>p.admit(request({jobId:'bad\u0001id'}))).toThrow(/jobId/)})
  it('rejects unsafe numeric metadata',()=>{const p=policy();expect(()=>p.admit(request({vertexCount:-1}))).toThrow(/vertexCount/);expect(()=>p.admit(request({requestedAt:Number.NaN}))).toThrow(/requestedAt/)})
  it('rejects invalid intent at runtime boundary',()=>{const p=policy();expect(()=>p.admit({...request(),intent:'urgent' as never})).toThrow(/intent/)})
  it('rejects inconsistent cardinality budgets',()=>{expect(()=>new ArcGisTopologyValidationLifecyclePolicy({...budget,maxJobsPerLayer:9})).toThrow(/maxJobsPerLayer/);expect(()=>new ArcGisTopologyValidationLifecyclePolicy({...budget,maxValidatingPerLayer:3})).toThrow(/maxValidatingPerLayer/)})
  it('fails closed after disposal',()=>{const p=policy();p.dispose();expect(()=>p.snapshot()).toThrow(/disposed/)})
  it('disposal is idempotent',()=>{const p=policy();p.dispose();expect(()=>p.dispose()).not.toThrow()})
  it('returns frozen detached scalar views',()=>{const p=policy();p.admit(request());const v=p.startNext(20)!;expect(Object.isFrozen(v)).toBe(true);expect(Object.keys(v).sort()).toEqual(['bytes','errorCount','expiresAt','intent','jobId','layerId','phase','revision','sequence','touchedAt','vertexCount'].sort())})
})
