export type ArcGisProjectionIntent = 'interactive' | 'navigation' | 'background'
export type ArcGisProjectionPhase = 'queued' | 'running' | 'ready'
export interface ArcGisProjectionBudget { maxJobs:number; maxJobsPerView:number; maxRunning:number; maxReady:number; maxPointsPerJob:number; maxReadyPoints:number; maxBytesPerJob:number; maxReadyBytes:number; queueTtlMs:number; runTtlMs:number; readyTtlMs:number }
export interface ArcGisProjectionRequest { viewId:string; jobId:string; sourceWkid:number; targetWkid:number; revision:number; intent:ArcGisProjectionIntent; pointCount:number; estimatedBytes:number; requestedAt:number }
export interface ArcGisProjectionView extends ArcGisProjectionRequest { readonly phase:ArcGisProjectionPhase; readonly actualPoints:number; readonly actualBytes:number; readonly sequence:number; readonly expiresAt:number }
type Entry = ArcGisProjectionView
const priority:Readonly<Record<ArcGisProjectionIntent,number>>=Object.freeze({background:0,navigation:1,interactive:2})
function positive(name:string,value:number){if(!Number.isInteger(value)||value<1)throw new Error(`${name} must be a positive integer`)}
function finite(name:string,value:number){if(!Number.isFinite(value)||value<0)throw new Error(`${name} must be finite and non-negative`)}
function id(name:string,value:string){const v=value.trim();if(!/^[A-Za-z0-9._:-]{1,160}$/.test(v))throw new Error(`invalid ${name}`);return v}
function wkid(name:string,value:number){if(!Number.isInteger(value)||value<1||value>999999)throw new Error(`invalid ${name}`);return value===102100?3857:value}
/** Payload-free scheduler for client projection work. Coordinates, geometries, workers and SDK projection objects remain caller-owned. */
export class ArcGisProjectionWorkLifecyclePolicy {
 readonly #budget:Readonly<ArcGisProjectionBudget>; readonly #entries=new Map<string,Entry>(); readonly #viewRevision=new Map<string,number>(); #sequence=0; #disposed=false
 constructor(b:ArcGisProjectionBudget){for(const [k,v] of Object.entries(b)){if(k.endsWith('Ms'))positive(k,v);else positive(k,v)};if(b.maxJobsPerView>b.maxJobs||b.maxRunning>b.maxJobs||b.maxReady>b.maxJobs)throw new Error('impossible cardinality budget');if(b.maxPointsPerJob>b.maxReadyPoints||b.maxBytesPerJob>b.maxReadyBytes)throw new Error('impossible residency budget');this.#budget=Object.freeze({...b})}
 enqueue(r:ArcGisProjectionRequest):ArcGisProjectionView{this.#active();const viewId=id('viewId',r.viewId),jobId=id('jobId',r.jobId),sourceWkid=wkid('sourceWkid',r.sourceWkid),targetWkid=wkid('targetWkid',r.targetWkid);positive('revision',r.revision);positive('pointCount',r.pointCount);positive('estimatedBytes',r.estimatedBytes);finite('requestedAt',r.requestedAt);if(sourceWkid===targetWkid)throw new Error('projection source and target must differ');if(r.pointCount>this.#budget.maxPointsPerJob||r.estimatedBytes>this.#budget.maxBytesPerJob)throw new Error('projection request budget exceeded');const watermark=this.#viewRevision.get(viewId);if(watermark!==undefined&&r.revision<watermark)throw new Error('stale projection revision');if(watermark!==undefined&&r.revision>watermark)this.advanceViewRevision(viewId,r.revision);if(this.#entries.has(jobId))throw new Error('duplicate projection job');if(this.#entries.size>=this.#budget.maxJobs)throw new Error('projection capacity exceeded');if(this.#countView(viewId)>=this.#budget.maxJobsPerView)throw new Error('view projection capacity exceeded');const e:Object=Object.freeze({...r,viewId,jobId,sourceWkid,targetWkid,phase:'queued',actualPoints:0,actualBytes:0,sequence:this.#sequence++,expiresAt:r.requestedAt+this.#budget.queueTtlMs});this.#entries.set(jobId,e as Entry);this.#viewRevision.set(viewId,r.revision);return this.#copy(e as Entry)}
 takeNext(now:number):ArcGisProjectionView|undefined{this.#active();finite('now',now);this.expire(now);if(this.#countPhase('running')>=this.#budget.maxRunning)return;const e=[...this.#entries.values()].filter(x=>x.phase==='queued').sort((a,b)=>priority[b.intent]-priority[a.intent]||a.requestedAt-b.requestedAt||a.jobId.localeCompare(b.jobId))[0];if(!e)return;const n=Object.freeze({...e,phase:'running' as const,expiresAt:now+this.#budget.runTtlMs});this.#entries.set(e.jobId,n);return this.#copy(n)}
 complete(jobId:string,revision:number,actualPoints:number,actualBytes:number,now:number):ArcGisProjectionView{this.#active();const key=id('jobId',jobId);positive('revision',revision);positive('actualPoints',actualPoints);positive('actualBytes',actualBytes);finite('now',now);const e=this.#entries.get(key);if(!e||e.phase!=='running')throw new Error('projection job is not running');if(e.revision!==revision||this.#viewRevision.get(e.viewId)!==revision)throw new Error('stale projection completion');if(now>e.expiresAt){this.#entries.delete(key);throw new Error('projection run lease expired')}if(actualPoints>this.#budget.maxPointsPerJob||actualBytes>this.#budget.maxBytesPerJob){this.#entries.delete(key);throw new Error('projection result budget exceeded')}if(this.#countPhase('ready')>=this.#budget.maxReady||this.#readyPoints()+actualPoints>this.#budget.maxReadyPoints||this.#readyBytes()+actualBytes>this.#budget.maxReadyBytes){this.#entries.delete(key);throw new Error('projection ready residency exceeded')}const n=Object.freeze({...e,phase:'ready' as const,actualPoints,actualBytes,expiresAt:now+this.#budget.readyTtlMs});this.#entries.set(key,n);return this.#copy(n)}
 consume(jobId:string){this.#active();const e=this.#entries.get(id('jobId',jobId));if(!e||e.phase!=='ready')return;this.#entries.delete(e.jobId);return this.#copy(e)}
 touch(jobId:string,now:number){this.#active();finite('now',now);const e=this.#entries.get(id('jobId',jobId));if(!e||e.phase!=='ready'||now>e.expiresAt)return false;this.#entries.set(e.jobId,Object.freeze({...e,expiresAt:now+this.#budget.readyTtlMs}));return true}
 cancel(jobId:string){this.#active();const e=this.#entries.get(id('jobId',jobId));if(!e||e.phase==='ready')return false;return this.#entries.delete(e.jobId)}
 advanceViewRevision(viewId:string,revision:number){this.#active();const v=id('viewId',viewId);positive('revision',revision);const old=this.#viewRevision.get(v);if(old!==undefined&&revision<old)throw new Error('revision cannot move backwards');let removed=0;for(const [k,e] of this.#entries)if(e.viewId===v&&e.revision<revision){this.#entries.delete(k);removed++}this.#viewRevision.set(v,revision);return removed}
 releaseView(viewId:string){this.#active();const v=id('viewId',viewId);let n=0;for(const [k,e] of this.#entries)if(e.viewId===v){this.#entries.delete(k);n++}this.#viewRevision.delete(v);return n}
 expire(now:number){this.#active();finite('now',now);let n=0;for(const [k,e] of this.#entries)if(now>e.expiresAt){this.#entries.delete(k);n++}return n}
 snapshot(){this.#active();return Object.freeze([...this.#entries.values()].sort((a,b)=>a.sequence-b.sequence).map(e=>this.#copy(e)))}
 fingerprint(){this.#active();return [...this.#entries.values()].sort((a,b)=>a.jobId.localeCompare(b.jobId)).map(e=>[e.viewId,e.jobId,e.sourceWkid,e.targetWkid,e.revision,e.intent,e.phase,e.pointCount,e.actualPoints,e.actualBytes].join(':')).join('|')}
 dispose(){this.#entries.clear();this.#viewRevision.clear();this.#disposed=true}
 #copy(e:Entry){return Object.freeze({...e})} #countView(v:string){let n=0;for(const e of this.#entries.values())if(e.viewId===v)n++;return n} #countPhase(p:ArcGisProjectionPhase){let n=0;for(const e of this.#entries.values())if(e.phase===p)n++;return n} #readyPoints(){let n=0;for(const e of this.#entries.values())if(e.phase==='ready')n+=e.actualPoints;return n} #readyBytes(){let n=0;for(const e of this.#entries.values())if(e.phase==='ready')n+=e.actualBytes;return n} #active(){if(this.#disposed)throw new Error('ArcGisProjectionWorkLifecyclePolicy is disposed')}
}
