export type ArcGisServiceRequestIntent = 'background' | 'visible' | 'interactive'
export type ArcGisServiceRequestPhase = 'queued' | 'running' | 'ready'
export type ArcGisServiceOperation = 'query' | 'identify' | 'legend' | 'metadata'

export interface ArcGisServiceRequestBudget { maxRequests:number; maxRequestsPerService:number; maxRunning:number; maxRunningPerService:number; maxReady:number; maxReadyBytes:number; maxResponseBytes:number; maxRetries:number; queueTtlMs:number; runTtlMs:number; readyTtlMs:number }
export interface ArcGisServiceRequest { requestId:string; serviceId:string; operation:ArcGisServiceOperation; intent:ArcGisServiceRequestIntent; revision:number; requestedAt:number; estimatedResponseBytes:number; signature:string }
export interface ArcGisServiceCompletion { requestId:string; serviceId:string; revision:number; responseBytes:number; completedAt:number }
export interface ArcGisServiceRequestView extends ArcGisServiceRequest { readonly phase:ArcGisServiceRequestPhase; readonly attempts:number; readonly expiresAt:number; readonly actualResponseBytes:number }
interface Entry extends ArcGisServiceRequest { phase:ArcGisServiceRequestPhase; attempts:number; expiresAt:number; actualResponseBytes:number; sequence:number }
const priority = Object.freeze({background:0,visible:1,interactive:2} satisfies Record<ArcGisServiceRequestIntent,number>)
const idPattern=/^[A-Za-z0-9._:-]{1,160}$/
function integer(name:string,value:number,min=0){if(!Number.isInteger(value)||value<min)throw new Error(`${name} must be an integer >= ${min}`)}
function finite(name:string,value:number){if(!Number.isFinite(value)||value<0)throw new Error(`${name} must be finite and non-negative`)}
function identifier(name:string,value:string){const normalized=value.trim();if(!idPattern.test(normalized))throw new Error(`${name} is invalid`);return normalized}
function requestSignature(value:string){const normalized=value.trim();if(!normalized||normalized.length>512||/[\u0000-\u001f]/.test(normalized))throw new Error('signature is invalid');return normalized}

/** Payload-free ArcGIS REST scheduling/dedupe authority. Transport, credentials, response JSON and AbortSignals remain caller-owned. */
export class ArcGisServiceRequestLifecyclePolicy {
 readonly #budget:Readonly<ArcGisServiceRequestBudget>; readonly #entries=new Map<string,Entry>(); readonly #signatureIndex=new Map<string,string>(); readonly #serviceRevisions=new Map<string,number>(); #sequence=0; #disposed=false
 constructor(b:ArcGisServiceRequestBudget){for(const [n,v] of Object.entries(b)){if(n.endsWith('Ms'))finite(n,v);else integer(n,v,n==='maxRetries'?0:1)} if(b.maxRequestsPerService>b.maxRequests||b.maxRunning>b.maxRequests||b.maxReady>b.maxRequests||b.maxRunningPerService>b.maxRunning||b.maxRunningPerService>b.maxRequestsPerService||b.maxResponseBytes>b.maxReadyBytes)throw new Error('service request budget is impossible');this.#budget=Object.freeze({...b})}
 enqueue(r:ArcGisServiceRequest):Readonly<ArcGisServiceRequestView>{this.#active();const requestId=identifier('requestId',r.requestId),serviceId=identifier('serviceId',r.serviceId),signature=requestSignature(r.signature);integer('revision',r.revision);finite('requestedAt',r.requestedAt);integer('estimatedResponseBytes',r.estimatedResponseBytes);if(!(r.intent in priority))throw new Error('request intent is invalid');if(!['query','identify','legend','metadata'].includes(r.operation))throw new Error('service operation is invalid');if(r.estimatedResponseBytes>this.#budget.maxResponseBytes)throw new Error('estimated response exceeds response budget');const watermark=this.#serviceRevisions.get(serviceId);if(watermark!==undefined&&r.revision<watermark)throw new Error('request revision is stale');if(watermark!==undefined&&r.revision>watermark)this.advanceServiceRevision(serviceId,r.revision);if(this.#entries.has(requestId))throw new Error('duplicate request authority');const key=this.#key(serviceId,r.operation,signature,r.revision),duplicate=this.#signatureIndex.get(key);if(duplicate&&this.#entries.has(duplicate))throw new Error('duplicate request signature');if(this.#entries.size>=this.#budget.maxRequests)throw new Error('request capacity exceeded');if(this.#count(e=>e.serviceId===serviceId)>=this.#budget.maxRequestsPerService)throw new Error('service request capacity exceeded');const entry:Entry=Object.freeze({...r,requestId,serviceId,signature,phase:'queued',attempts:0,actualResponseBytes:0,expiresAt:r.requestedAt+this.#budget.queueTtlMs,sequence:this.#sequence++});this.#entries.set(requestId,entry);this.#signatureIndex.set(key,requestId);this.#serviceRevisions.set(serviceId,r.revision);return this.#view(entry)}
 takeNext(now:number){this.#active();finite('now',now);this.expire(now);if(this.#count(e=>e.phase==='running')>=this.#budget.maxRunning)return undefined;const entry=[...this.#entries.values()].filter(e=>e.phase==='queued'&&this.#count(x=>x.phase==='running'&&x.serviceId===e.serviceId)<this.#budget.maxRunningPerService).sort((a,b)=>priority[b.intent]-priority[a.intent]||a.requestedAt-b.requestedAt||a.sequence-b.sequence||a.requestId.localeCompare(b.requestId))[0];if(!entry)return undefined;const running:Entry=Object.freeze({...entry,phase:'running',attempts:entry.attempts+1,expiresAt:now+this.#budget.runTtlMs});this.#entries.set(entry.requestId,running);return this.#view(running)}
 complete(c:ArcGisServiceCompletion){this.#active();const requestId=identifier('requestId',c.requestId),serviceId=identifier('serviceId',c.serviceId);integer('revision',c.revision);integer('responseBytes',c.responseBytes);finite('completedAt',c.completedAt);this.expire(c.completedAt);const e=this.#entries.get(requestId);if(!e||e.phase!=='running')throw new Error('request is not running');if(e.serviceId!==serviceId||e.revision!==c.revision)throw new Error('completion identity mismatch');if(this.#serviceRevisions.get(serviceId)!==c.revision){this.#remove(e);throw new Error('completion revision is stale')}if(c.responseBytes>this.#budget.maxResponseBytes){this.#remove(e);throw new Error('response exceeds response budget')}if(this.#count(x=>x.phase==='ready')>=this.#budget.maxReady){this.#remove(e);throw new Error('ready capacity exceeded')}if(this.#readyBytes()+c.responseBytes>this.#budget.maxReadyBytes){this.#remove(e);throw new Error('ready byte budget exceeded')}const ready:Entry=Object.freeze({...e,phase:'ready',actualResponseBytes:c.responseBytes,expiresAt:c.completedAt+this.#budget.readyTtlMs});this.#entries.set(requestId,ready);return this.#view(ready)}
 retry(id:string,now:number){this.#active();id=identifier('requestId',id);finite('now',now);const e=this.#entries.get(id);if(!e||e.phase!=='running'||now>e.expiresAt)return false;if(e.attempts>this.#budget.maxRetries){this.#remove(e);return false}this.#entries.set(id,Object.freeze({...e,phase:'queued',expiresAt:now+this.#budget.queueTtlMs}));return true}
 consume(id:string){this.#active();id=identifier('requestId',id);const e=this.#entries.get(id);if(!e||e.phase!=='ready')return undefined;this.#remove(e);return this.#view(e)}
 cancel(id:string){this.#active();id=identifier('requestId',id);const e=this.#entries.get(id);if(!e)return false;this.#remove(e);return true}
 touch(id:string,now:number){this.#active();id=identifier('requestId',id);finite('now',now);const e=this.#entries.get(id);if(!e||e.phase!=='ready'||now>e.expiresAt)return false;this.#entries.set(id,Object.freeze({...e,expiresAt:now+this.#budget.readyTtlMs}));return true}
 advanceServiceRevision(serviceId:string,revision:number){this.#active();serviceId=identifier('serviceId',serviceId);integer('revision',revision);const current=this.#serviceRevisions.get(serviceId);if(current!==undefined&&revision<current)throw new Error('service revision cannot move backwards');if(current===revision)return 0;let removed=0;for(const e of [...this.#entries.values()])if(e.serviceId===serviceId&&e.revision<revision){this.#remove(e);removed++}this.#serviceRevisions.set(serviceId,revision);return removed}
 releaseService(serviceId:string){this.#active();serviceId=identifier('serviceId',serviceId);let removed=0;for(const e of [...this.#entries.values()])if(e.serviceId===serviceId){this.#remove(e);removed++}this.#serviceRevisions.delete(serviceId);return removed}
 expire(now:number){this.#active();finite('now',now);let removed=0;for(const e of [...this.#entries.values()])if(now>e.expiresAt){this.#remove(e);removed++}return removed}
 snapshot(){this.#active();return Object.freeze([...this.#entries.values()].sort((a,b)=>a.sequence-b.sequence).map(e=>this.#view(e)))}
 fingerprint(){this.#active();return [...this.#entries.values()].sort((a,b)=>a.serviceId.localeCompare(b.serviceId)||a.requestId.localeCompare(b.requestId)).map(e=>[e.serviceId,e.requestId,e.operation,e.intent,e.revision,e.phase,e.attempts,e.actualResponseBytes].join(':')).join('|')}
 dispose(){this.#entries.clear();this.#signatureIndex.clear();this.#serviceRevisions.clear();this.#disposed=true}
 #key(s:string,o:ArcGisServiceOperation,q:string,r:number){return `${s}\u001f${o}\u001f${r}\u001f${q}`}
 #remove(e:Entry){this.#entries.delete(e.requestId);this.#signatureIndex.delete(this.#key(e.serviceId,e.operation,e.signature,e.revision))}
 #count(p:(e:Entry)=>boolean){let n=0;for(const e of this.#entries.values())if(p(e))n++;return n}
 #readyBytes(){let n=0;for(const e of this.#entries.values())if(e.phase==='ready')n+=e.actualResponseBytes;return n}
 #view(e:Entry):Readonly<ArcGisServiceRequestView>{return Object.freeze({requestId:e.requestId,serviceId:e.serviceId,operation:e.operation,intent:e.intent,revision:e.revision,requestedAt:e.requestedAt,estimatedResponseBytes:e.estimatedResponseBytes,signature:e.signature,phase:e.phase,attempts:e.attempts,expiresAt:e.expiresAt,actualResponseBytes:e.actualResponseBytes})}
 #active(){if(this.#disposed)throw new Error('ArcGisServiceRequestLifecyclePolicy is disposed')}
}
