export type ArcGisFeatureHydrationIntent = 'interactive' | 'visible' | 'background'
export type ArcGisFeatureHydrationPhase = 'queued' | 'loading' | 'ready'
export interface ArcGisFeatureHydrationBudget { maxJobs:number; maxJobsPerLayer:number; maxLoading:number; maxReady:number; maxObjectIdsPerJob:number; maxEstimatedBytesPerJob:number; maxAggregateReadyBytes:number; queueTtlMs:number; loadLeaseMs:number; readyTtlMs:number }
export interface ArcGisFeatureHydrationRequest { layerId:string; jobId:string; revision:number; intent:ArcGisFeatureHydrationIntent; requestedAt:number; objectIdCount:number; fieldCount:number; estimatedBytes:number }
export interface ArcGisFeatureHydrationSnapshot extends ArcGisFeatureHydrationRequest { phase:ArcGisFeatureHydrationPhase; actualBytes:number; featureCount:number; expiresAt:number }
type Entry=ArcGisFeatureHydrationSnapshot&{sequence:number}; const rank:Record<ArcGisFeatureHydrationIntent,number>={interactive:0,visible:1,background:2}; const sep='\u0000'
/** Scalar-only authority for FeatureServer hydration; SDK payloads, geometry, attributes, credentials and transport ownership remain caller-owned. */
export class ArcGisFeatureHydrationLifecyclePolicy {
 private readonly jobs=new Map<string,Entry>(); private readonly revisions=new Map<string,number>(); private sequence=0; private disposed=false
 constructor(private readonly budget:ArcGisFeatureHydrationBudget){this.validateBudget()}
 enqueue(input:ArcGisFeatureHydrationRequest):boolean{this.active();const r=this.normalize(input),w=this.revisions.get(r.layerId)??0;if(r.revision<w)return false;const key=this.key(r.layerId,r.jobId),previous=this.jobs.get(key);if(previous&&r.revision<=previous.revision)return false;if(r.objectIdCount>this.budget.maxObjectIdsPerJob||r.estimatedBytes>this.budget.maxEstimatedBytesPerJob)return false;const advances=r.revision>w,survives=(e:Entry)=>e!==previous&&!(advances&&e.layerId===r.layerId&&e.revision<r.revision);if(this.count(survives)+1>this.budget.maxJobs||this.count(e=>survives(e)&&e.layerId===r.layerId)+1>this.budget.maxJobsPerLayer)return false;if(advances)this.invalidateLayer(r.layerId,r.revision);else if(previous)this.jobs.delete(key);this.revisions.set(r.layerId,r.revision);this.jobs.set(key,{...r,phase:'queued',actualBytes:0,featureCount:0,expiresAt:r.requestedAt+this.budget.queueTtlMs,sequence:this.sequence++});return true}
 takeNext(now:number):ArcGisFeatureHydrationSnapshot|undefined{this.active();this.timestamp(now);this.expire(now);if(this.count(e=>e.phase==='loading')>=this.budget.maxLoading)return;const next=[...this.jobs.values()].filter(e=>e.phase==='queued').sort((a,b)=>rank[a.intent]-rank[b.intent]||a.requestedAt-b.requestedAt||a.sequence-b.sequence)[0];if(!next)return;next.phase='loading';next.expiresAt=now+this.budget.loadLeaseMs;return this.detach(next)}
 complete(layerId:string,jobId:string,revision:number,featureCount:number,actualBytes:number,now:number):boolean{this.active();this.timestamp(now);this.nonNegative(featureCount,'featureCount');this.nonNegative(actualBytes,'actualBytes');const layer=this.id(layerId,'layerId'),job=this.id(jobId,'jobId'),key=this.key(layer,job),entry=this.jobs.get(key);if(!entry||entry.phase!=='loading'||entry.revision!==revision)return false;if(now>=entry.expiresAt||revision<(this.revisions.get(layer)??0)||featureCount>entry.objectIdCount||actualBytes>this.budget.maxEstimatedBytesPerJob){this.jobs.delete(key);return false}this.release(e=>e!==entry&&now>=e.expiresAt);if(this.count(e=>e.phase==='ready')>=this.budget.maxReady||this.readyBytes()+actualBytes>this.budget.maxAggregateReadyBytes){this.jobs.delete(key);return false}entry.phase='ready';entry.featureCount=featureCount;entry.actualBytes=actualBytes;entry.expiresAt=now+this.budget.readyTtlMs;return true}
 consume(layerId:string,jobId:string,revision:number){return this.removeMatching(layerId,jobId,revision,'ready')} cancel(layerId:string,jobId:string,revision:number){return this.removeMatching(layerId,jobId,revision)}
 invalidateLayer(layerId:string,revision:number):number{this.active();const l=this.id(layerId,'layerId');this.positive(revision,'revision');const current=this.revisions.get(l)??0;if(revision<=current)return 0;this.revisions.set(l,revision);return this.release(e=>e.layerId===l&&e.revision<revision)}
 expire(now:number){this.active();this.timestamp(now);return this.release(e=>now>=e.expiresAt)} releaseLayer(layerId:string){this.active();const l=this.id(layerId,'layerId');this.revisions.delete(l);return this.release(e=>e.layerId===l)} snapshot(){this.active();return[...this.jobs.values()].sort((a,b)=>a.sequence-b.sequence).map(e=>this.detach(e))} fingerprint(){return this.snapshot().map(e=>`${e.layerId}:${e.jobId}:${e.revision}:${e.phase}:${e.intent}:${e.objectIdCount}:${e.fieldCount}:${e.actualBytes}`).join('|')} dispose(){if(!this.disposed){this.jobs.clear();this.revisions.clear();this.disposed=true}}
 private removeMatching(layerId:string,jobId:string,revision:number,phase?:ArcGisFeatureHydrationPhase){this.active();const key=this.key(this.id(layerId,'layerId'),this.id(jobId,'jobId')),e=this.jobs.get(key);if(!e||e.revision!==revision||(phase&&e.phase!==phase))return false;this.jobs.delete(key);return true}
 private normalize(r:ArcGisFeatureHydrationRequest){if(!(r.intent in rank))throw new Error('intent is invalid');this.positive(r.revision,'revision');this.timestamp(r.requestedAt);this.positive(r.objectIdCount,'objectIdCount');this.positive(r.fieldCount,'fieldCount');this.nonNegative(r.estimatedBytes,'estimatedBytes');return{...r,layerId:this.id(r.layerId,'layerId'),jobId:this.id(r.jobId,'jobId')}}
 private validateBudget(){for(const[n,v]of Object.entries(this.budget))this.positive(v,n);if(this.budget.maxJobsPerLayer>this.budget.maxJobs||this.budget.maxLoading>this.budget.maxJobs||this.budget.maxReady>this.budget.maxJobs)throw new RangeError('hydration cardinality budget is inconsistent');if(this.budget.maxAggregateReadyBytes<this.budget.maxEstimatedBytesPerJob)throw new RangeError('aggregate ready bytes must admit one maximum job')}
 private id(v:string,n:string){const x=v.trim();if(!x||x.length>160||x.includes(sep)||x.includes(':'))throw new Error(`${n} must contain safe characters`);return x} private key(l:string,j:string){return`${l}${sep}${j}`} private positive(v:number,n:string){if(!Number.isSafeInteger(v)||v<=0)throw new RangeError(`${n} must be a positive safe integer`)} private nonNegative(v:number,n:string){if(!Number.isSafeInteger(v)||v<0)throw new RangeError(`${n} must be a non-negative safe integer`)} private timestamp(v:number){if(!Number.isFinite(v)||v<0)throw new RangeError('timestamp must be finite and non-negative')} private count(fn:(e:Entry)=>boolean){let n=0;for(const e of this.jobs.values())if(fn(e))n++;return n} private readyBytes(){let n=0;for(const e of this.jobs.values())if(e.phase==='ready')n+=e.actualBytes;return n} private release(fn:(e:Entry)=>boolean){let n=0;for(const[k,e]of this.jobs)if(fn(e)){this.jobs.delete(k);n++}return n} private detach(e:Entry):ArcGisFeatureHydrationSnapshot{const{sequence:_s,...snapshot}=e;return{...snapshot}} private active(){if(this.disposed)throw new Error('ArcGisFeatureHydrationLifecyclePolicy is disposed')}
}
