import { describe, expect, it } from 'vitest'
import { ArcGisCacheResidencyPolicy, type ArcGisCacheBudget, type ArcGisCacheRequest } from './ArcGisCacheResidencyPolicy'

const budget: ArcGisCacheBudget = { maxEntries:6,maxEntriesPerService:4,maxLoading:3,maxResident:3,maxBytesPerEntry:1000,maxResidentBytes:2000,loadingTtlMs:100,residentTtlMs:200 }
const req=(o:Partial<ArcGisCacheRequest>={}):ArcGisCacheRequest=>({cacheKey:'k1',serviceId:'svc',layerId:'layer',revision:1,intent:'visible',estimatedBytes:100,requestedAt:0,...o})

describe('ArcGisCacheResidencyPolicy',()=>{
 it('admits payload-free loading authority',()=>{const p=new ArcGisCacheResidencyPolicy(budget);const v=p.enqueue(req());expect(v.phase).toBe('loading');expect(v).not.toHaveProperty('response');expect(v).not.toHaveProperty('features');expect(v).not.toHaveProperty('url')})
 it('reconciles estimate to actual residency',()=>{const p=new ArcGisCacheResidencyPolicy(budget);p.enqueue(req());expect(p.complete('k1',1,500,10).actualBytes).toBe(500)})
 it('rejects duplicate keys',()=>{const p=new ArcGisCacheResidencyPolicy(budget);p.enqueue(req());expect(()=>p.enqueue(req())).toThrow(/duplicate/)})
 it('bounds entry bytes at admission',()=>{const p=new ArcGisCacheResidencyPolicy(budget);expect(()=>p.enqueue(req({estimatedBytes:1001}))).toThrow(/byte/)})
 it('bounds actual bytes and releases failed authority',()=>{const p=new ArcGisCacheResidencyPolicy(budget);p.enqueue(req());expect(()=>p.complete('k1',1,1001,10)).toThrow(/byte/);expect(p.snapshot()).toHaveLength(0)})
 it('bounds global cardinality',()=>{const p=new ArcGisCacheResidencyPolicy({...budget,maxEntries:2,maxEntriesPerService:2,maxLoading:2,maxResident:2});p.enqueue(req({cacheKey:'a'}));p.enqueue(req({cacheKey:'b'}));expect(()=>p.enqueue(req({cacheKey:'c'}))).toThrow(/capacity/)})
 it('bounds per-service cardinality',()=>{const p=new ArcGisCacheResidencyPolicy({...budget,maxEntriesPerService:2});p.enqueue(req({cacheKey:'a'}));p.enqueue(req({cacheKey:'b'}));expect(()=>p.enqueue(req({cacheKey:'c'}))).toThrow(/service/)})
 it('bounds loading concurrency',()=>{const p=new ArcGisCacheResidencyPolicy({...budget,maxLoading:1});p.enqueue(req({cacheKey:'a'}));expect(()=>p.enqueue(req({cacheKey:'b'}))).toThrow(/loading/)})
 it('bounds resident cardinality',()=>{const p=new ArcGisCacheResidencyPolicy({...budget,maxResident:1});p.enqueue(req({cacheKey:'a'}));p.complete('a',1,100,1);p.enqueue(req({cacheKey:'b'}));expect(()=>p.complete('b',1,100,2)).toThrow(/resident/)})
 it('bounds aggregate resident bytes',()=>{const p=new ArcGisCacheResidencyPolicy({...budget,maxResidentBytes:1200});p.enqueue(req({cacheKey:'a'}));p.complete('a',1,800,1);p.enqueue(req({cacheKey:'b'}));expect(()=>p.complete('b',1,500,2)).toThrow(/byte/)})
 it('rejects stale completion',()=>{const p=new ArcGisCacheResidencyPolicy(budget);p.enqueue(req());p.advanceLayerRevision('layer',2);expect(()=>p.complete('k1',1,100,10)).toThrow(/not loading|stale/)})
 it('rejects stale admission',()=>{const p=new ArcGisCacheResidencyPolicy(budget);p.advanceLayerRevision('layer',2);expect(()=>p.enqueue(req({revision:1}))).toThrow(/stale/)})
 it('rejects backwards revision',()=>{const p=new ArcGisCacheResidencyPolicy(budget);p.advanceLayerRevision('layer',2);expect(()=>p.advanceLayerRevision('layer',1)).toThrow(/backwards/)})
 it('invalidates older layer entries on revision advance',()=>{const p=new ArcGisCacheResidencyPolicy(budget);p.enqueue(req({cacheKey:'a'}));expect(p.advanceLayerRevision('layer',2)).toBe(1);expect(p.snapshot()).toHaveLength(0)})
 it('expires loading lease',()=>{const p=new ArcGisCacheResidencyPolicy(budget);p.enqueue(req());expect(p.expire(101)).toBe(1)})
 it('expires resident lease',()=>{const p=new ArcGisCacheResidencyPolicy(budget);p.enqueue(req());p.complete('k1',1,100,10);expect(p.expire(211)).toBe(1)})
 it('touch extends live resident ttl',()=>{const p=new ArcGisCacheResidencyPolicy(budget);p.enqueue(req());p.complete('k1',1,100,10);expect(p.touch('k1',50)).toBe(true);expect(p.snapshot()[0].expiresAt).toBe(250)})
 it('touch refuses loading authority',()=>{const p=new ArcGisCacheResidencyPolicy(budget);p.enqueue(req());expect(p.touch('k1',10)).toBe(false)})
 it('consume transfers authority once',()=>{const p=new ArcGisCacheResidencyPolicy(budget);p.enqueue(req());p.complete('k1',1,100,10);expect(p.consume('k1',1)?.phase).toBe('resident');expect(p.consume('k1',1)).toBeUndefined()})
 it('consume rejects wrong revision',()=>{const p=new ArcGisCacheResidencyPolicy(budget);p.enqueue(req());p.complete('k1',1,100,10);expect(p.consume('k1',2)).toBeUndefined()})
 it('invalidates explicit key',()=>{const p=new ArcGisCacheResidencyPolicy(budget);p.enqueue(req());expect(p.invalidate('k1')).toBe(true);expect(p.invalidate('k1')).toBe(false)})
 it('releases layer authority',()=>{const p=new ArcGisCacheResidencyPolicy(budget);p.enqueue(req({cacheKey:'a'}));p.enqueue(req({cacheKey:'b'}));expect(p.releaseLayer('layer')).toBe(2)})
 it('releases service authority',()=>{const p=new ArcGisCacheResidencyPolicy(budget);p.enqueue(req({cacheKey:'a'}));p.enqueue(req({cacheKey:'b',serviceId:'other'}));expect(p.releaseService('svc')).toBe(1);expect(p.snapshot()[0].serviceId).toBe('other')})
 it('evicts background before visible and interactive',()=>{const p=new ArcGisCacheResidencyPolicy({...budget,maxResidentBytes:3000});for(const [cacheKey,intent] of [['i','interactive'],['b','background'],['v','visible']] as const){p.enqueue(req({cacheKey,intent}));p.complete(cacheKey,1,500,10)}expect(p.evictToBudget(1000)).toEqual(['b']);expect(p.snapshot().some(x=>x.cacheKey==='i')).toBe(true)})
 it('evicts earliest expiry deterministically within intent',()=>{const p=new ArcGisCacheResidencyPolicy({...budget,maxResidentBytes:3000});p.enqueue(req({cacheKey:'a'}));p.complete('a',1,500,10);p.enqueue(req({cacheKey:'b'}));p.complete('b',1,500,20);expect(p.evictToBudget(500)).toEqual(['a'])})
 it('fingerprint is deterministic and scalar-only',()=>{const a=new ArcGisCacheResidencyPolicy(budget),b=new ArcGisCacheResidencyPolicy(budget);a.enqueue(req({cacheKey:'x'}));b.enqueue(req({cacheKey:'x'}));expect(a.fingerprint()).toBe(b.fingerprint());expect(a.fingerprint()).not.toContain('[object Object]')})
 it.each(['','bad key','x'.repeat(300)])('rejects malformed cache key %s',cacheKey=>{const p=new ArcGisCacheResidencyPolicy(budget);expect(()=>p.enqueue(req({cacheKey}))).toThrow(/invalid/)})
 it.each([NaN,Infinity,-Infinity])('rejects non-finite time %s',requestedAt=>{const p=new ArcGisCacheResidencyPolicy(budget);expect(()=>p.enqueue(req({requestedAt}))).toThrow(/finite/)})
 it('rejects impossible cardinality budget',()=>expect(()=>new ArcGisCacheResidencyPolicy({...budget,maxLoading:7})).toThrow(/impossible/))
 it('rejects impossible byte budget',()=>expect(()=>new ArcGisCacheResidencyPolicy({...budget,maxBytesPerEntry:3000})).toThrow(/impossible/))
 it('dispose clears and fails closed',()=>{const p=new ArcGisCacheResidencyPolicy(budget);p.enqueue(req());p.dispose();expect(()=>p.snapshot()).toThrow(/disposed/);expect(()=>p.enqueue(req())).toThrow(/disposed/)})
})
