import { describe,expect,it } from 'vitest'
import { ArcGisEditRetryBudgetPolicy } from './ArcGisEditRetryBudgetPolicy'
const budget={maxLayers:3,maxEntries:5,maxAttempts:6,maxAttemptsPerLayer:3,maxDelayMs:1000,entryTtlMs:100}
const make=()=>new ArcGisEditRetryBudgetPolicy(budget)
const req=(retryId:string,layerId='roads',revision=1,retryClass:'conflict'|'transport'|'server'='transport',createdAt=1)=>({retryId,layerId,revision,retryClass,createdAt})
describe('ArcGisEditRetryBudgetPolicy',()=>{
 it('requires current revision',()=>{const p=make();expect(p.register(req('a'))).toBe(false);p.setRevision('roads',1);expect(p.register(req('a'))).toBe(true)})
 it('invalidates stale entries',()=>{const p=make();p.setRevision('roads',1);p.register(req('a'));expect(p.setRevision('roads',2)).toBe(1);expect(p.snapshot().entries).toBe(0)})
 it('rejects revision regression',()=>{const p=make();p.setRevision('roads',2);expect(p.setRevision('roads',1)).toBe(-1)})
 it('bounds layers',()=>{const p=new ArcGisEditRetryBudgetPolicy({...budget,maxLayers:1});p.setRevision('a',1);expect(p.setRevision('b',1)).toBe(-1)})
 it('bounds entries',()=>{const p=new ArcGisEditRetryBudgetPolicy({...budget,maxEntries:1});p.setRevision('roads',1);expect(p.register(req('a'))).toBe(true);expect(p.register(req('b'))).toBe(false)})
 it('rejects duplicate retry ids',()=>{const p=make();p.setRevision('roads',1);expect(p.register(req('a'))).toBe(true);expect(p.register(req('a'))).toBe(false)})
 it('schedules bounded delay',()=>{const p=make();p.setRevision('roads',1);p.register(req('a'));expect(p.schedule('a',1,2,100)).toBe(true);expect(p.schedule('a',1,3,1001)).toBe(false)})
 it('rejects stale schedule',()=>{const p=make();p.setRevision('roads',1);p.register(req('a'));expect(p.schedule('a',2,2,1)).toBe(false)})
 it('bounds aggregate attempts',()=>{const p=new ArcGisEditRetryBudgetPolicy({...budget,maxAttempts:1,maxAttemptsPerLayer:1});p.setRevision('roads',1);p.register(req('a'));p.register(req('b'));expect(p.schedule('a',1,2,1)).toBe(true);expect(p.schedule('b',1,2,1)).toBe(false)})
 it('bounds attempts per layer independently',()=>{const p=new ArcGisEditRetryBudgetPolicy({...budget,maxAttempts:3,maxAttemptsPerLayer:1});p.setRevision('a',1);p.setRevision('b',1);p.register(req('a','a'));p.register(req('b','a'));p.register(req('c','b'));expect(p.schedule('a',1,2,1)).toBe(true);expect(p.schedule('b',1,2,1)).toBe(false);expect(p.schedule('c',1,2,1)).toBe(true)})
 it('does not expose unscheduled entries as eligible',()=>{const p=make();p.setRevision('roads',1);p.register(req('a'));expect(p.nextEligible(10)).toBeNull()})
 it('waits until nextEligibleAt',()=>{const p=make();p.setRevision('roads',1);p.register(req('a'));p.schedule('a',1,10,20);expect(p.nextEligible(29)).toBeNull();expect(p.nextEligible(30)?.retryId).toBe('a')})
 it('orders eligible retries by eligibility then sequence',()=>{const p=make();p.setRevision('roads',1);p.register(req('a'));p.register(req('b'));p.schedule('a',1,10,20);p.schedule('b',1,10,10);expect(p.nextEligible(30)?.retryId).toBe('b')})
 it('uses sequence for equal eligibility',()=>{const p=make();p.setRevision('roads',1);p.register(req('a'));p.register(req('b'));p.schedule('a',1,10,10);p.schedule('b',1,10,10);expect(p.nextEligible(20)?.retryId).toBe('a')})
 it('resolve removes current entry',()=>{const p=make();p.setRevision('roads',1);p.register(req('a'));expect(p.resolve('a',1)?.retryId).toBe('a');expect(p.snapshot().entries).toBe(0)})
 it('resolve rejects stale revision',()=>{const p=make();p.setRevision('roads',1);p.register(req('a'));expect(p.resolve('a',2)).toBeNull()})
 it('cancel is idempotent',()=>{const p=make();p.setRevision('roads',1);p.register(req('a'));expect(p.cancel('a')).toBe(true);expect(p.cancel('a')).toBe(false)})
 it('releaseLayer clears entries and authority',()=>{const p=make();p.setRevision('roads',1);p.register(req('a'));expect(p.releaseLayer('roads')).toBe(1);expect(p.register(req('b'))).toBe(false)})
 it('expires entries at TTL',()=>{const p=make();p.setRevision('roads',1);p.register(req('a','roads',1,'transport',10));expect(p.expire(109)).toBe(0);expect(p.expire(110)).toBe(1)})
 it('schedule renews entry TTL',()=>{const p=make();p.setRevision('roads',1);p.register(req('a'));p.schedule('a',1,50,1);expect(p.expire(149)).toBe(0);expect(p.expire(150)).toBe(1)})
 it('reports scalar accounting',()=>{const p=make();p.setRevision('roads',1);p.register(req('a'));p.schedule('a',1,2,1);expect(p.snapshot()).toEqual({layers:1,entries:1,attempts:1})})
 it('fingerprint is deterministic and payload-free',()=>{const p=make();p.setRevision('roads',1);p.register(req('a'));p.schedule('a',1,2,3);expect(p.fingerprint()).toBe('roads:a:1:transport:1:5');expect(p.fingerprint()).not.toContain('geometry')})
 it('normalizes ids without retaining excess payload',()=>{const p=make();p.setRevision(' roads ',1);expect(p.register({...req(' a ',' roads '),...({attributes:{secret:'x'}} as object)})).toBe(true);expect(p.fingerprint()).toContain('roads:a:');expect(p.fingerprint()).not.toContain('secret')})
 it('validates identifiers and times',()=>{const p=make();expect(()=>p.setRevision('',1)).toThrow();p.setRevision('roads',1);expect(()=>p.register(req('a','roads',1,'transport',-1))).toThrow();expect(()=>p.schedule('missing',1,-1,1)).toThrow()})
 it('validates budget hierarchy',()=>{expect(()=>new ArcGisEditRetryBudgetPolicy({...budget,maxAttempts:1,maxAttemptsPerLayer:2})).toThrow();expect(()=>new ArcGisEditRetryBudgetPolicy({...budget,maxEntries:0})).toThrow()})
 it('dispose is idempotent and terminal',()=>{const p=make();p.setRevision('roads',1);p.register(req('a'));p.dispose();p.dispose();expect(()=>p.snapshot()).toThrow('disposed');expect(()=>p.register(req('b'))).toThrow('disposed')})
})
