export type ArcGisTransformStatus = 'queued' | 'running' | 'completed' | 'failed' | 'cancelled';

export interface ArcGisCoordinatePoint { readonly x: number; readonly y: number; readonly z: number | null }
export interface ArcGisCoordinateTransformState {
  readonly id: string; readonly sourceWkid: number; readonly targetWkid: number;
  readonly status: ArcGisTransformStatus; readonly createdAtMs: number; readonly updatedAtMs: number;
  readonly revision: number; readonly input: ArcGisCoordinatePoint; readonly output: ArcGisCoordinatePoint | null;
  readonly failureCode: string | null;
}
export interface ArcGisCoordinateTransformPolicy {
  readonly maxTransforms: number; readonly maxIdLength: number; readonly maxFailureCodeLength: number;
  readonly maxAbsCoordinate: number; readonly retentionMs: number; readonly maxClockSkewMs: number;
}
export interface ArcGisCoordinateTransformSnapshot {
  readonly generation: number; readonly activeId: string | null; readonly transforms: readonly ArcGisCoordinateTransformState[];
}
function positive(value:number,name:string){if(!Number.isSafeInteger(value)||value<=0)throw new Error(`${name} must be a positive safe integer`);return value}
function time(value:number,name:string){if(!Number.isFinite(value)||value<0)throw new Error(`${name} must be finite and >= 0`);return value}
function text(value:string,max:number,name:string){if(typeof value!=='string')throw new Error(`${name} must be a string`);const v=value.trim();if(!v||v.length>max||v.includes('\0'))throw new Error(`${name} outside configured bounds`);return v}
function wkid(value:number){return positive(value,'wkid')}
function status(value:ArcGisTransformStatus){if(!['queued','running','completed','failed','cancelled'].includes(value))throw new Error('invalid transform status');return value}
function terminal(value:ArcGisTransformStatus){return value==='completed'||value==='failed'||value==='cancelled'}
function transition(from:ArcGisTransformStatus,to:ArcGisTransformStatus){return from==='queued'?(to==='running'||to==='cancelled'):from==='running'?(to==='completed'||to==='failed'||to==='cancelled'):false}
function freezePoint(p:ArcGisCoordinatePoint){return Object.freeze({...p})}
function freezeState(s:ArcGisCoordinateTransformState){return Object.freeze({...s,input:freezePoint(s.input),output:s.output?freezePoint(s.output):null})}

/** Primitive-only lifecycle authority. Projection math stays in verified/injected ArcGIS adapters. */
export class ArcGisCoordinateTransformCoordinator {
  private readonly policy:ArcGisCoordinateTransformPolicy; private readonly transforms=new Map<string,ArcGisCoordinateTransformState>();
  private activeId:string|null=null; private generation=0; private disposed=false;
  constructor(policy:ArcGisCoordinateTransformPolicy){this.policy=Object.freeze({maxTransforms:positive(policy.maxTransforms,'maxTransforms'),maxIdLength:positive(policy.maxIdLength,'maxIdLength'),maxFailureCodeLength:positive(policy.maxFailureCodeLength,'maxFailureCodeLength'),maxAbsCoordinate:positive(policy.maxAbsCoordinate,'maxAbsCoordinate'),retentionMs:positive(policy.retentionMs,'retentionMs'),maxClockSkewMs:positive(policy.maxClockSkewMs,'maxClockSkewMs')})}
  create(input:{readonly id:string;readonly sourceWkid:number;readonly targetWkid:number;readonly point:ArcGisCoordinatePoint},timestampMs:number){this.usable();const now=time(timestampMs,'timestampMs');this.prune(now);const id=text(input.id,this.policy.maxIdLength,'transform id');if(this.transforms.has(id))throw new Error('transform id already exists');const state=freezeState({id,sourceWkid:wkid(input.sourceWkid),targetWkid:wkid(input.targetWkid),status:'queued',createdAtMs:now,updatedAtMs:now,revision:1,input:this.point(input.point),output:null,failureCode:null});this.transforms.set(id,state);this.capacity(id);this.activeId=id;this.generation++;return state}
  transition(idValue:string,nextValue:ArcGisTransformStatus,timestampMs:number,options?:{readonly output?:ArcGisCoordinatePoint;readonly failureCode?:string}){this.usable();const now=time(timestampMs,'timestampMs');this.prune(now);const id=text(idValue,this.policy.maxIdLength,'transform id');const current=this.transforms.get(id);if(!current)throw new Error('transform does not exist');if(now+this.policy.maxClockSkewMs<current.updatedAtMs)throw new Error('stale transform transition rejected');const next=status(nextValue);if(!transition(current.status,next))throw new Error(`invalid transform transition ${current.status} -> ${next}`);if(next==='completed'&&!options?.output)throw new Error('completed transform requires output');if(next==='failed'&&!options?.failureCode)throw new Error('failed transform requires failure code');if((next==='running'||next==='cancelled')&&(options?.output||options?.failureCode))throw new Error('non-result transform cannot contain terminal payload');const state=freezeState({...current,status:next,updatedAtMs:now,revision:current.revision+1,output:next==='completed'?this.point(options!.output!):null,failureCode:next==='failed'?text(options!.failureCode!,this.policy.maxFailureCodeLength,'failureCode'):null});this.transforms.set(id,state);this.activeId=id;this.generation++;return state}
  snapshot(timestampMs:number):ArcGisCoordinateTransformSnapshot{this.usable();this.prune(time(timestampMs,'timestampMs'));return Object.freeze({generation:this.generation,activeId:this.activeId,transforms:Object.freeze([...this.transforms.values()].sort((a,b)=>a.updatedAtMs-b.updatedAtMs||a.id.localeCompare(b.id)).map(freezeState))})}
  restore(snapshot:Pick<ArcGisCoordinateTransformSnapshot,'activeId'|'transforms'>,timestampMs:number){this.usable();const now=time(timestampMs,'timestampMs');if(!Array.isArray(snapshot.transforms)||snapshot.transforms.length>this.policy.maxTransforms)throw new Error('transform snapshot exceeds capacity');const staged=new Map<string,ArcGisCoordinateTransformState>();for(const source of snapshot.transforms){const id=text(source.id,this.policy.maxIdLength,'transform id');if(staged.has(id))throw new Error('duplicate transform id');const created=time(source.createdAtMs,'createdAtMs'),updated=time(source.updatedAtMs,'updatedAtMs');if(updated<created)throw new Error('transform update precedes creation');if(updated>now+this.policy.maxClockSkewMs)throw new Error('future transform snapshot rejected');if(now-updated>this.policy.retentionMs&&terminal(source.status))continue;const s=status(source.status);const output=source.output?this.point(source.output):null;const failure=source.failureCode===null?null:text(source.failureCode,this.policy.maxFailureCodeLength,'failureCode');if(s==='completed'&&(!output||failure!==null))throw new Error('completed transform has invalid payload');if(s==='failed'&&(output||failure===null))throw new Error('failed transform has invalid payload');if(!terminal(s)&&(output||failure))throw new Error('active transform has terminal payload');if(s==='cancelled'&&(output||failure))throw new Error('cancelled transform has terminal payload');staged.set(id,freezeState({id,sourceWkid:wkid(source.sourceWkid),targetWkid:wkid(source.targetWkid),status:s,createdAtMs:created,updatedAtMs:updated,revision:positive(source.revision,'revision'),input:this.point(source.input),output,failureCode:failure}))}let active:string|null=null;if(snapshot.activeId!==null){active=text(snapshot.activeId,this.policy.maxIdLength,'active transform id');if(!staged.has(active))throw new Error('active transform is missing')}this.transforms.clear();for(const [id,value] of staged)this.transforms.set(id,value);this.activeId=active;this.generation++}
  remove(idValue:string){this.usable();const id=text(idValue,this.policy.maxIdLength,'transform id');if(!this.transforms.delete(id))return false;if(this.activeId===id)this.activeId=null;this.generation++;return true}
  dispose(){if(this.disposed)return;this.disposed=true;this.transforms.clear();this.activeId=null}
  private point(value:ArcGisCoordinatePoint){if(!value||typeof value!=='object')throw new Error('coordinate point is required');const values=[value.x,value.y];if(value.z!==null)values.push(value.z);if(values.some(v=>!Number.isFinite(v)||Math.abs(v)>this.policy.maxAbsCoordinate))throw new Error('coordinate outside configured bounds');return freezePoint({x:value.x,y:value.y,z:value.z})}
  private prune(now:number){let changed=false;for(const [id,state] of this.transforms){if(!terminal(state.status)||now-state.updatedAtMs<=this.policy.retentionMs)continue;this.transforms.delete(id);if(this.activeId===id)this.activeId=null;changed=true}if(changed)this.generation++}
  private capacity(protectedId:string){while(this.transforms.size>this.policy.maxTransforms){const victim=[...this.transforms.values()].filter(v=>v.id!==protectedId).sort((a,b)=>Number(terminal(b.status))-Number(terminal(a.status))||a.updatedAtMs-b.updatedAtMs||a.id.localeCompare(b.id))[0];if(!victim)throw new Error('transform capacity cannot be satisfied');this.transforms.delete(victim.id);if(this.activeId===victim.id)this.activeId=null}}
  private usable(){if(this.disposed)throw new Error('ArcGisCoordinateTransformCoordinator is disposed')}
}
