import {describe,expect,it} from 'vitest'
import {ArcGisSpatialExecutionLifecyclePolicy,type ArcGisSpatialExecutionBudget,type ArcGisSpatialExecutionRequest} from './ArcGisSpatialExecutionLifecyclePolicy'
const budget:ArcGisSpatialExecutionBudget={maxExecutions:8,maxExecutionsPerView:5,maxExecutionsPerLayer:6,maxRunning:2,maxRunningPerView:1,maxReady:4,maxEstimatedVerticesPerExecution:500,maxActualVerticesPerExecution:1000,maxReadyVertices:2000,maxEstimatedBytesPerExecution:5000,maxActualBytesPerExecution:10000,maxReadyBytes:20000,queueTtlMs:100,runTtlMs:200,readyTtlMs:300}
const request=(o:Partial<ArcGisSpatialExecutionRequest>={}):ArcGisSpatialExecutionRequest=>({executionId:'exec-1',viewId:'view-1',layerId:'layer-1',revision:1,kind:'query',intent:'visible',requestedAt:10,estimatedVertices:100,estimatedBytes:1000,...o})
const running=(p:ArcGisSpatialExecutionLifecyclePolicy,o:Partial<ArcGisSpatialExecutionRequest>={})=>{const r=request(o);p.enqueue(r);p.takeNext(20);return r}
const complete=(p:ArcGisSpatialExecutionLifecyclePolicy,executionId='exec-1',o:Partial<{viewId:string;layerId:string;revision:number;actualVertices:number;actualBytes:number;completedAt:number}>={})=>p.complete({executionId,viewId:'view-1',layerId:'layer-1',revision:1,actualVertices:120,actualBytes:1200,completedAt:30,...o})
describe('ArcGisSpatialExecutionLifecyclePolicy',()=>{
 it('schedules intent deterministically',()=>{const p=new ArcGisSpatialExecutionLifecyclePolicy({...budget,maxRunningPerView:2});p.enqueue(request({executionId:'b',intent:'background',requestedAt:1}));p.enqueue(request({executionId:'v',requestedAt:2}));p.enqueue(request({executionId:'i',intent:'interactive',requestedAt:3}));expect(p.takeNext(10)?.executionId).toBe('i');expect(p.takeNext(11)?.executionId).toBe('v')})
 it('bounds global and per-view running concurrency',()=>{const p=new ArcGisSpatialExecutionLifecyclePolicy(budget);p.enqueue(request({executionId:'a',viewId:'v1'}));p.enqueue(request({executionId:'b',viewId:'v1'}));p.enqueue(request({executionId:'c',viewId:'v2'}));expect(p.takeNext(20)?.executionId).toBe('a');expect(p.takeNext(20)?.executionId).toBe('c');expect(p.takeNext(20)).toBeUndefined()})
 it('bounds authority and rejects duplicates',()=>{const p=new ArcGisSpatialExecutionLifecyclePolicy({...budget,maxExecutions:2,maxExecutionsPerView:2,maxExecutionsPerLayer:2,maxRunning:1,maxReady:1});p.enqueue(request({executionId:'a'}));p.enqueue(request({executionId:'b'}));expect(()=>p.enqueue(request({executionId:'c'}))).toThrow(/capacity/);expect(()=>p.enqueue(request({executionId:'a'}))).toThrow()})
 it('rejects oversized estimates without retention',()=>{const p=new ArcGisSpatialExecutionLifecyclePolicy(budget);expect(()=>p.enqueue(request({estimatedVertices:501}))).toThrow(/vertex/);expect(p.snapshot()).toHaveLength(0)})
 it('reconciles actual ready residency',()=>{const p=new ArcGisSpatialExecutionLifecyclePolicy(budget);running(p);expect(complete(p)).toMatchObject({phase:'ready',actualVertices:120,actualBytes:1200})})
 it('rejects oversized actual results and releases authority',()=>{const p=new ArcGisSpatialExecutionLifecyclePolicy(budget);running(p);expect(()=>complete(p,'exec-1',{actualBytes:10001})).toThrow(/byte/);expect(p.snapshot()).toHaveLength(0)})
 it('bounds aggregate ready residency',()=>{const p=new ArcGisSpatialExecutionLifecyclePolicy({...budget,maxReadyBytes:11000});running(p,{executionId:'a',viewId:'v1'});complete(p,'a',{viewId:'v1',actualBytes:8000});running(p,{executionId:'b',viewId:'v2'});expect(()=>complete(p,'b',{viewId:'v2',actualBytes:4000})).toThrow(/residency/)})
 it('purges expired ready residency before completion admission',()=>{const p=new ArcGisSpatialExecutionLifecyclePolicy({...budget,maxReady:1,maxReadyBytes:10000,readyTtlMs:20});running(p,{executionId:'old',viewId:'v1'});complete(p,'old',{viewId:'v1',actualBytes:9000,completedAt:30});p.enqueue(request({executionId:'fresh',viewId:'v2',requestedAt:40}));p.takeNext(41);expect(complete(p,'fresh',{viewId:'v2',actualBytes:9000,completedAt:51}).phase).toBe('ready');expect(p.snapshot().map(e=>e.executionId)).toEqual(['fresh'])})
 it('advances revision and invalidates stale work',()=>{const p=new ArcGisSpatialExecutionLifecyclePolicy(budget);p.enqueue(request());expect(p.advanceLayerRevision('layer-1',2)).toBe(1);expect(()=>p.enqueue(request({executionId:'stale',revision:1}))).toThrow(/stale/)})
 it('rejects late completion',()=>{const p=new ArcGisSpatialExecutionLifecyclePolicy(budget);running(p);expect(()=>complete(p,'exec-1',{completedAt:221})).toThrow(/expired/);expect(p.snapshot()).toHaveLength(0)})
 it('touches consumes cancels and tears down deterministically',()=>{const p=new ArcGisSpatialExecutionLifecyclePolicy(budget);running(p);complete(p);expect(p.touch('exec-1',40)).toBe(true);expect(p.cancel('exec-1')).toBe(false);expect(p.consume('exec-1')?.phase).toBe('ready');p.enqueue(request({executionId:'a'}));expect(p.releaseView('view-1')).toBe(1)})
 it('supports governed kinds without payload retention',()=>{const p=new ArcGisSpatialExecutionLifecyclePolicy(budget);const kinds=['query','identify','buffer','nearest','projection','measurement'] as const;kinds.forEach((kind,i)=>p.enqueue(request({executionId:`e-${i}`,viewId:`v-${i}`,kind})));expect(p.snapshot().map(e=>e.kind)).toEqual(kinds);expect(JSON.stringify(p.snapshot())).not.toMatch(/geometry|credential|abortController/)})
 it('returns frozen detached views and deterministic fingerprints',()=>{const a=new ArcGisSpatialExecutionLifecyclePolicy(budget),b=new ArcGisSpatialExecutionLifecyclePolicy(budget);a.enqueue(request({executionId:'b'}));a.enqueue(request({executionId:'a'}));b.enqueue(request({executionId:'a'}));b.enqueue(request({executionId:'b'}));expect(Object.isFrozen(a.snapshot())).toBe(true);expect(a.fingerprint()).toBe(b.fingerprint())})
 it('rejects malformed identifiers and impossible budgets',()=>{const p=new ArcGisSpatialExecutionLifecyclePolicy(budget);expect(()=>p.enqueue(request({executionId:'bad id'}))).toThrow(/invalid/);expect(()=>new ArcGisSpatialExecutionLifecyclePolicy({...budget,maxRunningPerView:3,maxRunning:2})).toThrow(/impossible/)})
 it('fails closed after disposal',()=>{const p=new ArcGisSpatialExecutionLifecyclePolicy(budget);p.enqueue(request());p.dispose();expect(()=>p.snapshot()).toThrow(/disposed/);expect(()=>p.enqueue(request())).toThrow(/disposed/)})
})
