import { describe, expect, it } from 'vitest'
import { ArcGisQueryResultMergeLifecyclePolicy, type QueryMergeBudget } from './ArcGisQueryResultMergeLifecyclePolicy'

const budget: QueryMergeBudget = { maxLayers:2,maxQueries:4,maxQueriesPerLayer:3,maxPagesPerQuery:3,maxFeaturesPerQuery:10,maxBytesPerQuery:1000,maxResidentFeatures:12,maxResidentBytes:1200,queryTtlMs:100 }
const request=(mergeId:string,queryKey=mergeId,layerId='roads',revision=1,intent:'interactive'|'visible'|'background'='visible',requestedAt=0)=>({mergeId,queryKey,layerId,revision,intent,requestedAt})

describe('ArcGisQueryResultMergeLifecyclePolicy',()=>{
  it('requires an admitted revision and rejects logical duplicates',()=>{const p=new ArcGisQueryResultMergeLifecyclePolicy(budget);expect(p.admit(request('a'))).toBe(false);expect(p.setRevision('roads',1)).toBe(0);expect(p.admit(request('a','q'))).toBe(true);expect(p.admit(request('b','q'))).toBe(false)})
  it('merges pages strictly in order and completes on transfer-limit clear',()=>{const p=new ArcGisQueryResultMergeLifecyclePolicy(budget);p.setRevision('roads',1);p.admit(request('a'));expect(p.append('a',1,{pageIndex:1,featureCount:2,estimatedBytes:20,exceededTransferLimit:true},1)).toBeNull();expect(p.append('a',1,{pageIndex:0,featureCount:2,estimatedBytes:20,exceededTransferLimit:true},1)?.phase).toBe('collecting');const done=p.append('a',1,{pageIndex:1,featureCount:1,estimatedBytes:10,exceededTransferLimit:false},2);expect(done).toMatchObject({phase:'complete',pages:2,featureCount:3,estimatedBytes:30,nextPageIndex:2});expect(p.append('a',1,{pageIndex:2,featureCount:1,estimatedBytes:1,exceededTransferLimit:false},3)).toBeNull()})
  it('consumes only complete results and releases scalar residency',()=>{const p=new ArcGisQueryResultMergeLifecyclePolicy(budget);p.setRevision('roads',1);p.admit(request('a'));expect(p.consume('a',1)).toBeNull();p.append('a',1,{pageIndex:0,featureCount:2,estimatedBytes:20,exceededTransferLimit:false},1);expect(p.consume('a',1)?.featureCount).toBe(2);expect(p.snapshot().queries).toBe(0)})
  it('invalidates stale revisions monotonically',()=>{const p=new ArcGisQueryResultMergeLifecyclePolicy(budget);p.setRevision('roads',2);p.admit(request('a','a','roads',2));expect(p.setRevision('roads',1)).toBe(-1);expect(p.setRevision('roads',3)).toBe(1);expect(p.append('a',2,{pageIndex:0,featureCount:1,estimatedBytes:1,exceededTransferLimit:false},1)).toBeNull()})
  it('bounds per-query page feature and byte budgets',()=>{const p=new ArcGisQueryResultMergeLifecyclePolicy({...budget,maxPagesPerQuery:1,maxFeaturesPerQuery:2,maxBytesPerQuery:20});p.setRevision('roads',1);p.admit(request('a'));expect(p.append('a',1,{pageIndex:0,featureCount:3,estimatedBytes:10,exceededTransferLimit:true},1)).toBeNull();expect(p.append('a',1,{pageIndex:0,featureCount:2,estimatedBytes:21,exceededTransferLimit:true},1)).toBeNull();expect(p.append('a',1,{pageIndex:0,featureCount:2,estimatedBytes:20,exceededTransferLimit:true},1)).not.toBeNull();expect(p.append('a',1,{pageIndex:1,featureCount:0,estimatedBytes:0,exceededTransferLimit:false},2)).toBeNull()})
  it('evicts lower-intent older residency under aggregate pressure',()=>{const p=new ArcGisQueryResultMergeLifecyclePolicy({...budget,maxResidentFeatures:6,maxFeaturesPerQuery:6});p.setRevision('roads',1);p.admit(request('bg','bg','roads',1,'background'));p.append('bg',1,{pageIndex:0,featureCount:4,estimatedBytes:40,exceededTransferLimit:false},1);p.admit(request('hot','hot','roads',1,'interactive'));expect(p.append('hot',1,{pageIndex:0,featureCount:4,estimatedBytes:40,exceededTransferLimit:false},2)?.phase).toBe('complete');expect(p.consume('bg',1)).toBeNull();expect(p.snapshot().features).toBe(4)})
  it('expires idle queries at the exact ttl boundary',()=>{const p=new ArcGisQueryResultMergeLifecyclePolicy(budget);p.setRevision('roads',1);p.admit(request('a'));expect(p.expire(99)).toBe(0);expect(p.expire(100)).toBe(1)})
  it('touch extends ttl without changing merge accounting',()=>{const p=new ArcGisQueryResultMergeLifecyclePolicy(budget);p.setRevision('roads',1);p.admit(request('a'));p.append('a',1,{pageIndex:0,featureCount:1,estimatedBytes:10,exceededTransferLimit:true},10);expect(p.touch('a',1,50)).toBe(true);expect(p.expire(149)).toBe(0);expect(p.expire(150)).toBe(1)})
  it('enforces global and per-layer cardinality',()=>{const p=new ArcGisQueryResultMergeLifecyclePolicy({...budget,maxQueries:2,maxQueriesPerLayer:1});p.setRevision('roads',1);p.setRevision('parks',1);expect(p.admit(request('a'))).toBe(true);expect(p.admit(request('b','b'))).toBe(false);expect(p.admit(request('c','c','parks'))).toBe(true);expect(p.snapshot().queries).toBe(2)})
  it('releases layer revision and entries together',()=>{const p=new ArcGisQueryResultMergeLifecyclePolicy(budget);p.setRevision('roads',1);p.admit(request('a'));expect(p.releaseLayer('roads')).toBe(1);expect(p.admit(request('b'))).toBe(false);expect(p.snapshot().layers).toBe(0)})
  it('produces frozen aggregate snapshots and deterministic fingerprints',()=>{const p=new ArcGisQueryResultMergeLifecyclePolicy(budget);p.setRevision('roads',1);p.admit(request('b','z'));p.admit(request('a','a'));p.append('a',1,{pageIndex:0,featureCount:2,estimatedBytes:20,exceededTransferLimit:false},1);const s=p.snapshot();expect(Object.isFrozen(s)).toBe(true);expect(s).toMatchObject({layers:1,queries:2,collecting:1,complete:1,pages:1,features:2,bytes:20});expect(p.fingerprint()).toContain('roads:a:1:visible:complete:1:2:20')})
  it('rejects malformed scalar admission without retaining payload-like state',()=>{const p=new ArcGisQueryResultMergeLifecyclePolicy(budget);p.setRevision('roads',1);expect(()=>p.admit(request('\u0000bad'))).toThrow();expect(()=>p.append('missing',1,{pageIndex:-1,featureCount:0,estimatedBytes:0,exceededTransferLimit:false},0)).toThrow();expect(JSON.stringify(p.snapshot())).not.toMatch(/geometry|token|credential|featureSet/i)})
  it('disposes terminally and idempotently',()=>{const p=new ArcGisQueryResultMergeLifecyclePolicy(budget);p.setRevision('roads',1);p.admit(request('a'));p.dispose();p.dispose();expect(()=>p.snapshot()).toThrow(/disposed/)})
})
