import{describe,expect,it}from'vitest'
import{ArcGisSpatialIntegrityPolicy}from'./ArcGisSpatialIntegrityPolicy'
const policy=(overrides={})=>new ArcGisSpatialIntegrityPolicy({maxCoordinates:100,maxRings:10,maxPaths:10,maxParts:20,maxWktLength:100,maxAbsoluteCoordinate:1_000_000,allowUnknownWkid:false,...overrides})
describe('ArcGisSpatialIntegrityPolicy',()=>{
it('accepts known ArcGIS spatial references',()=>expect(policy().admitSpatialReference({wkid:4326})).toMatchObject({accepted:true,spatialReference:{wkid:4326}}))
it('accepts Web Mercator aliases',()=>expect(policy().admitSpatialReference({wkid:102100,latestWkid:3857})).toMatchObject({accepted:true}))
it('rejects missing spatial reference identity',()=>expect(policy().admitSpatialReference({})).toEqual({accepted:false,reason:'spatial-reference-identity-required'}))
it('rejects unknown wkid by default',()=>expect(policy().admitSpatialReference({wkid:999999})).toEqual({accepted:false,reason:'unknown-wkid:999999'}))
it('can explicitly admit unknown wkids',()=>expect(policy({allowUnknownWkid:true}).admitSpatialReference({wkid:999999})).toMatchObject({accepted:true}))
it('sanitizes bounded wkt control characters',()=>{const result=policy().admitSpatialReference({wkt:'GEOGCS["x"]\n'});expect(result.accepted&&result.spatialReference.wkt).not.toMatch(/[\u0000-\u001f]/)})
it('rejects oversized wkt',()=>expect(policy({maxWktLength:4}).admitSpatialReference({wkt:'12345'})).toMatchObject({accepted:false}))
it('normalizes valid extents',()=>expect(policy().admitExtent({xmin:1,ymin:2,xmax:3,ymax:4,spatialReference:{wkid:4326}})).toMatchObject({accepted:true,extent:{xmin:1,ymin:2,xmax:3,ymax:4}}))
it('rejects inverted extents',()=>expect(policy().admitExtent({xmin:4,ymin:2,xmax:3,ymax:4,spatialReference:{wkid:4326}})).toEqual({accepted:false,reason:'extent-minimum-exceeds-maximum'}))
it('rejects non-finite extent coordinates',()=>expect(policy().admitExtent({xmin:NaN,ymin:2,xmax:3,ymax:4,spatialReference:{wkid:4326}})).toEqual({accepted:false,reason:'xmin must be finite'}))
it('rejects coordinates beyond configured budget',()=>expect(policy({maxAbsoluteCoordinate:10}).admitExtent({xmin:-11,ymin:0,xmax:1,ymax:1,spatialReference:{wkid:4326}})).toMatchObject({accepted:false}))
it('requires exactly one point coordinate',()=>expect(policy().validateCardinality('point',{coordinates:2})).toEqual({accepted:false,reason:'point-requires-one-coordinate'}))
it('accepts bounded multipoints',()=>expect(policy().validateCardinality('multipoint',{coordinates:5,parts:5})).toMatchObject({accepted:true}))
it('rejects multipoint ring contamination',()=>expect(policy().validateCardinality('multipoint',{coordinates:5,rings:1})).toEqual({accepted:false,reason:'multipoint-cannot-contain-rings-or-paths'}))
it('requires polyline paths',()=>expect(policy().validateCardinality('polyline',{coordinates:5,paths:0})).toEqual({accepted:false,reason:'polyline-requires-paths-only'}))
it('accepts bounded polyline paths',()=>expect(policy().validateCardinality('polyline',{coordinates:5,paths:2,parts:2})).toMatchObject({accepted:true}))
it('requires polygon rings',()=>expect(policy().validateCardinality('polygon',{coordinates:5,rings:0})).toEqual({accepted:false,reason:'polygon-requires-rings-only'}))
it('rejects polygon path contamination',()=>expect(policy().validateCardinality('polygon',{coordinates:5,rings:1,paths:1})).toEqual({accepted:false,reason:'polygon-requires-rings-only'}))
it('requires extent corner cardinality',()=>expect(policy().validateCardinality('extent',{coordinates:4})).toEqual({accepted:false,reason:'extent-requires-two-corner-coordinates'}))
it('enforces coordinate cardinality budget',()=>expect(policy().validateCardinality('multipoint',{coordinates:101})).toMatchObject({accepted:false}))
it('rejects more parts than coordinates',()=>expect(policy().validateCardinality('multipoint',{coordinates:2,parts:3})).toEqual({accepted:false,reason:'parts-exceed-coordinate-count'}))
it('rejects invalid construction budgets',()=>expect(()=>policy({maxCoordinates:0})).toThrow('maxCoordinates'))
})
