import { describe, expect, it } from 'vitest'
import { ArcGisSceneLodResidencyPolicy, type ArcGisSceneLodBudget } from './ArcGisSceneLodResidencyPolicy'

const budget: ArcGisSceneLodBudget = { maxTiles: 8, maxTilesPerView: 5, maxTilesPerLayer: 5, maxLoading: 2, maxLoadingPerView: 1, maxResident: 3, maxEstimatedTrianglesPerTile: 100, maxActualTrianglesPerTile: 200, maxResidentTriangles: 400, maxEstimatedBytesPerTile: 1000, maxActualBytesPerTile: 2000, maxResidentBytes: 4000, minLevel: 0, maxLevel: 12, queueTtlMs: 50, loadTtlMs: 50, residentTtlMs: 100 }
const request = (tileId: string, overrides = {}) => ({ tileId, viewId: 'view-1', layerId: 'scene-1', revision: 1, level: 4, intent: 'visible' as const, requestedAt: 10, estimatedTriangles: 50, estimatedBytes: 500, ...overrides })
const completion = (tileId: string, overrides = {}) => ({ tileId, viewId: 'view-1', layerId: 'scene-1', revision: 1, level: 4, actualTriangles: 80, actualBytes: 800, completedAt: 20, ...overrides })

describe('ArcGisSceneLodResidencyPolicy', () => {
  it('schedules interactive and finer LOD work deterministically', () => { const p = new ArcGisSceneLodResidencyPolicy(budget); p.enqueue(request('background', { viewId: 'v1', intent: 'background', level: 8 })); p.enqueue(request('visible', { viewId: 'v2', intent: 'visible', level: 4 })); p.enqueue(request('interactive-coarse', { viewId: 'v3', intent: 'interactive', level: 3 })); p.enqueue(request('interactive-fine', { viewId: 'v4', intent: 'interactive', level: 9 })); expect(p.takeNext(11)?.tileId).toBe('interactive-fine'); expect(p.takeNext(11)?.tileId).toBe('interactive-coarse') })
  it('enforces per-view loading concurrency without starving other views', () => { const p = new ArcGisSceneLodResidencyPolicy(budget); p.enqueue(request('a', { viewId: 'same', intent: 'interactive' })); p.enqueue(request('b', { viewId: 'same', intent: 'interactive' })); p.enqueue(request('c', { viewId: 'other', intent: 'visible' })); expect(p.takeNext(11)?.tileId).toBe('a'); expect(p.takeNext(11)?.tileId).toBe('c'); expect(p.takeNext(11)).toBeUndefined() })
  it('reconciles estimates to actual residency budgets', () => { const p = new ArcGisSceneLodResidencyPolicy(budget); p.enqueue(request('a')); p.takeNext(11); expect(p.complete(completion('a')).phase).toBe('resident'); expect(p.snapshot()[0]).toMatchObject({ actualTriangles: 80, actualBytes: 800 }) })
  it('rejects actual work exceeding per-tile budgets and releases authority', () => { const p = new ArcGisSceneLodResidencyPolicy(budget); p.enqueue(request('a')); p.takeNext(11); expect(() => p.complete(completion('a', { actualTriangles: 201 }))).toThrow('actual triangle budget exceeded'); expect(p.snapshot()).toHaveLength(0) })
  it('rejects malformed identifiers and impossible LOD levels', () => { const p = new ArcGisSceneLodResidencyPolicy(budget); expect(() => p.enqueue(request('bad id'))).toThrow('tileId is invalid'); expect(() => p.enqueue(request('a', { level: 13 }))).toThrow('LOD level outside budget') })
  it('invalidates stale work when layer revision advances', () => { const p = new ArcGisSceneLodResidencyPolicy(budget); p.enqueue(request('old')); p.takeNext(11); expect(p.advanceLayerRevision('scene-1', 2)).toBe(1); expect(p.snapshot()).toHaveLength(0); expect(() => p.enqueue(request('stale'))).toThrow('stale layer revision') })
  it('rejects late completions and removes expired loading authority', () => { const p = new ArcGisSceneLodResidencyPolicy(budget); p.enqueue(request('a')); p.takeNext(11); expect(() => p.complete(completion('a', { completedAt: 62 }))).toThrow('LOD load lease expired'); expect(p.snapshot()).toHaveLength(0) })
  it('expires queued and resident leases deterministically', () => { const p = new ArcGisSceneLodResidencyPolicy(budget); p.enqueue(request('queued')); expect(p.expire(61)).toBe(1); p.enqueue(request('resident', { requestedAt: 70 })); p.takeNext(71); p.complete(completion('resident', { completedAt: 72 })); expect(p.expire(173)).toBe(1) })
  it('touch extends only live resident leases', () => { const p = new ArcGisSceneLodResidencyPolicy(budget); p.enqueue(request('a')); p.takeNext(11); p.complete(completion('a')); expect(p.touch('a', 30)).toBe(true); expect(p.snapshot()[0].expiresAt).toBe(130); expect(p.touch('a', 131)).toBe(false) })
  it('consume returns a detached immutable scalar view', () => { const p = new ArcGisSceneLodResidencyPolicy(budget); p.enqueue(request('a')); p.takeNext(11); p.complete(completion('a')); const consumed = p.consume('a'); expect(consumed?.tileId).toBe('a'); expect(Object.isFrozen(consumed)).toBe(true); expect(p.snapshot()).toHaveLength(0) })
  it('cancel refuses resident authority but removes queued/loading work', () => { const p = new ArcGisSceneLodResidencyPolicy(budget); p.enqueue(request('queued')); expect(p.cancel('queued')).toBe(true); p.enqueue(request('resident')); p.takeNext(11); p.complete(completion('resident')); expect(p.cancel('resident')).toBe(false) })
  it('tears down view and layer authority without retaining payload graphs', () => { const p = new ArcGisSceneLodResidencyPolicy(budget); p.enqueue(request('a', { viewId: 'v1' })); p.enqueue(request('b', { viewId: 'v2' })); expect(p.releaseView('v1')).toBe(1); expect(p.releaseLayer('scene-1')).toBe(1); expect(p.snapshot()).toHaveLength(0) })
  it('evicts lower-intent coarse residents under GPU pressure', () => { const p = new ArcGisSceneLodResidencyPolicy({ ...budget, maxResident: 2, maxResidentTriangles: 200, maxResidentBytes: 2000 }); p.enqueue(request('background', { viewId: 'v1', intent: 'background', level: 2 })); p.takeNext(11); p.complete(completion('background')); p.enqueue(request('visible', { viewId: 'v2', intent: 'visible', level: 5 })); p.takeNext(21); p.complete(completion('visible', { viewId: 'v2', completedAt: 22 })); p.enqueue(request('interactive', { viewId: 'v3', intent: 'interactive', level: 9 })); p.takeNext(31); p.complete(completion('interactive', { viewId: 'v3', completedAt: 32 })); expect(policyIds(p)).toEqual(['interactive', 'visible']) })
  it('does not evict equal or higher intent residency for lower priority work', () => { const p = new ArcGisSceneLodResidencyPolicy({ ...budget, maxResident: 1, maxResidentTriangles: 100, maxResidentBytes: 1000 }); p.enqueue(request('interactive', { viewId: 'v1', intent: 'interactive' })); p.takeNext(11); p.complete(completion('interactive')); p.enqueue(request('background', { viewId: 'v2', intent: 'background', requestedAt: 30 })); p.takeNext(31); expect(() => p.complete(completion('background', { viewId: 'v2', completedAt: 32 }))).toThrow('resident LOD capacity exceeded'); expect(policyIds(p)).toEqual(['interactive']) })
  it('fails closed after disposal', () => { const p = new ArcGisSceneLodResidencyPolicy(budget); p.enqueue(request('a')); p.dispose(); expect(() => p.snapshot()).toThrow('disposed'); expect(() => p.enqueue(request('b'))).toThrow('disposed') })
  it('keeps fingerprints scalar and deterministic', () => { const p = new ArcGisSceneLodResidencyPolicy(budget); p.enqueue(request('b', { viewId: 'v2' })); p.enqueue(request('a', { viewId: 'v1' })); expect(p.fingerprint()).toContain('a:v1:scene-1:1:4:visible:queued:0:0'); expect(p.fingerprint().indexOf('a:')).toBeLessThan(p.fingerprint().indexOf('b:')) })
})
function policyIds(policy: ArcGisSceneLodResidencyPolicy): string[] { return policy.snapshot().filter(item => item.phase === 'resident').map(item => item.tileId).sort() }
