import { describe, expect, it } from 'vitest';
import { ArcGisViewLodCoordinator, type ArcGisViewLodRequest } from './ArcGisViewLodCoordinator';

const policy = { maxLayers: 3, maxFeatureBudget: 1000, maxDrawCalls: 100, maxGpuBytes: 10000, maxLevel: 5, pressureHighWatermark: .85, pressureLowWatermark: .5, recoveryFrames: 2 } as const;
const req = (layerId:string, workload:ArcGisViewLodRequest['workload']='visible', extra:Partial<ArcGisViewLodRequest>={}):ArcGisViewLodRequest => ({ layerId, viewMode:'2d', workload, desiredLevel:5, minLevel:1, estimatedFeatures:200, estimatedDrawCalls:20, estimatedGpuBytes:2000, ...extra });

describe('ArcGisViewLodCoordinator',()=>{
  it('admits and snapshots deterministic layer state',()=>{ const c=new ArcGisViewLodCoordinator(policy); expect(c.upsert(req('roads'),1)).toMatchObject({layerId:'roads',effectiveLevel:5,degraded:false,generation:1}); expect(c.list().map(x=>x.layerId)).toEqual(['roads']); });
  it('rejects malformed policies',()=>{ expect(()=>new ArcGisViewLodCoordinator({...policy,maxLayers:0})).toThrow(); expect(()=>new ArcGisViewLodCoordinator({...policy,pressureLowWatermark:.9})).toThrow(); });
  it('rejects malformed requests',()=>{ const c=new ArcGisViewLodCoordinator(policy); expect(()=>c.upsert(req(' '),1)).toThrow(); expect(()=>c.upsert(req('x','visible',{minLevel:6}),1)).toThrow(); expect(()=>c.upsert(req('x','visible',{estimatedFeatures:1001}),1)).toThrow(); });
  it('degrades lower priority work first under aggregate pressure',()=>{ const c=new ArcGisViewLodCoordinator(policy); c.upsert(req('critical','critical',{estimatedFeatures:450}),1); c.upsert(req('background','background',{estimatedFeatures:450}),2); c.upsert(req('visible','visible',{estimatedFeatures:450}),3); expect(c.get('background')!.effectiveLevel).toBeLessThan(5); expect(c.get('critical')!.effectiveLevel).toBe(5); expect(c.budgetSnapshot().pressure).toBeLessThanOrEqual(1); });
  it('preserves minimum LOD and fails closed when minimum cannot fit',()=>{ const c=new ArcGisViewLodCoordinator({...policy,maxFeatureBudget:300}); c.upsert(req('a','visible',{estimatedFeatures:200}),1); expect(()=>c.upsert(req('b','visible',{estimatedFeatures:300}),2)).toThrow(); });
  it('evicts only lower priority work at layer capacity',()=>{ const c=new ArcGisViewLodCoordinator(policy); c.upsert(req('a','background'),1); c.upsert(req('b','visible'),2); c.upsert(req('c','visible'),3); c.upsert(req('d','critical'),4); expect(c.get('a')).toBeNull(); expect(c.get('d')).not.toBeNull(); });
  it('refuses equal priority eviction at layer capacity',()=>{ const c=new ArcGisViewLodCoordinator(policy); c.upsert(req('a'),1); c.upsert(req('b'),2); c.upsert(req('c'),3); expect(()=>c.upsert(req('d'),4)).toThrow('capacity'); });
  it('does not allow a layer to cross view modes implicitly',()=>{ const c=new ArcGisViewLodCoordinator(policy); c.upsert(req('a'),1); expect(()=>c.upsert(req('a','visible',{viewMode:'3d'}),2)).toThrow('viewMode'); });
  it('supports explicit remove before 2d to 3d migration',()=>{ const c=new ArcGisViewLodCoordinator(policy); c.upsert(req('a'),1); c.remove('a'); expect(c.upsert(req('a','visible',{viewMode:'3d'}),2).viewMode).toBe('3d'); });
  it('returns immutable snapshots',()=>{ const c=new ArcGisViewLodCoordinator(policy); const s=c.upsert(req('a'),1); expect(Object.isFrozen(s)).toBe(true); expect(Object.isFrozen(c.list())).toBe(true); expect(Object.isFrozen(c.budgetSnapshot())).toBe(true); });
  it('reports aggregate budget accounting',()=>{ const c=new ArcGisViewLodCoordinator(policy); c.upsert(req('a'),1); const b=c.budgetSnapshot(); expect(b.layers).toBe(1); expect(b.features).toBe(200); expect(b.drawCalls).toBe(20); expect(b.gpuBytes).toBe(2000); });
  it('degrades on high-watermark frames',()=>{ const c=new ArcGisViewLodCoordinator(policy); c.upsert(req('a','background',{estimatedFeatures:900}),1); const before=c.get('a')!.effectiveLevel; c.recordFrame(2); expect(c.get('a')!.effectiveLevel).toBeLessThan(before); });
  it('recovers only after configured low-pressure frames',()=>{ const c=new ArcGisViewLodCoordinator(policy); c.upsert(req('a','background',{desiredLevel:5,minLevel:1,estimatedFeatures:900}),1); c.recordFrame(2); const low=c.get('a')!.effectiveLevel; c.upsert(req('a','background',{desiredLevel:5,minLevel:1,estimatedFeatures:100}),3); c.recordFrame(4); expect(c.get('a')!.effectiveLevel).toBe(low); c.recordFrame(5); expect(c.get('a')!.effectiveLevel).toBeGreaterThan(low); });
  it('recovers critical work before background work',()=>{ const c=new ArcGisViewLodCoordinator({...policy,recoveryFrames:1}); c.upsert(req('critical','critical',{estimatedFeatures:800}),1); c.upsert(req('background','background',{estimatedFeatures:800}),2); const criticalBefore=c.get('critical')!.effectiveLevel; c.upsert(req('critical','critical',{estimatedFeatures:50}),3); c.upsert(req('background','background',{estimatedFeatures:50}),4); c.recordFrame(5); expect(c.get('critical')!.effectiveLevel).toBeGreaterThanOrEqual(criticalBefore); });
  it('keeps stable generation across updates',()=>{ const c=new ArcGisViewLodCoordinator(policy); const a=c.upsert(req('a'),1); const b=c.upsert(req('a','critical'),2); expect(b.generation).toBe(a.generation); });
  it('allocates a new generation after removal',()=>{ const c=new ArcGisViewLodCoordinator(policy); const a=c.upsert(req('a'),1); c.remove('a'); const b=c.upsert(req('a'),2); expect(b.generation).toBeGreaterThan(a.generation); });
  it('sorts list deterministically',()=>{ const c=new ArcGisViewLodCoordinator(policy); c.upsert(req('z'),1); c.upsert(req('a'),2); expect(c.list().map(x=>x.layerId)).toEqual(['a','z']); });
  it('filters list by view mode',()=>{ const c=new ArcGisViewLodCoordinator(policy); c.upsert(req('a'),1); c.upsert(req('b','visible',{viewMode:'3d'}),2); expect(c.list('3d').map(x=>x.layerId)).toEqual(['b']); });
  it('normalizes layer identifiers',()=>{ const c=new ArcGisViewLodCoordinator(policy); expect(c.upsert(req(' roads '),1).layerId).toBe('roads'); expect(c.get(' roads ')!.layerId).toBe('roads'); });
  it('rejects unsafe numeric values',()=>{ const c=new ArcGisViewLodCoordinator(policy); expect(()=>c.upsert(req('a','visible',{estimatedGpuBytes:Number.MAX_SAFE_INTEGER+1}),1)).toThrow(); expect(()=>c.upsert(req('a'),-1)).toThrow(); });
  it('removal is idempotent for missing layers',()=>{ const c=new ArcGisViewLodCoordinator(policy); expect(c.remove('missing')).toBeNull(); });
  it('disposal clears state and prevents reuse',()=>{ const c=new ArcGisViewLodCoordinator(policy); c.upsert(req('a'),1); c.dispose(); c.dispose(); expect(()=>c.list()).toThrow('disposed'); expect(()=>c.upsert(req('b'),2)).toThrow('disposed'); });
});
