export interface ArcGisTimeWindowInput { readonly layerId:string; readonly startMs:number; readonly endMs:number; readonly revision:number; readonly mode:'instant'|'range'; readonly stepMs?:number }
export interface ArcGisTimeWindowBudgets { readonly minEpochMs:number; readonly maxEpochMs:number; readonly maxSpanMs:number; readonly minStepMs:number; readonly maxSteps:number }
export interface ArcGisTimeWindowPlan { readonly layerId:string; readonly startMs:number; readonly endMs:number; readonly revision:number; readonly mode:'instant'|'range'; readonly stepMs?:number; readonly stepCount:number; readonly fingerprint:string }
const ID_PATTERN=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
function safeInteger(value:number,label:string){if(!Number.isSafeInteger(value))throw new Error(`${label} must be a safe integer`);return value}
function nonNegative(value:number,label:string){const normalized=safeInteger(value,label);if(normalized<0)throw new Error(`${label} must be non-negative`);return normalized}
function hash(text:string){let value=2166136261;for(let index=0;index<text.length;index+=1){value^=text.charCodeAt(index);value=Math.imul(value,16777619)}return(value>>>0).toString(16).padStart(8,'0')}
export class ArcGisTimeWindowPolicy {
 readonly #budgets:Readonly<ArcGisTimeWindowBudgets>;
 constructor(budgets:ArcGisTimeWindowBudgets){const normalized={minEpochMs:safeInteger(budgets.minEpochMs,'minEpochMs'),maxEpochMs:safeInteger(budgets.maxEpochMs,'maxEpochMs'),maxSpanMs:nonNegative(budgets.maxSpanMs,'maxSpanMs'),minStepMs:nonNegative(budgets.minStepMs,'minStepMs'),maxSteps:nonNegative(budgets.maxSteps,'maxSteps')};if(normalized.maxEpochMs<normalized.minEpochMs)throw new Error('invalid epoch budget');if(normalized.maxSpanMs<1||normalized.minStepMs<1||normalized.maxSteps<1)throw new Error('temporal budgets must be positive');this.#budgets=Object.freeze(normalized)}
 plan(input:ArcGisTimeWindowInput):ArcGisTimeWindowPlan{const layerId=input.layerId.trim();if(!ID_PATTERN.test(layerId)||layerId!==input.layerId)throw new Error('invalid layer id');const startMs=safeInteger(input.startMs,'startMs'),endMs=safeInteger(input.endMs,'endMs'),revision=nonNegative(input.revision,'revision');if(startMs<this.#budgets.minEpochMs||endMs>this.#budgets.maxEpochMs)throw new Error('time window exceeds epoch budget');if(endMs<startMs)throw new Error('time window must be ordered');const span=endMs-startMs;if(span>this.#budgets.maxSpanMs)throw new Error('time window exceeds span budget');let stepMs:number|undefined,stepCount=1;if(input.mode==='instant'){if(startMs!==endMs)throw new Error('instant window requires equal endpoints');if(input.stepMs!==undefined)throw new Error('instant window cannot define step')}else{if(startMs===endMs)throw new Error('range window requires positive span');if(input.stepMs===undefined)throw new Error('range window requires step');stepMs=nonNegative(input.stepMs,'stepMs');if(stepMs<this.#budgets.minStepMs)throw new Error('step below temporal budget');stepCount=Math.ceil(span/stepMs)+1;if(stepCount>this.#budgets.maxSteps)throw new Error('temporal step budget exceeded')}const canonical=JSON.stringify([layerId,startMs,endMs,revision,input.mode,stepMs??null,stepCount]);return Object.freeze({layerId,startMs,endMs,revision,mode:input.mode,...(stepMs===undefined?{}:{stepMs}),stepCount,fingerprint:hash(canonical)})}
 assertRevision(plan:ArcGisTimeWindowPlan,currentRevision:number){const revision=nonNegative(currentRevision,'currentRevision');if(plan.revision!==revision)throw new Error('stale temporal plan revision')}
}
