import { describe, expect, it } from 'vitest'
import { ArcGisQueryResponseCacheLifecyclePolicy, type QueryResponseCacheBudget, type QueryResponseCacheRequest } from './ArcGisQueryResponseCacheLifecyclePolicy'

const budget: QueryResponseCacheBudget = { maxLayers:3,maxEntries:5,maxEntriesPerLayer:3,maxFeaturesPerEntry:20,maxBytesPerEntry:2000,maxResidentFeatures:40,maxResidentBytes:4000,ttlMs:100 }
const policy=(custom:Partial<QueryResponseCacheBudget>={})=>new ArcGisQueryResponseCacheLifecyclePolicy({...budget,...custom})
const request=(cacheKey:string,layerId='parcels',revision=1,intent:QueryResponseCacheRequest['intent']='visible',storedAt=0,featureCount=5,byteCount=500,signature=`sig-${cacheKey}`):QueryResponseCacheRequest=>({cacheKey,layerId,revision,intent,featureCount,byteCount,storedAt,signature})

describe('ArcGisQueryResponseCacheLifecyclePolicy',()=>{
  it('validates coherent bounded budgets',()=>{expect(()=>policy({maxEntries:0})).toThrow();expect(()=>policy({maxEntriesPerLayer:6})).toThrow();expect(()=>policy({maxResidentFeatures:10})).toThrow();expect(()=>policy({ttlMs:0})).toThrow()})
  it('requires current layer revision',()=>{const s=policy();expect(s.admit(request('a'))).toBeNull();expect(s.setRevision('parcels',1)).toBe(0);expect(s.admit(request('a'))?.cacheKey).toBe('a')})
  it('invalidates stale revision residency',()=>{const s=policy();s.setRevision('parcels',1);s.admit(request('a'));expect(s.setRevision('parcels',2)).toBe(1);expect(s.get('a',1,1)).toBeNull();expect(s.setRevision('parcels',1)).toBe(-1)})
  it('rejects unsafe scalar metadata',()=>{const s=policy();s.setRevision('parcels',1);expect(()=>s.admit(request(''))).toThrow();expect(()=>s.admit({...request('a'),signature:'bad\nvalue'})).toThrow();expect(()=>s.admit({...request('a'),featureCount:-1})).toThrow();expect(()=>s.admit({...request('a'),byteCount:Number.NaN})).toThrow();expect(()=>s.admit({...request('a'),intent:'other' as never})).toThrow()})
  it('rejects individually oversized responses',()=>{const s=policy();s.setRevision('parcels',1);expect(s.admit(request('a','parcels',1,'visible',0,21,500))).toBeNull();expect(s.admit(request('b','parcels',1,'visible',0,5,2001))).toBeNull()})
  it('dedupes identical cache keys without growing residency',()=>{const s=policy();s.setRevision('parcels',1);s.admit(request('a'));const second=s.admit(request('a','parcels',1,'visible',10));expect(second?.touchedAt).toBe(10);expect(s.snapshot().entries).toBe(1)})
  it('rejects cache-key collisions with different signatures',()=>{const s=policy();s.setRevision('parcels',1);s.admit(request('a'));expect(s.admit(request('a','parcels',1,'visible',1,5,500,'different'))).toBeNull();expect(s.snapshot().entries).toBe(1)})
  it('dedupes logical signatures across alternate keys',()=>{const s=policy();s.setRevision('parcels',1);s.admit(request('a','parcels',1,'visible',0,5,500,'same'));const view=s.admit(request('b','parcels',1,'visible',5,5,500,'same'));expect(view?.cacheKey).toBe('a');expect(s.snapshot().entries).toBe(1)})
  it('enforces per-layer cardinality by deterministic intent eviction',()=>{const s=policy({maxEntriesPerLayer:2});s.setRevision('p',1);s.admit(request('b','p',1,'background'));s.admit(request('v','p',1,'visible'));expect(s.admit(request('i','p',1,'interactive'))?.cacheKey).toBe('i');expect(s.get('b',1,1)).toBeNull();expect(s.snapshot().entries).toBe(2)})
  it('does not evict higher-intent entries for lower-intent arrivals',()=>{const s=policy({maxEntriesPerLayer:1});s.setRevision('p',1);s.admit(request('i','p',1,'interactive'));expect(s.admit(request('b','p',1,'background'))).toBeNull();expect(s.get('i',1,1)?.cacheKey).toBe('i')})
  it('enforces global cardinality across layers',()=>{const s=policy({maxEntries:2,maxEntriesPerLayer:2});s.setRevision('a',1);s.setRevision('b',1);s.setRevision('c',1);s.admit(request('a','a',1,'background'));s.admit(request('b','b',1,'visible'));expect(s.admit(request('c','c',1,'interactive'))?.cacheKey).toBe('c');expect(s.snapshot().entries).toBe(2);expect(s.get('a',1,1)).toBeNull()})
  it('relieves aggregate feature pressure',()=>{const s=policy({maxResidentFeatures:20});s.setRevision('p',1);s.admit(request('old','p',1,'background',0,15,500));expect(s.admit(request('new','p',1,'interactive',1,10,500))?.cacheKey).toBe('new');expect(s.get('old',1,2)).toBeNull();expect(s.snapshot().residentFeatures).toBe(10)})
  it('relieves aggregate byte pressure',()=>{const s=policy({maxResidentBytes:2000});s.setRevision('p',1);s.admit(request('old','p',1,'background',0,5,1500));expect(s.admit(request('new','p',1,'interactive',1,5,1000))?.cacheKey).toBe('new');expect(s.snapshot().residentBytes).toBe(1000)})
  it('rejects pressure admission when only higher-intent residency exists',()=>{const s=policy({maxResidentBytes:2000});s.setRevision('p',1);s.admit(request('interactive','p',1,'interactive',0,5,1500));expect(s.admit(request('background','p',1,'background',1,5,1000))).toBeNull();expect(s.snapshot().residentBytes).toBe(1500)})
  it('expires entries at the TTL boundary',()=>{const s=policy();s.setRevision('p',1);s.admit(request('a','p'));expect(s.get('a',1,99)?.cacheKey).toBe('a');expect(s.get('a',1,100)).toBeNull()})
  it('touch extends only live matching revisions',()=>{const s=policy();s.setRevision('p',1);s.admit(request('a','p'));expect(s.touch('a',1,50)).toBe(true);expect(s.get('a',1,149)?.cacheKey).toBe('a');expect(s.touch('a',2,149)).toBe(false);expect(s.get('a',1,150)).toBeNull()})
  it('bulk expiry returns deterministic removal count',()=>{const s=policy();s.setRevision('p',1);s.admit(request('a','p',1,'visible',0));s.admit(request('b','p',1,'visible',50));expect(s.expire(100)).toBe(1);expect(s.snapshot().entries).toBe(1)})
  it('supports explicit invalidation and layer release',()=>{const s=policy();s.setRevision('a',1);s.setRevision('b',1);s.admit(request('a1','a'));s.admit(request('a2','a'));s.admit(request('b1','b'));expect(s.invalidate('a1')).toBe(true);expect(s.releaseLayer('a')).toBe(1);expect(s.snapshot().layers).toBe(1);expect(s.snapshot().entries).toBe(1)})
  it('returns frozen payload-free snapshots and views',()=>{const s=policy();s.setRevision('p',1);const view=s.admit(request('a','p'))!;const snap=s.snapshot();expect(Object.isFrozen(view)).toBe(true);expect(Object.isFrozen(snap)).toBe(true);expect(snap).toEqual({layers:1,entries:1,residentFeatures:5,residentBytes:500});expect('payload' in view).toBe(false)})
  it('fingerprints scalar state deterministically',()=>{const s=policy();s.setRevision('b',1);s.setRevision('a',1);s.admit(request('z','b',1,'visible',0,5,500,'sig-z'));s.admit(request('a','a',1,'interactive',0,4,400,'sig-a'));expect(s.fingerprint()).toBe('a:a:1:interactive:4:400:sig-a|b:z:1:visible:5:500:sig-z')})
  it('disposes terminally and idempotently',()=>{const s=policy();s.setRevision('p',1);s.admit(request('a','p'));s.dispose();s.dispose();expect(()=>s.snapshot()).toThrow(/disposed/);expect(()=>s.admit(request('b','p'))).toThrow(/disposed/)})
})
