import {describe,expect,it} from 'vitest'
import {ArcGisQueryCountLifecyclePolicy,type QueryCountBudget} from './ArcGisQueryCountLifecyclePolicy'
const budget:QueryCountBudget={maxLayers:2,maxQueued:3,maxRunning:2,maxRunningPerLayer:1,maxResident:2,queueTtlMs:100,leaseTtlMs:50,residentTtlMs:200}
const ready=()=>{const p=new ArcGisQueryCountLifecyclePolicy(budget);p.setRevision('roads',1);p.setRevision('buildings',1);return p}
describe('ArcGisQueryCountLifecyclePolicy',()=>{
 it('schedules intent deterministically while respecting per-layer concurrency',()=>{const p=ready();p.enqueue({key:'bg',layerId:'roads',revision:1,intent:'background',signature:'all',queuedAt:1});p.enqueue({key:'interactive',layerId:'roads',revision:1,intent:'interactive',signature:'visible',queuedAt:2});p.enqueue({key:'other',layerId:'buildings',revision:1,intent:'visible',signature:'all',queuedAt:3});expect(p.startNext(10)?.key).toBe('interactive');expect(p.startNext(10)?.key).toBe('other');expect(p.startNext(10)).toBeNull()})
 it('deduplicates logical work and rejects request-key collisions',()=>{const p=ready();expect(p.enqueue({key:'a',layerId:'roads',revision:1,intent:'visible',signature:'same',queuedAt:1})).toBe(true);expect(p.enqueue({key:'alias',layerId:'roads',revision:1,intent:'visible',signature:'same',queuedAt:2})).toBe(true);expect(p.snapshot().queued).toBe(1);expect(p.enqueue({key:'a',layerId:'buildings',revision:1,intent:'visible',signature:'other',queuedAt:3})).toBe(false)})
 it('invalidates stale revisions and refuses stale completion',()=>{const p=ready();p.enqueue({key:'a',layerId:'roads',revision:1,intent:'visible',signature:'all',queuedAt:1});expect(p.startNext(2)?.key).toBe('a');expect(p.setRevision('roads',2)).toBe(1);expect(p.complete('a',1,12,3)).toBeNull();expect(p.enqueue({key:'stale',layerId:'roads',revision:1,intent:'visible',signature:'all',queuedAt:4})).toBe(false)})
 it('keeps only scalar count metadata and expires leases/results at boundaries',()=>{const p=ready();p.enqueue({key:'a',layerId:'roads',revision:1,intent:'visible',signature:'where=1',queuedAt:1});const lease=p.startNext(10);expect(lease?.expiresAt).toBe(60);expect(p.renew('a',1,59)).toBe(true);const result=p.complete('a',1,42,60);expect(result?.count).toBe(42);expect(Object.isFrozen(result)).toBe(true);expect(p.get('a',1,259)?.count).toBe(42);expect(p.get('a',1,260)).toBeNull()})
 it('bounds resident counts with deterministic least-recently-used eviction',()=>{const p=ready();for(const [key,layer,at] of [['a','roads',1],['b','buildings',2]] as const){p.enqueue({key,layerId:layer,revision:1,intent:'visible',signature:key,queuedAt:at});p.startNext(at+1);p.complete(key,1,at,at+2)}p.get('a',1,10);p.enqueue({key:'c',layerId:'roads',revision:1,intent:'interactive',signature:'c',queuedAt:11});p.startNext(12);p.complete('c',1,3,13);expect(p.get('b',1,14)).toBeNull();expect(p.get('a',1,14)?.count).toBe(1);expect(p.get('c',1,14)?.count).toBe(3)})
 it('fails closed on invalid scalar input and terminal disposal',()=>{const p=ready();expect(()=>p.enqueue({key:'x',layerId:'roads',revision:1,intent:'visible',signature:'x',queuedAt:Number.NaN})).toThrow('queuedAt');p.dispose();p.dispose();expect(()=>p.snapshot()).toThrow('disposed')})
})
