export type QueryCountIntent='interactive'|'visible'|'background'
export interface QueryCountBudget{maxLayers:number;maxQueued:number;maxRunning:number;maxRunningPerLayer:number;maxResident:number;queueTtlMs:number;leaseTtlMs:number;residentTtlMs:number}
export interface QueryCountRequest{key:string;layerId:string;revision:number;intent:QueryCountIntent;signature:string;queuedAt:number}
export interface QueryCountLease{readonly key:string;readonly layerId:string;readonly revision:number;readonly intent:QueryCountIntent;readonly signature:string;readonly startedAt:number;readonly expiresAt:number}
export interface QueryCountResult{readonly key:string;readonly layerId:string;readonly revision:number;readonly signature:string;readonly count:number;readonly capturedAt:number;readonly expiresAt:number}
interface Q extends QueryCountRequest{sequence:number;expiresAt:number}
interface R extends Q{startedAt:number;leaseExpiresAt:number}
interface C{key:string;layerId:string;revision:number;signature:string;count:number;capturedAt:number;expiresAt:number;sequence:number;touchedAt:number}
const rank:Readonly<Record<QueryCountIntent,number>>=Object.freeze({interactive:2,visible:1,background:0})
const intents:readonly QueryCountIntent[]=['interactive','visible','background']
function ident(n:string,v:string,m=512){if(typeof v!=='string'||/[\u0000-\u001f\u007f]/.test(v))throw new Error(`${n} is invalid`);const x=v.trim();if(!x||x.length>m)throw new Error(`${n} is invalid`);return x}
function nat(n:string,v:number){if(!Number.isSafeInteger(v)||v<0)throw new Error(`${n} must be a non-negative safe integer`)}
function pos(n:string,v:number){if(!Number.isSafeInteger(v)||v<1)throw new Error(`${n} must be positive`)}
function time(n:string,v:number){if(!Number.isFinite(v)||v<0)throw new Error(`${n} must be finite and non-negative`)}
export class ArcGisQueryCountLifecyclePolicy{
 readonly #b:Readonly<QueryCountBudget>;readonly #rev=new Map<string,number>();readonly #q=new Map<string,Q>();readonly #r=new Map<string,R>();readonly #c=new Map<string,C>();#seq=0;#dead=false
 constructor(b:QueryCountBudget){for(const k of ['maxLayers','maxQueued','maxRunning','maxRunningPerLayer','maxResident'] as const)pos(k,b[k]);for(const k of ['queueTtlMs','leaseTtlMs','residentTtlMs'] as const){time(k,b[k]);if(b[k]===0)throw new Error(`${k} must be positive`)}if(b.maxRunningPerLayer>b.maxRunning)throw new Error('maxRunningPerLayer cannot exceed maxRunning');this.#b=Object.freeze({...b})}
 setRevision(layerId:string,revision:number){this.#live();const layer=ident('layerId',layerId);nat('revision',revision);const old=this.#rev.get(layer);if(old!==undefined&&revision<old)return -1;if(old===revision)return 0;if(old===undefined&&this.#rev.size>=this.#b.maxLayers)throw new Error('maxLayers exceeded');this.#rev.set(layer,revision);let n=0;for(const map of [this.#q,this.#r,this.#c])for(const[k,e]of map)if(e.layerId===layer&&e.revision!==revision){map.delete(k);n++}return n}
 enqueue(request:QueryCountRequest){this.#live();const e=this.#normalize(request);if(this.#rev.get(e.layerId)!==e.revision)return false;const same=this.#find(e.key);if(same)return same.layerId===e.layerId&&same.revision===e.revision&&same.signature===e.signature;const logical=[...this.#q.values(),...this.#r.values()].some(x=>x.layerId===e.layerId&&x.revision===e.revision&&x.signature===e.signature);if(logical)return true;if(this.#q.size>=this.#b.maxQueued&&!this.#evict(e.intent))return false;this.#q.set(e.key,{...e,sequence:++this.#seq,expiresAt:e.queuedAt+this.#b.queueTtlMs});return true}
 startNext(now:number):QueryCountLease|null{this.#live();time('now',now);this.expire(now);if(this.#r.size>=this.#b.maxRunning)return null;const a=[...this.#q.values()].filter(e=>e.queuedAt<=now&&this.#running(e.layerId)<this.#b.maxRunningPerLayer).sort((x,y)=>rank[y.intent]-rank[x.intent]||x.sequence-y.sequence||x.key.localeCompare(y.key));const e=a[0];if(!e)return null;this.#q.delete(e.key);const r:R={...e,startedAt:now,leaseExpiresAt:now+this.#b.leaseTtlMs};this.#r.set(r.key,r);return Object.freeze({key:r.key,layerId:r.layerId,revision:r.revision,intent:r.intent,signature:r.signature,startedAt:r.startedAt,expiresAt:r.leaseExpiresAt})}
 renew(key:string,revision:number,now:number){this.#live();const k=ident('key',key);nat('revision',revision);time('now',now);const e=this.#r.get(k);if(!e||e.revision!==revision||this.#rev.get(e.layerId)!==revision||now<e.startedAt||now>=e.leaseExpiresAt)return false;e.leaseExpiresAt=now+this.#b.leaseTtlMs;return true}
 complete(key:string,revision:number,count:number,now:number):QueryCountResult|null{this.#live();const k=ident('key',key);nat('revision',revision);nat('count',count);time('now',now);const r=this.#r.get(k);if(!r||r.revision!==revision||this.#rev.get(r.layerId)!==revision||now<r.startedAt||now>=r.leaseExpiresAt)return null;this.#r.delete(k);const c:C={key:k,layerId:r.layerId,revision,signature:r.signature,count,capturedAt:now,expiresAt:now+this.#b.residentTtlMs,sequence:r.sequence,touchedAt:now};this.#c.set(k,c);this.#pressure(k);return this.#result(c)}
 get(key:string,revision:number,now:number){this.#live();const k=ident('key',key);nat('revision',revision);time('now',now);const c=this.#c.get(k);if(!c||c.revision!==revision||this.#rev.get(c.layerId)!==revision)return null;if(now<c.capturedAt)return null;if(now>=c.expiresAt){this.#c.delete(k);return null}c.touchedAt=now;return this.#result(c)}
 cancel(key:string){this.#live();const k=ident('key',key);return this.#q.delete(k)||this.#r.delete(k)}
 releaseLayer(layerId:string){this.#live();const layer=ident('layerId',layerId);let n=0;for(const map of [this.#q,this.#r,this.#c])for(const[k,e]of map)if(e.layerId===layer){map.delete(k);n++}this.#rev.delete(layer);return n}
 expire(now:number){this.#live();time('now',now);let n=0;for(const[k,e]of this.#q)if(now>=e.expiresAt){this.#q.delete(k);n++}for(const[k,e]of this.#r)if(now>=e.leaseExpiresAt){this.#r.delete(k);n++}for(const[k,e]of this.#c)if(now>=e.expiresAt){this.#c.delete(k);n++}return n}
 snapshot(){this.#live();return Object.freeze({layers:this.#rev.size,queued:this.#q.size,running:this.#r.size,resident:this.#c.size})}
 fingerprint(){this.#live();return [...this.#q.values()].map(e=>`q:${e.layerId}:${e.key}:${e.revision}:${e.signature}`).concat([...this.#r.values()].map(e=>`r:${e.layerId}:${e.key}:${e.revision}:${e.signature}`),[...this.#c.values()].map(e=>`c:${e.layerId}:${e.key}:${e.revision}:${e.signature}:${e.count}`)).sort().join('|')}
 dispose(){if(this.#dead)return;this.#q.clear();this.#r.clear();this.#c.clear();this.#rev.clear();this.#dead=true}
 #normalize(e:QueryCountRequest){const key=ident('key',e.key),layerId=ident('layerId',e.layerId),signature=ident('signature',e.signature);nat('revision',e.revision);time('queuedAt',e.queuedAt);if(!intents.includes(e.intent))throw new Error('intent is invalid');return{key,layerId,revision:e.revision,intent:e.intent,signature,queuedAt:e.queuedAt}}
 #find(k:string):Q|R|C|undefined{return this.#q.get(k)??this.#r.get(k)??this.#c.get(k)}
 #running(layer:string){let n=0;for(const e of this.#r.values())if(e.layerId===layer)n++;return n}
 #evict(intent:QueryCountIntent){const a=[...this.#q.values()].filter(e=>rank[e.intent]<=rank[intent]).sort((x,y)=>rank[x.intent]-rank[y.intent]||x.sequence-y.sequence||x.key.localeCompare(y.key));if(!a[0])return false;this.#q.delete(a[0].key);return true}
 #pressure(protectedKey:string){while(this.#c.size>this.#b.maxResident){const a=[...this.#c.values()].filter(e=>e.key!==protectedKey).sort((x,y)=>x.touchedAt-y.touchedAt||x.sequence-y.sequence||x.key.localeCompare(y.key));if(!a[0]){this.#c.delete(protectedKey);return}this.#c.delete(a[0].key)}}
 #result(c:C):QueryCountResult{return Object.freeze({key:c.key,layerId:c.layerId,revision:c.revision,signature:c.signature,count:c.count,capturedAt:c.capturedAt,expiresAt:c.expiresAt})}
 #live(){if(this.#dead)throw new Error('ArcGisQueryCountLifecyclePolicy is disposed')}
}
