import { describe, expect, it } from 'vitest'
import { ArcGisEditConflictLifecyclePolicy, type EditConflictBudget, type EditConflictRequest } from './ArcGisEditConflictLifecyclePolicy'
const budget: EditConflictBudget={maxLayers:3,maxConflicts:6,maxConflictsPerLayer:4,maxResolving:2,maxResolvingPerLayer:1,maxResident:3,maxResidentPerLayer:2,maxFieldsPerConflict:20,maxBytesPerConflict:2000,maxResidentFields:40,maxResidentBytes:4000,queueTtlMs:100,resolveLeaseMs:200,residentTtlMs:300}
const request=(o:Partial<EditConflictRequest>={}):EditConflictRequest=>({conflictId:'c1',layerId:'parcels',revision:1,intent:'interactive',strategy:'manual',fieldCount:4,estimatedBytes:400,requestedAt:10,...o})
const policy=()=>{const p=new ArcGisEditConflictLifecyclePolicy(budget);p.setRevision('parcels',1);return p}
describe('ArcGisEditConflictLifecyclePolicy',()=>{
 it('admits bounded payload-free metadata',()=>{const p=policy();expect(p.admit(request())).toBe(true);expect(p.snapshot()).toEqual({layers:1,conflicts:1,queued:1,resolving:0,resident:0,residentFields:0,residentBytes:0})})
 it('requires an authoritative revision',()=>{const p=new ArcGisEditConflictLifecyclePolicy(budget);expect(p.admit(request())).toBe(false)})
 it('rejects stale revisions',()=>{const p=policy();expect(p.admit(request({revision:0}))).toBe(false)})
 it('advancing revision invalidates stale work',()=>{const p=policy();p.admit(request());expect(p.setRevision('parcels',2)).toBe(1);expect(p.snapshot().conflicts).toBe(0)})
 it('does not roll revision backwards',()=>{const p=policy();expect(p.setRevision('parcels',0)).toBe(-1)})
 it('bounds tracked layers',()=>{const p=new ArcGisEditConflictLifecyclePolicy({...budget,maxLayers:1});expect(p.setRevision('a',1)).toBe(0);expect(p.setRevision('b',1)).toBe(-1)})
 it('rejects per-conflict field overflow',()=>{const p=policy();expect(p.admit(request({fieldCount:21}))).toBe(false)})
 it('rejects per-conflict byte overflow',()=>{const p=policy();expect(p.admit(request({estimatedBytes:2001}))).toBe(false)})
 it('dedupes conflict ids',()=>{const p=policy();expect(p.admit(request())).toBe(true);expect(p.admit(request())).toBe(false)})
 it('bounds global cardinality',()=>{const p=new ArcGisEditConflictLifecyclePolicy({...budget,maxConflicts:2,maxConflictsPerLayer:2});p.setRevision('parcels',1);expect(p.admit(request({conflictId:'a'}))).toBe(true);expect(p.admit(request({conflictId:'b'}))).toBe(true);expect(p.admit(request({conflictId:'c'}))).toBe(false)})
 it('bounds per-layer cardinality',()=>{const p=new ArcGisEditConflictLifecyclePolicy({...budget,maxConflictsPerLayer:1});p.setRevision('parcels',1);expect(p.admit(request({conflictId:'a'}))).toBe(true);expect(p.admit(request({conflictId:'b'}))).toBe(false)})
 it('schedules interactive before visible before background',()=>{const p=policy();p.admit(request({conflictId:'b',intent:'background'}));p.admit(request({conflictId:'v',intent:'visible'}));p.admit(request({conflictId:'i',intent:'interactive'}));expect(p.startNext(20)?.conflictId).toBe('i')})
 it('preserves fifo within priority',()=>{const p=policy();p.admit(request({conflictId:'a'}));p.admit(request({conflictId:'b'}));expect(p.startNext(20)?.conflictId).toBe('a')})
 it('bounds resolving globally',()=>{const p=new ArcGisEditConflictLifecyclePolicy({...budget,maxResolving:1,maxResolvingPerLayer:1});p.setRevision('parcels',1);p.admit(request({conflictId:'a'}));p.admit(request({conflictId:'b'}));expect(p.startNext(20)?.conflictId).toBe('a');expect(p.startNext(21)).toBeNull()})
 it('bounds resolving per layer while allowing another layer',()=>{const p=new ArcGisEditConflictLifecyclePolicy(budget);p.setRevision('parcels',1);p.setRevision('roads',1);p.admit(request({conflictId:'a'}));p.admit(request({conflictId:'b'}));p.admit(request({conflictId:'r',layerId:'roads'}));expect(p.startNext(20)?.conflictId).toBe('a');expect(p.startNext(20)?.conflictId).toBe('r')})
 it('reconciles actual completion accounting',()=>{const p=policy();p.admit(request());p.startNext(20);expect(p.complete('c1',1,8,900,30)).toBe(true);expect(p.snapshot().residentFields).toBe(8);expect(p.snapshot().residentBytes).toBe(900)})
 it('rejects stale completion after revision advance',()=>{const p=policy();p.admit(request());p.startNext(20);p.setRevision('parcels',2);expect(p.complete('c1',1,4,400,30)).toBe(false)})
 it('rejects oversized actual result and drops work',()=>{const p=policy();p.admit(request());p.startNext(20);expect(p.complete('c1',1,21,400,30)).toBe(false);expect(p.snapshot().conflicts).toBe(0)})
 it('evicts background residency for interactive pressure',()=>{const p=new ArcGisEditConflictLifecyclePolicy({...budget,maxResident:1,maxResidentPerLayer:1});p.setRevision('parcels',1);p.admit(request({conflictId:'old',intent:'background'}));p.startNext(20);p.complete('old',1,4,400,30);p.admit(request({conflictId:'new',intent:'interactive'}));p.startNext(40);expect(p.complete('new',1,4,400,50)).toBe(true);expect(p.fingerprint()).toContain('new')})
 it('evicts least recently touched residency under equal intent',()=>{const p=new ArcGisEditConflictLifecyclePolicy({...budget,maxResident:2,maxResidentPerLayer:2,maxResidentFields:8});p.setRevision('parcels',1);for(const c of ['a','b']){p.admit(request({conflictId:c}));p.startNext(20);p.complete(c,1,4,400,30)}p.touch('b',40);p.admit(request({conflictId:'c'}));p.startNext(50);expect(p.complete('c',1,4,400,60)).toBe(true);expect(p.fingerprint()).not.toContain(':a:')})
 it('expires queued work at ttl boundary',()=>{const p=policy();p.admit(request());expect(p.expire(110)).toBe(1)})
 it('expires resolving lease',()=>{const p=policy();p.admit(request());p.startNext(20);expect(p.expire(220)).toBe(1)})
 it('expires resident result',()=>{const p=policy();p.admit(request());p.startNext(20);p.complete('c1',1,4,400,30);expect(p.expire(330)).toBe(1)})
 it('touch extends resident ttl',()=>{const p=policy();p.admit(request());p.startNext(20);p.complete('c1',1,4,400,30);expect(p.touch('c1',300)).toBe(true);expect(p.expire(330)).toBe(0)})
 it('consumes resident exactly once',()=>{const p=policy();p.admit(request());p.startNext(20);p.complete('c1',1,4,400,30);expect(p.consume('c1',1)?.phase).toBe('resident');expect(p.consume('c1',1)).toBeNull()})
 it('cancel removes queued work',()=>{const p=policy();p.admit(request());expect(p.cancel('c1')).toBe(true);expect(p.snapshot().conflicts).toBe(0)})
 it('releaseLayer removes metadata and watermark',()=>{const p=policy();p.admit(request());expect(p.releaseLayer('parcels')).toBe(1);expect(p.snapshot().layers).toBe(0)})
 it('fingerprint is deterministic across insertion order',()=>{const a=policy(),b=policy();a.admit(request({conflictId:'b'}));a.admit(request({conflictId:'a'}));b.admit(request({conflictId:'a'}));b.admit(request({conflictId:'b'}));expect(a.fingerprint()).toBe(b.fingerprint())})
 it('normalizes identifiers',()=>{const p=policy();expect(p.admit(request({conflictId:' c1 ',layerId:' parcels '}))).toBe(true);expect(p.fingerprint()).toContain('parcels:c1')})
 it('rejects control characters',()=>{const p=policy();expect(()=>p.admit(request({conflictId:'bad\u0001id'}))).toThrow(/conflictId/)})
 it('rejects unsafe numeric metadata',()=>{const p=policy();expect(()=>p.admit(request({fieldCount:-1}))).toThrow(/fieldCount/);expect(()=>p.admit(request({requestedAt:Number.NaN}))).toThrow(/requestedAt/)})
 it('rejects inconsistent budgets',()=>{expect(()=>new ArcGisEditConflictLifecyclePolicy({...budget,maxConflictsPerLayer:7})).toThrow(/maxConflictsPerLayer/);expect(()=>new ArcGisEditConflictLifecyclePolicy({...budget,maxFieldsPerConflict:41})).toThrow(/field budgets/)})
 it('fails closed after disposal',()=>{const p=policy();p.dispose();expect(()=>p.snapshot()).toThrow(/disposed/)})
 it('keeps scalar detached snapshots',()=>{const p=policy();p.admit(request());const v=p.startNext(20)!;expect(Object.isFrozen(v)).toBe(true);expect(Object.keys(v).sort()).toEqual(['bytes','conflictId','expiresAt','fieldCount','intent','layerId','phase','revision','sequence','strategy','touchedAt'].sort())})
})
