export type QueryCacheIntent = 'interactive' | 'visible' | 'background'
export interface QueryResponseCacheBudget { maxLayers:number; maxEntries:number; maxEntriesPerLayer:number; maxFeaturesPerEntry:number; maxBytesPerEntry:number; maxResidentFeatures:number; maxResidentBytes:number; ttlMs:number }
export interface QueryResponseCacheRequest { cacheKey:string; layerId:string; revision:number; intent:QueryCacheIntent; featureCount:number; byteCount:number; storedAt:number; signature:string }
export interface QueryResponseCacheView extends QueryResponseCacheRequest { readonly sequence:number; readonly touchedAt:number; readonly expiresAt:number }
export interface QueryResponseCacheSnapshot { readonly layers:number; readonly entries:number; readonly residentFeatures:number; readonly residentBytes:number }
interface CacheEntry extends QueryResponseCacheRequest { sequence:number; touchedAt:number; expiresAt:number }
const intentRank:Readonly<Record<QueryCacheIntent,number>>=Object.freeze({interactive:2,visible:1,background:0}); const intents:readonly QueryCacheIntent[]=['interactive','visible','background']
function identifier(name:string,value:string,max=256):string{const normalized=value.trim();if(!normalized||normalized.length>max||/[\u0000-\u001f\u007f]/.test(normalized))throw new Error(`${name} is invalid`);return normalized}
function positiveInteger(name:string,value:number):void{if(!Number.isSafeInteger(value)||value<1)throw new Error(`${name} must be a positive safe integer`)}
function nonNegativeInteger(name:string,value:number):void{if(!Number.isSafeInteger(value)||value<0)throw new Error(`${name} must be a non-negative safe integer`)}
function clock(name:string,value:number):void{if(!Number.isFinite(value)||value<0)throw new Error(`${name} must be finite and non-negative`)}
/** Payload-free bounded authority for ArcGIS REST query-response cache residency. Caller retains payload ownership. */
export class ArcGisQueryResponseCacheLifecyclePolicy {
 readonly #budget:Readonly<QueryResponseCacheBudget>; readonly #entries=new Map<string,CacheEntry>(); readonly #revisions=new Map<string,number>(); #sequence=0; #disposed=false
 constructor(budget:QueryResponseCacheBudget){for(const key of ['maxLayers','maxEntries','maxEntriesPerLayer','maxFeaturesPerEntry','maxBytesPerEntry','maxResidentFeatures','maxResidentBytes'] as const)positiveInteger(key,budget[key]);clock('ttlMs',budget.ttlMs);if(budget.ttlMs===0)throw new Error('ttlMs must be positive');if(budget.maxEntriesPerLayer>budget.maxEntries)throw new Error('maxEntriesPerLayer cannot exceed maxEntries');if(budget.maxResidentFeatures<budget.maxFeaturesPerEntry)throw new Error('maxResidentFeatures cannot be smaller than maxFeaturesPerEntry');if(budget.maxResidentBytes<budget.maxBytesPerEntry)throw new Error('maxResidentBytes cannot be smaller than maxBytesPerEntry');this.#budget=Object.freeze({...budget})}
 setRevision(layerId:string,revision:number):number{this.#assertLive();const layer=identifier('layerId',layerId);nonNegativeInteger('revision',revision);const current=this.#revisions.get(layer);if(current!==undefined&&revision<current)return -1;if(current===revision)return 0;if(current===undefined&&this.#revisions.size>=this.#budget.maxLayers)throw new Error('maxLayers exceeded');this.#revisions.set(layer,revision);let removed=0;for(const[key,entry]of this.#entries)if(entry.layerId===layer&&entry.revision!==revision){this.#entries.delete(key);removed++}return removed}
 admit(request:QueryResponseCacheRequest):QueryResponseCacheView|null{this.#assertLive();const normalized=this.#normalize(request);if(this.#revisions.get(normalized.layerId)!==normalized.revision)return null;if(normalized.featureCount>this.#budget.maxFeaturesPerEntry||normalized.byteCount>this.#budget.maxBytesPerEntry)return null;const existing=this.#entries.get(normalized.cacheKey);if(existing){if(existing.layerId!==normalized.layerId||existing.revision!==normalized.revision||existing.signature!==normalized.signature)return null;existing.touchedAt=normalized.storedAt;existing.expiresAt=normalized.storedAt+this.#budget.ttlMs;return this.#view(existing)}const same=[...this.#entries.values()].find(e=>e.layerId===normalized.layerId&&e.revision===normalized.revision&&e.signature===normalized.signature);if(same){same.touchedAt=normalized.storedAt;same.expiresAt=normalized.storedAt+this.#budget.ttlMs;return this.#view(same)}if(this.#layerCount(normalized.layerId)>=this.#budget.maxEntriesPerLayer&&!this.#evictOne(normalized.intent,normalized.layerId))return null;if(this.#entries.size>=this.#budget.maxEntries&&!this.#evictOne(normalized.intent))return null;const entry:CacheEntry={...normalized,sequence:++this.#sequence,touchedAt:normalized.storedAt,expiresAt:normalized.storedAt+this.#budget.ttlMs};this.#entries.set(entry.cacheKey,entry);if(!this.#relievePressure(entry)){this.#entries.delete(entry.cacheKey);return null}return this.#view(entry)}
 get(cacheKey:string,revision:number,now:number):QueryResponseCacheView|null{this.#assertLive();const key=identifier('cacheKey',cacheKey);nonNegativeInteger('revision',revision);clock('now',now);const entry=this.#entries.get(key);if(!entry||entry.revision!==revision||this.#revisions.get(entry.layerId)!==revision)return null;if(now>=entry.expiresAt){this.#entries.delete(key);return null}return this.#view(entry)}
 touch(cacheKey:string,revision:number,now:number):boolean{this.#assertLive();const key=identifier('cacheKey',cacheKey);nonNegativeInteger('revision',revision);clock('now',now);const entry=this.#entries.get(key);if(!entry||entry.revision!==revision||this.#revisions.get(entry.layerId)!==revision||now>=entry.expiresAt)return false;entry.touchedAt=now;entry.expiresAt=now+this.#budget.ttlMs;return true}
 invalidate(cacheKey:string):boolean{this.#assertLive();return this.#entries.delete(identifier('cacheKey',cacheKey))}
 releaseLayer(layerId:string):number{this.#assertLive();const layer=identifier('layerId',layerId);let removed=0;for(const[key,entry]of this.#entries)if(entry.layerId===layer){this.#entries.delete(key);removed++}this.#revisions.delete(layer);return removed}
 expire(now:number):number{this.#assertLive();clock('now',now);let removed=0;for(const[key,entry]of this.#entries)if(now>=entry.expiresAt){this.#entries.delete(key);removed++}return removed}
 snapshot():QueryResponseCacheSnapshot{this.#assertLive();const t=this.#totals();return Object.freeze({layers:this.#revisions.size,entries:this.#entries.size,residentFeatures:t.features,residentBytes:t.bytes})}
 fingerprint():string{this.#assertLive();return[...this.#entries.values()].sort((a,b)=>a.layerId.localeCompare(b.layerId)||a.cacheKey.localeCompare(b.cacheKey)).map(e=>`${e.layerId}:${e.cacheKey}:${e.revision}:${e.intent}:${e.featureCount}:${e.byteCount}:${e.signature}`).join('|')}
 dispose():void{if(this.#disposed)return;this.#entries.clear();this.#revisions.clear();this.#disposed=true}
 #normalize(request:QueryResponseCacheRequest):QueryResponseCacheRequest{const cacheKey=identifier('cacheKey',request.cacheKey),layerId=identifier('layerId',request.layerId),signature=identifier('signature',request.signature,512);nonNegativeInteger('revision',request.revision);nonNegativeInteger('featureCount',request.featureCount);nonNegativeInteger('byteCount',request.byteCount);clock('storedAt',request.storedAt);if(!intents.includes(request.intent))throw new Error('intent is invalid');return{...request,cacheKey,layerId,signature}}
 #layerCount(layerId:string):number{let count=0;for(const e of this.#entries.values())if(e.layerId===layerId)count++;return count}
 #totals():{features:number;bytes:number}{let features=0,bytes=0;for(const e of this.#entries.values()){features+=e.featureCount;bytes+=e.byteCount}return{features,bytes}}
 #relievePressure(protectedEntry:CacheEntry):boolean{for(;;){const t=this.#totals();if(t.features<=this.#budget.maxResidentFeatures&&t.bytes<=this.#budget.maxResidentBytes)return true;const c=this.#evictionCandidate(protectedEntry.intent,undefined,protectedEntry.cacheKey);if(!c)return false;this.#entries.delete(c.cacheKey)}}
 #evictOne(incomingIntent:QueryCacheIntent,layerId?:string):boolean{const c=this.#evictionCandidate(incomingIntent,layerId);if(!c)return false;this.#entries.delete(c.cacheKey);return true}
 #evictionCandidate(incomingIntent:QueryCacheIntent,layerId?:string,protectedKey?:string):CacheEntry|null{const candidates=[...this.#entries.values()].filter(e=>e.cacheKey!==protectedKey&&(layerId===undefined||e.layerId===layerId)&&intentRank[e.intent]<=intentRank[incomingIntent]);candidates.sort((a,b)=>intentRank[a.intent]-intentRank[b.intent]||a.touchedAt-b.touchedAt||a.sequence-b.sequence||a.cacheKey.localeCompare(b.cacheKey));return candidates[0]??null}
 #view(e:CacheEntry):QueryResponseCacheView{return Object.freeze({cacheKey:e.cacheKey,layerId:e.layerId,revision:e.revision,intent:e.intent,featureCount:e.featureCount,byteCount:e.byteCount,storedAt:e.storedAt,signature:e.signature,sequence:e.sequence,touchedAt:e.touchedAt,expiresAt:e.expiresAt})}
 #assertLive():void{if(this.#disposed)throw new Error('ArcGisQueryResponseCacheLifecyclePolicy is disposed')}
}
