export interface ArcGisQueryKey{readonly serviceId:string;readonly layerId:number;readonly where:string;readonly geometryFingerprint?:string;readonly outFields:readonly string[];readonly returnGeometry:boolean;readonly resultOffset?:number;readonly resultRecordCount?:number}
export interface ArcGisQueryBudget{readonly maxEntries:number;readonly maxInflight:number;readonly maxWaitersPerQuery:number;readonly maxCacheAgeMs:number;readonly maxCachedBytes:number;readonly maxResponseBytes:number;readonly maxWhereLength:number;readonly maxOutFields:number}
export interface ArcGisQueryResponse<T>{readonly value:T;readonly estimatedBytes:number;readonly datasetRevision?:string}
export interface ArcGisQueryContext{readonly signal:AbortSignal;readonly key:ArcGisQueryKey}
export type ArcGisQueryExecutor<T>=(context:ArcGisQueryContext)=>Promise<ArcGisQueryResponse<T>>
interface CacheEntry<T>{readonly response:ArcGisQueryResponse<T>;readonly storedAt:number;lastAccess:number}
interface Flight<T>{readonly controller:AbortController;promise:Promise<ArcGisQueryResponse<T>>;waiters:number;settled:boolean}
export interface ArcGisQueryDiagnostics{readonly cacheEntries:number;readonly cachedBytes:number;readonly inflight:number;readonly cacheHits:number;readonly cacheMisses:number;readonly dedupedWaiters:number;readonly evictions:number}
const MAX_SAFE_BYTES=256*1024*1024,MAX_SAFE_ENTRIES=10_000
function integer(v:number,n:string,min:number,max:number){if(!Number.isSafeInteger(v)||v<min||v>max)throw new Error(`${n} must be an integer in [${min}, ${max}]`);return v}
function text(v:string,n:string,max:number){const x=v.trim().replace(/\s+/g,' ');if(!x||x.length>max||/[\u0000-\u001f\u007f]/.test(x))throw new Error(`invalid ${n}`);return x}
function normalize(k:ArcGisQueryKey,b:ArcGisQueryBudget):ArcGisQueryKey{const serviceId=text(k.serviceId,'serviceId',256),where=text(k.where,'where',b.maxWhereLength);integer(k.layerId,'layerId',0,100000);if(k.outFields.length>b.maxOutFields)throw new Error('outFields budget exceeded');const outFields=[...new Set(k.outFields.map(x=>text(x,'outField',128)))].sort();const geometryFingerprint=k.geometryFingerprint===undefined?undefined:text(k.geometryFingerprint,'geometryFingerprint',512);const resultOffset=k.resultOffset===undefined?undefined:integer(k.resultOffset,'resultOffset',0,Number.MAX_SAFE_INTEGER);const resultRecordCount=k.resultRecordCount===undefined?undefined:integer(k.resultRecordCount,'resultRecordCount',1,100000);return Object.freeze({serviceId,layerId:k.layerId,where,geometryFingerprint,outFields:Object.freeze(outFields),returnGeometry:k.returnGeometry,resultOffset,resultRecordCount})}
const fingerprint=(k:ArcGisQueryKey)=>JSON.stringify([k.serviceId,k.layerId,k.where,k.geometryFingerprint??'',k.outFields,k.returnGeometry,k.resultOffset??0,k.resultRecordCount??0])
function aborted(){const e=new Error('ArcGIS query aborted');e.name='AbortError';return e}
export class ArcGisQueryCoordinator<T>{private readonly budget:ArcGisQueryBudget;private readonly executor:ArcGisQueryExecutor<T>;private readonly now:()=>number;private readonly cache=new Map<string,CacheEntry<T>>();private readonly flights=new Map<string,Flight<T>>();private cachedBytes=0;private hits=0;private misses=0;private deduped=0;private evictions=0
constructor(executor:ArcGisQueryExecutor<T>,budget:ArcGisQueryBudget,now:()=>number=Date.now){this.executor=executor;this.now=now;this.budget=Object.freeze({maxEntries:integer(budget.maxEntries,'maxEntries',1,MAX_SAFE_ENTRIES),maxInflight:integer(budget.maxInflight,'maxInflight',1,1000),maxWaitersPerQuery:integer(budget.maxWaitersPerQuery,'maxWaitersPerQuery',1,10000),maxCacheAgeMs:integer(budget.maxCacheAgeMs,'maxCacheAgeMs',0,86400000),maxCachedBytes:integer(budget.maxCachedBytes,'maxCachedBytes',1,MAX_SAFE_BYTES),maxResponseBytes:integer(budget.maxResponseBytes,'maxResponseBytes',1,MAX_SAFE_BYTES),maxWhereLength:integer(budget.maxWhereLength,'maxWhereLength',1,32768),maxOutFields:integer(budget.maxOutFields,'maxOutFields',1,1000)})}
diagnostics():ArcGisQueryDiagnostics{return Object.freeze({cacheEntries:this.cache.size,cachedBytes:this.cachedBytes,inflight:this.flights.size,cacheHits:this.hits,cacheMisses:this.misses,dedupedWaiters:this.deduped,evictions:this.evictions})}
invalidateAll(){this.cache.clear();this.cachedBytes=0}
invalidateService(serviceId:string){const normalized=text(serviceId,'serviceId',256);let removed=0;for(const[key,entry]of this.cache){if((JSON.parse(key)as unknown[])[0]!==normalized)continue;this.cache.delete(key);this.cachedBytes-=entry.response.estimatedBytes;removed++}return removed}
async query(key:ArcGisQueryKey,signal?:AbortSignal){if(signal?.aborted)throw aborted();const normalized=normalize(key,this.budget),id=fingerprint(normalized),cached=this.readCache(id);if(cached){this.hits++;return cached}this.misses++;let flight=this.flights.get(id);if(flight){if(flight.waiters>=this.budget.maxWaitersPerQuery)throw new Error('ArcGIS query waiter budget exceeded');flight.waiters++;this.deduped++}else{if(this.flights.size>=this.budget.maxInflight)throw new Error('ArcGIS query inflight budget exceeded');flight=this.start(id,normalized);this.flights.set(id,flight)}return this.wait(id,flight,signal)}
private start(id:string,key:ArcGisQueryKey){const controller=new AbortController();const flight:Flight<T>={controller,waiters:1,settled:false,promise:Promise.resolve(undefined as never)};flight.promise=this.executor({signal:controller.signal,key}).then(r=>{integer(r.estimatedBytes,'estimatedBytes',0,this.budget.maxResponseBytes);this.store(id,r);return r}).finally(()=>{flight.settled=true;if(flight.waiters===0)this.flights.delete(id)});return flight}
private wait(id:string,flight:Flight<T>,signal?:AbortSignal){return new Promise<ArcGisQueryResponse<T>>((resolve,reject)=>{let done=false;const release=()=>{if(done)return;done=true;signal?.removeEventListener('abort',onAbort);flight.waiters--;if(flight.waiters===0){if(!flight.settled)flight.controller.abort();else this.flights.delete(id)}};const onAbort=()=>{release();reject(aborted())};signal?.addEventListener('abort',onAbort,{once:true});flight.promise.then(v=>{if(!done){release();resolve(v)}},e=>{if(!done){release();reject(e)}})})}
private readCache(id:string){const e=this.cache.get(id);if(!e)return;const now=this.now();if(now<e.storedAt||now-e.storedAt>this.budget.maxCacheAgeMs){this.cache.delete(id);this.cachedBytes-=e.response.estimatedBytes;return}e.lastAccess=now;return e.response}
private store(id:string,response:ArcGisQueryResponse<T>){if(response.estimatedBytes>this.budget.maxCachedBytes)return;const previous=this.cache.get(id);if(previous)this.cachedBytes-=previous.response.estimatedBytes;const now=this.now();this.cache.set(id,{response,storedAt:now,lastAccess:now});this.cachedBytes+=response.estimatedBytes;while(this.cache.size>this.budget.maxEntries||this.cachedBytes>this.budget.maxCachedBytes)this.evict()}
private evict(){let oldest:string|undefined,at=Infinity;for(const[key,e]of this.cache)if(e.lastAccess<at){oldest=key;at=e.lastAccess}if(!oldest)return;const e=this.cache.get(oldest);if(!e)return;this.cache.delete(oldest);this.cachedBytes-=e.response.estimatedBytes;this.evictions++}}
