export type QueryPageIntent='interactive'|'visible'|'background'
export type QueryPagePhase='queued'|'loading'|'resident'
export interface QueryPageBudget{maxLayers:number;maxPages:number;maxPagesPerLayer:number;maxLoading:number;maxLoadingPerLayer:number;maxResident:number;maxResidentPerLayer:number;maxFeaturesPerPage:number;maxBytesPerPage:number;maxResidentFeatures:number;maxResidentBytes:number;queueTtlMs:number;loadLeaseMs:number;residentTtlMs:number}
export interface QueryPageRequest{pageId:string;queryKey:string;layerId:string;revision:number;page:number;intent:QueryPageIntent;estimatedFeatures:number;estimatedBytes:number;requestedAt:number}
export interface QueryPageView extends QueryPageRequest{readonly phase:QueryPagePhase;readonly sequence:number;readonly touchedAt:number;readonly expiresAt:number;readonly features:number;readonly bytes:number;readonly hasMore:boolean}
interface Entry extends QueryPageRequest{phase:QueryPagePhase;sequence:number;touchedAt:number;expiresAt:number;features:number;bytes:number;hasMore:boolean}
const intents:readonly QueryPageIntent[]=['interactive','visible','background'];const rank:Readonly<Record<QueryPageIntent,number>>=Object.freeze({interactive:2,visible:1,background:0})
function id(n:string,v:string):string{const x=v.trim();if(!x||x.length>192||/[\u0000-\u001f]/.test(x))throw new Error(`${n} is invalid`);return x}function integer(n:string,v:number,min=0):void{if(!Number.isSafeInteger(v)||v<min)throw new Error(`${n} must be a safe integer >= ${min}`)}function clock(n:string,v:number):void{if(!Number.isFinite(v)||v<0)throw new Error(`${n} must be finite and non-negative`)}
/** Bounded payload-free authority for ArcGIS offset/page query lifecycle and residency. */
export class ArcGisQueryPageLifecyclePolicy{
 readonly #budget:Readonly<QueryPageBudget>;readonly #entries=new Map<string,Entry>();readonly #revisions=new Map<string,number>();readonly #pageKeys=new Map<string,string>();#sequence=0;#disposed=false
 constructor(b:QueryPageBudget){for(const k of ['maxLayers','maxPages','maxPagesPerLayer','maxLoading','maxLoadingPerLayer','maxResident','maxResidentPerLayer','maxFeaturesPerPage','maxBytesPerPage','maxResidentFeatures','maxResidentBytes'] as const)integer(k,b[k],1);clock('queueTtlMs',b.queueTtlMs);clock('loadLeaseMs',b.loadLeaseMs);clock('residentTtlMs',b.residentTtlMs);if(b.maxPagesPerLayer>b.maxPages)throw new Error('maxPagesPerLayer exceeds maxPages');if(b.maxLoading>b.maxPages||b.maxResident>b.maxPages)throw new Error('phase budget exceeds maxPages');if(b.maxLoadingPerLayer>b.maxLoading||b.maxLoadingPerLayer>b.maxPagesPerLayer)throw new Error('maxLoadingPerLayer exceeds parent budget');if(b.maxResidentPerLayer>b.maxResident||b.maxResidentPerLayer>b.maxPagesPerLayer)throw new Error('maxResidentPerLayer exceeds parent budget');if(b.maxResidentFeatures<b.maxFeaturesPerPage||b.maxResidentBytes<b.maxBytesPerPage)throw new Error('aggregate residency must fit one page');this.#budget=Object.freeze({...b})}
 setRevision(layerId:string,next:number):number{this.#live();const layer=id('layerId',layerId);integer('revision',next);const current=this.#revisions.get(layer);if(current!==undefined&&next<current)return-1;if(current===undefined&&this.#revisions.size>=this.#budget.maxLayers)return-1;this.#revisions.set(layer,next);if(current===undefined||current===next)return 0;let n=0;for(const[key,e]of this.#entries)if(e.layerId===layer&&e.revision!==next){this.#remove(key);n++}return n}
 admit(r:QueryPageRequest):boolean{this.#live();const pageId=id('pageId',r.pageId),queryKey=id('queryKey',r.queryKey),layerId=id('layerId',r.layerId);integer('revision',r.revision);integer('page',r.page);integer('estimatedFeatures',r.estimatedFeatures,1);integer('estimatedBytes',r.estimatedBytes,1);clock('requestedAt',r.requestedAt);if(!intents.includes(r.intent))throw new Error('intent is invalid');if(this.#revisions.get(layerId)!==r.revision||r.estimatedFeatures>this.#budget.maxFeaturesPerPage||r.estimatedBytes>this.#budget.maxBytesPerPage)return false;if(this.#entries.has(pageId)||this.#pageKeys.has(this.#key(layerId,r.revision,queryKey,r.page)))return false;if(this.#entries.size>=this.#budget.maxPages||this.#layerCount(layerId)>=this.#budget.maxPagesPerLayer)return false;const sequence=++this.#sequence;const e:Entry={...r,pageId,queryKey,layerId,phase:'queued',sequence,touchedAt:r.requestedAt,expiresAt:r.requestedAt+this.#budget.queueTtlMs,features:r.estimatedFeatures,bytes:r.estimatedBytes,hasMore:false};this.#entries.set(pageId,e);this.#pageKeys.set(this.#key(layerId,r.revision,queryKey,r.page),pageId);return true}
 startNext(now:number):QueryPageView|null{this.#live();clock('now',now);this.expire(now);if(this.#phaseCount('loading')>=this.#budget.maxLoading)return null;let c:Entry|undefined;for(const e of this.#entries.values()){if(e.phase!=='queued'||this.#layerPhaseCount(e.layerId,'loading')>=this.#budget.maxLoadingPerLayer)continue;if(!c||rank[e.intent]>rank[c.intent]||(rank[e.intent]===rank[c.intent]&&(e.page<c.page||(e.page===c.page&&(e.requestedAt<c.requestedAt||(e.requestedAt===c.requestedAt&&e.sequence<c.sequence))))))c=e}if(!c)return null;c.phase='loading';c.touchedAt=now;c.expiresAt=now+this.#budget.loadLeaseMs;return this.#view(c)}
 renew(pageId:string,revision:number,now:number):boolean{this.#live();const e=this.#entries.get(id('pageId',pageId));integer('revision',revision);clock('now',now);this.expire(now);if(!e||e.phase!=='loading'||e.revision!==revision||this.#revisions.get(e.layerId)!==revision)return false;e.touchedAt=now;e.expiresAt=now+this.#budget.loadLeaseMs;return true}
 complete(pageId:string,revision:number,features:number,bytes:number,hasMore:boolean,now:number):QueryPageView|null{this.#live();const key=id('pageId',pageId);integer('revision',revision);integer('features',features);integer('bytes',bytes);clock('now',now);const e=this.#entries.get(key);this.expire(now);if(!e||e.phase!=='loading'||e.revision!==revision||this.#revisions.get(e.layerId)!==revision)return null;if(features>this.#budget.maxFeaturesPerPage||bytes>this.#budget.maxBytesPerPage){this.#remove(key);return null}e.features=features;e.bytes=bytes;e.hasMore=Boolean(hasMore);while(this.#phaseCount('resident')>=this.#budget.maxResident||this.#layerPhaseCount(e.layerId,'resident')>=this.#budget.maxResidentPerLayer||this.#residentFeatures()+features>this.#budget.maxResidentFeatures||this.#residentBytes()+bytes>this.#budget.maxResidentBytes){const v=this.#victim(e.layerId);if(!v){this.#remove(key);return null}this.#remove(v.pageId)}e.phase='resident';e.touchedAt=now;e.expiresAt=now+this.#budget.residentTtlMs;return this.#view(e)}
 nextRequest(pageId:string,nextPageId:string,now:number):QueryPageRequest|null{this.#live();const e=this.#entries.get(id('pageId',pageId));const next=id('nextPageId',nextPageId);clock('now',now);this.expire(now);if(!e||e.phase!=='resident'||!e.hasMore||this.#revisions.get(e.layerId)!==e.revision)return null;return Object.freeze({pageId:next,queryKey:e.queryKey,layerId:e.layerId,revision:e.revision,page:e.page+1,intent:e.intent,estimatedFeatures:e.estimatedFeatures,estimatedBytes:e.estimatedBytes,requestedAt:now})}
 consume(pageId:string,revision:number):QueryPageView|null{this.#live();const key=id('pageId',pageId);integer('revision',revision);const e=this.#entries.get(key);if(!e||e.phase!=='resident'||e.revision!==revision||this.#revisions.get(e.layerId)!==revision)return null;const v=this.#view(e);this.#remove(key);return v}
 cancel(pageId:string):boolean{this.#live();const key=id('pageId',pageId);if(!this.#entries.has(key))return false;this.#remove(key);return true}releaseLayer(layerId:string):number{this.#live();const layer=id('layerId',layerId);let n=0;for(const[k,e]of this.#entries)if(e.layerId===layer){this.#remove(k);n++}this.#revisions.delete(layer);return n}expire(now:number):number{this.#live();clock('now',now);let n=0;for(const[k,e]of this.#entries)if(e.expiresAt<=now){this.#remove(k);n++}return n}
 snapshot():Readonly<{layers:number;pages:number;queued:number;loading:number;resident:number;residentFeatures:number;residentBytes:number}>{this.#live();return Object.freeze({layers:this.#revisions.size,pages:this.#entries.size,queued:this.#phaseCount('queued'),loading:this.#phaseCount('loading'),resident:this.#phaseCount('resident'),residentFeatures:this.#residentFeatures(),residentBytes:this.#residentBytes()})}fingerprint():string{this.#live();return[...this.#entries.values()].sort((a,b)=>a.layerId.localeCompare(b.layerId)||a.queryKey.localeCompare(b.queryKey)||a.page-b.page).map(e=>`${e.layerId}:${e.queryKey}:${e.revision}:${e.page}:${e.phase}:${e.features}:${e.bytes}:${e.hasMore?1:0}`).join('|')}dispose():void{if(this.#disposed)return;this.#entries.clear();this.#pageKeys.clear();this.#revisions.clear();this.#disposed=true}
 #remove(pageId:string):void{const e=this.#entries.get(pageId);if(!e)return;this.#entries.delete(pageId);this.#pageKeys.delete(this.#key(e.layerId,e.revision,e.queryKey,e.page))}#key(layer:string,revision:number,query:string,page:number):string{return`${layer}\u0000${revision}\u0000${query}\u0000${page}`}#victim(preferred:string):Entry|undefined{const a=[...this.#entries.values()].filter(e=>e.phase==='resident');a.sort((x,y)=>(x.layerId===preferred?0:1)-(y.layerId===preferred?0:1)||rank[x.intent]-rank[y.intent]||x.touchedAt-y.touchedAt||x.sequence-y.sequence);return a[0]}#layerCount(layer:string):number{let n=0;for(const e of this.#entries.values())if(e.layerId===layer)n++;return n}#phaseCount(p:QueryPagePhase):number{let n=0;for(const e of this.#entries.values())if(e.phase===p)n++;return n}#layerPhaseCount(layer:string,p:QueryPagePhase):number{let n=0;for(const e of this.#entries.values())if(e.layerId===layer&&e.phase===p)n++;return n}#residentFeatures():number{let n=0;for(const e of this.#entries.values())if(e.phase==='resident')n+=e.features;return n}#residentBytes():number{let n=0;for(const e of this.#entries.values())if(e.phase==='resident')n+=e.bytes;return n}#view(e:Entry):QueryPageView{return Object.freeze({pageId:e.pageId,queryKey:e.queryKey,layerId:e.layerId,revision:e.revision,page:e.page,intent:e.intent,estimatedFeatures:e.estimatedFeatures,estimatedBytes:e.estimatedBytes,requestedAt:e.requestedAt,phase:e.phase,sequence:e.sequence,touchedAt:e.touchedAt,expiresAt:e.expiresAt,features:e.features,bytes:e.bytes,hasMore:e.hasMore})}#live():void{if(this.#disposed)throw new Error('query page lifecycle policy is disposed')}
}
