import { describe, expect, it } from 'vitest'
import { ArcGisLayerRefreshCoordinator, type ArcGisLayerRefreshBudget } from './ArcGisLayerRefreshCoordinator'
const budget:ArcGisLayerRefreshBudget={maxJobs:4,maxJobsPerLayer:3,maxConcurrent:2,maxConcurrentPerLayer:1,maxReadyBytes:1000,maxReadyBytesPerLayer:700,maxBytesPerJob:500,queueLeaseMs:100,loadingLeaseMs:50,readyTtlMs:200}
const request=(layerId:string,refreshKey:string,revision=1,requestedAt=0,intent:'interactive'|'visible'|'background'='visible')=>({layerId,refreshKey,revision,requestedAt,intent,estimatedBytes:100})
describe('ArcGisLayerRefreshCoordinator',()=>{
 it('prioritizes interactive work deterministically',()=>{const p=new ArcGisLayerRefreshCoordinator(budget);p.enqueue(request('a','bg',1,1,'background'));p.enqueue(request('b','visible',1,2));p.enqueue(request('c','interactive',1,3,'interactive'));expect(p.takeNext(4)?.refreshKey).toBe('interactive');expect(p.takeNext(4)?.refreshKey).toBe('visible')})
 it('enforces per-layer loading concurrency',()=>{const p=new ArcGisLayerRefreshCoordinator(budget);p.enqueue(request('a','1',1,1,'interactive'));p.enqueue(request('a','2',1,2,'interactive'));p.enqueue(request('b','3',1,3));expect(p.takeNext(4)?.refreshKey).toBe('1');expect(p.takeNext(4)?.refreshKey).toBe('3');expect(p.takeNext(4)).toBeUndefined()})
 it('invalidates stale generations',()=>{const p=new ArcGisLayerRefreshCoordinator(budget);p.enqueue(request('a','old1',1,1));p.enqueue(request('a','old2',1,2));expect(p.enqueue(request('a','new',2,3))).toBe(true);expect(p.snapshot().map(x=>x.refreshKey)).toEqual(['new']);expect(p.enqueue(request('a','stale',1,4))).toBe(false)})
 it('rejects late completion',()=>{const p=new ArcGisLayerRefreshCoordinator(budget);p.enqueue(request('a','page'));p.takeNext(10);expect(p.complete('a','page',1,10,60)).toBe(false);expect(p.snapshot()).toEqual([])})
 it('reconciles actual ready bytes',()=>{const p=new ArcGisLayerRefreshCoordinator(budget);p.enqueue(request('a','1'));p.takeNext(1);expect(p.complete('a','1',1,400,2)).toBe(true);p.enqueue(request('a','2',1,3));p.takeNext(4);expect(p.complete('a','2',1,400,5)).toBe(false)})
 it('expires ready residency before aggregate admission',()=>{const p=new ArcGisLayerRefreshCoordinator(budget);p.enqueue(request('a','old'));p.takeNext(1);expect(p.complete('a','old',1,500,2)).toBe(true);p.enqueue(request('b','fresh',1,150));p.takeNext(151);expect(p.complete('b','fresh',1,500,202)).toBe(true);expect(p.snapshot().map(x=>x.refreshKey)).toEqual(['fresh'])})
 it('expires same-layer residency before admission',()=>{const p=new ArcGisLayerRefreshCoordinator(budget);p.enqueue(request('a','old'));p.takeNext(1);p.complete('a','old',1,500,2);p.enqueue(request('a','fresh',1,150));p.takeNext(151);expect(p.complete('a','fresh',1,500,202)).toBe(true)})
 it('consumes ready work once',()=>{const p=new ArcGisLayerRefreshCoordinator(budget);p.enqueue(request('a','page'));p.takeNext(1);p.complete('a','page',1,10,2);expect(p.consume('a','page',1,3)?.actualBytes).toBe(10);expect(p.consume('a','page',1,3)).toBeUndefined()})
 it('bounds global and per-layer cardinality',()=>{const p=new ArcGisLayerRefreshCoordinator(budget);expect(p.enqueue(request('a','1'))).toBe(true);expect(p.enqueue(request('a','2',1,1))).toBe(true);expect(p.enqueue(request('a','3',1,2))).toBe(true);expect(p.enqueue(request('a','4',1,3))).toBe(false);expect(p.enqueue(request('b','1',1,4))).toBe(true);expect(p.enqueue(request('c','1',1,5))).toBe(false)})
 it('returns detached snapshots',()=>{const p=new ArcGisLayerRefreshCoordinator(budget);p.enqueue(request('a','page'));const external=p.snapshot()[0]!;external.layerId='tampered';expect(p.snapshot()[0]?.layerId).toBe('a')})
 it('releases only the requested layer',()=>{const p=new ArcGisLayerRefreshCoordinator(budget);p.enqueue(request('a','1'));p.enqueue(request('b','2',1,1));expect(p.releaseLayer('a')).toBe(1);expect(p.snapshot().map(x=>x.layerId)).toEqual(['b'])})
 it('fails closed on malformed inputs',()=>{const p=new ArcGisLayerRefreshCoordinator(budget);expect(()=>p.enqueue({...request('','x'),layerId:' '})).toThrow();expect(()=>p.enqueue({...request('a','x'),revision:0})).toThrow();expect(()=>p.enqueue({...request('a','x'),estimatedBytes:501})).toThrow()})
 it('validates coherent budgets',()=>{expect(()=>new ArcGisLayerRefreshCoordinator({...budget,maxJobsPerLayer:5})).toThrow();expect(()=>new ArcGisLayerRefreshCoordinator({...budget,maxConcurrentPerLayer:3})).toThrow();expect(()=>new ArcGisLayerRefreshCoordinator({...budget,maxBytesPerJob:701})).toThrow()})
 it('disposal clears state and prevents reuse',()=>{const p=new ArcGisLayerRefreshCoordinator(budget);p.enqueue(request('a','page'));p.dispose();p.dispose();expect(()=>p.snapshot()).toThrow('disposed')})
})
