export type SpatialQueryWindowIntent = 'interactive' | 'visible' | 'prefetch'
export interface SpatialQueryWindowKey { layerId:string; revision:number; level:number; column:number; row:number }
export interface SpatialQueryWindowBudget { maxWindows:number; maxWindowsPerLayer:number; maxResident:number; maxResidentBytes:number; ttlMs:number }
interface WindowState extends SpatialQueryWindowKey { id:string; intent:SpatialQueryWindowIntent; bytes:number; touchedAt:number; expiresAt:number; sequence:number }
const rank:Readonly<Record<SpatialQueryWindowIntent,number>>=Object.freeze({interactive:2,visible:1,prefetch:0})
function identifier(value:string):string{const v=value.trim();if(!v||v.length>192||/[\u0000-\u001f]/.test(v))throw new Error('invalid identifier');return v}
function count(value:number):void{if(!Number.isSafeInteger(value)||value<0)throw new Error('invalid count')}
/** Payload-free bounded authority for viewport-partitioned ArcGIS REST query residency. */
export class ArcGisSpatialQueryWindowLifecyclePolicy {
 readonly #budget:Readonly<SpatialQueryWindowBudget>; readonly #windows=new Map<string,WindowState>(); readonly #revisions=new Map<string,number>(); #sequence=0; #disposed=false
 constructor(budget:SpatialQueryWindowBudget){count(budget.maxWindows);count(budget.maxWindowsPerLayer);count(budget.maxResident);count(budget.maxResidentBytes);count(budget.ttlMs);if(!budget.maxWindows||!budget.maxWindowsPerLayer||budget.maxWindowsPerLayer>budget.maxWindows||!budget.maxResident||budget.maxResident>budget.maxWindows||!budget.maxResidentBytes||!budget.ttlMs)throw new Error('invalid budget');this.#budget=Object.freeze({...budget})}
 setRevision(layerId:string,revision:number):number{this.#live();const layer=identifier(layerId);count(revision);const current=this.#revisions.get(layer);if(current!==undefined&&revision<current)return -1;this.#revisions.set(layer,revision);if(current===undefined||current===revision)return 0;let removed=0;for(const [key,w] of this.#windows)if(w.layerId===layer&&w.revision!==revision){this.#windows.delete(key);removed++}return removed}
 admit(id:string,key:SpatialQueryWindowKey,intent:SpatialQueryWindowIntent,bytes:number,now:number):boolean{this.#live();const windowId=identifier(id),layerId=identifier(key.layerId);count(key.revision);count(key.level);count(key.column);count(key.row);count(bytes);count(now);if(!(intent in rank))throw new Error('invalid intent');if(this.#revisions.get(layerId)!==key.revision||!bytes||bytes>this.#budget.maxResidentBytes||this.#windows.has(windowId)||this.#windows.size>=this.#budget.maxWindows)return false;let layerCount=0;for(const w of this.#windows.values()){if(w.layerId===layerId)layerCount++;if(w.layerId===layerId&&w.revision===key.revision&&w.level===key.level&&w.column===key.column&&w.row===key.row)return false}if(layerCount>=this.#budget.maxWindowsPerLayer)return false;this.#windows.set(windowId,{...key,layerId,id:windowId,intent,bytes,touchedAt:now,expiresAt:now+this.#budget.ttlMs,sequence:++this.#sequence});this.#evict(windowId);return this.#windows.has(windowId)}
 touch(id:string,revision:number,now:number):boolean{this.#live();count(revision);count(now);const w=this.#windows.get(identifier(id));if(!w||w.revision!==revision||this.#revisions.get(w.layerId)!==revision||now>=w.expiresAt)return false;w.touchedAt=now;w.expiresAt=now+this.#budget.ttlMs;return true}
 consume(id:string,revision:number):Readonly<SpatialQueryWindowKey&{bytes:number}>|null{this.#live();count(revision);const key=identifier(id),w=this.#windows.get(key);if(!w||w.revision!==revision||this.#revisions.get(w.layerId)!==revision)return null;this.#windows.delete(key);return Object.freeze({layerId:w.layerId,revision:w.revision,level:w.level,column:w.column,row:w.row,bytes:w.bytes})}
 expire(now:number):number{this.#live();count(now);let removed=0;for(const [key,w] of this.#windows)if(now>=w.expiresAt){this.#windows.delete(key);removed++}return removed}
 releaseLayer(layerId:string):number{this.#live();const layer=identifier(layerId);let removed=0;for(const [key,w] of this.#windows)if(w.layerId===layer){this.#windows.delete(key);removed++}this.#revisions.delete(layer);return removed}
 snapshot():Readonly<{layers:number;windows:number;bytes:number}>{this.#live();let bytes=0;for(const w of this.#windows.values())bytes+=w.bytes;return Object.freeze({layers:this.#revisions.size,windows:this.#windows.size,bytes})}
 fingerprint():string{this.#live();return[...this.#windows.values()].sort((a,b)=>a.layerId.localeCompare(b.layerId)||a.level-b.level||a.column-b.column||a.row-b.row||a.sequence-b.sequence).map(w=>`${w.layerId}:${w.revision}:${w.level}/${w.column}/${w.row}:${w.intent}`).join('|')}
 dispose():void{if(this.#disposed)return;this.#windows.clear();this.#revisions.clear();this.#disposed=true}
 #evict(protectedId:string):void{const total=()=>{let n=0;for(const w of this.#windows.values())n+=w.bytes;return n};while(this.#windows.size>this.#budget.maxResident||total()>this.#budget.maxResidentBytes){const victim=[...this.#windows.values()].filter(w=>w.id!==protectedId).sort((a,b)=>rank[a.intent]-rank[b.intent]||a.touchedAt-b.touchedAt||a.sequence-b.sequence)[0];if(!victim){this.#windows.delete(protectedId);break}this.#windows.delete(victim.id)}}
 #live():void{if(this.#disposed)throw new Error('ArcGisSpatialQueryWindowLifecyclePolicy is disposed')}
}
