import { describe, expect, it } from 'vitest'
import { ArcGisSketchSessionLifecyclePolicy, type SketchSessionBudget, type SketchSessionRequest } from './ArcGisSketchSessionLifecyclePolicy'
const budget: SketchSessionBudget = { maxViews:3,maxSessions:8,maxSessionsPerView:4,maxActive:2,maxActivePerView:1,maxResident:3,maxResidentPerView:2,maxVerticesPerSession:100,maxBytesPerSession:1000,maxResidentVertices:180,maxResidentBytes:1800,queueTtlMs:50,activeLeaseMs:100,residentTtlMs:200 }
function request(overrides:Partial<SketchSessionRequest>={}):SketchSessionRequest{return{sessionId:'session-a',viewId:'view-a',revision:1,intent:'interactive',geometryKind:'polygon',vertexCount:20,estimatedBytes:200,requestedAt:10,...overrides}}
function policy(custom:Partial<SketchSessionBudget>={}):ArcGisSketchSessionLifecyclePolicy{return new ArcGisSketchSessionLifecyclePolicy({...budget,...custom})}
describe('ArcGisSketchSessionLifecyclePolicy',()=>{
 it('rejects inconsistent budgets',()=>{expect(()=>policy({maxSessionsPerView:9})).toThrow(/maxSessionsPerView/);expect(()=>policy({maxActivePerView:3})).toThrow(/maxActivePerView/);expect(()=>policy({maxResidentPerView:4})).toThrow(/maxResidentPerView/);expect(()=>policy({maxVerticesPerSession:181})).toThrow(/vertex budgets/);expect(()=>policy({maxBytesPerSession:1801})).toThrow(/byte budgets/)})
 it('requires current revision',()=>{const s=policy();expect(s.admit(request())).toBe(false);expect(s.setRevision('view-a',1)).toBe(0);expect(s.admit(request())).toBe(true);expect(s.snapshot()).toMatchObject({views:1,sessions:1,queued:1})})
 it('fails closed for unsafe scalar inputs',()=>{const s=policy();s.setRevision('view-a',1);expect(()=>s.admit(request({sessionId:'\u0000bad'}))).toThrow(/sessionId/);expect(()=>s.admit(request({vertexCount:-1}))).toThrow(/vertexCount/);expect(()=>s.admit(request({requestedAt:Number.NaN}))).toThrow(/requestedAt/)})
 it('bounds view cardinality and revision rollback',()=>{const s=policy({maxViews:2});expect(s.setRevision('a',2)).toBe(0);expect(s.setRevision('b',1)).toBe(0);expect(s.setRevision('c',1)).toBe(-1);expect(s.setRevision('a',1)).toBe(-1)})
 it('invalidates stale sessions on revision advance',()=>{const s=policy({maxActivePerView:2});s.setRevision('view-a',1);s.admit(request({sessionId:'q'}));s.admit(request({sessionId:'a',requestedAt:11}));s.startNext(12);s.complete('q',1,20,200,13);s.startNext(14);expect(s.setRevision('view-a',2)).toBe(2);expect(s.snapshot().sessions).toBe(0)})
 it('schedules by intent then FIFO',()=>{const s=policy({maxActive:3,maxActivePerView:3});s.setRevision('view-a',1);s.admit(request({sessionId:'bg',intent:'background',requestedAt:1}));s.admit(request({sessionId:'v',intent:'visible',requestedAt:2}));s.admit(request({sessionId:'i',requestedAt:3}));expect(s.startNext(5)?.sessionId).toBe('i');expect(s.startNext(6)?.sessionId).toBe('v');expect(s.startNext(7)?.sessionId).toBe('bg')})
 it('enforces per-view concurrency',()=>{const s=policy();s.setRevision('a',1);s.setRevision('b',1);s.admit(request({sessionId:'a1',viewId:'a'}));s.admit(request({sessionId:'a2',viewId:'a',requestedAt:11}));s.admit(request({sessionId:'b1',viewId:'b',requestedAt:12}));expect(s.startNext(13)?.sessionId).toBe('a1');expect(s.startNext(14)?.sessionId).toBe('b1');expect(s.startNext(15)).toBeNull()})
 it('reconciles actual completion metadata',()=>{const s=policy();s.setRevision('view-a',1);s.admit(request({estimatedBytes:900,vertexCount:90}));s.startNext(11);expect(s.complete('session-a',1,25,250,12)).toBe(true);expect(s.snapshot()).toMatchObject({residentVertices:25,residentBytes:250})})
 it('drops oversized actual completion',()=>{const s=policy();s.setRevision('view-a',1);s.admit(request());s.startNext(11);expect(s.complete('session-a',1,101,200,12)).toBe(false);expect(s.snapshot().sessions).toBe(0)})
 it('evicts lower intent under memory pressure',()=>{const s=policy({maxResidentBytes:500,maxResidentVertices:100,maxBytesPerSession:500});s.setRevision('a',1);s.setRevision('b',1);s.admit(request({sessionId:'bg',viewId:'a',intent:'background',estimatedBytes:300}));s.startNext(11);s.complete('bg',1,30,300,12);s.admit(request({sessionId:'i',viewId:'b',estimatedBytes:300,requestedAt:13}));s.startNext(14);expect(s.complete('i',1,30,300,15)).toBe(true);expect(s.consume('bg',1)).toBeNull();expect(s.consume('i',1)).not.toBeNull()})
 it('expires lifecycle phases',()=>{const s=policy();s.setRevision('view-a',1);s.admit(request({sessionId:'q',requestedAt:0}));expect(s.expire(50)).toBe(1);s.admit(request({sessionId:'a',requestedAt:60}));s.startNext(61);expect(s.expire(161)).toBe(1)})
 it('rejects stale completion after lease expiry',()=>{const s=policy();s.setRevision('view-a',1);s.admit(request({requestedAt:0}));s.startNext(1);expect(s.complete('session-a',1,10,100,102)).toBe(false)})
 it('returns frozen detached scalar views',()=>{const s=policy();s.setRevision('view-a',1);const p=request();s.admit(p);p.sessionId='mutated';const lease=s.startNext(11);expect(lease?.sessionId).toBe('session-a');expect(Object.isFrozen(lease)).toBe(true)})
 it('fingerprints deterministic governance state',()=>{const s=policy();s.setRevision('view-a',1);s.admit(request());expect(s.fingerprint()).toBe('view-a:session-a:1:interactive:polygon:queued:20:200')})
 it('releases view state',()=>{const s=policy({maxViews:1});s.setRevision('a',1);s.admit(request({viewId:'a'}));expect(s.releaseView('a')).toBe(1);expect(s.setRevision('b',1)).toBe(0)})
 it('prevents duplicate session ids',()=>{const s=policy();s.setRevision('view-a',1);expect(s.admit(request())).toBe(true);expect(s.admit(request())).toBe(false)})
 it('consume requires authoritative revision',()=>{const s=policy();s.setRevision('view-a',2);s.admit(request({revision:2}));s.startNext(11);s.complete('session-a',2,10,100,12);expect(s.consume('session-a',1)).toBeNull();expect(s.consume('session-a',2)).not.toBeNull()})
 it('dispose fails closed',()=>{const s=policy();s.setRevision('view-a',1);s.dispose();expect(()=>s.snapshot()).toThrow(/disposed/);expect(()=>s.admit(request())).toThrow(/disposed/)})
})