export type ArcGisEditValidationOperation = 'add' | 'update' | 'delete'
export type ArcGisEditGeometryType = 'none' | 'point' | 'multipoint' | 'polyline' | 'polygon'
export type ArcGisEditFieldType = 'string' | 'integer' | 'double' | 'boolean' | 'date' | 'guid' | 'oid' | 'globalid'

export interface ArcGisEditValidationBudget {
  maxSchemas: number; maxFieldsPerSchema: number; maxFeaturesPerBatch: number; maxAttributesPerFeature: number
  maxStringLength: number; maxFieldNameLength: number; maxAttributeBytesPerFeature: number; maxBatchAttributeBytes: number
  maxVerticesPerFeature: number; maxBatchVertices: number
}
export interface ArcGisEditFieldDefinition { name: string; type: ArcGisEditFieldType; editable: boolean; nullable: boolean; hasDefaultValue?: boolean; maxLength?: number }
export interface ArcGisEditLayerSchema { layerId: string; revision: number; geometryType: ArcGisEditGeometryType; wkid: number; objectIdField?: string; globalIdField?: string; operations: readonly ArcGisEditValidationOperation[]; fields: readonly ArcGisEditFieldDefinition[] }
export interface ArcGisEditAttribute { field: string; value: string | number | boolean | null }
export interface ArcGisEditFeatureMutation { clientId: string; objectId?: number; globalId?: string; geometryType: ArcGisEditGeometryType; wkid: number; vertexCount: number; attributes: readonly ArcGisEditAttribute[] }
export interface ArcGisEditValidationRequest { layerId: string; revision: number; operation: ArcGisEditValidationOperation; features: readonly ArcGisEditFeatureMutation[] }
export interface ArcGisEditValidationPlan { readonly layerId: string; readonly revision: number; readonly operation: ArcGisEditValidationOperation; readonly featureCount: number; readonly attributeCount: number; readonly attributeBytes: number; readonly vertexCount: number; readonly clientIds: readonly string[]; readonly fieldNames: readonly string[]; readonly fingerprint: string }
interface Field { readonly name: string; readonly key: string; readonly type: ArcGisEditFieldType; readonly editable: boolean; readonly nullable: boolean; readonly hasDefaultValue: boolean; readonly maxLength: number }
interface Schema { readonly layerId: string; readonly revision: number; readonly geometryType: ArcGisEditGeometryType; readonly wkid: number; readonly objectId: string | null; readonly globalId: string | null; readonly operations: ReadonlySet<ArcGisEditValidationOperation>; readonly fields: ReadonlyMap<string, Field> }
const fieldTypes = new Set<ArcGisEditFieldType>(['string','integer','double','boolean','date','guid','oid','globalid'])
const geometryTypes = new Set<ArcGisEditGeometryType>(['none','point','multipoint','polyline','polygon'])
const operations = new Set<ArcGisEditValidationOperation>(['add','update','delete'])
const safeId = /^[A-Za-z0-9_.:-]+$/; const safeField = /^[A-Za-z_][A-Za-z0-9_]*$/; const guid = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
const pos=(n:string,v:number)=>{if(!Number.isSafeInteger(v)||v<1)throw new Error(`${n}-positive`);return v}; const nonneg=(n:string,v:number)=>{if(!Number.isSafeInteger(v)||v<0)throw new Error(`${n}-nonnegative`);return v}
const id=(n:string,v:string,m=256)=>{const x=v.trim();if(!x||x.length>m||!safeId.test(x))throw new Error(`invalid-${n}`);return x}; const key=(v:string)=>v.toLocaleLowerCase('en-US')
const fname=(v:string,m:number)=>{const x=v.trim();if(!x||x.length>m||!safeField.test(x))throw new Error('invalid-field-name');return x}; const wkid=(v:number)=>{const x=nonneg('wkid',v);return x===102100||x===102113?3857:x}
const bytes=(v:string)=>new TextEncoder().encode(v).byteLength
const hash=(parts:readonly string[])=>{let h=2166136261;for(const p of parts){for(let i=0;i<p.length;i++){h^=p.charCodeAt(i);h=Math.imul(h,16777619)}h^=31;h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,'0')}

/** Payload-free FeatureServer edit admission. SDK objects, geometry coordinates, credentials and transport handles remain caller-owned. */
export class ArcGisEditValidationPolicy {
  readonly #b: Readonly<ArcGisEditValidationBudget>; readonly #schemas=new Map<string,Schema>(); #disposed=false
  constructor(b:ArcGisEditValidationBudget){this.#b=Object.freeze({maxSchemas:pos('maxSchemas',b.maxSchemas),maxFieldsPerSchema:pos('maxFieldsPerSchema',b.maxFieldsPerSchema),maxFeaturesPerBatch:pos('maxFeaturesPerBatch',b.maxFeaturesPerBatch),maxAttributesPerFeature:pos('maxAttributesPerFeature',b.maxAttributesPerFeature),maxStringLength:pos('maxStringLength',b.maxStringLength),maxFieldNameLength:pos('maxFieldNameLength',b.maxFieldNameLength),maxAttributeBytesPerFeature:pos('maxAttributeBytesPerFeature',b.maxAttributeBytesPerFeature),maxBatchAttributeBytes:pos('maxBatchAttributeBytes',b.maxBatchAttributeBytes),maxVerticesPerFeature:pos('maxVerticesPerFeature',b.maxVerticesPerFeature),maxBatchVertices:pos('maxBatchVertices',b.maxBatchVertices)});if(this.#b.maxAttributeBytesPerFeature>this.#b.maxBatchAttributeBytes||this.#b.maxVerticesPerFeature>this.#b.maxBatchVertices)throw new Error('inconsistent-budget')}
  registerSchema(input:ArcGisEditLayerSchema){this.#active();const layerId=id('layer-id',input.layerId),revision=nonneg('revision',input.revision),gt=this.#geometry(input.geometryType),sr=wkid(input.wkid);if((gt==='none')!==(sr===0))throw new Error('invalid-schema-spatial-reference');if(input.fields.length<1||input.fields.length>this.#b.maxFieldsPerSchema)throw new Error('schema-field-budget');const current=this.#schemas.get(layerId);if(current&&revision<=current.revision)throw new Error('schema-revision-must-advance');if(!current&&this.#schemas.size>=this.#b.maxSchemas)throw new Error('schema-capacity');const fields=new Map<string,Field>();for(const f of input.fields){const name=fname(f.name,this.#b.maxFieldNameLength),k=key(name);if(fields.has(k))throw new Error('duplicate-schema-field');if(!fieldTypes.has(f.type))throw new Error('invalid-field-type');const ml=f.type==='string'?pos('maxLength',f.maxLength??this.#b.maxStringLength):0;if(ml>this.#b.maxStringLength)throw new Error('field-string-budget');fields.set(k,Object.freeze({name,key:k,type:f.type,editable:f.editable===true,nullable:f.nullable===true,hasDefaultValue:f.hasDefaultValue===true,maxLength:ml}))}const objectId=this.#identity(input.objectIdField,fields,'oid'),globalId=this.#identity(input.globalIdField,fields,'globalid');const ops=new Set<ArcGisEditValidationOperation>();for(const op of input.operations){if(!operations.has(op)||ops.has(op))throw new Error('invalid-or-duplicate-operation');ops.add(op)}if((ops.has('update')||ops.has('delete'))&&!objectId&&!globalId)throw new Error('mutation-schema-missing-identity');this.#schemas.set(layerId,Object.freeze({layerId,revision,geometryType:gt,wkid:sr,objectId,globalId,operations:ops,fields}));return Object.freeze({layerId,revision,fieldCount:fields.size,fingerprint:hash([layerId,String(revision),gt,String(sr),...[...fields].map(([k,v])=>`${k}:${v.type}`).sort()])})}
  validate(r:ArcGisEditValidationRequest):ArcGisEditValidationPlan{this.#active();const layerId=id('layer-id',r.layerId),revision=nonneg('revision',r.revision);if(!operations.has(r.operation))throw new Error('invalid-edit-operation');const s=this.#schemas.get(layerId);if(!s)throw new Error('edit-schema-not-registered');if(revision!==s.revision)throw new Error('stale-edit-schema-revision');if(!s.operations.has(r.operation))throw new Error('edit-operation-not-advertised');if(r.features.length<1||r.features.length>this.#b.maxFeaturesPerBatch)throw new Error('edit-feature-budget');const ids=new Set<string>(),names=new Map<string,string>(),parts=[layerId,String(revision),r.operation];let attributeCount=0,attributeBytes=0,vertexCount=0;const normalized=r.features.map(f=>this.#feature(s,r.operation,f)).sort((a,b)=>a.clientId.localeCompare(b.clientId));for(const f of normalized){if(ids.has(f.clientId))throw new Error('duplicate-edit-client-id');ids.add(f.clientId);attributeCount+=f.count;attributeBytes+=f.bytes;vertexCount+=f.vertices;if(attributeBytes>this.#b.maxBatchAttributeBytes)throw new Error('edit-batch-attribute-byte-budget');if(vertexCount>this.#b.maxBatchVertices)throw new Error('edit-batch-vertex-budget');for(const n of f.names)names.set(key(n),n);parts.push(f.fingerprint)}return Object.freeze({layerId,revision,operation:r.operation,featureCount:normalized.length,attributeCount,attributeBytes,vertexCount,clientIds:Object.freeze([...ids].sort()),fieldNames:Object.freeze([...names.values()].sort()),fingerprint:hash(parts)})}
  currentRevision(layerId:string){this.#active();return this.#schemas.get(id('layer-id',layerId))?.revision} releaseLayer(layerId:string){this.#active();return this.#schemas.delete(id('layer-id',layerId))} snapshot(){this.#active();return Object.freeze([...this.#schemas.values()].sort((a,b)=>a.layerId.localeCompare(b.layerId)).map(s=>Object.freeze({layerId:s.layerId,revision:s.revision,fieldCount:s.fields.size})))} dispose(){this.#schemas.clear();this.#disposed=true}
  #feature(s:Schema,op:ArcGisEditValidationOperation,f:ArcGisEditFeatureMutation){const clientId=id('client-id',f.clientId,160),vertices=nonneg('vertexCount',f.vertexCount);if(vertices>this.#b.maxVerticesPerFeature)throw new Error('edit-feature-vertex-budget');const objectId=f.objectId===undefined?null:pos('objectId',f.objectId),globalId=f.globalId===undefined?null:this.#guid(f.globalId);if(op==='add'&&(objectId!==null||globalId!==null))throw new Error('add-cannot-carry-server-identity');if(op!=='add'&&objectId===null&&globalId===null)throw new Error('edit-identity-required');if(op==='delete'&&(f.attributes.length||f.geometryType!=='none'||f.wkid!==0||vertices!==0))throw new Error('delete-must-be-identity-only');if(op!=='delete'){if(s.geometryType==='none'){if(f.geometryType!=='none'||f.wkid!==0||vertices!==0)throw new Error('table-edit-cannot-carry-geometry')}else if(f.geometryType==='none'){if(f.wkid!==0||vertices!==0)throw new Error('empty-geometry-metadata')}else if(f.geometryType!==s.geometryType||wkid(f.wkid)!==s.wkid)throw new Error('geometry-or-spatial-reference-mismatch')}if(f.attributes.length>this.#b.maxAttributesPerFeature)throw new Error('edit-attribute-count-budget');const seen=new Set<string>(),names:string[]=[],fp=[clientId,String(objectId??''),globalId??'',f.geometryType,String(wkid(f.wkid)),String(vertices)];let total=0;for(const a of [...f.attributes].sort((x,y)=>key(x.field).localeCompare(key(y.field)))){const n=fname(a.field,this.#b.maxFieldNameLength),k=key(n);if(seen.has(k))throw new Error('duplicate-edit-attribute');seen.add(k);const d=s.fields.get(k);if(!d)throw new Error('edit-field-not-in-schema');if(!d.editable)throw new Error('edit-field-not-editable');if(k===s.objectId||k===s.globalId)throw new Error('identity-field-mutation');const scalar=this.#scalar(d,a.value);total+=bytes(n)+bytes(scalar);if(total>this.#b.maxAttributeBytesPerFeature)throw new Error('edit-feature-attribute-byte-budget');names.push(d.name);fp.push(`${k}:${scalar}`)}if(op==='add')for(const d of s.fields.values())if(d.editable&&!d.nullable&&!d.hasDefaultValue&&!seen.has(d.key))throw new Error('required-add-field-missing');return{clientId,count:f.attributes.length,bytes:total,vertices,names,fingerprint:hash(fp)}}
  #scalar(d:Field,v:string|number|boolean|null){if(v===null){if(!d.nullable)throw new Error('non-nullable-field');return'null'}if(d.type==='string'){if(typeof v!=='string'||v.length>d.maxLength)throw new Error('invalid-string');return`s:${v}`}if(d.type==='integer'||d.type==='date'){if(typeof v!=='number'||!Number.isSafeInteger(v))throw new Error('invalid-integer');return`n:${v}`}if(d.type==='double'){if(typeof v!=='number'||!Number.isFinite(v))throw new Error('invalid-double');return`n:${v}`}if(d.type==='boolean'){if(typeof v!=='boolean')throw new Error('invalid-boolean');return v?'b:1':'b:0'}if(d.type==='guid'){if(typeof v!=='string')throw new Error('invalid-guid');return`g:${this.#guid(v)}`}throw new Error('identity-field-mutation')}
  #identity(v:string|undefined,fields:Map<string,Field>,type:'oid'|'globalid'){if(!v)return null;const k=key(fname(v,this.#b.maxFieldNameLength)),d=fields.get(k);if(!d||d.type!==type||d.editable)throw new Error(`invalid-${type}-field`);return k} #guid(v:string){const x=v.trim().replace(/^\{|\}$/g,'').toLowerCase();if(!guid.test(x))throw new Error('invalid-global-id');return x} #geometry(v:ArcGisEditGeometryType){if(!geometryTypes.has(v))throw new Error('invalid-geometry-type');return v} #active(){if(this.#disposed)throw new Error('ArcGisEditValidationPolicy is disposed')}
}
