import { describe, expect, it } from 'vitest'
import { ArcGisServiceRequestLifecyclePolicy, type ArcGisServiceRequest, type ArcGisServiceRequestBudget } from './ArcGisServiceRequestLifecyclePolicy'
const budget:ArcGisServiceRequestBudget={maxRequests:6,maxRequestsPerService:4,maxRunning:2,maxRunningPerService:1,maxReady:3,maxReadyBytes:20_000,maxResponseBytes:10_000,maxRetries:1,queueTtlMs:100,runTtlMs:200,readyTtlMs:300}
const request=(o:Partial<ArcGisServiceRequest>={}):ArcGisServiceRequest=>({requestId:'r1',serviceId:'s1',operation:'query',intent:'visible',revision:1,requestedAt:10,estimatedResponseBytes:2000,signature:'where=1=1',...o})
const running=(p:ArcGisServiceRequestLifecyclePolicy,o:Partial<ArcGisServiceRequest>={})=>{p.enqueue(request(o));return p.takeNext(20)!}
describe('ArcGisServiceRequestLifecyclePolicy',()=>{
 it('schedules by intent and service concurrency',()=>{const p=new ArcGisServiceRequestLifecyclePolicy(budget);p.enqueue(request({requestId:'b',signature:'b',intent:'background'}));p.enqueue(request({requestId:'i',serviceId:'s2',signature:'i',intent:'interactive'}));expect(p.takeNext(20)?.requestId).toBe('i');expect(p.takeNext(20)?.requestId).toBe('b')})
 it('deduplicates service operation signatures',()=>{const p=new ArcGisServiceRequestLifecyclePolicy(budget);p.enqueue(request());expect(()=>p.enqueue(request({requestId:'r2'}))).toThrow(/duplicate request signature/)})
 it('bounds cardinality and estimated response bytes',()=>{const p=new ArcGisServiceRequestLifecyclePolicy({...budget,maxRequests:1,maxRequestsPerService:1,maxRunning:1,maxReady:1});p.enqueue(request());expect(()=>p.enqueue(request({requestId:'r2',serviceId:'s2',signature:'b'}))).toThrow(/capacity/);expect(()=>new ArcGisServiceRequestLifecyclePolicy(budget).enqueue(request({estimatedResponseBytes:10001}))).toThrow(/estimated response/)})
 it('reconciles actual ready bytes and aggregate residency',()=>{const p=new ArcGisServiceRequestLifecyclePolicy(budget);running(p);expect(p.complete({requestId:'r1',serviceId:'s1',revision:1,responseBytes:4000,completedAt:30}).actualResponseBytes).toBe(4000)})
 it('rejects oversized actual responses and clears failed authority',()=>{const p=new ArcGisServiceRequestLifecyclePolicy(budget);running(p);expect(()=>p.complete({requestId:'r1',serviceId:'s1',revision:1,responseBytes:10001,completedAt:30})).toThrow(/response exceeds/);expect(p.snapshot()).toHaveLength(0)})
 it('invalidates stale revisions',()=>{const p=new ArcGisServiceRequestLifecyclePolicy(budget);running(p);expect(p.advanceServiceRevision('s1',2)).toBe(1);expect(()=>p.enqueue(request({requestId:'old',signature:'old'}))).toThrow(/stale/)})
 it('rejects late and mismatched completions',()=>{const p=new ArcGisServiceRequestLifecyclePolicy(budget);running(p);expect(()=>p.complete({requestId:'r1',serviceId:'wrong',revision:1,responseBytes:1,completedAt:30})).toThrow(/identity/);expect(()=>p.complete({requestId:'r1',serviceId:'s1',revision:1,responseBytes:1,completedAt:221})).toThrow(/lease expired/)})
 it('supports bounded retry',()=>{const p=new ArcGisServiceRequestLifecyclePolicy(budget);running(p);expect(p.retry('r1',30)).toBe(true);expect(p.takeNext(31)?.attempts).toBe(2);expect(p.retry('r1',40)).toBe(false);expect(p.snapshot()).toHaveLength(0)})
 it('touches, consumes and releases ready authority',()=>{const p=new ArcGisServiceRequestLifecyclePolicy(budget);running(p);p.complete({requestId:'r1',serviceId:'s1',revision:1,responseBytes:100,completedAt:30});expect(p.touch('r1',40)).toBe(true);expect(p.consume('r1')?.phase).toBe('ready');expect(p.snapshot()).toHaveLength(0)})
 it('expires and tears down service authority',()=>{const p=new ArcGisServiceRequestLifecyclePolicy(budget);p.enqueue(request({requestedAt:0}));expect(p.expire(101)).toBe(1);p.enqueue(request({requestId:'r2',signature:'b'}));expect(p.releaseService('s1')).toBe(1)})
 it('returns frozen payload-free views and fingerprints',()=>{const p=new ArcGisServiceRequestLifecyclePolicy(budget);const v=p.enqueue(request({signature:'secret-query'}));expect(Object.isFrozen(v)).toBe(true);for(const key of ['url','body','headers','credential','response','abortController','signal'])expect(v).not.toHaveProperty(key);expect(p.fingerprint()).not.toContain('secret-query')})
 it.each([NaN,Infinity,-Infinity])('rejects non-finite time %s',requestedAt=>expect(()=>new ArcGisServiceRequestLifecyclePolicy(budget).enqueue(request({requestedAt}))).toThrow(/finite/))
 it('rejects malformed identifiers, signatures and impossible budgets',()=>{expect(()=>new ArcGisServiceRequestLifecyclePolicy(budget).enqueue(request({requestId:'bad id'}))).toThrow(/invalid/);expect(()=>new ArcGisServiceRequestLifecyclePolicy(budget).enqueue(request({signature:'bad\nquery'}))).toThrow(/signature/);expect(()=>new ArcGisServiceRequestLifecyclePolicy({...budget,maxRunning:7})).toThrow(/impossible/)})
 it('fails closed after dispose',()=>{const p=new ArcGisServiceRequestLifecyclePolicy(budget);p.enqueue(request());p.dispose();expect(()=>p.snapshot()).toThrow(/disposed/)})
})
