import {describe,expect,it} from 'vitest'
import {ArcGisEditReceiptLifecyclePolicy} from './ArcGisEditReceiptLifecyclePolicy'
const budget={maxLayers:3,maxReceipts:5,maxReceiptsPerLayer:3,maxOperations:20,ttlMs:100}
const make=()=>new ArcGisEditReceiptLifecyclePolicy(budget)
const req=(receiptId:string,layerId='roads',revision=1,outcome:'applied'|'partial'|'rejected'='applied',operations=2,createdAt=1)=>({receiptId,layerId,revision,outcome,operations,createdAt})
describe('ArcGisEditReceiptLifecyclePolicy',()=>{
 it('requires revision authority',()=>{const p=make();expect(p.record(req('a'))).toBe(false);p.setRevision('roads',1);expect(p.record(req('a'))).toBe(true)})
 it('invalidates stale receipts',()=>{const p=make();p.setRevision('roads',1);p.record(req('a'));expect(p.setRevision('roads',2)).toBe(1);expect(p.snapshot().receipts).toBe(0)})
 it('rejects revision regression',()=>{const p=make();p.setRevision('roads',2);expect(p.setRevision('roads',1)).toBe(-1)})
 it('bounds layer authority',()=>{const p=new ArcGisEditReceiptLifecyclePolicy({...budget,maxLayers:1});p.setRevision('a',1);expect(p.setRevision('b',1)).toBe(-1)})
 it('bounds receipt cardinality',()=>{const p=new ArcGisEditReceiptLifecyclePolicy({...budget,maxReceipts:1,maxReceiptsPerLayer:1});p.setRevision('roads',1);expect(p.record(req('a'))).toBe(true);expect(p.record(req('b'))).toBe(false)})
 it('bounds per-layer receipts',()=>{const p=new ArcGisEditReceiptLifecyclePolicy({...budget,maxReceiptsPerLayer:1});p.setRevision('roads',1);expect(p.record(req('a'))).toBe(true);expect(p.record(req('b'))).toBe(false)})
 it('bounds aggregate operations',()=>{const p=new ArcGisEditReceiptLifecyclePolicy({...budget,maxOperations:2});p.setRevision('roads',1);expect(p.record(req('a'))).toBe(true);expect(p.record(req('b','roads',1,'applied',1))).toBe(false)})
 it('rejects duplicate ids',()=>{const p=make();p.setRevision('roads',1);expect(p.record(req('a'))).toBe(true);expect(p.record(req('a'))).toBe(false)})
 it('returns current receipt',()=>{const p=make();p.setRevision('roads',1);p.record(req('a'));expect(p.get('a',1,2)?.outcome).toBe('applied')})
 it('rejects stale get',()=>{const p=make();p.setRevision('roads',1);p.record(req('a'));expect(p.get('a',2,2)).toBeNull()})
 it('touches TTL on get',()=>{const p=make();p.setRevision('roads',1);p.record(req('a'));p.get('a',1,50);expect(p.expire(149)).toBe(0);expect(p.expire(150)).toBe(1)})
 it('consumes current receipt',()=>{const p=make();p.setRevision('roads',1);p.record(req('a'));expect(p.consume('a',1)?.receiptId).toBe('a');expect(p.snapshot().receipts).toBe(0)})
 it('rejects stale consume',()=>{const p=make();p.setRevision('roads',1);p.record(req('a'));expect(p.consume('a',2)).toBeNull()})
 it('expires at TTL',()=>{const p=make();p.setRevision('roads',1);p.record(req('a','roads',1,'applied',2,10));expect(p.expire(109)).toBe(0);expect(p.expire(110)).toBe(1)})
 it('releases a layer',()=>{const p=make();p.setRevision('roads',1);p.record(req('a'));p.record(req('b'));expect(p.releaseLayer('roads')).toBe(2);expect(p.record(req('c'))).toBe(false)})
 it('accounts outcomes separately',()=>{const p=make();p.setRevision('roads',1);p.record(req('a'));p.record(req('b','roads',1,'partial'));p.record(req('c','roads',1,'rejected'));expect(p.snapshot()).toEqual({layers:1,receipts:3,operations:6,applied:1,partial:1,rejected:1})})
 it('fingerprint is deterministic scalar metadata',()=>{const p=make();p.setRevision('roads',1);p.record(req('a'));expect(p.fingerprint()).toBe('roads:a:1:applied:2');expect(p.fingerprint()).not.toContain('attributes')})
 it('normalizes ids and ignores excess payload',()=>{const p=make();p.setRevision(' roads ',1);expect(p.record({...req(' a ',' roads '),...({geometry:{x:1},attributes:{secret:'x'}} as object)})).toBe(true);expect(p.fingerprint()).toContain('roads:a:');expect(p.fingerprint()).not.toContain('secret')})
 it('validates identifiers',()=>{const p=make();expect(()=>p.setRevision('',1)).toThrow();p.setRevision('roads',1);expect(()=>p.record(req('','roads'))).toThrow()})
 it('validates operations and time',()=>{const p=make();p.setRevision('roads',1);expect(()=>p.record(req('a','roads',1,'applied',0))).toThrow();expect(()=>p.record(req('b','roads',1,'applied',1,-1))).toThrow()})
 it('validates budget hierarchy',()=>{expect(()=>new ArcGisEditReceiptLifecyclePolicy({...budget,maxReceipts:1,maxReceiptsPerLayer:2})).toThrow();expect(()=>new ArcGisEditReceiptLifecyclePolicy({...budget,maxOperations:0})).toThrow()})
 it('dispose is idempotent and terminal',()=>{const p=make();p.setRevision('roads',1);p.record(req('a'));p.dispose();p.dispose();expect(()=>p.snapshot()).toThrow('disposed');expect(()=>p.record(req('b'))).toThrow('disposed')})
})
