import test from 'node:test';
import assert from 'node:assert/strict';
import {DEFAULT_REQUIRED,MAX_REQUIRED_WORKFLOWS,MAX_RUN_EVIDENCE,evaluateReleaseEvidenceQuorum,formatReleaseEvidenceQuorum} from './release-evidence-quorum.mjs';
const A='a'.repeat(40),B='b'.repeat(40);
const run=(name,overrides={})=>({name,headSha:B,event:'pull_request',status:'completed',conclusion:'success',runId:100+DEFAULT_REQUIRED.indexOf(name),attempt:1,createdAt:'2026-10-04T02:00:00.000Z',updatedAt:'2026-10-04T02:05:00.000Z',...overrides});
const fixture=(overrides={})=>({version:1,headSha:B,baseSha:A,currentMainSha:A,observedAt:'2026-10-04T02:10:00.000Z',maxEvidenceAgeMs:3600000,runs:DEFAULT_REQUIRED.map(name=>run(name)),...overrides});
const has=(input,code,options)=>assert.ok(evaluateReleaseEvidenceQuorum(input,options).findings.some(x=>x.code===code));
test('accepts fresh exact-head successful quorum',()=>assert.equal(evaluateReleaseEvidenceQuorum(fixture()).passed,true));
test('requires every workflow',()=>{const x=fixture();x.runs=x.runs.slice(1);has(x,'required-run-missing')});
test('rejects evidence from another head',()=>{const x=fixture();x.runs[0]=run(DEFAULT_REQUIRED[0],{headSha:A});has(x,'required-run-missing')});
test('rejects stale base',()=>has(fixture({baseSha:'c'.repeat(40)}),'base-stale'));
test('rejects candidate head equal to main',()=>{const x=fixture({headSha:A});x.runs=x.runs.map((r,i)=>({...r,headSha:A,runId:200+i}));has(x,'head-equals-main')});
test('rejects pending run',()=>{const x=fixture();x.runs[0]=run(DEFAULT_REQUIRED[0],{status:'in_progress',conclusion:null});has(x,'run-pending');has(x,'run-not-success')});
test('rejects failed run',()=>{const x=fixture();x.runs[0]=run(DEFAULT_REQUIRED[0],{conclusion:'failure'});has(x,'run-not-success')});
test('rejects untrusted event',()=>{const x=fixture();x.runs[0]=run(DEFAULT_REQUIRED[0],{event:'push'});has(x,'run-event-untrusted')});
test('accepts pull_request_target',()=>{const x=fixture();x.runs[0]=run(DEFAULT_REQUIRED[0],{event:'pull_request_target'});assert.equal(evaluateReleaseEvidenceQuorum(x).passed,true)});
test('rejects stale evidence',()=>has(fixture({maxEvidenceAgeMs:60000}),'run-stale'));
test('rejects future evidence',()=>{const x=fixture();x.runs[0]=run(DEFAULT_REQUIRED[0],{updatedAt:'2026-10-04T03:00:00.000Z'});has(x,'run-from-future')});
test('latest attempt supersedes older failure',()=>{const x=fixture();x.runs[0]={...x.runs[0],conclusion:'failure'};x.runs.push(run(DEFAULT_REQUIRED[0],{runId:999,attempt:2,updatedAt:'2026-10-04T02:06:00.000Z'}));assert.equal(evaluateReleaseEvidenceQuorum(x).passed,true)});
test('latest failure cannot be hidden',()=>{const x=fixture();x.runs.push(run(DEFAULT_REQUIRED[0],{runId:999,attempt:2,conclusion:'failure',updatedAt:'2026-10-04T02:06:00.000Z'}));has(x,'run-not-success')});
test('detects ambiguous latest run',()=>{const x=fixture();x.runs.push(run(DEFAULT_REQUIRED[0],{runId:999}));has(x,'ambiguous-latest-run')});
test('detects run id collision',()=>{const x=fixture();x.runs.push(run('Other Workflow',{runId:100}));has(x,'run-id-collision')});
test('rejects invalid run identifiers',()=>{const x=fixture();x.runs[0]=run(DEFAULT_REQUIRED[0],{runId:0,attempt:0});has(x,'run-id-invalid');has(x,'run-attempt-invalid')});
test('rejects reversed timestamps',()=>{const x=fixture();x.runs[0]=run(DEFAULT_REQUIRED[0],{createdAt:'2026-10-04T02:09:00.000Z'});has(x,'run-time-reversed')});
test('rejects invalid observed timestamp',()=>has(fixture({observedAt:'never'}),'observed-at-invalid'));
test('rejects invalid age policy',()=>{has(fixture({maxEvidenceAgeMs:59999}),'age-policy-invalid');has(fixture({maxEvidenceAgeMs:86400001}),'age-policy-invalid')});
test('rejects malformed roots and version',()=>{has(null,'evidence-invalid');has([],'evidence-invalid');has(fixture({version:2}),'version-invalid')});
test('normalizes uppercase SHA',()=>{const x=fixture({headSha:B.toUpperCase(),baseSha:A.toUpperCase(),currentMainSha:A.toUpperCase()});x.runs=x.runs.map(r=>({...r,headSha:B.toUpperCase()}));assert.equal(evaluateReleaseEvidenceQuorum(x).passed,true)});
test('rejects malformed run metadata',()=>{const x=fixture();x.runs[0]=run('bad\nname',{status:'',conclusion:'bad\nvalue'});has(x,'run-name-invalid');has(x,'run-status-invalid');has(x,'run-conclusion-invalid')});
test('rejects duplicate required names',()=>has(fixture(),'required-name-duplicate',{required:['Release QA','Release QA']}));
test('rejects malformed required policy instead of weakening quorum',()=>{has(fixture(),'required-invalid',{required:[]});has(fixture(),'required-invalid',{required:null});has(fixture(),'required-invalid',{required:'Release QA'});has(fixture(),'required-invalid',{required:Array.from({length:MAX_REQUIRED_WORKFLOWS+1},(_,i)=>`Workflow ${i}`)})});
test('rejects required names containing controls or unsupported punctuation',()=>{has(fixture(),'required-name-invalid',{required:['Release QA\nspoof']});has(fixture(),'required-name-invalid',{required:['Release QA <spoof>']})});
test('supports narrowed explicit quorum',()=>{const x=fixture();x.runs=[run('Release QA')];assert.equal(evaluateReleaseEvidenceQuorum(x,{required:['Release QA']}).passed,true)});
test('bounds evidence cardinality per workflow',()=>{const x=fixture();for(let i=0;i<33;i++)x.runs.push(run('Release QA',{runId:1000+i,attempt:2+i,updatedAt:'2026-10-04T02:06:00.000Z'}));has(x,'run-cardinality-exceeded')});
test('bounds total evidence before normalization work',()=>{const x=fixture({runs:Array.from({length:MAX_RUN_EVIDENCE+1},(_,i)=>run('Release QA',{runId:10000+i,attempt:i+1}))});has(x,'runs-limit')});
test('accepts total evidence exactly at global bound when policy quorum is present',()=>{const extras=Array.from({length:MAX_RUN_EVIDENCE-DEFAULT_REQUIRED.length},(_,i)=>run(`Noise ${i}`,{runId:10000+i,attempt:1}));const x=fixture({runs:[...DEFAULT_REQUIRED.map(name=>run(name)),...extras]});assert.equal(evaluateReleaseEvidenceQuorum(x).passed,true)});
test('formatter and immutable result are deterministic',()=>{const r=evaluateReleaseEvidenceQuorum(fixture({baseSha:'c'.repeat(40)}));assert.match(formatReleaseEvidenceQuorum(r),/base-stale/);assert.ok(Object.isFrozen(r));assert.ok(Object.isFrozen(r.findings));assert.ok(Object.isFrozen(r.summary))});
